var OAuth;null==OAuth&&(OAuth={});OAuth.setProperties=function(a,b){if(null!=a&&null!=b)for(var c in b)a[c]=b[c];return a};
OAuth.setProperties(OAuth,{percentEncode:function(a){if(null==a)return"";if(a instanceof Array){for(var b="";0<a.length;++a)""!=b&&(b+="&"),b+=OAuth.percentEncode(a[0]);return b}a=encodeURIComponent(a);a=a.replace(/!/g,"%21");a=a.replace(/\*/g,"%2A");a=a.replace(/'/g,"%27");a=a.replace(/\(/g,"%28");return a=a.replace(/\)/g,"%29")},decodePercent:function(a){null!=a&&(a=a.replace(/\+/g," "));return decodeURIComponent(a)},getParameterList:function(a){if(null==a)return[];if("object"!=typeof a)return OAuth.decodeForm(a+
"");if(a instanceof Array)return a;var b=[],c;for(c in a)b.push([c,a[c]]);return b},getParameterMap:function(a){if(null==a)return{};if("object"!=typeof a)return OAuth.getParameterMap(OAuth.decodeForm(a+""));if(a instanceof Array){for(var b={},c=0;c<a.length;++c){var d=a[c][0];void 0===b[d]&&(b[d]=a[c][1])}return b}return a},getParameter:function(a,b){if(a instanceof Array)for(var c=0;c<a.length;++c){if(a[c][0]==b)return a[c][1]}else return OAuth.getParameterMap(a)[b];return null},formEncode:function(a){var b=
"";a=OAuth.getParameterList(a);for(var c=0;c<a.length;++c){var d=a[c][1];null==d&&(d="");""!=b&&(b+="&");b+=OAuth.percentEncode(a[c][0])+"="+OAuth.percentEncode(d)}return b},decodeForm:function(a){var b=[];a=a.split("&");for(var c=0;c<a.length;++c){var d=a[c];if(""!=d){var e=d.indexOf("=");if(0>e){var f=OAuth.decodePercent(d);d=null}else f=OAuth.decodePercent(d.substring(0,e)),d=OAuth.decodePercent(d.substring(e+1));b.push([f,d])}}return b},setParameter:function(a,b,c){var d=a.parameters;if(d instanceof
Array){for(a=0;a<d.length;++a)d[a][0]==b&&(void 0===c?d.splice(a,1):(d[a][1]=c,c=void 0));void 0!==c&&d.push([b,c])}else d=OAuth.getParameterMap(d),d[b]=c,a.parameters=d},setParameters:function(a,b){b=OAuth.getParameterList(b);for(var c=0;c<b.length;++c)OAuth.setParameter(a,b[c][0],b[c][1])},completeRequest:function(a,b){null==a.method&&(a.method="GET");var c=OAuth.getParameterMap(a.parameters);null==c.oauth_consumer_key&&OAuth.setParameter(a,"oauth_consumer_key",b.consumerKey||"");null==c.oauth_token&&
null!=b.token&&OAuth.setParameter(a,"oauth_token",b.token);null==c.oauth_version&&OAuth.setParameter(a,"oauth_version","1.0");null==c.oauth_timestamp&&OAuth.setParameter(a,"oauth_timestamp",OAuth.timestamp());null==c.oauth_nonce&&OAuth.setParameter(a,"oauth_nonce",OAuth.nonce(6));OAuth.SignatureMethod.sign(a,b)},setTimestampAndNonce:function(a){OAuth.setParameter(a,"oauth_timestamp",OAuth.timestamp());OAuth.setParameter(a,"oauth_nonce",OAuth.nonce(6))},addToURL:function(a,b){newURL=a;null!=b&&(b=
OAuth.formEncode(b),0<b.length&&(newURL=0>a.indexOf("?")?newURL+"?":newURL+"&",newURL+=b));return newURL},getAuthorizationHeader:function(a,b){a='OAuth realm="'+OAuth.percentEncode(a)+'"';b=OAuth.getParameterList(b);for(var c=0;c<b.length;++c){var d=b[c],e=d[0];0==e.indexOf("oauth_")&&(a+=","+OAuth.percentEncode(e)+'="'+OAuth.percentEncode(d[1])+'"')}return a},correctTimestampFromSrc:function(a){},correctTimestamp:function(a){OAuth.timeCorrectionMsec=1E3*a-(new Date).getTime()},timeCorrectionMsec:0,
timestamp:function(){var a=(new Date).getTime()+OAuth.timeCorrectionMsec;return Math.floor(a/1E3)},nonce:function(a){for(var b=OAuth.nonce.CHARS,c="",d=0;d<a;++d){var e=Math.floor(Math.random()*b.length);c+=b.substring(e,e+1)}return c}});OAuth.nonce.CHARS="0123456789ABCDEFGHIJKLMNOPQRSTUVWXTZabcdefghiklmnopqrstuvwxyz";OAuth.declareClass=function(a,b,c){var d=a[b];a[b]=c;if(null!=c&&null!=d)for(var e in d)"prototype"!=e&&(c[e]=d[e]);return c};OAuth.declareClass(OAuth,"SignatureMethod",function(){});
OAuth.setProperties(OAuth.SignatureMethod.prototype,{sign:function(a){var b=OAuth.SignatureMethod.getBaseString(a);b=this.getSignature(b);OAuth.setParameter(a,"oauth_signature",b);return b},initialize:function(a,b){a=null!=b.accessorSecret&&9<a.length&&"-Accessor"==a.substring(a.length-9)?b.accessorSecret:b.consumerSecret;this.key=OAuth.percentEncode(a)+"&"+OAuth.percentEncode(b.tokenSecret)}});
OAuth.setProperties(OAuth.SignatureMethod,{sign:function(a,b){var c=OAuth.getParameterMap(a.parameters).oauth_signature_method;if(null==c||""==c)c="HMAC-SHA1",OAuth.setParameter(a,"oauth_signature_method",c);OAuth.SignatureMethod.newMethod(c,b).sign(a)},newMethod:function(a,b){var c=OAuth.SignatureMethod.REGISTERED[a];if(null!=c){var d=new c;d.initialize(a,b);return d}a=Error("signature_method_rejected");b="";for(d in OAuth.SignatureMethod.REGISTERED)""!=b&&(b+="&"),b+=OAuth.percentEncode(d);a.oauth_acceptable_signature_methods=
b;throw a;},REGISTERED:{},registerMethodClass:function(a,b){for(var c=0;c<a.length;++c)OAuth.SignatureMethod.REGISTERED[a[c]]=b},makeSubclass:function(a){var b=OAuth.SignatureMethod,c=function(){b.call(this)};c.prototype=new b;c.prototype.getSignature=a;return c.prototype.constructor=c},getBaseString:function(a){var b=a.action,c=b.indexOf("?");if(0>c)c=a.parameters;else{c=OAuth.decodeForm(b.substring(c+1));for(var d=OAuth.getParameterList(a.parameters),e=0;e<d.length;++e)c.push(d[e])}return OAuth.percentEncode(a.method.toUpperCase())+
"&"+OAuth.percentEncode(OAuth.SignatureMethod.normalizeUrl(b))+"&"+OAuth.percentEncode(OAuth.SignatureMethod.normalizeParameters(c))},normalizeUrl:function(a){var b=OAuth.SignatureMethod.parseUri(a);a=b.protocol.toLowerCase();var c=b.authority.toLowerCase();if("http"==a&&80==b.port||"https"==a&&443==b.port){var d=c.lastIndexOf(":");0<=d&&(c=c.substring(0,d))}(b=b.path)||(b="/");return a+"://"+c+b},parseUri:function(a){var b="source protocol authority userInfo user password host port relative path directory file query anchor".split(" ");
a=/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@\/]*):?([^:@\/]*))?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/.exec(a);for(var c={},d=14;d--;)c[b[d]]=a[d]||"";return c},normalizeParameters:function(a){if(null==a)return"";var b=OAuth.getParameterList(a);a=[];for(var c=0;c<b.length;++c){var d=b[c];"oauth_signature"!=d[0]&&a.push([OAuth.percentEncode(d[0])+" "+OAuth.percentEncode(d[1]),d])}a.sort(function(e,f){return e[0]<f[0]?-1:e[0]>f[0]?1:0});b=[];for(c=0;c<a.length;++c)b.push(a[c][1]);
return OAuth.formEncode(b)}});OAuth.SignatureMethod.registerMethodClass(["PLAINTEXT","PLAINTEXT-Accessor"],OAuth.SignatureMethod.makeSubclass(function(a){return this.key}));OAuth.SignatureMethod.registerMethodClass(["HMAC-SHA1","HMAC-SHA1-Accessor"],OAuth.SignatureMethod.makeSubclass(function(a){b64pad="=";return b64_hmac_sha1(this.key,a)}));OAuth.correctTimestampFromSrc();
