/*
 ZeroClipboard
 The ZeroClipboard library provides an easy way to copy text to the clipboard using an invisible Adobe Flash movie and a JavaScript interface.
 Copyright (c) 2009-2014 Jon Rohan, James M. Greene
 Licensed MIT
 http://zeroclipboard.org/
 v2.2.0
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(f){var n=0;return function(){return n<f.length?{done:!1,value:f[n++]}:{done:!0}}};$jscomp.arrayIterator=function(f){return{next:$jscomp.arrayIteratorImpl(f)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(f,n,l){if(f==Array.prototype||f==Object.prototype)return f;f[n]=l.value;return f};$jscomp.getGlobal=function(f){f=["object"==typeof globalThis&&globalThis,f,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var n=0;n<f.length;++n){var l=f[n];if(l&&l.Math==Math)return l}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(f,n){var l=$jscomp.propertyToPolyfillSymbol[n];if(null==l)return f[n];l=f[l];return void 0!==l?l:f[n]};
$jscomp.polyfill=function(f,n,l,t){n&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(f,n,l,t):$jscomp.polyfillUnisolated(f,n,l,t))};$jscomp.polyfillUnisolated=function(f,n,l,t){l=$jscomp.global;f=f.split(".");for(t=0;t<f.length-1;t++){var u=f[t];if(!(u in l))return;l=l[u]}f=f[f.length-1];t=l[f];n=n(t);n!=t&&null!=n&&$jscomp.defineProperty(l,f,{configurable:!0,writable:!0,value:n})};
$jscomp.polyfillIsolated=function(f,n,l,t){var u=f.split(".");f=1===u.length;t=u[0];t=!f&&t in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var D=0;D<u.length-1;D++){var M=u[D];if(!(M in t))return;t=t[M]}u=u[u.length-1];l=$jscomp.IS_SYMBOL_NATIVE&&"es6"===l?t[u]:null;n=n(l);null!=n&&(f?$jscomp.defineProperty($jscomp.polyfills,u,{configurable:!0,writable:!0,value:n}):n!==l&&($jscomp.propertyToPolyfillSymbol[u]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(u):$jscomp.POLYFILL_PREFIX+u,u=
$jscomp.propertyToPolyfillSymbol[u],$jscomp.defineProperty(t,u,{configurable:!0,writable:!0,value:n})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(f){if(f)return f;var n=function(u,D){this.$jscomp$symbol$id_=u;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:D})};n.prototype.toString=function(){return this.$jscomp$symbol$id_};var l=0,t=function(u){if(this instanceof t)throw new TypeError("Symbol is not a constructor");return new n("jscomp_symbol_"+(u||"")+"_"+l++,u)};return t},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(f){if(f)return f;f=Symbol("Symbol.iterator");for(var n="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),l=0;l<n.length;l++){var t=$jscomp.global[n[l]];"function"===typeof t&&"function"!=typeof t.prototype[f]&&$jscomp.defineProperty(t.prototype,f,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return f},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(f){f={next:f};f[Symbol.iterator]=function(){return this};return f};$jscomp.iteratorFromArray=function(f,n){f instanceof String&&(f+="");var l=0,t=!1,u={next:function(){if(!t&&l<f.length){var D=l++;return{value:n(D,f[D]),done:!1}}t=!0;return{done:!0,value:void 0}}};u[Symbol.iterator]=function(){return u};return u};
$jscomp.polyfill("Array.prototype.keys",function(f){return f?f:function(){return $jscomp.iteratorFromArray(this,function(n){return n})}},"es6","es3");
(function(f,n){var l=f.document,t=f.navigator,u=f.setTimeout,D=f.clearTimeout,M=f.setInterval,pa=f.clearInterval,Z=f.getComputedStyle,P=f.encodeURIComponent,aa=f.ActiveXObject,qa=f.Error,ra=f.Number.parseInt||f.parseInt,J=f.Number.parseFloat||f.parseFloat,sa=f.Number.isNaN||f.isNaN,ba=f.Date.now,ca=f.Object.keys,ta=f.Object.defineProperty,z=f.Object.prototype.hasOwnProperty,ua=f.Array.prototype.slice,va=function(){var a=function(d){return d};if("function"===typeof f.wrap&&"function"===typeof f.unwrap)try{var b=
l.createElement("div"),c=f.unwrap(b);1===b.nodeType&&c&&1===c.nodeType&&(a=f.unwrap)}catch(d){}return a}(),v=function(a){return ua.call(a,0)},w=function(){var a,b,c,d=v(arguments),g=d[0]||{};var h=1;for(a=d.length;h<a;h++)if(null!=(b=d[h]))for(c in b)if(z.call(b,c)){var e=b[c];g!==e&&e!==n&&(g[c]=e)}return g},H=function(a){var b;if("object"!==typeof a||null==a||"number"===typeof a.nodeType)var c=a;else if("number"===typeof a.length){c=[];var d=0;for(b=a.length;d<b;d++)z.call(a,d)&&(c[d]=H(a[d]))}else for(d in c=
{},a)z.call(a,d)&&(c[d]=H(a[d]));return c},da=function(a,b){if(a&&1===a.nodeType&&a.ownerDocument&&b&&(1===b.nodeType&&b.ownerDocument&&b.ownerDocument===a.ownerDocument||9===b.nodeType&&!b.ownerDocument&&b===a.ownerDocument)){do{if(a===b)return!0;a=a.parentNode}while(a)}return!1},ea=function(a){if("string"===typeof a&&a){a.split("#")[0].split("?");var b=a.slice(0,a.lastIndexOf("/")+1)}return b},wa=function(){var a,b;if(l.currentScript&&(a=l.currentScript.src))return a;var c=l.getElementsByTagName("script");
if(1===c.length)return c[0].src||n;if("readyState"in c[0])for(b=c.length;b--;)if("interactive"===c[b].readyState&&(a=c[b].src))return a;if("loading"===l.readyState&&(a=c[c.length-1].src))return a;var d;try{throw new qa;}catch(h){c=h}if(c&&!(d=c.sourceURL||c.fileName)){d=c.stack;if("string"===typeof d&&d)if((c=d.match(/^(?:|[^:@]*@|.+\)@(?=http[s]?|file)|.+?\s+(?: at |@)(?:[^:\(]+ )*[\(]?)((?:http[s]?|file):\/\/[\/]?.+?\/[^:\)]*?)(?::\d+)(?::\d+)?/))&&c[1])var g=c[1];else(c=d.match(/\)@((?:http[s]?|file):\/\/[\/]?.+?\/[^:\)]*?)(?::\d+)(?::\d+)?/))&&
c[1]&&(g=c[1]);d=g}return(a=d)?a:n},fa=null==f.opener&&(!!f.top&&f!=f.top||!!f.parent&&f!=f.parent),m={bridge:null,version:"0.0.0",pluginType:"unknown",disabled:null,outdated:null,sandboxed:null,unavailable:null,degraded:null,deactivated:null,overdue:null,ready:null},E,F={},C,Q,y={},R=null,S=0,T=0,xa={ready:"Flash communication is established",error:{"flash-disabled":"Flash is disabled or not installed. May also be attempting to run Flash in a sandboxed iframe, which is impossible.","flash-outdated":"Flash is too outdated to support ZeroClipboard",
"flash-sandboxed":"Attempting to run Flash in a sandboxed iframe, which is impossible","flash-unavailable":"Flash is unable to communicate bidirectionally with JavaScript","flash-degraded":"Flash is unable to preserve data fidelity when communicating with JavaScript","flash-deactivated":"Flash is too outdated for your browser and/or is configured as click-to-activate.\nThis may also mean that the ZeroClipboard SWF object could not be loaded, so please check your `swfPath` configuration and/or network connectivity.\nMay also be attempting to run Flash in a sandboxed iframe, which is impossible.",
"flash-overdue":"Flash communication was established but NOT within the acceptable time limit","version-mismatch":"ZeroClipboard JS version number does not match ZeroClipboard SWF version number","clipboard-error":"At least one error was thrown while ZeroClipboard was attempting to inject your data into the clipboard","config-mismatch":"ZeroClipboard configuration does not match Flash's reality","swf-not-found":"The ZeroClipboard SWF object could not be loaded, so please check your `swfPath` configuration and/or network connectivity"}},
ya="flash-unavailable flash-degraded flash-overdue version-mismatch config-mismatch clipboard-error".split(" "),G="flash-disabled flash-outdated flash-sandboxed flash-unavailable flash-degraded flash-deactivated flash-overdue".split(" "),za=new RegExp("^flash-("+G.map(function(a){return a.replace(/^flash-/,"")}).join("|")+")$"),Aa=new RegExp("^flash-("+G.slice(1).map(function(a){return a.replace(/^flash-/,"")}).join("|")+")$"),r={swfPath:function(){var a;if(!(a=ea(wa()))){var b,c=l.getElementsByTagName("script");
for(a=c.length;a--;){if(!(b=c[a].src)){var d=null;break}b=ea(b);if(null==d)d=b;else if(d!==b){d=null;break}}a=d||n}return(a||"")+"ZeroClipboard.swf"}(),trustedDomains:f.location.host?[f.location.host]:[],cacheBust:!0,forceEnhancedClipboard:!1,flashLoadTimeout:3E4,autoActivate:!0,bubbleEvents:!0,containerId:"global-zeroclipboard-html-bridge",containerClass:"global-zeroclipboard-container",swfObjectId:"global-zeroclipboard-flash-bridge",hoverClass:"zeroclipboard-is-hover",activeClass:"zeroclipboard-is-active",
forceHandCursor:!1,title:null,zIndex:999999999},Ba=function(a){if("object"===typeof a&&null!==a)for(var b in a)if(z.call(a,b))if(/^(?:forceHandCursor|title|zIndex|bubbleEvents)$/.test(b))r[b]=a[b];else if(null==m.bridge)if("containerId"===b||"swfObjectId"===b){var c=a[b];if("string"===typeof c&&c&&/^[A-Za-z][A-Za-z0-9_:\-\.]*$/.test(c))r[b]=a[b];else throw Error("The specified `"+b+"` value is not valid as an HTML4 Element ID");}else r[b]=a[b];if("string"===typeof a&&a){if(z.call(r,a))return r[a]}else return H(r)},
Ca=function(){U();for(var a=["userAgent","platform","appName"],b={},c=0,d=a.length;c<d;c++)a[c]in t&&(b[a[c]]=t[a[c]]);a=["bridge"];c={};for(var g in m)-1===a.indexOf(g)&&(c[g]=m[g]);return{browser:b,flash:c,zeroclipboard:{version:k.version,config:k.config()}}},Da=function(){return!!(m.disabled||m.outdated||m.sandboxed||m.unavailable||m.degraded||m.deactivated)},Ea=function(a,b){var c,d={};if("string"===typeof a&&a)var g=a.toLowerCase().split(/\s+/);else if("object"===typeof a&&a&&"undefined"===typeof b)for(h in a)if(z.call(a,
h)&&"string"===typeof h&&h&&"function"===typeof a[h])k.on(h,a[h]);if(g&&g.length){var h=0;for(c=g.length;h<c;h++)a=g[h].replace(/^on/,""),d[a]=!0,F[a]||(F[a]=[]),F[a].push(b);d.ready&&m.ready&&k.emit({type:"ready"});if(d.error){h=0;for(c=G.length;h<c;h++)if(!0===m[G[h].replace(/^flash-/,"")]){k.emit({type:"error",name:G[h]});break}E!==n&&k.version!==E&&k.emit({type:"error",name:"version-mismatch",jsVersion:k.version,swfVersion:E})}}return k},Fa=function(a,b){var c,d,g;if(0===arguments.length)var h=
ca(F);else if("string"===typeof a&&a)h=a.split(/\s+/);else if("object"===typeof a&&a&&"undefined"===typeof b)for(e in a)z.call(a,e)&&"string"===typeof e&&e&&"function"===typeof a[e]&&k.off(e,a[e]);if(h&&h.length){var e=0;for(c=h.length;e<c;e++)if(a=h[e].toLowerCase().replace(/^on/,""),(g=F[a])&&g.length)if(b)for(d=g.indexOf(b);-1!==d;)g.splice(d,1),d=g.indexOf(b,d);else g.length=0}return k},Ga=function(a){return"string"===typeof a&&a?H(F[a])||null:H(F)},Ia=function(a){if(a=ha(a)){var b=a;var c=b.target||
C||null,d="swf"===b._source;delete b._source;switch(b.type){case "error":!(c="flash-sandboxed"===b.name)&&(c=null,!1===fa||b&&"error"===b.type&&b.name&&-1!==ya.indexOf(b.name))&&(c=!1);"boolean"===typeof c&&(m.sandboxed=c);-1!==G.indexOf(b.name)?w(m,{disabled:"flash-disabled"===b.name,outdated:"flash-outdated"===b.name,unavailable:"flash-unavailable"===b.name,degraded:"flash-degraded"===b.name,deactivated:"flash-deactivated"===b.name,overdue:"flash-overdue"===b.name,ready:!1}):"version-mismatch"===
b.name&&(E=b.swfVersion,w(m,{disabled:!1,outdated:!1,unavailable:!1,degraded:!1,deactivated:!1,overdue:!1,ready:!1}));N();break;case "ready":E=b.swfVersion;c=!0===m.deactivated;w(m,{disabled:!1,outdated:!1,sandboxed:!1,unavailable:!1,degraded:!1,deactivated:!1,overdue:c,ready:!c});N();break;case "beforecopy":Q=c;break;case "copy":var g,h;c=b.relatedTarget;!y["text/html"]&&!y["text/plain"]&&c&&(h=c.value||c.outerHTML||c.innerHTML)&&(g=c.value||c.textContent||c.innerText)?(b.clipboardData.clearData(),
b.clipboardData.setData("text/plain",g),h!==g&&b.clipboardData.setData("text/html",h)):!y["text/plain"]&&b.target&&(g=b.target.getAttribute("data-clipboard-text"))&&(b.clipboardData.clearData(),b.clipboardData.setData("text/plain",g));break;case "aftercopy":Ha(b);k.clearData();if(g=c){try{var e=l.activeElement}catch(ia){e=null}g=c!==e}g&&c.focus&&c.focus();break;case "_mouseover":k.focus(c);!0===r.bubbleEvents&&d&&(c&&c!==b.relatedTarget&&!da(b.relatedTarget,c)&&I(w({},b,{type:"mouseenter",bubbles:!1,
cancelable:!1})),I(w({},b,{type:"mouseover"})));break;case "_mouseout":k.blur();!0===r.bubbleEvents&&d&&(c&&c!==b.relatedTarget&&!da(b.relatedTarget,c)&&I(w({},b,{type:"mouseleave",bubbles:!1,cancelable:!1})),I(w({},b,{type:"mouseout"})));break;case "_mousedown":ja(c,r.activeClass);!0===r.bubbleEvents&&d&&I(w({},b,{type:b.type.slice(1)}));break;case "_mouseup":K(c,r.activeClass);!0===r.bubbleEvents&&d&&I(w({},b,{type:b.type.slice(1)}));break;case "_click":Q=null;!0===r.bubbleEvents&&d&&I(w({},b,{type:b.type.slice(1)}));
break;case "_mousemove":!0===r.bubbleEvents&&d&&I(w({},b,{type:b.type.slice(1)}))}b=/^_(?:click|mouse(?:over|out|down|up|move))$/.test(b.type)?!0:void 0;if(!b){if("ready"===a.type&&!0===m.overdue)return k.emit({type:"error",name:"flash-overdue"});b=w({},a);if("object"===typeof b&&b&&b.type&&(c=ka(b),(g=(F["*"]||[]).concat(F[b.type]||[]))&&g.length))for(h=0,e=g.length;h<e;h++){d=g[h];var q=this;"string"===typeof d&&"function"===typeof f[d]&&(d=f[d]);"object"===typeof d&&d&&"function"===typeof d.handleEvent&&
(q=d,d=d.handleEvent);if("function"===typeof d){var p=w({},b);la(d,q,[p],c)}}if("copy"===a.type){var x={};a={};if("object"===typeof y&&y){for(B in y)if(B&&z.call(y,B)&&"string"===typeof y[B]&&y[B])switch(B.toLowerCase()){case "text/plain":case "text":case "air:text":case "flash:text":x.text=y[B];a.text=B;break;case "text/html":case "html":case "air:html":case "flash:html":x.html=y[B];a.html=B;break;case "application/rtf":case "text/rtf":case "rtf":case "richtext":case "air:rtf":case "flash:rtf":x.rtf=
y[B],a.rtf=B}var B={data:x,formatMap:a}}else B=void 0;x=B.data;R=B.formatMap}return x}}},Ka=function(){var a=m.sandboxed;U();"boolean"!==typeof m.ready&&(m.ready=!1);m.sandboxed!==a&&!0===m.sandboxed?(m.ready=!1,k.emit({type:"error",name:"flash-sandboxed"})):k.isFlashUnusable()||null!==m.bridge||(a=r.flashLoadTimeout,"number"===typeof a&&0<=a&&(S=u(function(){"boolean"!==typeof m.deactivated&&(m.deactivated=!0);!0===m.deactivated&&k.emit({type:"error",name:"flash-deactivated"})},a)),m.overdue=!1,
Ja())},Ma=function(){k.clearData();k.blur();k.emit("destroy");La();k.off()},Na=function(a,b){if("object"===typeof a&&a&&"undefined"===typeof b){var c=a;k.clearData()}else if("string"===typeof a&&a)c={},c[a]=b;else return;for(var d in c)"string"===typeof d&&d&&z.call(c,d)&&"string"===typeof c[d]&&c[d]&&(y[d]=c[d])},Oa=function(a){if("undefined"===typeof a){if(y)for(var b in y)z.call(y,b)&&delete y[b];R=null}else"string"===typeof a&&z.call(y,a)&&delete y[a]},Pa=function(a){if("undefined"===typeof a)return H(y);
if("string"===typeof a&&z.call(y,a))return y[a]},Qa=function(a){if(a&&1===a.nodeType){C&&(K(C,r.activeClass),C!==a&&K(C,r.hoverClass));C=a;ja(a,r.hoverClass);var b=a.getAttribute("title")||r.title;if("string"===typeof b&&b){var c=L(m.bridge);c&&c.setAttribute("title",b)}a=!0===r.forceHandCursor||"pointer"===ma(a,"cursor");!0===m.ready&&(m.bridge&&"function"===typeof m.bridge.setHandCursor?m.bridge.setHandCursor(a):m.ready=!1);var d;C&&(d=L(m.bridge))&&(a=V(C),w(d.style,{width:a.width+"px",height:a.height+
"px",top:a.top+"px",left:a.left+"px",zIndex:""+W(r.zIndex)}))}},Ra=function(){var a=L(m.bridge);a&&(a.removeAttribute("title"),a.style.left="0px",a.style.top="-9999px",a.style.width="1px",a.style.height="1px");C&&(K(C,r.hoverClass),K(C,r.activeClass),C=null)},Sa=function(){return C||null},ha=function(a){if("string"===typeof a&&a){var b=a;a={}}else"object"===typeof a&&a&&"string"===typeof a.type&&a.type&&(b=a.type);if(b){b=b.toLowerCase();!a.target&&(/^(copy|aftercopy|_click)$/.test(b)||"error"===
b&&"clipboard-error"===a.name)&&(a.target=Q);w(a,{type:b,target:a.target||C||null,relatedTarget:a.relatedTarget||null,currentTarget:m&&m.bridge||null,timeStamp:a.timeStamp||ba()||null});b=xa[a.type];"error"===a.type&&a.name&&b&&(b=b[a.name]);b&&(a.message=b);"ready"===a.type&&w(a,{target:null,version:m.version});"error"===a.type&&(za.test(a.name)&&w(a,{target:null,minimumVersion:"11.0.0"}),Aa.test(a.name)&&w(a,{version:m.version}));"copy"===a.type&&(a.clipboardData={setData:k.setData,clearData:k.clearData});
if("aftercopy"===a.type&&(b=R,"object"===typeof a&&a&&"object"===typeof b&&b)){var c={};for(e in a)if(z.call(a,e))if("errors"===e){c[e]=a[e]?a[e].slice():[];for(var d=0,g=c[e].length;d<g;d++)c[e][d].format=b[c[e][d].format]}else if("success"!==e&&"data"!==e)c[e]=a[e];else{c[e]={};d=a[e];for(var h in d)h&&z.call(d,h)&&z.call(b,h)&&(c[e][b[h]]=d[h])}a=c}if(a.target&&!a.relatedTarget){var e=a;h=(h=(h=a.target)&&h.getAttribute&&h.getAttribute("data-clipboard-target"))?l.getElementById(h):null;e.relatedTarget=
h}if((e=a)&&/^_(?:click|mouse(?:over|out|down|up|move))$/.test(e.type)){h=e.target;a="_mouseover"===e.type&&e.relatedTarget?e.relatedTarget:n;b="_mouseout"===e.type&&e.relatedTarget?e.relatedTarget:n;d=V(h);c=d.left+("number"===typeof e._stageX?e._stageX:0);d=d.top+("number"===typeof e._stageY?e._stageY:0);g=c-(l.body.scrollLeft+l.documentElement.scrollLeft);var q=d-(l.body.scrollTop+l.documentElement.scrollTop),p=(f.screenLeft||f.screenX||0)+g,x=(f.screenTop||f.screenY||0)+q,B="number"===typeof e.movementX?
e.movementX:0,ia="number"===typeof e.movementY?e.movementY:0;delete e._stageX;delete e._stageY;w(e,{srcElement:h,fromElement:a,toElement:b,screenX:p,screenY:x,pageX:c,pageY:d,clientX:g,clientY:q,x:g,y:q,movementX:B,movementY:ia,offsetX:0,offsetY:0,layerX:0,layerY:0})}return e}},ka=function(a){return!/^(?:(?:before)?copy|destroy)$/.test(a&&"string"===typeof a.type&&a.type||"")},la=function(a,b,c,d){d?u(function(){a.apply(b,c)},0):a.apply(b,c)},Ha=function(a){if(a.errors&&0<a.errors.length){var b=H(a);
w(b,{type:"error",name:"clipboard-error"});delete b.success;u(function(){k.emit(b)},0)}},I=function(a){if(a&&"string"===typeof a.type&&a){var b=a.target||null;var c=b&&b.ownerDocument||l;a=w({view:c.defaultView||f,canBubble:!0,cancelable:!0,detail:"click"===a.type?1:0,button:"number"===typeof a.which?a.which-1:"number"===typeof a.button?a.button:c.createEvent?0:1},a);b&&c.createEvent&&b.dispatchEvent&&(a=[a.type,a.canBubble,a.cancelable,a.view,a.detail,a.screenX,a.screenY,a.clientX,a.clientY,a.ctrlKey,
a.altKey,a.shiftKey,a.metaKey,a.button,a.relatedTarget],c=c.createEvent("MouseEvents"),c.initMouseEvent&&(c.initMouseEvent.apply(c,a),c._source="js",b.dispatchEvent(c)))}},Ta=function(){var a=r.flashLoadTimeout;if("number"===typeof a&&0<=a){var b=r.swfObjectId+"_fallbackContent";T=M(function(){var c=l.getElementById(b);if(c){var d=Z(c,null);var g=0<J(d.height),h=0<J(d.width),e=0<=J(d.top),q=0<=J(d.left),p=g&&h&&e&&q;c=p?null:V(c);d="none"!==d.display&&"collapse"!==d.visibility&&(p||!!c&&(g||0<c.height)&&
(h||0<c.width)&&(e||0<=c.top)&&(q||0<=c.left))}else d=!1;d&&(N(),m.deactivated=null,k.emit({type:"error",name:"swf-not-found"}))},Math.min(1E3,a/10))}},L=function(a){for(a=a&&a.parentNode;a&&"OBJECT"===a.nodeName&&a.parentNode;)a=a.parentNode;return a||null},Ja=function(){var a,b=m.bridge,c=L(b);if(!b){b=Ua(f.location.host,r);var d="never"===b?"none":"all";c=w({jsVersion:k.version},r);var g,h,e="",q=[];if(c.trustedDomains)if("string"===typeof c.trustedDomains)var p=[c.trustedDomains];else"object"===
typeof c.trustedDomains&&"length"in c.trustedDomains&&(p=c.trustedDomains);if(p&&p.length){var x=0;for(g=p.length;x<g;x++)if(z.call(p,x)&&p[x]&&"string"===typeof p[x]&&(h=X(p[x]))){if("*"===h){q.length=0;q.push(h);break}q.push.apply(q,[h,"//"+h,f.location.protocol+"//"+h])}}q.length&&(e+="trustedOrigins="+P(q.join(",")));!0===c.forceEnhancedClipboard&&(e+=(e?"&":"")+"forceEnhancedClipboard=true");"string"===typeof c.swfObjectId&&c.swfObjectId&&(e+=(e?"&":"")+"swfObjectId="+P(c.swfObjectId));"string"===
typeof c.jsVersion&&c.jsVersion&&(e+=(e?"&":"")+"jsVersion="+P(c.jsVersion));p=e;c=r.swfPath;x=null==r||r&&!0===r.cacheBust?(-1===r.swfPath.indexOf("?")?"?":"&")+"noCache="+ba():"";x=c+x;c=l.createElement("div");c.id=r.containerId;c.className=r.containerClass;c.style.position="absolute";c.style.left="0px";c.style.top="-9999px";c.style.width="1px";c.style.height="1px";c.style.zIndex=""+W(r.zIndex);g=l.createElement("div");c.appendChild(g);l.body.appendChild(c);h=l.createElement("div");e="activex"===
m.pluginType;h.innerHTML='<object id="'+r.swfObjectId+'" name="'+r.swfObjectId+'" width="100%" height="100%" '+(e?'classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"':'type="application/x-shockwave-flash" data="'+x+'"')+">"+(e?'<param name="movie" value="'+x+'"/>':"")+'<param name="allowScriptAccess" value="'+b+'"/><param name="allowNetworking" value="'+d+'"/><param name="menu" value="false"/><param name="wmode" value="transparent"/><param name="flashvars" value="'+p+'"/><div id="'+r.swfObjectId+
'_fallbackContent">&nbsp;</div></object>';b=h.firstChild;va(b).ZeroClipboard=k;c.replaceChild(b,g);Ta()}b||((b=l[r.swfObjectId])&&(a=b.length)&&(b=b[a-1]),!b&&c&&(b=c.firstChild));m.bridge=b||null;return b},La=function(){var a=m.bridge;if(a){var b=L(a);b&&("activex"===m.pluginType&&"readyState"in a?(a.style.display="none",function d(){if(4===a.readyState){for(var g in a)"function"===typeof a[g]&&(a[g]=null);a.parentNode&&a.parentNode.removeChild(a);b.parentNode&&b.parentNode.removeChild(b)}else u(d,
10)}()):(a.parentNode&&a.parentNode.removeChild(a),b.parentNode&&b.parentNode.removeChild(b)));N();m.ready=null;m.bridge=null;m.deactivated=null;E=n}},X=function(a){if(null==a||""===a)return null;a=a.replace(/^\s+|\s+$/g,"");if(""===a)return null;var b=a.indexOf("//");a=-1===b?a:a.slice(b+2);var c=a.indexOf("/");return(a=-1===c?a:-1===b||0===c?null:a.slice(0,c))&&".swf"===a.slice(-4).toLowerCase()?null:a||null},Ua=function(){return function(a,b){var c=X(b.swfPath);null===c&&(c=a);var d=b.trustedDomains,
g,h;b=[];"string"===typeof d&&(d=[d]);if("object"===typeof d&&d&&"number"===typeof d.length){var e=0;for(g=d.length;e<g;e++)if(z.call(d,e)&&(h=X(d[e]))){if("*"===h){b.length=0;b.push("*");break}-1===b.indexOf(h)&&b.push(h)}}h=b.length;if(0<h){if(1===h&&"*"===b[0])return"always";if(-1!==b.indexOf(a))return 1===h&&a===c?"sameDomain":"always"}return"never"}}(),ja=function(a,b){var c,d=[];"string"===typeof b&&b&&(d=b.split(/\s+/));if(a&&1===a.nodeType&&0<d.length)if(a.classList)for(b=0,c=d.length;b<c;b++)a.classList.add(d[b]);
else if(a.hasOwnProperty("className")){var g=" "+a.className+" ";b=0;for(c=d.length;b<c;b++)-1===g.indexOf(" "+d[b]+" ")&&(g+=d[b]+" ");a.className=g.replace(/^\s+|\s+$/g,"")}return a},K=function(a,b){var c,d=[];"string"===typeof b&&b&&(d=b.split(/\s+/));if(a&&1===a.nodeType&&0<d.length)if(a.classList&&0<a.classList.length)for(b=0,c=d.length;b<c;b++)a.classList.remove(d[b]);else if(a.className){var g=(" "+a.className+" ").replace(/[\r\n\t]/g," ");b=0;for(c=d.length;b<c;b++)g=g.replace(" "+d[b]+" ",
" ");a.className=g.replace(/^\s+|\s+$/g,"")}return a},ma=function(a,b){var c=Z(a,null).getPropertyValue(b);return"cursor"!==b||c&&"auto"!==c||"A"!==a.nodeName?c:"pointer"},V=function(a){var b={left:0,top:0,width:0,height:0};if(a.getBoundingClientRect){a=a.getBoundingClientRect();var c=f.pageXOffset,d=f.pageYOffset,g=l.documentElement.clientLeft||0,h=l.documentElement.clientTop||0,e=0,q=0;if("relative"===ma(l.body,"position")){q=l.body.getBoundingClientRect();var p=l.documentElement.getBoundingClientRect();
e=q.left-p.left||0;q=q.top-p.top||0}b.left=a.left+c-g-e;b.top=a.top+d-h-q;b.width="width"in a?a.width:a.right-a.left;b.height="height"in a?a.height:a.bottom-a.top}return b},N=function(){D(S);S=0;pa(T);T=0},W=function(a){if(/^(?:auto|inherit)$/.test(a))return a;var b;"number"!==typeof a||sa(a)?"string"===typeof a&&(b=W(ra(a,10))):b=a;return"number"===typeof b?b:"auto"},U=function(a){var b=m.sandboxed,c=null;a=!0===a;if(!1===fa)c=!1;else{try{var d=f.frameElement||null}catch(e){var g={name:e.name,message:e.message}}if(d&&
1===d.nodeType&&"IFRAME"===d.nodeName)try{c=d.hasAttribute("sandbox")}catch(e){c=null}else{try{var h=document.domain||null}catch(e){h=null}if(null===h||g&&"SecurityError"===g.name&&/(^|[\s\(\[@])sandbox(es|ed|ing|[\s\.,!\)\]@]|$)/.test(g.message.toLowerCase()))c=!0}}m.sandboxed=c;b===c||a||na(aa);return c},na=function(a){function b(p){p=p.match(/[\d]+/g);p.length=3;return p.join(".")}function c(p){p&&(d=!0,p.version&&(e=b(p.version)),!e&&p.description&&(e=b(p.description)),p.filename&&(p=p.filename,
h=!!p&&(p=p.toLowerCase())&&(/^(pepflashplayer\.dll|libpepflashplayer\.so|pepperflashplayer\.plugin)$/.test(p)||"chrome.plugin"===p.slice(-13))))}var d=!1,g=!1,h=!1,e="";if(t.plugins&&t.plugins.length)a=t.plugins["Shockwave Flash"],c(a),t.plugins["Shockwave Flash 2.0"]&&(d=!0,e="2.0.0.11");else if(t.mimeTypes&&t.mimeTypes.length)a=(a=t.mimeTypes["application/x-shockwave-flash"])&&a.enabledPlugin,c(a);else if("undefined"!==typeof a){g=!0;try{var q=new a("ShockwaveFlash.ShockwaveFlash.7");d=!0;e=b(q.GetVariable("$version"))}catch(p){try{q=
new a("ShockwaveFlash.ShockwaveFlash.6"),d=!0,e="6.0.21"}catch(x){try{q=new a("ShockwaveFlash.ShockwaveFlash"),d=!0,e=b(q.GetVariable("$version"))}catch(B){g=!1}}}}m.disabled=!0!==d;m.outdated=e&&J(e)<J("11.0.0");m.version=e||"0.0.0";m.pluginType=h?"pepper":g?"activex":d?"netscape":"unknown"};na(aa);U(!0);var k=function(){if(!(this instanceof k))return new k;"function"===typeof k._createClient&&k._createClient.apply(this,v(arguments))};ta(k,"version",{value:"2.2.0",writable:!1,configurable:!0,enumerable:!0});
k.config=function(){return Ba.apply(this,v(arguments))};k.state=function(){return Ca.apply(this,v(arguments))};k.isFlashUnusable=function(){return Da.apply(this,v(arguments))};k.on=function(){return Ea.apply(this,v(arguments))};k.off=function(){return Fa.apply(this,v(arguments))};k.handlers=function(){return Ga.apply(this,v(arguments))};k.emit=function(){return Ia.apply(this,v(arguments))};k.create=function(){return Ka.apply(this,v(arguments))};k.destroy=function(){return Ma.apply(this,v(arguments))};
k.setData=function(){return Na.apply(this,v(arguments))};k.clearData=function(){return Oa.apply(this,v(arguments))};k.getData=function(){return Pa.apply(this,v(arguments))};k.focus=k.activate=function(){return Qa.apply(this,v(arguments))};k.blur=k.deactivate=function(){return Ra.apply(this,v(arguments))};k.activeElement=function(){return Sa.apply(this,v(arguments))};var Va=0,A={},Wa=0,O={},Y={};w(r,{autoActivate:!0});var Xa=function(a){var b=this;b.id=""+Va++;A[b.id]={instance:b,elements:[],handlers:{}};
a&&b.clip(a);k.on("*",function(c){return b.emit(c)});k.on("destroy",function(){b.destroy()});k.create()},Ya=function(a,b){var c,d={},g=(c=A[this.id])&&c.handlers;if(!c)throw Error("Attempted to add new listener(s) to a destroyed ZeroClipboard client instance");if("string"===typeof a&&a)var h=a.toLowerCase().split(/\s+/);else if("object"===typeof a&&a&&"undefined"===typeof b)for(e in a)if(z.call(a,e)&&"string"===typeof e&&e&&"function"===typeof a[e])this.on(e,a[e]);if(h&&h.length){var e=0;for(c=h.length;e<
c;e++)a=h[e].replace(/^on/,""),d[a]=!0,g[a]||(g[a]=[]),g[a].push(b);d.ready&&m.ready&&this.emit({type:"ready",client:this});if(d.error){e=0;for(c=G.length;e<c;e++)if(m[G[e].replace(/^flash-/,"")]){this.emit({type:"error",name:G[e],client:this});break}E!==n&&k.version!==E&&this.emit({type:"error",name:"version-mismatch",jsVersion:k.version,swfVersion:E})}}return this},Za=function(a,b){var c,d,g,h=(c=A[this.id])&&c.handlers;if(!h)return this;if(0===arguments.length)var e=ca(h);else if("string"===typeof a&&
a)e=a.split(/\s+/);else if("object"===typeof a&&a&&"undefined"===typeof b)for(q in a)z.call(a,q)&&"string"===typeof q&&q&&"function"===typeof a[q]&&this.off(q,a[q]);if(e&&e.length){var q=0;for(c=e.length;q<c;q++)if(a=e[q].toLowerCase().replace(/^on/,""),(g=h[a])&&g.length)if(b)for(d=g.indexOf(b);-1!==d;)g.splice(d,1),d=g.indexOf(b,d);else g.length=0}return this},$a=function(a){var b=null,c=A[this.id]&&A[this.id].handlers;c&&(b="string"===typeof a&&a?c[a]?c[a].slice(0):[]:H(c));return b},ab=function(a){var b=
a;if(!b||!b.type||b.client&&b.client!==this)var c=!1;else{var d=(c=A[this.id])&&c.elements,g=!!d&&0<d.length,h=!b.target||g&&-1!==d.indexOf(b.target);d=b.relatedTarget&&g&&-1!==d.indexOf(b.relatedTarget);b=b.client&&b.client===this;c=c&&(h||d||b)?!0:!1}if(c&&("object"===typeof a&&a&&"string"===typeof a.type&&a.type&&(a=w({},a)),a=w({},ha(a),{client:this}),h=A[this.id],"object"===typeof a&&a&&a.type&&h&&(c=ka(a),(h=(h&&h.handlers["*"]||[]).concat(h&&h.handlers[a.type]||[]))&&h.length)))for(b=0,d=h.length;b<
d;b++){g=h[b];var e=this;"string"===typeof g&&"function"===typeof f[g]&&(g=f[g]);"object"===typeof g&&g&&"function"===typeof g.handleEvent&&(e=g,g=g.handleEvent);if("function"===typeof g){var q=w({},a);la(g,e,[q],c)}}return this},cb=function(a){if(!A[this.id])throw Error("Attempted to clip element(s) to a destroyed ZeroClipboard client instance");a=oa(a);for(var b=0;b<a.length;b++)if(z.call(a,b)&&a[b]&&1===a[b].nodeType){a[b].zcClippingId?-1===O[a[b].zcClippingId].indexOf(this.id)&&O[a[b].zcClippingId].push(this.id):
(a[b].zcClippingId="zcClippingId_"+Wa++,O[a[b].zcClippingId]=[this.id],!0===r.autoActivate&&bb(a[b]));var c=A[this.id]&&A[this.id].elements;-1===c.indexOf(a[b])&&c.push(a[b])}return this},db=function(a){var b=A[this.id];if(!b)return this;b=b.elements;var c;a="undefined"===typeof a?b.slice(0):oa(a);for(var d=a.length;d--;)if(z.call(a,d)&&a[d]&&1===a[d].nodeType){for(c=0;-1!==(c=b.indexOf(a[d],c));)b.splice(c,1);var g=O[a[d].zcClippingId];if(g){for(c=0;-1!==(c=g.indexOf(this.id,c));)g.splice(c,1);if(0===
g.length){if(!0===r.autoActivate){var h=a[d];if(h&&1===h.nodeType){var e=Y[h.zcClippingId];if("object"===typeof e&&e){for(var q=["move","leave","enter","out","over"],p=0,x=q.length;p<x;p++)g="mouse"+q[p],c=e[g],"function"===typeof c&&h.removeEventListener(g,c,!1);delete Y[h.zcClippingId]}}}delete a[d].zcClippingId}}}return this},eb=function(){var a=A[this.id];return a&&a.elements?a.elements.slice(0):[]},fb=function(){A[this.id]&&(this.unclip(),this.off(),delete A[this.id])},oa=function(a){"string"===
typeof a&&(a=[]);return"number"!==typeof a.length?[a]:a},bb=function(a){if(a&&1===a.nodeType){var b=function(d){if(d||(d=f.event))"js"!==d._source&&(d.stopImmediatePropagation(),d.preventDefault()),delete d._source},c=function(d){if(d||(d=f.event))b(d),k.focus(a)};a.addEventListener("mouseover",c,!1);a.addEventListener("mouseout",b,!1);a.addEventListener("mouseenter",b,!1);a.addEventListener("mouseleave",b,!1);a.addEventListener("mousemove",b,!1);Y[a.zcClippingId]={mouseover:c,mouseout:b,mouseenter:b,
mouseleave:b,mousemove:b}}};k._createClient=function(){Xa.apply(this,v(arguments))};k.prototype.on=function(){return Ya.apply(this,v(arguments))};k.prototype.off=function(){return Za.apply(this,v(arguments))};k.prototype.handlers=function(){return $a.apply(this,v(arguments))};k.prototype.emit=function(){return ab.apply(this,v(arguments))};k.prototype.clip=function(){return cb.apply(this,v(arguments))};k.prototype.unclip=function(){return db.apply(this,v(arguments))};k.prototype.elements=function(){return eb.apply(this,
v(arguments))};k.prototype.destroy=function(){return fb.apply(this,v(arguments))};k.prototype.setText=function(a){if(!A[this.id])throw Error("Attempted to set pending clipboard data from a destroyed ZeroClipboard client instance");k.setData("text/plain",a);return this};k.prototype.setHtml=function(a){if(!A[this.id])throw Error("Attempted to set pending clipboard data from a destroyed ZeroClipboard client instance");k.setData("text/html",a);return this};k.prototype.setRichText=function(a){if(!A[this.id])throw Error("Attempted to set pending clipboard data from a destroyed ZeroClipboard client instance");
k.setData("application/rtf",a);return this};k.prototype.setData=function(){if(!A[this.id])throw Error("Attempted to set pending clipboard data from a destroyed ZeroClipboard client instance");k.setData.apply(this,v(arguments));return this};k.prototype.clearData=function(){if(!A[this.id])throw Error("Attempted to clear pending clipboard data from a destroyed ZeroClipboard client instance");k.clearData.apply(this,v(arguments));return this};k.prototype.getData=function(){if(!A[this.id])throw Error("Attempted to get pending clipboard data from a destroyed ZeroClipboard client instance");
return k.getData.apply(this,v(arguments))};"function"===typeof define&&define.amd?define(function(){return k}):"object"===typeof module&&module&&"object"===typeof module.exports&&module.exports?module.exports=k:f.ZeroClipboard=k})(function(){return this||window}());
