/*
 ZeroClipboard
 The ZeroClipboard library provides an easy way to copy text to the clipboard using an invisible Adobe Flash movie and a JavaScript interface.
 Copyright (c) 2009-2014 Jon Rohan, James M. Greene
 Licensed MIT
 http://zeroclipboard.org/
 v2.2.0
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(f){var n=0;return function(){return n<f.length?{done:!1,value:f[n++]}:{done:!0}}};$jscomp.arrayIterator=function(f){return{next:$jscomp.arrayIteratorImpl(f)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(f,n,k){if(f==Array.prototype||f==Object.prototype)return f;f[n]=k.value;return f};$jscomp.getGlobal=function(f){f=["object"==typeof globalThis&&globalThis,f,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var n=0;n<f.length;++n){var k=f[n];if(k&&k.Math==Math)return k}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(f,n){var k=$jscomp.propertyToPolyfillSymbol[n];if(null==k)return f[n];k=f[k];return void 0!==k?k:f[n]};
$jscomp.polyfill=function(f,n,k,p){n&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(f,n,k,p):$jscomp.polyfillUnisolated(f,n,k,p))};$jscomp.polyfillUnisolated=function(f,n,k,p){k=$jscomp.global;f=f.split(".");for(p=0;p<f.length-1;p++){var t=f[p];if(!(t in k))return;k=k[t]}f=f[f.length-1];p=k[f];n=n(p);n!=p&&null!=n&&$jscomp.defineProperty(k,f,{configurable:!0,writable:!0,value:n})};
$jscomp.polyfillIsolated=function(f,n,k,p){var t=f.split(".");f=1===t.length;p=t[0];p=!f&&p in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var E=0;E<t.length-1;E++){var P=t[E];if(!(P in p))return;p=p[P]}t=t[t.length-1];k=$jscomp.IS_SYMBOL_NATIVE&&"es6"===k?p[t]:null;n=n(k);null!=n&&(f?$jscomp.defineProperty($jscomp.polyfills,t,{configurable:!0,writable:!0,value:n}):n!==k&&($jscomp.propertyToPolyfillSymbol[t]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(t):$jscomp.POLYFILL_PREFIX+t,t=
$jscomp.propertyToPolyfillSymbol[t],$jscomp.defineProperty(p,t,{configurable:!0,writable:!0,value:n})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(f){if(f)return f;var n=function(t,E){this.$jscomp$symbol$id_=t;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:E})};n.prototype.toString=function(){return this.$jscomp$symbol$id_};var k=0,p=function(t){if(this instanceof p)throw new TypeError("Symbol is not a constructor");return new n("jscomp_symbol_"+(t||"")+"_"+k++,t)};return p},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(f){if(f)return f;f=Symbol("Symbol.iterator");for(var n="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),k=0;k<n.length;k++){var p=$jscomp.global[n[k]];"function"===typeof p&&"function"!=typeof p.prototype[f]&&$jscomp.defineProperty(p.prototype,f,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return f},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(f){f={next:f};f[Symbol.iterator]=function(){return this};return f};$jscomp.iteratorFromArray=function(f,n){f instanceof String&&(f+="");var k=0,p=!1,t={next:function(){if(!p&&k<f.length){var E=k++;return{value:n(E,f[E]),done:!1}}p=!0;return{done:!0,value:void 0}}};t[Symbol.iterator]=function(){return t};return t};
$jscomp.polyfill("Array.prototype.keys",function(f){return f?f:function(){return $jscomp.iteratorFromArray(this,function(n){return n})}},"es6","es3");
(function(f,n){var k=f.document,p=f.navigator,t=f.setTimeout,E=f.clearTimeout,P=f.setInterval,la=f.clearInterval,aa=f.getComputedStyle,R=f.encodeURIComponent,ba=f.ActiveXObject,ma=f.Error,na=f.Number.parseInt||f.parseInt,I=f.Number.parseFloat||f.parseFloat,oa=f.Number.isNaN||f.isNaN,ca=f.Date.now,pa=f.Object.keys,qa=f.Object.defineProperty,y=f.Object.prototype.hasOwnProperty,ra=f.Array.prototype.slice,sa=function(){var a=function(d){return d};if("function"===typeof f.wrap&&"function"===typeof f.unwrap)try{var b=
k.createElement("div"),c=f.unwrap(b);1===b.nodeType&&c&&1===c.nodeType&&(a=f.unwrap)}catch(d){}return a}(),z=function(a){return ra.call(a,0)},w=function(){var a,b,c,d=z(arguments),h=d[0]||{};var g=1;for(a=d.length;g<a;g++)if(null!=(b=d[g]))for(c in b)if(y.call(b,c)){var e=b[c];h!==e&&e!==n&&(h[c]=e)}return h},H=function(a){var b;if("object"!==typeof a||null==a||"number"===typeof a.nodeType)var c=a;else if("number"===typeof a.length){c=[];var d=0;for(b=a.length;d<b;d++)y.call(a,d)&&(c[d]=H(a[d]))}else for(d in c=
{},a)y.call(a,d)&&(c[d]=H(a[d]));return c},da=function(a,b){if(a&&1===a.nodeType&&a.ownerDocument&&b&&(1===b.nodeType&&b.ownerDocument&&b.ownerDocument===a.ownerDocument||9===b.nodeType&&!b.ownerDocument&&b===a.ownerDocument)){do{if(a===b)return!0;a=a.parentNode}while(a)}return!1},ea=function(a){if("string"===typeof a&&a){a.split("#")[0].split("?");var b=a.slice(0,a.lastIndexOf("/")+1)}return b},ta=function(){var a,b;if(k.currentScript&&(a=k.currentScript.src))return a;var c=k.getElementsByTagName("script");
if(1===c.length)return c[0].src||n;if("readyState"in c[0])for(b=c.length;b--;)if("interactive"===c[b].readyState&&(a=c[b].src))return a;if("loading"===k.readyState&&(a=c[c.length-1].src))return a;var d;try{throw new ma;}catch(g){c=g}if(c&&!(d=c.sourceURL||c.fileName)){d=c.stack;if("string"===typeof d&&d)if((c=d.match(/^(?:|[^:@]*@|.+\)@(?=http[s]?|file)|.+?\s+(?: at |@)(?:[^:\(]+ )*[\(]?)((?:http[s]?|file):\/\/[\/]?.+?\/[^:\)]*?)(?::\d+)(?::\d+)?/))&&c[1])var h=c[1];else(c=d.match(/\)@((?:http[s]?|file):\/\/[\/]?.+?\/[^:\)]*?)(?::\d+)(?::\d+)?/))&&
c[1]&&(h=c[1]);d=h}return(a=d)?a:n},fa=null==f.opener&&(!!f.top&&f!=f.top||!!f.parent&&f!=f.parent),l={bridge:null,version:"0.0.0",pluginType:"unknown",disabled:null,outdated:null,sandboxed:null,unavailable:null,degraded:null,deactivated:null,overdue:null,ready:null},J,F={},B,S,x={},T=null,U=0,V=0,ua={ready:"Flash communication is established",error:{"flash-disabled":"Flash is disabled or not installed. May also be attempting to run Flash in a sandboxed iframe, which is impossible.","flash-outdated":"Flash is too outdated to support ZeroClipboard",
"flash-sandboxed":"Attempting to run Flash in a sandboxed iframe, which is impossible","flash-unavailable":"Flash is unable to communicate bidirectionally with JavaScript","flash-degraded":"Flash is unable to preserve data fidelity when communicating with JavaScript","flash-deactivated":"Flash is too outdated for your browser and/or is configured as click-to-activate.\nThis may also mean that the ZeroClipboard SWF object could not be loaded, so please check your `swfPath` configuration and/or network connectivity.\nMay also be attempting to run Flash in a sandboxed iframe, which is impossible.",
"flash-overdue":"Flash communication was established but NOT within the acceptable time limit","version-mismatch":"ZeroClipboard JS version number does not match ZeroClipboard SWF version number","clipboard-error":"At least one error was thrown while ZeroClipboard was attempting to inject your data into the clipboard","config-mismatch":"ZeroClipboard configuration does not match Flash's reality","swf-not-found":"The ZeroClipboard SWF object could not be loaded, so please check your `swfPath` configuration and/or network connectivity"}},
va="flash-unavailable flash-degraded flash-overdue version-mismatch config-mismatch clipboard-error".split(" "),K="flash-disabled flash-outdated flash-sandboxed flash-unavailable flash-degraded flash-deactivated flash-overdue".split(" "),wa=new RegExp("^flash-("+K.map(function(a){return a.replace(/^flash-/,"")}).join("|")+")$"),xa=new RegExp("^flash-("+K.slice(1).map(function(a){return a.replace(/^flash-/,"")}).join("|")+")$"),q={swfPath:function(){var a;if(!(a=ea(ta()))){var b,c=k.getElementsByTagName("script");
for(a=c.length;a--;){if(!(b=c[a].src)){var d=null;break}b=ea(b);if(null==d)d=b;else if(d!==b){d=null;break}}a=d||n}return(a||"")+"ZeroClipboard.swf"}(),trustedDomains:f.location.host?[f.location.host]:[],cacheBust:!0,forceEnhancedClipboard:!1,flashLoadTimeout:3E4,autoActivate:!0,bubbleEvents:!0,containerId:"global-zeroclipboard-html-bridge",containerClass:"global-zeroclipboard-container",swfObjectId:"global-zeroclipboard-flash-bridge",hoverClass:"zeroclipboard-is-hover",activeClass:"zeroclipboard-is-active",
forceHandCursor:!1,title:null,zIndex:999999999},ya=function(a){if("object"===typeof a&&null!==a)for(var b in a)if(y.call(a,b))if(/^(?:forceHandCursor|title|zIndex|bubbleEvents)$/.test(b))q[b]=a[b];else if(null==l.bridge)if("containerId"===b||"swfObjectId"===b){var c=a[b];if("string"===typeof c&&c&&/^[A-Za-z][A-Za-z0-9_:\-\.]*$/.test(c))q[b]=a[b];else throw Error("The specified `"+b+"` value is not valid as an HTML4 Element ID");}else q[b]=a[b];if("string"===typeof a&&a){if(y.call(q,a))return q[a]}else return H(q)},
za=function(){W();for(var a=["userAgent","platform","appName"],b={},c=0,d=a.length;c<d;c++)a[c]in p&&(b[a[c]]=p[a[c]]);a=["bridge"];c={};for(var h in l)-1===a.indexOf(h)&&(c[h]=l[h]);return{browser:b,flash:c,zeroclipboard:{version:m.version,config:m.config()}}},Aa=function(){return!!(l.disabled||l.outdated||l.sandboxed||l.unavailable||l.degraded||l.deactivated)},Ba=function(a,b){var c,d={};if("string"===typeof a&&a)var h=a.toLowerCase().split(/\s+/);else if("object"===typeof a&&a&&"undefined"===typeof b)for(g in a)if(y.call(a,
g)&&"string"===typeof g&&g&&"function"===typeof a[g])m.on(g,a[g]);if(h&&h.length){var g=0;for(c=h.length;g<c;g++)a=h[g].replace(/^on/,""),d[a]=!0,F[a]||(F[a]=[]),F[a].push(b);d.ready&&l.ready&&m.emit({type:"ready"});if(d.error){g=0;for(c=K.length;g<c;g++)if(!0===l[K[g].replace(/^flash-/,"")]){m.emit({type:"error",name:K[g]});break}J!==n&&m.version!==J&&m.emit({type:"error",name:"version-mismatch",jsVersion:m.version,swfVersion:J})}}return m},Ca=function(a,b){var c,d,h;if(0===arguments.length)var g=
pa(F);else if("string"===typeof a&&a)g=a.split(/\s+/);else if("object"===typeof a&&a&&"undefined"===typeof b)for(e in a)y.call(a,e)&&"string"===typeof e&&e&&"function"===typeof a[e]&&m.off(e,a[e]);if(g&&g.length){var e=0;for(c=g.length;e<c;e++)if(a=g[e].toLowerCase().replace(/^on/,""),(h=F[a])&&h.length)if(b)for(d=h.indexOf(b);-1!==d;)h.splice(d,1),d=h.indexOf(b,d);else h.length=0}return m},Da=function(a){return"string"===typeof a&&a?H(F[a])||null:H(F)},Ha=function(a){if("string"===typeof a&&a){var b=
a;a={}}else"object"===typeof a&&a&&"string"===typeof a.type&&a.type&&(b=a.type);if(b){b=b.toLowerCase();!a.target&&(/^(copy|aftercopy|_click)$/.test(b)||"error"===b&&"clipboard-error"===a.name)&&(a.target=S);w(a,{type:b,target:a.target||B||null,relatedTarget:a.relatedTarget||null,currentTarget:l&&l.bridge||null,timeStamp:a.timeStamp||ca()||null});b=ua[a.type];"error"===a.type&&a.name&&b&&(b=b[a.name]);b&&(a.message=b);"ready"===a.type&&w(a,{target:null,version:l.version});"error"===a.type&&(wa.test(a.name)&&
w(a,{target:null,minimumVersion:"11.0.0"}),xa.test(a.name)&&w(a,{version:l.version}));"copy"===a.type&&(a.clipboardData={setData:m.setData,clearData:m.clearData});if("aftercopy"===a.type&&(b=T,"object"===typeof a&&a&&"object"===typeof b&&b)){var c={};for(e in a)if(y.call(a,e))if("errors"===e){c[e]=a[e]?a[e].slice():[];for(var d=0,h=c[e].length;d<h;d++)c[e][d].format=b[c[e][d].format]}else if("success"!==e&&"data"!==e)c[e]=a[e];else{c[e]={};d=a[e];for(var g in d)g&&y.call(d,g)&&y.call(b,g)&&(c[e][b[g]]=
d[g])}a=c}if(a.target&&!a.relatedTarget){var e=a;g=(g=(g=a.target)&&g.getAttribute&&g.getAttribute("data-clipboard-target"))?k.getElementById(g):null;e.relatedTarget=g}if(a&&/^_(?:click|mouse(?:over|out|down|up|move))$/.test(a.type)){e=a.target;g="_mouseover"===a.type&&a.relatedTarget?a.relatedTarget:n;b="_mouseout"===a.type&&a.relatedTarget?a.relatedTarget:n;d=X(e);c=d.left+("number"===typeof a._stageX?a._stageX:0);d=d.top+("number"===typeof a._stageY?a._stageY:0);h=c-(k.body.scrollLeft+k.documentElement.scrollLeft);
var v=d-(k.body.scrollTop+k.documentElement.scrollTop),r=(f.screenLeft||f.screenX||0)+h,C=(f.screenTop||f.screenY||0)+v,ha="number"===typeof a.movementX?a.movementX:0,Ea="number"===typeof a.movementY?a.movementY:0;delete a._stageX;delete a._stageY;w(a,{srcElement:e,fromElement:g,toElement:b,screenX:r,screenY:C,pageX:c,pageY:d,clientX:h,clientY:v,x:h,y:v,movementX:ha,movementY:Ea,offsetX:0,offsetY:0,layerX:0,layerY:0})}}else a=void 0;if(a){var u;e=a;g=e.target||B||null;b="swf"===e._source;delete e._source;
switch(e.type){case "error":!(u="flash-sandboxed"===e.name)&&(u=null,!1===fa||e&&"error"===e.type&&e.name&&-1!==va.indexOf(e.name))&&(u=!1);"boolean"===typeof u&&(l.sandboxed=u);-1!==K.indexOf(e.name)?w(l,{disabled:"flash-disabled"===e.name,outdated:"flash-outdated"===e.name,unavailable:"flash-unavailable"===e.name,degraded:"flash-degraded"===e.name,deactivated:"flash-deactivated"===e.name,overdue:"flash-overdue"===e.name,ready:!1}):"version-mismatch"===e.name&&(J=e.swfVersion,w(l,{disabled:!1,outdated:!1,
unavailable:!1,degraded:!1,deactivated:!1,overdue:!1,ready:!1}));Q();break;case "ready":J=e.swfVersion;u=!0===l.deactivated;w(l,{disabled:!1,outdated:!1,sandboxed:!1,unavailable:!1,degraded:!1,deactivated:!1,overdue:u,ready:!u});Q();break;case "beforecopy":S=g;break;case "copy":var M,D=e.relatedTarget;!x["text/html"]&&!x["text/plain"]&&D&&(M=D.value||D.outerHTML||D.innerHTML)&&(u=D.value||D.textContent||D.innerText)?(e.clipboardData.clearData(),e.clipboardData.setData("text/plain",u),M!==u&&e.clipboardData.setData("text/html",
M)):!x["text/plain"]&&e.target&&(u=e.target.getAttribute("data-clipboard-text"))&&(e.clipboardData.clearData(),e.clipboardData.setData("text/plain",u));break;case "aftercopy":Fa(e);m.clearData();if(u=g){try{D=k.activeElement}catch(Ua){D=null}u=g!==D}u&&g.focus&&g.focus();break;case "_mouseover":m.focus(g);!0===q.bubbleEvents&&b&&(g&&g!==e.relatedTarget&&!da(e.relatedTarget,g)&&G(w({},e,{type:"mouseenter",bubbles:!1,cancelable:!1})),G(w({},e,{type:"mouseover"})));break;case "_mouseout":m.blur();!0===
q.bubbleEvents&&b&&(g&&g!==e.relatedTarget&&!da(e.relatedTarget,g)&&G(w({},e,{type:"mouseleave",bubbles:!1,cancelable:!1})),G(w({},e,{type:"mouseout"})));break;case "_mousedown":ia(g,q.activeClass);!0===q.bubbleEvents&&b&&G(w({},e,{type:e.type.slice(1)}));break;case "_mouseup":N(g,q.activeClass);!0===q.bubbleEvents&&b&&G(w({},e,{type:e.type.slice(1)}));break;case "_click":S=null;!0===q.bubbleEvents&&b&&G(w({},e,{type:e.type.slice(1)}));break;case "_mousemove":!0===q.bubbleEvents&&b&&G(w({},e,{type:e.type.slice(1)}))}u=
/^_(?:click|mouse(?:over|out|down|up|move))$/.test(e.type)?!0:void 0;if(!u){if("ready"===a.type&&!0===l.overdue)return m.emit({type:"error",name:"flash-overdue"});u=w({},a);if("object"===typeof u&&u&&u.type&&(M=!/^(?:(?:before)?copy|destroy)$/.test(u&&"string"===typeof u.type&&u.type||""),(D=(F["*"]||[]).concat(F[u.type]||[]))&&D.length))for(e=0,g=D.length;e<g;e++)b=D[e],c=this,"string"===typeof b&&"function"===typeof f[b]&&(b=f[b]),"object"===typeof b&&b&&"function"===typeof b.handleEvent&&(c=b,
b=b.handleEvent),"function"===typeof b&&(d=w({},u),Ga(b,c,[d],M));if("copy"===a.type){var L={};u={};if("object"===typeof x&&x){for(A in x)if(A&&y.call(x,A)&&"string"===typeof x[A]&&x[A])switch(A.toLowerCase()){case "text/plain":case "text":case "air:text":case "flash:text":L.text=x[A];u.text=A;break;case "text/html":case "html":case "air:html":case "flash:html":L.html=x[A];u.html=A;break;case "application/rtf":case "text/rtf":case "rtf":case "richtext":case "air:rtf":case "flash:rtf":L.rtf=x[A],u.rtf=
A}var A={data:L,formatMap:u}}else A=void 0;L=A.data;T=A.formatMap}return L}}},Ja=function(){var a=l.sandboxed;W();"boolean"!==typeof l.ready&&(l.ready=!1);l.sandboxed!==a&&!0===l.sandboxed?(l.ready=!1,m.emit({type:"error",name:"flash-sandboxed"})):m.isFlashUnusable()||null!==l.bridge||(a=q.flashLoadTimeout,"number"===typeof a&&0<=a&&(U=t(function(){"boolean"!==typeof l.deactivated&&(l.deactivated=!0);!0===l.deactivated&&m.emit({type:"error",name:"flash-deactivated"})},a)),l.overdue=!1,Ia())},La=function(){m.clearData();
m.blur();m.emit("destroy");Ka();m.off()},Ma=function(a,b){if("object"===typeof a&&a&&"undefined"===typeof b){var c=a;m.clearData()}else if("string"===typeof a&&a)c={},c[a]=b;else return;for(var d in c)"string"===typeof d&&d&&y.call(c,d)&&"string"===typeof c[d]&&c[d]&&(x[d]=c[d])},Na=function(a){if("undefined"===typeof a){if(x)for(var b in x)y.call(x,b)&&delete x[b];T=null}else"string"===typeof a&&y.call(x,a)&&delete x[a]},Oa=function(a){if("undefined"===typeof a)return H(x);if("string"===typeof a&&
y.call(x,a))return x[a]},Pa=function(a){if(a&&1===a.nodeType){B&&(N(B,q.activeClass),B!==a&&N(B,q.hoverClass));B=a;ia(a,q.hoverClass);var b=a.getAttribute("title")||q.title;if("string"===typeof b&&b){var c=O(l.bridge);c&&c.setAttribute("title",b)}a=!0===q.forceHandCursor||"pointer"===ja(a,"cursor");!0===l.ready&&(l.bridge&&"function"===typeof l.bridge.setHandCursor?l.bridge.setHandCursor(a):l.ready=!1);var d;B&&(d=O(l.bridge))&&(a=X(B),w(d.style,{width:a.width+"px",height:a.height+"px",top:a.top+
"px",left:a.left+"px",zIndex:""+Y(q.zIndex)}))}},Qa=function(){var a=O(l.bridge);a&&(a.removeAttribute("title"),a.style.left="0px",a.style.top="-9999px",a.style.width="1px",a.style.height="1px");B&&(N(B,q.hoverClass),N(B,q.activeClass),B=null)},Ra=function(){return B||null},Ga=function(a,b,c,d){d?t(function(){a.apply(b,c)},0):a.apply(b,c)},Fa=function(a){if(a.errors&&0<a.errors.length){var b=H(a);w(b,{type:"error",name:"clipboard-error"});delete b.success;t(function(){m.emit(b)},0)}},G=function(a){if(a&&
"string"===typeof a.type&&a){var b=a.target||null;var c=b&&b.ownerDocument||k;a=w({view:c.defaultView||f,canBubble:!0,cancelable:!0,detail:"click"===a.type?1:0,button:"number"===typeof a.which?a.which-1:"number"===typeof a.button?a.button:c.createEvent?0:1},a);b&&c.createEvent&&b.dispatchEvent&&(a=[a.type,a.canBubble,a.cancelable,a.view,a.detail,a.screenX,a.screenY,a.clientX,a.clientY,a.ctrlKey,a.altKey,a.shiftKey,a.metaKey,a.button,a.relatedTarget],c=c.createEvent("MouseEvents"),c.initMouseEvent&&
(c.initMouseEvent.apply(c,a),c._source="js",b.dispatchEvent(c)))}},Sa=function(){var a=q.flashLoadTimeout;if("number"===typeof a&&0<=a){var b=q.swfObjectId+"_fallbackContent";V=P(function(){var c=k.getElementById(b);if(c){var d=aa(c,null);var h=0<I(d.height),g=0<I(d.width),e=0<=I(d.top),v=0<=I(d.left),r=h&&g&&e&&v;c=r?null:X(c);d="none"!==d.display&&"collapse"!==d.visibility&&(r||!!c&&(h||0<c.height)&&(g||0<c.width)&&(e||0<=c.top)&&(v||0<=c.left))}else d=!1;d&&(Q(),l.deactivated=null,m.emit({type:"error",
name:"swf-not-found"}))},Math.min(1E3,a/10))}},O=function(a){for(a=a&&a.parentNode;a&&"OBJECT"===a.nodeName&&a.parentNode;)a=a.parentNode;return a||null},Ia=function(){var a,b=l.bridge,c=O(b);if(!b){b=Ta(f.location.host,q);var d="never"===b?"none":"all";c=w({jsVersion:m.version},q);var h,g,e="",v=[];if(c.trustedDomains)if("string"===typeof c.trustedDomains)var r=[c.trustedDomains];else"object"===typeof c.trustedDomains&&"length"in c.trustedDomains&&(r=c.trustedDomains);if(r&&r.length){var C=0;for(h=
r.length;C<h;C++)if(y.call(r,C)&&r[C]&&"string"===typeof r[C]&&(g=Z(r[C]))){if("*"===g){v.length=0;v.push(g);break}v.push.apply(v,[g,"//"+g,f.location.protocol+"//"+g])}}v.length&&(e+="trustedOrigins="+R(v.join(",")));!0===c.forceEnhancedClipboard&&(e+=(e?"&":"")+"forceEnhancedClipboard=true");"string"===typeof c.swfObjectId&&c.swfObjectId&&(e+=(e?"&":"")+"swfObjectId="+R(c.swfObjectId));"string"===typeof c.jsVersion&&c.jsVersion&&(e+=(e?"&":"")+"jsVersion="+R(c.jsVersion));r=e;c=q.swfPath;C=null==
q||q&&!0===q.cacheBust?(-1===q.swfPath.indexOf("?")?"?":"&")+"noCache="+ca():"";C=c+C;c=k.createElement("div");c.id=q.containerId;c.className=q.containerClass;c.style.position="absolute";c.style.left="0px";c.style.top="-9999px";c.style.width="1px";c.style.height="1px";c.style.zIndex=""+Y(q.zIndex);h=k.createElement("div");c.appendChild(h);k.body.appendChild(c);g=k.createElement("div");e="activex"===l.pluginType;g.innerHTML='<object id="'+q.swfObjectId+'" name="'+q.swfObjectId+'" width="100%" height="100%" '+
(e?'classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"':'type="application/x-shockwave-flash" data="'+C+'"')+">"+(e?'<param name="movie" value="'+C+'"/>':"")+'<param name="allowScriptAccess" value="'+b+'"/><param name="allowNetworking" value="'+d+'"/><param name="menu" value="false"/><param name="wmode" value="transparent"/><param name="flashvars" value="'+r+'"/><div id="'+q.swfObjectId+'_fallbackContent">&nbsp;</div></object>';b=g.firstChild;sa(b).ZeroClipboard=m;c.replaceChild(b,h);Sa()}b||((b=
k[q.swfObjectId])&&(a=b.length)&&(b=b[a-1]),!b&&c&&(b=c.firstChild));l.bridge=b||null;return b},Ka=function(){var a=l.bridge;if(a){var b=O(a);b&&("activex"===l.pluginType&&"readyState"in a?(a.style.display="none",function d(){if(4===a.readyState){for(var h in a)"function"===typeof a[h]&&(a[h]=null);a.parentNode&&a.parentNode.removeChild(a);b.parentNode&&b.parentNode.removeChild(b)}else t(d,10)}()):(a.parentNode&&a.parentNode.removeChild(a),b.parentNode&&b.parentNode.removeChild(b)));Q();l.ready=null;
l.bridge=null;l.deactivated=null;J=n}},Z=function(a){if(null==a||""===a)return null;a=a.replace(/^\s+|\s+$/g,"");if(""===a)return null;var b=a.indexOf("//");a=-1===b?a:a.slice(b+2);var c=a.indexOf("/");return(a=-1===c?a:-1===b||0===c?null:a.slice(0,c))&&".swf"===a.slice(-4).toLowerCase()?null:a||null},Ta=function(){return function(a,b){var c=Z(b.swfPath);null===c&&(c=a);var d=b.trustedDomains,h,g;b=[];"string"===typeof d&&(d=[d]);if("object"===typeof d&&d&&"number"===typeof d.length){var e=0;for(h=
d.length;e<h;e++)if(y.call(d,e)&&(g=Z(d[e]))){if("*"===g){b.length=0;b.push("*");break}-1===b.indexOf(g)&&b.push(g)}}g=b.length;if(0<g){if(1===g&&"*"===b[0])return"always";if(-1!==b.indexOf(a))return 1===g&&a===c?"sameDomain":"always"}return"never"}}(),ia=function(a,b){var c,d=[];"string"===typeof b&&b&&(d=b.split(/\s+/));if(a&&1===a.nodeType&&0<d.length)if(a.classList)for(b=0,c=d.length;b<c;b++)a.classList.add(d[b]);else if(a.hasOwnProperty("className")){var h=" "+a.className+" ";b=0;for(c=d.length;b<
c;b++)-1===h.indexOf(" "+d[b]+" ")&&(h+=d[b]+" ");a.className=h.replace(/^\s+|\s+$/g,"")}return a},N=function(a,b){var c,d=[];"string"===typeof b&&b&&(d=b.split(/\s+/));if(a&&1===a.nodeType&&0<d.length)if(a.classList&&0<a.classList.length)for(b=0,c=d.length;b<c;b++)a.classList.remove(d[b]);else if(a.className){var h=(" "+a.className+" ").replace(/[\r\n\t]/g," ");b=0;for(c=d.length;b<c;b++)h=h.replace(" "+d[b]+" "," ");a.className=h.replace(/^\s+|\s+$/g,"")}return a},ja=function(a,b){var c=aa(a,null).getPropertyValue(b);
return"cursor"!==b||c&&"auto"!==c||"A"!==a.nodeName?c:"pointer"},X=function(a){var b={left:0,top:0,width:0,height:0};if(a.getBoundingClientRect){a=a.getBoundingClientRect();var c=f.pageXOffset,d=f.pageYOffset,h=k.documentElement.clientLeft||0,g=k.documentElement.clientTop||0,e=0,v=0;if("relative"===ja(k.body,"position")){v=k.body.getBoundingClientRect();var r=k.documentElement.getBoundingClientRect();e=v.left-r.left||0;v=v.top-r.top||0}b.left=a.left+c-h-e;b.top=a.top+d-g-v;b.width="width"in a?a.width:
a.right-a.left;b.height="height"in a?a.height:a.bottom-a.top}return b},Q=function(){E(U);U=0;la(V);V=0},Y=function(a){if(/^(?:auto|inherit)$/.test(a))return a;var b;"number"!==typeof a||oa(a)?"string"===typeof a&&(b=Y(na(a,10))):b=a;return"number"===typeof b?b:"auto"},W=function(a){var b=l.sandboxed,c=null;a=!0===a;if(!1===fa)c=!1;else{try{var d=f.frameElement||null}catch(e){var h={name:e.name,message:e.message}}if(d&&1===d.nodeType&&"IFRAME"===d.nodeName)try{c=d.hasAttribute("sandbox")}catch(e){c=
null}else{try{var g=document.domain||null}catch(e){g=null}if(null===g||h&&"SecurityError"===h.name&&/(^|[\s\(\[@])sandbox(es|ed|ing|[\s\.,!\)\]@]|$)/.test(h.message.toLowerCase()))c=!0}}l.sandboxed=c;b===c||a||ka(ba);return c},ka=function(a){function b(r){r=r.match(/[\d]+/g);r.length=3;return r.join(".")}function c(r){r&&(d=!0,r.version&&(e=b(r.version)),!e&&r.description&&(e=b(r.description)),r.filename&&(r=r.filename,g=!!r&&(r=r.toLowerCase())&&(/^(pepflashplayer\.dll|libpepflashplayer\.so|pepperflashplayer\.plugin)$/.test(r)||
"chrome.plugin"===r.slice(-13))))}var d=!1,h=!1,g=!1,e="";if(p.plugins&&p.plugins.length)a=p.plugins["Shockwave Flash"],c(a),p.plugins["Shockwave Flash 2.0"]&&(d=!0,e="2.0.0.11");else if(p.mimeTypes&&p.mimeTypes.length)a=(a=p.mimeTypes["application/x-shockwave-flash"])&&a.enabledPlugin,c(a);else if("undefined"!==typeof a){h=!0;try{var v=new a("ShockwaveFlash.ShockwaveFlash.7");d=!0;e=b(v.GetVariable("$version"))}catch(r){try{v=new a("ShockwaveFlash.ShockwaveFlash.6"),d=!0,e="6.0.21"}catch(C){try{v=
new a("ShockwaveFlash.ShockwaveFlash"),d=!0,e=b(v.GetVariable("$version"))}catch(ha){h=!1}}}}l.disabled=!0!==d;l.outdated=e&&I(e)<I("11.0.0");l.version=e||"0.0.0";l.pluginType=g?"pepper":h?"activex":d?"netscape":"unknown"};ka(ba);W(!0);var m=function(){if(!(this instanceof m))return new m;"function"===typeof m._createClient&&m._createClient.apply(this,z(arguments))};qa(m,"version",{value:"2.2.0",writable:!1,configurable:!0,enumerable:!0});m.config=function(){return ya.apply(this,z(arguments))};m.state=
function(){return za.apply(this,z(arguments))};m.isFlashUnusable=function(){return Aa.apply(this,z(arguments))};m.on=function(){return Ba.apply(this,z(arguments))};m.off=function(){return Ca.apply(this,z(arguments))};m.handlers=function(){return Da.apply(this,z(arguments))};m.emit=function(){return Ha.apply(this,z(arguments))};m.create=function(){return Ja.apply(this,z(arguments))};m.destroy=function(){return La.apply(this,z(arguments))};m.setData=function(){return Ma.apply(this,z(arguments))};m.clearData=
function(){return Na.apply(this,z(arguments))};m.getData=function(){return Oa.apply(this,z(arguments))};m.focus=m.activate=function(){return Pa.apply(this,z(arguments))};m.blur=m.deactivate=function(){return Qa.apply(this,z(arguments))};m.activeElement=function(){return Ra.apply(this,z(arguments))};"function"===typeof define&&define.amd?define(function(){return m}):"object"===typeof module&&module&&"object"===typeof module.exports&&module.exports?module.exports=m:f.ZeroClipboard=m})(function(){return this||
window}());
