"------------------------------------------------------------------------------
" Practical Vim by Drew Neil
"------------------------------------------------------------------------------
" Chapter 2: Tips 12
" Chapter 8: Tips 47-...-49
"
" Tip 50: Find by Character
let mapleader = ','
" Tip 51: Search to Navigate
" set incsearch


"##### Modern Vim Book
set nocompatible
filetype plugin indent on



"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
"set grepprg=grep\ -nH\ $*
let g:tex_flavor = "latex"
"
" Also, this installs to /usr/share/vim/vimfiles, which may not be in
" your runtime path (RTP). Be sure to add it too, e.g:
" set runtimepath=~/.vim,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,~/.vim/after
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
" this line is responsible for loading latex-suite when a .tex file is
" opened.
"filetype plugin on
" for automatic indentation specific to LaTeX.
"filetype indent on



" ------------------------------------------------------------------------------
" configure editor with tabs and nice stuff...
" ------------------------------------------------------------------------------
set expandtab           " enter spaces when tab is pressed
"set textwidth=80        " break lines when line length increases
set tabstop=4           " use 4 spaces to represent tab
set softtabstop=4
set shiftwidth=4        " number of spaces to use for auto indent

" make backspaces more powerfull
"set backspace=indent,eol,start



"set runtimepath+=/usr/share/vim/vimfiles
"set runtimepath+=/usr/share/vim/vim82

" ------------------------------------------------------------------------------
" VimTeX configuration
" ------------------------------------------------------------------------------
syntax enable
let maplocalleader = ","
let g:vimtex_enabled = 1
let g:vimtex_compiler_enabled = 1
let g:vimtex_compiler_silent = 0
let g:vimtex_compiler_method = 'latexmk'
let g:vimtex_view_method = 'zathura'
let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'

"let g:vimtex_syntax_enabled = 1
"let g:vimtex_quickfix_mode = 0
"set conceallevel=1
"let g:tex_conceal = 'abdmg'

" Compilation:
function! Callback(msg)
  let l:m = matchlist(a:msg, '\vRun number (\d+) of rule ''(.*)''')
  if !empty(l:m)
    echomsg l:m[2] . ' (' . l:m[1] . ')'
  endif
endfunction
let g:vimtex_compiler_latexmk = {
    \ 'aux_dir': "aux",
    \ 'out_dir': {-> expand("%:t:r")},
    \ 'callback' : 1,
    \ 'continuous' : 1,
    \ 'executable' : 'latexmk',
    \ 'hooks' : [function('Callback')],
    \ 'options' : [
    \ '-verbose',
    \ '-file-line-error',
    \ '-synctex=1',
    \ '-interaction=nonstopmode',
    \ '-shell-escape'
    \ ],
    \}
let g:vimtex_compiler_latexmk_engines = {
    \ '_'                : '-pdf',
    \ 'pdflatex'         : '-pdf',
    \ 'dvipdfex'         : '-pdfdvi',
    \ 'lualatex'         : '-lualatex',
    \ 'xelatex'          : '-xelatex',
    \ 'context (pdftex)' : '-pdf -pdflatex=texexec',
    \ 'context (luatex)' : '-pdf -pdflatex=context',
    \ 'context (xetex)'  : '-pdf -pdflatex=''texexec --xtx''',
    \}

" Completion:
let g:vimtex_complete_enabled = 1
let g:vimtex_complete_close_braces = 1


let g:vimtex_quickfix_ignore_filters = [
      \ 'AtBeginDocument',
      \ 'already exist and will not be redefined',
      \]

" Toggle Math
let g:vimtex_env_toggle_math_map = {
      \ '\[': '$',
      \ '$': 'equation',
      \ '$$': '\[',
      \ '\(': '$',
      \ 'equation': 'align',
      \}

" Toggle delimiters
let g:vimtex_delim_list = {'mods' : {}}
let g:vimtex_delim_list.mods.name = [
          \ ['\left', '\right'],
          \ ['\mleft', '\mright'],
          \ ['\bigl', '\bigr'],
          \ ['\Bigl', '\Bigr'],
          \ ['\biggl', '\biggr'],
          \ ['\Biggl', '\Biggr'],
          \ ['\big', '\big'],
          \ ['\Big', '\Big'],
          \ ['\bigg', '\bigg'],
          \ ['\Bigg', '\Bigg'],
          \]
let g:vimtex_delim_toggle_mod_list = [
    \ ['\bigl', '\bigr'],
    \ ['\Bigl', '\Bigr'],
    \ ['\left', '\right'],
\]

" ------------------------------------------------------------------------------
" minpac configuration
" ------------------------------------------------------------------------------
packadd minpac
call minpac#init()
call minpac#add('k-takata/minpac', {'type': 'opt'})
" call minpac#add('tpope/vim-unimpaired')
" call minpac#add('tpope/vim-scriptease', {'type': 'opt'})
command! PackUpdate call minpac#update()
command! PackClean call minpac#clean()

" ------------------------------------------------------------------------------
" fzf configuration
" ------------------------------------------------------------------------------
nnoremap <C-p> :<C-u>FZF<CR>

" ------------------------------------------------------------------------------
" UltiSnips
" ------------------------------------------------------------------------------
let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
let g:UltiSnipsSnippetDirectories = [$VIMCONFIG.'/snippets/UltiSnips']

" ------------------------------------------------------------------------------
" Inkscape figure manager
" ------------------------------------------------------------------------------
"inoremap <C-f> <Esc>: silent exec '.!inkscape-figures create "'.getline('.').'" "'.b:vimtex.root.'/figures/"'<CR><CR>:w<CR>
"nnoremap <C-f> : silent exec '!inkscape-figures edit "'.b:vimtex.root.'/figures/" > /dev/null 2>&1 &'<CR><CR>:redraw!<CR>

" ------------------------------------------------------------------------------
" Zathura
" ------------------------------------------------------------------------------
nnoremap <F9>
    \ :exec "!szathura %:r.pdf" line('.')  col('.') "% > /dev/null"<cr><cr>
nnoremap <C-F9>
    \ :exec "!szathura %:r.pdf" > /dev/null 2>&1 &"<cr><cr>


" ------------------------------------------------------------------------------
" Language switching command
" ------------------------------------------------------------------------------
" Switch to English - mapping
nnoremap <Leader>e :<C-U>call EngType()<CR>
" Switch to Arabic - mapping
nnoremap <Leader>a :<C-U>call AraType()<CR>

" Switch to English - function
function! EngType()
    set keymap= " Restore default (US) keyboard layout
    set norightleft
endfunction

" Switch to Arabic - function
function! AraType()
    set keymap=arabic "Modified keymap. File in ~/.vim/keymap/
    set rightleft
endfunction


""" Manage Multiple Files
" Top 37
nnoremap <silent> [b :bprevious<CR>
nnoremap <silent> ]b :bnext<CR>
nnoremap <silent> [B :bfirst<CR>
nnoremap <silent> ]B :blast<CR>

""" spell
"let loaded_spellfile_plugin = 0
set spelllang=fr,en_us
set spellfile=~/.vim/spell/fr.utf-8.add
set spellfile+=~/.vim/spell/latex.utf-8.add
set spellfile+=~/.vim/spell/colors.utf-8.add

" With the following command you can turn off spellchecking for all LaTeX comments
augroup CommentSyntax
    autocmd!
    autocmd BufRead,BufNewFile * syntax match Comment /%[^"]\+$/ contains=@NoSpell
augroup END

" Close a buffer without closing the window
" from: https://stackoverflow.com/questions/1444322/how-can-i-close-a-buffer-without-closing-the-window
map <leader>q :bp<bar>sp<bar>bn<bar>bd<CR>

" Tab Pages
nnoremap <leader>tn :tabnew<CR>:tabmove<CR>
nnoremap <leader>tc :tabclose<CR>
nnoremap <tab> :tabnext<CR>
nnoremap <S-tab> :tabprevious<CR>


" ------------------------------------------------------------------------------
" Color Scheme
" ------------------------------------------------------------------------------
colorscheme desert
" colorscheme shine
" set background=dark

" set ruler               " show line and column number
" syntax on               " syntax highlighting
" set showcmd             " show (partial) command in status line


set cursorcolumn
set cursorline

" ------------------------------------------------------------------------------
" Copy/Paste
" ------------------------------------------------------------------------------
vnoremap <leader>y "+y
nnoremap <leader>yy "+yy
nnoremap <leader>ya gg"+yG
set clipboard=unnamed

" Don't touch unnamed register when pasting over visual selection
xnoremap <expr> p 'pgv"' . v:register . 'y'


" ------------------------------------------------------------------------------
" INDENTATION
" ------------------------------------------------------------------------------
let g:tex_indent_items = 1
let g:vimtex_indent_enabled = 1
let g:vimtex_indent_bib_enabled = 1
let g:vimtex_indent_conditionals = {
      \ 'open': '\v%(\\newif)@<!\\if%(f>fieldnamenumequalthenelsetoggle)@!',
      \ 'else': '\\else\>',
      \ 'close': '\\fi\>',
      \}


" ------------------------------------------------------------------------------
" FOLDING
" ------------------------------------------------------------------------------
let g:vimtex_fold_enabled = 1
let g:vimtex_fold_types = {
      \ 'preamble' : {'enabled' : 1},
      \ 'envs' : {'enabled' : 1},
      \ 'sections' : {'enabled' : 1},
      \ 'comments' : {'enabled' : 1},
      \}

" ------------------------------------------------------------------------------
" MAPPING
" ------------------------------------------------------------------------------
"map! <C-F> <Esc>gUiw`]a
" Some mapping from learnvimscriptthehardway
" imap <C-u> <Esc>viwU`]a
"nnoremap <leader>ev :vsplit $MYVIMRC<cr>
"nnoremap <leader>sv :source $MYVIMRC<cr>
"nnoremap <leader>" viw<esc>a"<esc>bi"<esc>lel
"vnoremap <leader>" <esc>`>a"<esc>`<i"<esc>``l
"inoremap jk <esc>
"
vnoremap <localleader>w :<C-u>s/\%V\s\+//g<CR>gv<Esc>
nnoremap <localleader>p :<C-u>%s/\(\~\\|fig\)\@<!\s*\(;\\|:\\|?\)/\~\2/gc
nnoremap <localleader>m :<C-u>%s/\v\$\$\n?(\_.{-})\n?\$\$/\='\['."\r\t".substitute(submatch(1), "\n", "\r\t", "g")."\r".'\]'/gc<CR>


" ------------------------------------------------------------------------------
" AUTOCOMMANDS
" ------------------------------------------------------------------------------
"autocmd FileType latex nnoremap <buffer> <localleader>c I%<esc>
"autocmd FileType python nnoremap <buffer> <localleader>c I#<esc>
"autocmd FileType latex nnoremap <localleader>m viw<esc>`>a"<esc>`<i"<esc>``l
"augroup python_statusline
"    autocmd!
"    autocmd FileType python setlocal statusline=%f%=%l/%L
"augroup END
"autocmd FileType latex nnoremap <buffer> <localleader>= vie<gv><esc>
autocmd FileType latex nnoremap <buffer> <localleader>i v0c<Tab>\item<esc>
"autocmd FileType latex nnoremap <buffer> <localleader>m ts$
" augroup latex_mappings
"     autocmd!
"     autocmd FileType tex nnoremap <buffer> <localleader>m ts$
" augroup END
" autocmd FileType latex nnoremap <buffer> <localleader>m :<C-u>execute "normal! ts$"<CR>
autocmd FileType tex nnoremap <buffer> <localleader>e :<c-u>execute "normal vie<gv>"<cr>
autocmd FileType tex nnoremap <buffer> <localleader>n :<c-u>execute "normal ]Nvi$"<CR>
autocmd FileType tex setlocal textwidth=80
autocmd FileType tex setlocal colorcolumn=80 " Right vertical guide
