var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,d,f){b instanceof String&&(b=String(b));for(var k=b.length,g=0;g<k;g++){var r=b[g];if(d.call(f,r,g,b))return{i:g,v:r}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,d,f){if(b==Array.prototype||b==Object.prototype)return b;b[d]=f.value;return b};$jscomp.getGlobal=function(b){b=["object"==typeof globalThis&&globalThis,b,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var d=0;d<b.length;++d){var f=b[d];if(f&&f.Math==Math)return f}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(b,d){var f=$jscomp.propertyToPolyfillSymbol[d];if(null==f)return b[d];f=b[f];return void 0!==f?f:b[d]};
$jscomp.polyfill=function(b,d,f,k){d&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(b,d,f,k):$jscomp.polyfillUnisolated(b,d,f,k))};$jscomp.polyfillUnisolated=function(b,d,f,k){f=$jscomp.global;b=b.split(".");for(k=0;k<b.length-1;k++){var g=b[k];if(!(g in f))return;f=f[g]}b=b[b.length-1];k=f[b];d=d(k);d!=k&&null!=d&&$jscomp.defineProperty(f,b,{configurable:!0,writable:!0,value:d})};
$jscomp.polyfillIsolated=function(b,d,f,k){var g=b.split(".");b=1===g.length;k=g[0];k=!b&&k in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var r=0;r<g.length-1;r++){var v=g[r];if(!(v in k))return;k=k[v]}g=g[g.length-1];f=$jscomp.IS_SYMBOL_NATIVE&&"es6"===f?k[g]:null;d=d(f);null!=d&&(b?$jscomp.defineProperty($jscomp.polyfills,g,{configurable:!0,writable:!0,value:d}):d!==f&&($jscomp.propertyToPolyfillSymbol[g]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(g):$jscomp.POLYFILL_PREFIX+g,g=
$jscomp.propertyToPolyfillSymbol[g],$jscomp.defineProperty(k,g,{configurable:!0,writable:!0,value:d})))};$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(d,f){return $jscomp.findInternal(this,d,f).v}},"es6","es3");
var AutoComplete=function(b,d){function f(a){var c=-1,e="";$.each(n.multipleSeparator,function(m,p){(m=a.lastIndexOf(p))>c&&(e=p,c=m)});return[c,e]}function k(){h.hide()}function g(a){if(!w)switch(a.keyCode){case 38:a.preventDefault();u(-1);1==n.moveToSelect&&r();break;case 40:a.preventDefault();u(1);1==n.moveToSelect&&r();break;case 9:case 13:n.moveToSelect?h.hide():h.is(":visible")&&(v()?h.hide():u(1),a.preventDefault(),a.stopPropagation());break;case 27:h.is(":visible")&&(a.preventDefault(),a.stopPropagation(),
h.hide());break;case 32:h.is(":visible")&&(a.stopPropagation(),h.hide());l.val();break;default:q=-1,x&&clearTimeout(x),x=setTimeout(function(){l.val().length<n.minChars?h.hide():B(l.val())},n.delay)}}function r(){var a=h.find("li").eq(q).html();l.val(a)}function v(a){void 0!==a&&(q=a,u(0));a=q;if(!(0>a)){var c=h.find("li").eq(a).text();0<=c.indexOf(" ")&&(c='"'+c+'"');if("multiple"==n.mode){a=l.val();var e=f(a);new_value=1<=e[0]?a.substr(0,e[0]+1)+c+e[1]:c+" "}else new_value=c;l.val(new_value);l.trigger("input");
h.hide();n.onItemSelect&&setTimeout(function(){n.onItemSelect(c)},1);setTimeout(function(){l[0].focus();var m=l[0],p=l.val().length;m.createTextRange?(m=m.createTextRange(),m.move("character",p),m.select()):0<=m.selectionStart&&(m.focus(),m.setSelectionRange(p,p))},13);return!0}}function u(a){var c=h.find("li");0!=c.size()&&(q+=a,0>q?q=c.size()-1:q>=c.size()&&(q=0),c.removeClass("over").eq(q).addClass("over"))}function B(a){if("multiple"==n.mode){var c=f(a),e="";e=0<c[0]?a.substr(c[0]+1):a;y=""==
a.substring(0,c[0])?a.substring(0,c[0]):a.substring(0,c[0])+" ";if(0<e.length)tags=ParseTags.parseTags(e,!0),a=tags.pop();else{a=e;h.hide();return}}var m=a.toLowerCase();a=m;c=[];var p=[];1==n.moveToSelect&&0==a.indexOf("#")&&(a=a.slice(1));e=0;for(var t;t=n.data[e],e<n.data.length;e++)0==t.toLowerCase().indexOf(a)?0==m.indexOf("#")?c.push("#"+t):c.push(t):0!=t.toLowerCase().indexOf(a)&&-1!=t.toLowerCase().indexOf(a)&&(0==m.indexOf("#")?p.push("#"+t):p.push(t));p.sort(function(C,D){return C.indexOf(a)<=
D.indexOf(a)?-1:1});c=c.concat(p);m=[];for(e=0;e<c.length;e++)-1!=c[e].indexOf("#")&&-1!=c[e].indexOf(" ")?(p=c[e].slice(1),p='#"'+p+'"'):p=c[e],m.push(y+p);n.moveToSelect?z(a,m):z(a,c)}function z(a,c){c&&0<c.length?(7<c.length&&c.splice(7,99999),a=function(e){for(var m=e.offsetLeft||0,p=e.offsetTop||0;e=e.offsetParent;)m+=e.offsetLeft,p+=e.offsetTop;$.browser.opera&&"CSS1Compat"!=document.compatMode&&(p+=30);return{x:m+0,y:p+0}}(l[0]),h.find("li").unbind(),h.find("ul").html($.map(c,function(e){return"<li>"+
e+"</li>"}).join("")).end().css({top:n.moveToSelect?a.y+l[0].offsetHeight-4:a.y+l[0].offsetHeight+3,left:a.x}).show(),h.find("li").mouseover(function(e){q=h.find("li").index(e.target);u(0)}).mousedown(function(e){q=h.find("li").index(e.target);u(0);v();return!1})):h.hide()}function A(a){h.hide()}var l=$(b),x,q=-1,y=null,w=!1;l[0].autoCompleter&&l[0].autoCompleter.destroy();l[0].autoCompleter=this;var n=d=$.extend({inputClass:"ac_input",moveToSelect:!1,resultsClass:"ac_results",minChars:1,delay:100,
matchCase:0,matchSubset:1,matchContains:0,mustMatch:0,loadingClass:"ac_loading",selectFirst:!1,selectOnly:!1,mode:"multiple",multipleSeparator:" "},d||{});"string"==typeof n.multipleSeparator&&(n.multipleSeparator=n.multipleSeparator.split(""));this.destroy=function(){l.unbind("keydown",g).unbind("blur",A);l.on("input",function(){l.val()});$(window).unbind("scroll",k);l[0].autoCompleter=null};this.disable=function(){w=!0};this.enable=function(){w=!1};l.attr("autocomplete","off").addClass(n.inputClass).bind("keydown",
g).bind("blur",A).bind("click",function(){setTimeout(function(){""==l.val()&&h.hide()},100)});$.browser.supportPositionFixed||$(window).bind("scroll",k);var h=$("#"+d.id);0==h.size()&&(h=$('<div id="'+d.id+'"><ul></ul></div>').addClass(n.resultsClass).hide().css({position:$.browser.supportPositionFixed?"fixed":"absolute"}).appendTo(document.body).hide(),$.browser.ieBelow7&&h.append(document.createElement("<iframe class=\"bgiframe\" src=\"javascript:false;document.write('');\" tabindex=\"-1\" style=\"display:block; position:absolute; top: expression(((parseInt(this.parentNode.currentStyle.borderTopWidth)  || 0) * -1) + 'px'); left:expression(((parseInt(this.parentNode.currentStyle.borderLeftWidth) || 0) * -1) + 'px'); z-index:-1; filter:Alpha(Opacity='0'); width:expression(this.parentNode.offsetWidth + 'px'); height:expression(this.parentNode.offsetHeight + 'px')\"/>")))};
