var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};
$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in d))return;d=d[g]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(d,e,{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};
$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};
$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};
$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};
$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var c=a.next();$jscomp.generator.ensureIteratorResultIsObject_(c);if(c.done)this.yieldResult=c.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(c.value,b)};$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};
$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(c){return{value:c,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var d=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var e=d.value}catch(f){return this.context_.yieldAllIterator_=null,this.context_.throw_(f),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.initSymbol=function(){};$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(e,f){this.$jscomp$symbol$id_=e;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:f})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c=0,d=function(e){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(e||"")+"_"+c++,e)};return d},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=$jscomp.global[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&$jscomp.defineProperty(d.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(g){return g instanceof e?g:new e(function(h,k){h(g)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(g){if(null==this.batch_){this.batch_=[];var h=this;this.asyncExecuteFunction(function(){h.executeBatch_()})}this.batch_.push(g)};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(g){d(g,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var g=
this.batch_;this.batch_=[];for(var h=0;h<g.length;++h){var k=g[h];g[h]=null;try{k()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(g){this.asyncExecuteFunction(function(){throw g;})};var e=function(g){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var h=this.createResolveAndReject_();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}};e.prototype.createResolveAndReject_=function(){function g(l){return function(m){k||(k=!0,l.call(h,m))}}var h=this,k=!1;
return{resolve:g(this.resolveTo_),reject:g(this.reject_)}};e.prototype.resolveTo_=function(g){if(g===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof e)this.settleSameAsPromise_(g);else{a:switch(typeof g){case "object":var h=null!=g;break a;case "function":h=!0;break a;default:h=!1}h?this.resolveToNonPromiseObj_(g):this.fulfill_(g)}};e.prototype.resolveToNonPromiseObj_=function(g){var h=void 0;try{h=g.then}catch(k){this.reject_(k);return}"function"==typeof h?
this.settleSameAsThenable_(h,g):this.fulfill_(g)};e.prototype.reject_=function(g){this.settle_(2,g)};e.prototype.fulfill_=function(g){this.settle_(1,g)};e.prototype.settle_=function(g,h){if(0!=this.state_)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.state_);this.state_=g;this.result_=h;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var g=0;g<this.onSettledCallbacks_.length;++g)f.asyncExecute(this.onSettledCallbacks_[g]);
this.onSettledCallbacks_=null}};var f=new b;e.prototype.settleSameAsPromise_=function(g){var h=this.createResolveAndReject_();g.callWhenSettled_(h.resolve,h.reject)};e.prototype.settleSameAsThenable_=function(g,h){var k=this.createResolveAndReject_();try{g.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};e.prototype.then=function(g,h){function k(n,p){return"function"==typeof n?function(r){try{l(n(r))}catch(t){m(t)}}:p}var l,m,q=new e(function(n,p){l=n;m=p});this.callWhenSettled_(k(g,l),k(h,m));return q};
e.prototype.catch=function(g){return this.then(void 0,g)};e.prototype.callWhenSettled_=function(g,h){function k(){switch(l.state_){case 1:g(l.result_);break;case 2:h(l.result_);break;default:throw Error("Unexpected state: "+l.state_);}}var l=this;null==this.onSettledCallbacks_?f.asyncExecute(k):this.onSettledCallbacks_.push(k)};e.resolve=c;e.reject=function(g){return new e(function(h,k){k(g)})};e.race=function(g){return new e(function(h,k){for(var l=$jscomp.makeIterator(g),m=l.next();!m.done;m=l.next())c(m.value).callWhenSettled_(h,
k)})};e.all=function(g){var h=$jscomp.makeIterator(g),k=h.next();return k.done?c([]):new e(function(l,m){function q(r){return function(t){n[r]=t;p--;0==p&&l(n)}}var n=[],p=0;do n.push(void 0),p++,c(k.value).callWhenSettled_(q(n.length-1),m),k=h.next();while(!k.done)})};return e},"es6","es3");
$jscomp.iteratorFromArray=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6","es3");var D=D||{},newClickVersion="3.3.91";
function getSelectedTab(a){chrome.tabs.query({active:!0,currentWindow:!0},function(b){a(b[0])})}function postMessageRefreashPage(){window.postMessage({action:"refreshPage"},"*")}var doc_html="",readerData={};
D.useConfig=function(a){D.config={cn:{TOOLBAR_SERVER:"https://toolbar3.diigo.cn",UPLOAD_SERVER:"https://www.diigo.cn",DOMAIN:"diigo.cn"},www:{TOOLBAR_SERVER:"https://toolbar3.diigo.com",UPLOAD_SERVER:"https://www.diigo.com",DOMAIN:"diigo.com"},preview:{TOOLBAR_SERVER:"https://preview.diigo.com",UPLOAD_SERVER:"https://preview.diigo.com",DOMAIN:"diigo.com"}}[{dev:"cn",dev1:"preview",dev2:"www"}[a]||a];/dev/.test(a)&&(D.config.dontUseGA=!0)};var GlobalData;
function resetGlobalData(){var a={signedIn:!1,user:"",userId:null,realName:"",userLevel:0,myTags:[],myTagsWithCount:[],myBmLists:[],myGroups:[],myContacts:[],outliners:[],permissions:{capture:!0,image:!0,premium:!0,snapshot:!0,highlight:!0}};saveStorage("globalData",a);GlobalData=a}
var SignInManager=D.SignInManager={checkSignInCookie:function(a){var b=this;chrome.cookies.get({url:"https://www.diigo.com",name:"diigoandlogincookie"},function(c){if(c)var d=c.value.split("-.-")[1];b.onUsernameSeen(d);a&&a()})},onUsernameSeen:function(a){var b=this,c,d;return $jscomp.asyncExecutePromiseGeneratorProgram(function(e){if(1==e.nextAddress)return c=b,e.yield(getStorage("globalData"),2);d=e.yieldResult;a?c.isSignedIn()?a!=d.user&&(c._onSignOut(),c._onSignIn(a)):c._onSignIn(a):c.isSignedIn()&&
c._onSignOut();e.jumpToEnd()})},isSignedIn:function(){return GlobalData.user&&GlobalData.signedIn},isUserInfoLoaded:function(){return this.isSignedIn()&&GlobalData.username},_onSignIn:function(a){debug("[SignInManager] _onSignIn",a);updateStorage("globalData",{user:a,signedIn:!0});GlobalData.user=a;GlobalData.signedIn=!0;this.loadMyStuff();EventMachine.needToReload();forEachWebTab(function(b){Messenger.send(b.id,{name:"signIn",details:{user:a},fromTabId:null})});CrossPromotion.userChanged()},_onSignOut:function(){debug("[SignInManager] _onSignOut",
GlobalData.user);resetGlobalData();chrome.storage.local.remove(["researchModeData","researchMode"]);Preloader.cleanUpAllTabData();forEachWebTab(function(a){Messenger.send(a.id,{name:"signOut",fromTabId:null})})},loadMyStuff:function(){debug("[SignInManager] loadMyStuff",GlobalData.user);(new WebAPICall).invoke("user_loadMyStuff",{what:"myTags myGroups myProfile myBookmarkLists myContacts permissions"},{user:GlobalData.user,transId:null,complete:function(a){var b,c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(d){if(1==
d.nextAddress){if(!a.resp)return d.jumpTo(0);GlobalData.permissions=a.resp.result.permissions;updateStorage("globalData",{permissions:a.resp.result.permissions});return d.yield(getStorage(["prefs.directlyShowSearchResults","prefs.shortcutAnnotate","free_trial_count"]),3)}b=d.yieldResult;"undefined"===typeof b["prefs.directlyShowSearchResults"]&&"undefined"!==typeof b["prefs.shortcutAnnotate"]&&(GlobalData.permissions.autoShowAnnotation?(setStorage("prefs.comboSearch",!0),setStorage("prefs.directlyShowSearchResults",
!0)):setStorage("prefs.directlyShowSearchResults",!1));c=a.resp.result.permissions.autoShowAnnotation;"undefined"!==typeof c&&0==c&&(b.free_trial_count?b.free_trial_count&&100<=b.free_trial_count&&(Prefs.set({"prefs.autoload":!1}),Prefs.set({free_trial:!1})):(Prefs.set({"prefs.autoload":!0}),Prefs.set({free_trial:!0})));forEachWebTab(function(e){Messenger.send(e.id,{name:"myStuffLoaded",details:a.resp.result,fromTabId:null})});d.jumpToEnd()})}})}},Preloader=D.Preloader={table:{},init:function(){},
onTabRemoved:function(a){this.cleanUpTabData(a)},onTabUpdated:function(a,b,c){var d=this,e,f,g,h,k;return $jscomp.asyncExecutePromiseGeneratorProgram(function(l){if(1==l.nextAddress)return console.log(b.status),e=d,l.yield(Prefs.get("prefs.autoload"),2);f=l.yieldResult;if("loading"==b.status){e.table[a]&&e.cleanUpTabData(a);if(!SignInManager.isSignedIn())return l.return();g=c.url;if(!isURLApplicable(g))return l.return();h=new WebAPICall;e.table[a]={api:h,loading:!0};debug("[Preloader]","loading for",
a,g);h.invoke("bm_loadBookmark",{url:g,what:"bookmarkInfo annotations pageComments"},{user:GlobalData.user,complete:function(m){e.table[a].loading=!1;m.cancelled||(m=m.resp)&&1==m.code&&(e.table[a].result=m.result,e.user=m.user,m.result.saved&&e.updateBrowserActionIcon(c.id,!0),Messenger.send(a,{name:"refreshBookmarkInfo"}),"true"==f&&e.hasPrivateAnnotation(m.result.annotations,m.user)&&sendRunCommand(a,{type:"autoshow"}))}})}else"complete"==b.status&&(e.table[a]?1!=e.table[a].loading&&(k=e.table[a].result,
"true"==f&&e.hasPrivateAnnotation(k.annotations,e.user)&&sendRunCommand(a,{type:"autoshow"})):console.log(e.table[a]));l.jumpToEnd()})},hasPrivateAnnotation:function(a,b){var c=0,d;for(d=0;d<a.length;d++)a[d].user!=b&&1!=a[d].onlyInGroup||c++;return 0==c?!1:!0},cleanUpAllTabData:function(){for(var a in this.table)this.cleanUpTabData(a)},cleanUpTabData:function(a){this.table[a]&&(debug("[Preloader] cleaning up",a),this.table[a].api.cancel(),delete this.table[a])},preloadedResultForTab:function(a){return this.table[a]?
this.table[a].result:null},isPreloadingForTab:function(a){return(a=this.table[a])&&a.loading},updateBrowserActionIcon:function(a,b){chrome.action.setIcon({tabId:a,path:"/img/"+(b?"logo-19-bookmarked.png":"logo-19.png")})}};
function isURLApplicable(a,b){var c=parseUri(a),d=c.path;if(!/^https?$/i.test(c.protocol))return!1;if(/\.?diigo\./i.test(c.host)){if(/^\/annotated\//i.test(d)||/(player|slides?)\.diigo\./i.test(c.host)&&/^\/(list|feed)/i.test(d)||/^\/bookmark\//i.test(d)||/^\/user\//i.test(d)||/^\/cached/i.test(d)||/^\/item\/pdf/i.test(d)&&!b)return!1}else if(/^https?:\/\/chrome\.google\.com\/(extensions|webstore)/i.test(a))return!1;return!0}
var WebAPI={saveBookmark:function(a,b){this.webCall("bm_saveBookmark",a,b)},createPdfItem:function(a,b){this.webCall("pdf_createItem",a,b)},refreshStuff:function(a){this.webCall("user_loadMyStuff",{what:"myTags myGroups myProfile myBookmarkLists myContacts permissions"},null,a)},deleteBookmark:function(a){this.webCall("bm_deleteBookmark",a)},createList:function(a,b){this.webCall("list_create",{title:a,mode:2},null,b)},mhtml_upload_done:function(a,b){this.webCall("mhtml_upload_done",a,null,b)},webCall:function(a,
b,c,d){var e=new WebAPICall;"saveLink"!=c&&chrome.action.setIcon({tabId:b.tabId,path:"/img/doing-icon.png"});e.invoke(a,b,{user:GlobalData.user,complete:function(f){console.log("api invoke",a);console.log(f.status,f.resp);if(f&&1==f.resp.code){if("saveLink"!=c){var g="img/"+("bm_saveBookmark"==a||"pdf_createItem"==a?"logo-19-bookmarked.png":"logo-19.png");console.log("save success",f.resp);chrome.action.setIcon({tabId:b.tabId,path:g});"bm_saveBookmark"==a||"bm_deleteBookmark"==a?chrome.tabs.sendMessage(b.tabId,
{name:"saveBookmarkSuccess",data:f.resp.result,ctx:b}):"mhtml_upload_done"==a&&chrome.tabs.sendMessage(b.tabId,{name:"saveMHTMLSuccess",result:f.resp.result})}d&&("list_create"==a?(GlobalData.outliners.push(f.resp.result.list),GlobalData.outliners.sort(function(h,k){return h.title>k.title?1:-1}),updateStorage("globalData",{outliners:GlobalData.outliners}),console.log(a,d),d({outliners:GlobalData.outliners,lists:GlobalData.myBmLists,newOutliner:f.resp.result.list})):"user_loadMyStuff"==a?(extend(GlobalData,
f.resp.result),console.log("update GlobalData",GlobalData),updateStorage("globalData",GlobalData),d({outliners:GlobalData.outliners,lists:GlobalData.myBmLists,groups:GlobalData.myGroups})):d())}}})}};function updateTabTable(a,b){a=Preloader.table[b.tabId].result;console.log(a);var c=a.bookmarkInfo||{};a.saved=!0;a.url=b.url;c.description=b.description;c.title=b.title;c.unread=b.unread;c.mode=b.mode;c.tags=b.tags}
var Messenger={send:function(a,b,c){debug("bg send msg to",a,b.name,b);chrome.tabs.sendMessage(a,b,c)},onMessage:function(a,b,c){debug("bg recv msg from",b.tab&&b.tab.id,a.name,a,b);if(this.handlers[a.name])return this.handlers[a.name](a,b,c),!0},handlers:{sendAnalysisData:function(a,b,c){sendAnalysisData(a.data)},popupSaveBookmark:function(a,b,c){WebAPI.saveBookmark(a.data);c()},showToolbar:function(a,b,c){console.log("show toolbar");showToolbar(a.type,a.tabId)},getNewClickVersion:function(a,b,c){c(newClickVersion)},
newtip:function(a,b,c){chrome.action.setBadgeText({text:""});window.open("https://www.diigo.com/extension/chrome/new.html?v="+D.version)},annotateAfterSaving:function(a,b,c){1==a.data?saveStorage("prefs.annotateAfterSaving","true"):saveStorage("prefs.annotateAfterSaving","false")},capture:function(a,b,c){chrome.tabs.captureVisibleTab({format:"png"},function(d){getSelectedTab(function(e){console.log("send dataURL",a);chrome.tabs.sendMessage(e.id,{name:"dataURL",dataURL:d,cw:a.cw,ch:a.ch,ct:a.ct,cl:a.cl,
target:a.target})})})},captureVideo:function(a,b,c){var d=a.scale;console.log(d);chrome.tabs.captureVisibleTab({format:"png"},function(e){var f=document.createElement("canvas"),g=f.getContext("2d");$(f).attr("width",d.width).attr("height",d.height);document.body.appendChild(f);var h=new Image;h.src=e;h.onload=function(){g.drawImage(h,d.left,d.top,d.width,d.height,0,0,d.width,d.height);var k=f.toDataURL();console.log(k);c(k);$(f).remove()}})},WebAPI:function(a,b,c){var d=a.details;console.log(d.cmd);
(new WebAPICall).invoke(d.cmd,d.data,{user:GlobalData.user,transId:d.transId,isInGroup:d.isInGroup,complete:function(e){console.log(d.cmd,e.status,e.resp,c);e&&c({status:e.status,resp:e.resp,cmd:e.cmd})}})},ifSignIn:function(a,b,c){chrome.cookies.get({url:"https://www.diigo.com",name:"diigoandlogincookie"},function(d){d&&getSelectedTab(function(e){chrome.tabs.sendMessage(e.id,{name:"SignedIn"})})})},doHighlight:function(){var a,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==
c.nextAddress)return c.yield(getStorage("free_trial_count"),2);a=c.yieldResult;b=parseInt(a);b+=1;saveStorage("free_trial_count",b);c.jumpToEnd()})},getLastFocusedWindow:function(a,b,c){getSelectedTab(function(d){console.log("tab",d);d.openerTabId&&chrome.tabs.get(d.openerTabId,function(e){var f=/https?:\/\/(?:.+\.)?google\.[a-z]{2,3}(?:\.[a-z]{2})?(?:\:[0-9]+)?\/(?:webhp[^#]*)?(#((?:.+&)?q=)([^&]+)(.*)&fp=[^&]+)/;if(/https?:\/\/(?:.+\.)?google\.[a-z]{2,3}(?:\.[a-z]{2})?(?:\:[0-9]+)?\/(?:advanced_)?search.*(([?&]q=)([^&]+))/.test(e.url)||
f.test(e.url)){debug("it's a google search");e=decodeURIComponent(e.url).match(/[&|?]q=(.*?)(&|$|#)/g);f=e.length;for(var g=0;g<f;g++)var h=e[g].match(/[&|?]q=(.*?)(&|$|#)/i)[1]}chrome.tabs.sendMessage(d.id,{name:"googleSearchRecommend",googleSearchKeyWord:h})})})},listCreateSuccess:function(a,b,c){GlobalData.outliners.push(a.data);updateStorage("globalData",{outliners:GlobalData.outliners});chrome.tabs.query({},function(d){d.forEach(function(e,f,g){"https://www.diigo.com/outliner"===e.url?chrome.scripting.executeScript({target:{tabId:e.id},
func:postMessageRefreshPage},function(){console.log(e,"notify update list")}):e.id!==b.tab.id&&chrome.tabs.sendMessage(e.id,{name:"refreshOutliner"})})})},updateGlobalData:function(a,b,c){var d={};a=a.details;for(var e in a)a[e]!=GlobalData[e]&&(d[e]=GlobalData[e]=a[e]);forEachWebTab(function(f){Messenger.send(f.id,{name:"globalDataChanged",details:{changes:d},fromTabId:b.tab.id})});updateStorage("globalData",GlobalData)},updatePermission:function(a,b,c){c=a.data;switch(a.type){case "highlight":GlobalData.permissions.annPermission=
c;updateStorage("globalData",{permissions:GlobalData.permissions});break;case "image":GlobalData.permissions.imagePermission=c;updateStorage("globalData",{permissions:GlobalData.permissions});break;case "pdf":GlobalData.permissions.pdfPermission=c,updateStorage("globalData",{permissions:GlobalData.permissions})}forEachWebTab(function(d){Messenger.send(d.id,{name:"globalDataChanged",details:{changes:{permissions:GlobalData.permissions}},fromTabId:b.tab.id})})},initialData:function(a,b,c){Prefs.get(Prefs.prefsToPreload).then(function(d){c({extensionID:D.extensionID,
globalData:GlobalData,preloadedPrefs:d,tabId:b.tab.id,version:D.version,loadBookmarkResult:Preloader.preloadedResultForTab(b.tab.id),shouldLoadBookmarkByMyself:!Preloader.isPreloadingForTab(b.tab.id),shoudLoadMyStuff:!GlobalData.realName||EventMachine.needToReload()})})},mytags:function(a,b,c){c(GlobalData.myTags)},bookmarkChanged:function(a,b,c){D.Preloader.updateBrowserActionIcon(b.tab.id,a.details.saved)},updateBrowserActionIconToDoing:function(a,b,c){chrome.action.setIcon({tabId:b.tab.id,path:"/img/doing-icon.png"})},
saveImageToDiigo:function(a,b,c){D.saveImageToDiigo(a.details,b.tab,a.Type)},uploadImageToDiigo:function(a,b,c){D.saveImageToDiigo(a.src,b.tab,a.type)},checkIn:function(a,b,c){},activateMeAfterSignIn:function(a,b,c){D.activateTheTabIdAfterSignIn=b.tab.id},createTab:function(a,b,c){chrome.tabs.create({url:a.details.url,index:b.tab.index+1})},closeTab:function(a,b,c){setTimeout(function(){chrome.tabs.remove(b.tab.id)},600)},saveThisLink:function(a,b,c){WebAPI.saveBookmark(a.data,"saveLink")},saveBookmarkFromBookmarkWin:function(a,
b,c){a.data.tabId=b.tab.id;WebAPI.saveBookmark(a.data)},openWindow:function(a,b,c){chrome.tabs.create({url:a.details.url})},getPrefs:function(a,b,c){Prefs.get(a.details.keys).then(function(d){c(d)});return!0},setPrefs:function(a,b,c){a=Prefs.set(a.details.data,null,b.tab.id);c&&c(a)},getUserData:function(a,b,c){var d,e;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){if(1==f.nextAddress)return d=a.details.keys,f.yield(Prefs.getUserData(d),2);e=f.yieldResult;c(e);f.jumpToEnd()})},setUserData:function(a,
b,c){a=Prefs.setUserData(a.details.data,b.tab.id);c&&c(a)},twitterGrabPin:function(a,b,c){TwitterOAuth.getAccessToken(a.details.pin,b.tab.id)},twitterCheckAuthentication:function(a,b,c){a=TwitterOAuth.checkAuthentication();a.then?a.then(function(d){c(d)}):c(a)},twitterSend:function(a,b,c){TwitterOAuth.updateStatus(a.details,c)},twitterChangeUser:function(a,b,c){D.switchToTabIdAfterTwitterOauth=b.tab.id;TwitterOAuth.changeUser()},twitterConnect:function(a,b,c){D.switchToTabIdAfterTwitterOauth=b.tab.id;
TwitterOAuth.changeUser()},shortenUrl:function(a,b,c){var d=a.details.url;fetch("https://api.bit.ly/shorten?version=2.0.1&login=diigo&apiKey=R_051efe0ca04a325db066155db77c2d08&longUrl="+encodeURIComponent(d)).then(function(e){return e.json()}).then(function(e){console.log("bit.ly",e);if("success"==e.status){try{var f=JSON.parse(req.responseText)}catch(g){error("error parsing json from bit.ly",req.responseText);c(d);return}"OK"==f.statusCode?(d=f.results[d].shortUrl,debug("[bit.ly url] success",d)):
error("[bit.ly url] failure",f)}else error("[bit.ly url] failure",req);c(d)}).catch(function(e){console.log(e);c(d)})},uploadCache:function(a,b,c){a=a.details;(new CachePage({urlMD5:a.urlMD5,text:a.text,html:a.html,groups:a.groups,tabId:b.tab.id,username:GlobalData.user,ispdf:a.ispdf,pdfurl:a.pdfurl})).start()},googleEvent:function(a,b,c){window.ga&&(a=a.msg,window.ga("send","event",a.eventType,a.action,a.label))},pickPromotionMessage:function(a,b,c){c(CrossPromotion.pickMessage())},promotionMessageClicked:function(a,
b,c){CrossPromotion.messageClicked(a.details.id)},searchDiigoGoogle:function(a,b,c){D.searchDiigoGoogle(a.details.text,b.tab)},copy:function(a,b,c){var d=a.details;getCurrentTab().then(function(e){chrome.tabs.sendMessage(e.id,{name:"copy",content:d})})},changeColor:function(a,b,c){saveStorage("prefs.lastUsedColor",a.color)},closeComboSearch:function(a,b,c){saveStorage("prefs.comboSearch","false")},getSearchPref:function(a,b,c){var d;return $jscomp.asyncExecutePromiseGeneratorProgram(function(e){if(1==
e.nextAddress)return e.yield(getStorage("prefs.directlyShowSearchResults"),2);d=e.yieldResult;c("true"==d&&GlobalData.permissions.autoShowAnnotation);e.jumpToEnd()})},openPdf:function(a,b,c){".pdf"==a.url.substring(a.url.length-4)?chrome.tabs.create({url:"/pdf/viewer.html?file="+a.url}):chrome.tabs.create({url:"/pdf/viewer.html"})},doc_html:function(a,b,c){chrome.tabs.sendRequest(b.tab.id,{name:"doc_html",data:a})},openReader:function(a,b,c){readerData.uri=a.data.uri;readerData.body=a.data.body;readerData.title=
a.data.title;chrome.tabs.update(b.tab.id,{url:"/reader.html"})},refreshBookmark:function(a,b,c){var d=b.tab.id,e=b.tab;a=b.tab.url;(new WebAPICall).invoke("bm_loadBookmark",{url:a,what:"bookmarkInfo annotations pageComments"},{user:GlobalData.user,complete:function(f){Preloader.table[d].loading=!1;f.cancelled||(f=f.resp)&&1==f.code&&(Preloader.table[d].result=f.result,Preloader.user=f.user,f.result.saved&&Preloader.updateBrowserActionIcon(e.id,!0),Messenger.send(d,{name:"refreshBookmark"}))}})},importKindle:function(a,
b,c){$.ajax({type:"POST",url:D.config.UPLOAD_SERVER+"/import_all/kindle",data:{toolbar_data:JSON.stringify(a.data)},success:function(){chrome.tabs.sendMessage(b.tab.id,{name:"kindleImportSuccess",title:a.data.title})},error:function(d){console.log(d);chrome.tabs.sendMessage(b.tab.id,{name:"kindleImportFailed",title:a.data.title})}})},importMHTML:function(a,b,c){var d=a.details;chrome.tabs.sendMessage(b.tab.id,{name:"updateNoticeAndToolboar",status:"hidden"});chrome.pageCapture.saveAsMHTML({tabId:b.tab.id},
function(e){chrome.tabs.sendMessage(b.tab.id,{name:"updateNoticeAndToolboar",status:"show"});d.mhtml_upload_url&&fetch(d.mhtml_upload_url,{method:"PUT"}).then(function(f){if(f.ok)return f.text()}).then(function(f){f.replace(/[\r\n]/g,"");WebAPI.mhtml_upload_done({link_id:d.link_id,charset:d.charset,tabId:b.tab.id})})})},addAnnotation:function(a,b,c){a.annotation&&chrome.tabs.sendMessage(b.tab.id,{name:"addAnnotation",annotation:a.annotation})},editItem:function(a,b,c){a.annotation&&a.cmd&&chrome.tabs.sendMessage(b.tab.id,
{name:"editItem",annotation:a.annotation,cmd:a.cmd})},sample:function(a,b,c){}}};function getAllTabs(a){chrome.windows.getAll({populate:!0},function(b){var c=[];b.forEach(function(d){d.tabs.forEach(function(e){c.push(e)})});a(c)})}function forEachWebTab(a){forEachTab(a,function(b){return/^https?:\/\//.test(b.url)})}function forEachTab(a,b){getAllTabs(function(c){c.forEach(function(d){b&&!b(d)||a(d)})})}
function broadcastMessage(a){chrome.windows.getAll({populate:!0},function(b){b.forEach(function(c){c.tabs.forEach(function(d){Messenger.send(d.id,a)})})})}function executeContentScripts(a,b,c){chrome.scripting.executeScript({target:{tabId:a},files:b},function(){c&&c()})}function getExtensionVersion(){return chrome.runtime.getManifest().version}function sendRunCommand(a,b){Messenger.send(a,{name:"run",details:extend({extensionID:D.extensionID,version:D.version,logLevel:D.logLevel},b||{})})}
function showWindow(){getSelectedTab(function(a){chrome.tabs.sendMessage(a.id,{name:"showWindow"})})}
function showToolbar(a,b){"undefined"!=typeof b?(chrome.scripting.executeScript({target:{tabId:b},files:["js/checkTab.js"]},function(){debug("executeScript callback")}),EventMachine.onActivate(),sendRunCommand(b,{userClick:!0,type:a})):getSelectedTab(function(c){/^https?:\/\/chrome\.google\.com\/(extensions|webstore)/i.test(c.url)?alert(chrome.i18n.getMessage("alertGallery")):isURLApplicable(c.url)?(chrome.scripting.executeScript({target:{tabId:c.id},files:["js/checkTab.js"]},function(){debug("executeScript callback")}),
EventMachine.onActivate(),sendRunCommand(c.id,{userClick:!0,type:a})):alert(chrome.i18n.getMessage("alertUnsupportedPage"))})}function getCurrentTab(){var a,b,c,d,e;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){if(1==f.nextAddress)return a={active:!0,currentWindow:!0},b=$jscomp,c=b.makeIterator,f.yield(chrome.tabs.query(a),2);d=c.call(b,f.yieldResult);e=d.next().value;return f.return(e)})}
function init(){getStorage(null).then(function(a){console.log("All options",a);D.logLevel=a.logLevel||"never";D.version=getExtensionVersion();a.version!=D.version&&a.version&&Upgrader.isVersionBefore(a.version,"3.3.30")&&(saveStorage("prefs.autoload",!0),saveStorage("prefs.autoloadBookmarkStatus",!0));D.extensionID=chrome.runtime.getURL("").match(/:\/\/(\w+)\//)[1];Upgrader.check();Prefs.setDefaultPrefs();resetGlobalData();SignInManager.checkSignInCookie();TwitterOAuth.init();EventMachine.init();
D.Preloader.init();ContextMenu.init();ComboSearch.init();CrossPromotion.init();chrome.runtime.onMessage.addListener(function(b,c,d){console.log("[request name]",b.name);if("sendCtx"!=b.name&&"saved"!=b.name&&"sendRetags"!=b.name&&"updateGroups"!=b.name&&"updateLists"!=b.name)return Messenger.onMessage(b,c,d),!0});chrome.tabs.onUpdated.addListener(function(b,c,d){var e;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){if(1==f.nextAddress){console.log(c.status);"https://www.diigo.com/chrome_diigo_extension_done"==
c.url&&chrome.tabs.remove(d.id);/https:\/\/www.diigo.com\/user\/(.*)\?from=extension/.test(d.url)&&"complete"==c.status&&chrome.tabs.sendMessage(b,{name:"showTutorial"});/https:\/\/www.diigo.com/.test(d.url);if("complete"!=c.status||!/diigo\.(com|cn)\/images\/diigo-logo.png#SIGNED_IN/i.test(d.url))return f.jumpTo(2);debug("[Sign in tab opened by extension detected!]",b,c,d);chrome.tabs.remove(b);chrome.tabs.update(D.activateTheTabIdAfterSignIn,{selected:!0});return f.yield(getStorage("gcc_login_send"),
3)}2!=f.nextAddress&&((e=f.yieldResult)||chrome.cookies.get({url:"https://www.diigo.com",name:"diigoandlogincookie"},function(g){g&&(console.log("111"),e||(sendAnalysisData({gcc_cookie_login_ext_chrome:1}),saveStorage("gcc_login_send","true")))}));EventMachine.onTabUpdated(b,c,d);Preloader.onTabUpdated(b,c,d);SignInManager.checkSignInCookie(function(){var g,h,k,l,m,q;return $jscomp.asyncExecutePromiseGeneratorProgram(function(n){if(1==n.nextAddress)return g=$jscomp,h=g.makeIterator,n.yield(Prefs.get(["prefs.autoloadBookmarkStatus",
"prefs.comboSearch","prefs.SearchO"]),2);k=h.call(g,n.yieldResult);k.next();l=k.next().value;m=k.next().value;"true"===l&&(q="true"===m,ComboSearch.onTabUpdated(b,c,d,q));if("true"===m&&"true"===l)return n.return();n.jumpToEnd()})});f.jumpToEnd()})});chrome.tabs.onRemoved.addListener(function(b){Preloader.onTabRemoved(b)})})}
var Prefs={prefsToPreload:["prefs.bookmark.privateByDefault"],_observers:[],observeChanges:function(a){this._observers.push(a)},_notifyChanges:function(a){for(var b=0,c=this._observers.length;b<c;b++)this._observers[b].call(null,a)},setDefaultPrefs:function(){function a(c,d){var e,f;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){if(1==g.nextAddress)return g.yield(b.get(c),2);e=g.yieldResult;void 0===e&&(f={},f[c]=d,Prefs.set(f));g.jumpToEnd()})}console.log("[SW] Set default perfs");
var b=this;a("prefs.contextMenu",!0);a("prefs.autoload",!0);a("prefs.autoloadBookmarkStatus",!0);a("prefs.comboSearch",!0);a("prefs.SearchO",!0);a("prefs.annotateAfterSaving",!1);a("prefs.autoShowHighlightIcon",!0);a("prefs.lastUsedColor","yellow");a("prefs.autoImageClipper",!1);a("prefs.shortcutReadlater",!0);a("prefs.shortcutOpenOutlinerSidebar",!0);a("prefs.shortcutOpenOutlinerSidebarCtrl",!0);a("prefs.shortcutOpenOutlinerSidebarAlt",!0);a("prefs.shortcutBookmark",!0);a("prefs.shortcutAnnotate",
!0);a("prefs.shortcutReadlaterCtrl",!0);a("prefs.shortcutReadlaterAlt",!0);a("prefs.shortcutBookmarkCtrl",!0);a("prefs.shortcutBookmarkAlt",!0);a("prefs.shortcutAnnotateCtrl",!0);a("prefs.shortcutAnnotateAlt",!0);a("prefs.autoCloseReadLater",!0);a("prefs.shortcutAnnotateArticle",!0);a("prefs.shortcutAnnotatePDF",!0);a("prefs.shortcutAnnotateScreenshot",!0);a("prefs.shortcutAnnotateArticleCtrl",!0);a("prefs.shortcutAnnotatePDFCtrl",!0);a("prefs.shortcutAnnotateScreenshotCtrl",!0);a("prefs.shortcutAnnotateArticleAlt",
!0);a("prefs.shortcutAnnotatePDFAlt",!0);a("prefs.shortcutAnnotateScreenshotAlt",!0);a("prefs.shortcutBookmarkKey","D");a("prefs.shortcutReadlaterKey","R");a("prefs.shortcutOpenOutlinerSidebarKey","O");a("prefs.shortcutAnnotateKey","A");a("prefs.shortcutAnnotateArticleKey","T");a("prefs.shortcutAnnotatePDFKey","P");a("prefs.shortcutAnnotateScreenshotKey","S");a("free_trial_count",0);a("isPdfTipClicked",!1);a("search_type","meta");a("prefs.showPdfButton",!0);a("prefs.showVideoCapture",!0);a("prefs.bookmark.privateByDefault",
!0);a("lastSearch",JSON.stringify({tab:"recent",key:""}))},prefixForUser:function(){var a=GlobalData.user;if(!a||0==a.length)throw"Invalid user";return"user."+a+"."},get:function(a,b){b=b||"";Array.isArray(a)?a.forEach(function(c,d,e){e[d]=b+c}):a=b+a;return getStorage(a)},setObject:function(a,b){b=b||"";var c={};forEach(a,function(d,e){e=b+e;debug("[prefs] set",e,d);d=String(d);saveStorage(e,d);c[e]=d});return c},set:function(a,b,c){var d=this.setObject(a,b);isEmptyObject(d)||(forEachWebTab(function(e){Messenger.send(e.id,
{name:"prefsChanged",details:{data:d},fromTabId:c})}),this._notifyChanges(d));return d},remove:function(a,b){b=b||"";return Array.isArray(a)?(a.forEach(function(c){removeFromStorage(b+c)}),{}):this.remove([a],b)[a]},getUserData:function(a){return this.get(a,this.prefixForUser())},setUserData:function(a,b){return this.set(a,this.prefixForUser(),b)},removeUserData:function(a){return this.remove(a,this.prefixForUser())}},EventMachine=D.EventMachine={_locationCounter:0,_activationCounter:0,_lastReloadTime:new Date,
_shouldReload:!1,init:function(){},onTabUpdated:function(a,b,c){"complete"==b.status&&this.changeLocation(c.url)},onActivate:function(){this._activationCounter++;5<=this._activationCounter&&(debug("[EventMachine] onActivate 5 times"),this._shouldReload=!0,this._activationCounter=0)},needToReload:function(){15<((new Date).getTime()-this._lastReloadTime.getTime())/1E3/60&&(debug("[EventMachine] 15 mins"),this._shouldReload=!0);return this._shouldReload?(this._shouldReload=!1,this._locationCounter=this._activationCounter=
0,this._lastReloadTime=new Date,!0):!1},changeLocation:function(a){a=++this._locationCounter;0==a%20&&(debug("[EventMachine] changeLocation 20 times"),this._shouldReload=!0);16777215<a&&(this._locationCounter=0)}},ContextMenu={init:function(){var a=this;Prefs.observeChanges(function(b){void 0!==b["prefs.contextMenu"]&&a.createContextMenu()})},createContextMenu:function(){var a=chrome.contextMenus.create({id:"saveImage",title:"Save image to Diigo",contexts:["image"]});chrome.contextMenus.create({id:"tagImage",
title:"Tag as a stand-alone image",contexts:["image"],parentId:a});chrome.contextMenus.create({id:"attachBookmark",title:"Attach it to the bookmark",contexts:["image"],parentId:a});chrome.contextMenus.create({id:"saveToDiigo",title:"Save to Diigo",contexts:["link"]});a=chrome.contextMenus.create({id:"diigo",title:"Diigo"});chrome.contextMenus.create({id:"saveBookmark",title:"Save Bookmark",parentId:a});chrome.contextMenus.create({id:"annotateArticle",title:"Annotate Article",parentId:a});chrome.contextMenus.create({id:"annotatePDF",
title:"Annotate PDF",parentId:a});chrome.contextMenus.create({id:"annotateScreenshot",title:"Annotate Screenshot",parentId:a});chrome.contextMenus.create({id:"readLater",title:"Read Later",parentId:a});chrome.contextMenus.create({id:"stickyNote",title:"Sticky note",parentId:a});a=chrome.contextMenus.create({id:"diigo2",title:"Diigo",contexts:["selection"]});chrome.contextMenus.create({id:"highlight",title:"Highlight",contexts:["selection"],parentId:a});chrome.contextMenus.create({id:"search",title:"Search Diigo+Google for selection",
parentId:a,contexts:["selection"]});chrome.contextMenus.onClicked.addListener(function(b,c){var d=b.pageUrl;switch(b.menuItemId){case "tagImage":D.saveImageToDiigo(d,c,"tag");break;case "attachBookmark":D.saveImageToDiigo(d,c,"attach");break;case "saveToDiigo":fetch(d).then(function(e){return e.text()}).then(function(e){e=e.replace(/[\r\n]/g,"");var f="";try{f=e.match(/<title>(.*)<\/title>/)[1].trim()}catch(g){f=null}chrome.tabs.sendMessage(c.id,{name:"showWindow",data:{linkTitle:f,url:b.linkUrl}})});
break;case "saveBookmark":showWindow();break;case "annotateArticle":chrome.scripting.executeScript({target:{tabId:c.id},files:["js/checkTab.js"]},function(){});chrome.tabs.sendMessage(c.id,{name:"annotate"});break;case "annotatePDF":chrome.tabs.create({url:"/pdf/viewer.html"});break;case "annotateScreenshot":chrome.scripting.executeScript({target:{tabId:c.id},files:["js/checkTab.js"]},function(){});chrome.tabs.sendMessage(c.id,{name:"screenshot"});break;case "readLater":chrome.tabs.sendMessage(c.id,
{name:"readlater"});break;case "stickyNote":showToolbar("stickynote");break;case "highlight":showToolbar("highlight");chrome.tabs.sendMessage(c.id,{name:"contextmenuHighlight"});break;case "search":D.searchDiigoGoogle(b.selectionText,c)}})},removeContextMenu:function(){chrome.contextMenus.removeAll()}};D.searchDiigoGoogle=function(a,b){a&&0<a.length&&(a={url:"https://www.diigo.com/search/g?q="+encodeURIComponent(a)+"&sa=Search"},b&&(a.index=b.index+1),chrome.tabs.create(a))};
D.saveImageToDiigo=function(a,b,c){if(/data:image\/.*;base64/.test(a.srcUrl)){var d=a.srcUrl.match(/data:image\/(.*);base64/)[1];chrome.tabs.sendMessage(b.id,{name:"saveImageToDiigo",data:a.srcUrl,type:c,dtype:d,image_src:a})}else fetch(a.srcUrl).then(function(e){return e.blob()}).then(function(e){var f=e.type.slice(6),g=new FileReader;g.onload=function(){chrome.tabs.sendMessage(b.id,{name:"saveImageToDiigo",data:g.result,type:c,dtype:f,image_src:a})};g.readAsDataURL(e)}).catch(function(e){return console.error(e)})};
var WebAPICall=function(a){this.context=a};
WebAPICall.prototype={invoke:function(a,b,c){this.callOptions=c;var d=c.transId||WebAPICall.transIdStepper++,e=c.user;d={cmd:a,v:13,_nocache:Math.random(),json:JSON.stringify(b),user:e,transId:d};debug("[WebAPICall]",a,b);c.isInGroup?(d={cmd:a,extra:b.extra,image:b.file_content},e=b.src_url):(b=D.config.TOOLBAR_SERVER,e="user_signIn"==a?evalTpl(b+"/chappai/pv=#{pv}/ct=tb/cv=#{cv}/cmd=#{cmd}",{pv:13,cv:D.version,cmd:a}):evalTpl(b+"/chappai/pv=#{pv}/ct=tb/cv=#{cv}/user=#{user}/cmd=#{cmd}/",{pv:13,cv:D.version,
user:e,cmd:a}));this.performInvocation(e,d,c,a)},cancel:function(){this.cancelled=!0;this.xhr&&(this.xhr.abort(),this.xhr=null)},performInvocation:function(a,b,c,d){var e=this;console.log(a);fetch(a,{method:"POST",body:objectToParams(b),headers:{"Content-Type":"application/x-www-form-urlencoded"}}).then(function(f){return f.json()}).then(function(f){if("upload_file"==d||"bm_saveBookmark"==d||"list_create"==d)e.status=f.status,e.cmd=d;if(e.resp=f)if(1==f.code&&(e.ok=!0),f.user)SignInManager.onUsernameSeen(f.user);
c.complete(e,f)})}};var WebAPICall_Static={transIdStepper:1,_baseUrl:null,setup:function(a){this._baseUrl=a.baseUrl}};extend(WebAPICall,WebAPICall_Static);
var Upgrader={check:function(){var a=this,b=D.version;Prefs.get("version").then(function(c){c=c?c:"0";console.log("cur, prev",b,c);0<a.compareVersion(b,c)&&a.upgrade(c)})},upgrade:function(a){debug("Performing upgrade from",a,"to",D.version);this.isVersionBefore(a,"1.6.2.4")&&Prefs.set({"prefs.autoloadBookmarkStatus":!0});Prefs.set({version:D.version})},compareVersion:function(a,b){function c(e){if(/[^\d.]/.test(e))throw"version must be in formatted like 1.2.4";return e.split(".").map(function(f){return parseInt(f,
10)})}if(a===b)return 0;a=c(a);b=c(b);for(var d=0;d<a.length&&d<b.length;d++)if(a[d]!=b[d])return a[d]>b[d]?1:-1;return a.length==b.length?0:a.length>b.length?1:-1},isVersionBefore:function(a,b,c){try{void 0===c&&(c=!1);var d=this.compareVersion(a,b);return c&&0==d?!0:0>d}catch(e){return!1}}};function sendAnalysisData(a){fetch("https://www.diigo.com/stats",{method:"POST",body:JSON.stringify(a)})}init();
"undefined"==typeof browser&&chrome.runtime.onInstalled.addListener(function(a){if("install"==a.reason){var b=chrome.runtime.getManifest();chrome.cookies.getAll({url:"https://www.diigo.com"},function(c){var d,e,f;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){d=getStorage("version");e=0<c.length?1:0;f={gcc_cookie_installed_ext_chrome:1,gcc_cookie_ext_chrome_version:b.version,gcc_cookie_ext_chrome_last_version:d||"none",gcc_cookie_visited_diigo:e};sendAnalysisData(f);g.jumpToEnd()})});
chrome.tabs.query({url:"https://www.diigo.com/common/install"},function(c){for(var d=0,e=c.length;d<e;d++){var f=c[d];chrome.cookies.get({url:"https://www.diigo.com",name:"diigoandlogincookie"},function(g){g&&(username=g.value.split("-.-")[1])&&chrome.tabs.update(f.id,{url:"https://www.diigo.com/user/"+username+"?from=extension"})})}})}});function objectToParams(a){var b="",c;for(c in a)b+=encodeURIComponent(c)+"="+encodeURIComponent(a[c])+"&";return b};
