var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,g){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,g):$jscomp.polyfillUnisolated(a,b,c,g))};
$jscomp.polyfillUnisolated=function(a,b,c,g){c=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var e=a[g];if(!(e in c))return;c=c[e]}a=a[a.length-1];g=c[a];b=b(g);b!=g&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,g){var e=a.split(".");a=1===e.length;g=e[0];g=!a&&g in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var d=0;d<e.length-1;d++){var f=e[d];if(!(f in g))return;g=g[f]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?g[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(g,e,{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.generator={};
$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};
$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};
$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};
$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var c=a.next();$jscomp.generator.ensureIteratorResultIsObject_(c);if(c.done)this.yieldResult=c.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(c.value,b)};$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};
$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(c){return{value:c,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var g=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(g);if(!g.done)return this.context_.stop_(),g;var e=g.value}catch(d){return this.context_.yieldAllIterator_=null,this.context_.throw_(d),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(g){return a.next(g)}function c(g){return a.throw(g)}return new Promise(function(g,e){function d(f){f.done?g(f.value):Promise.resolve(f.value).then(b,c).then(d,e)}d(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.initSymbol=function(){};$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(e,d){this.$jscomp$symbol$id_=e;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:d})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c=0,g=function(e){if(this instanceof g)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(e||"")+"_"+c++,e)};return g},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var g=$jscomp.global[b[c]];"function"===typeof g&&"function"!=typeof g.prototype[a]&&$jscomp.defineProperty(g.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(f){return f instanceof e?f:new e(function(h,k){h(f)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(f){if(null==this.batch_){this.batch_=[];var h=this;this.asyncExecuteFunction(function(){h.executeBatch_()})}this.batch_.push(f)};var g=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(f){g(f,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var f=
this.batch_;this.batch_=[];for(var h=0;h<f.length;++h){var k=f[h];f[h]=null;try{k()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(f){this.asyncExecuteFunction(function(){throw f;})};var e=function(f){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var h=this.createResolveAndReject_();try{f(h.resolve,h.reject)}catch(k){h.reject(k)}};e.prototype.createResolveAndReject_=function(){function f(l){return function(m){k||(k=!0,l.call(h,m))}}var h=this,k=!1;
return{resolve:f(this.resolveTo_),reject:f(this.reject_)}};e.prototype.resolveTo_=function(f){if(f===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof e)this.settleSameAsPromise_(f);else{a:switch(typeof f){case "object":var h=null!=f;break a;case "function":h=!0;break a;default:h=!1}h?this.resolveToNonPromiseObj_(f):this.fulfill_(f)}};e.prototype.resolveToNonPromiseObj_=function(f){var h=void 0;try{h=f.then}catch(k){this.reject_(k);return}"function"==typeof h?
this.settleSameAsThenable_(h,f):this.fulfill_(f)};e.prototype.reject_=function(f){this.settle_(2,f)};e.prototype.fulfill_=function(f){this.settle_(1,f)};e.prototype.settle_=function(f,h){if(0!=this.state_)throw Error("Cannot settle("+f+", "+h+"): Promise already settled in state"+this.state_);this.state_=f;this.result_=h;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var f=0;f<this.onSettledCallbacks_.length;++f)d.asyncExecute(this.onSettledCallbacks_[f]);
this.onSettledCallbacks_=null}};var d=new b;e.prototype.settleSameAsPromise_=function(f){var h=this.createResolveAndReject_();f.callWhenSettled_(h.resolve,h.reject)};e.prototype.settleSameAsThenable_=function(f,h){var k=this.createResolveAndReject_();try{f.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};e.prototype.then=function(f,h){function k(n,p){return"function"==typeof n?function(q){try{l(n(q))}catch(r){m(r)}}:p}var l,m,t=new e(function(n,p){l=n;m=p});this.callWhenSettled_(k(f,l),k(h,m));return t};
e.prototype.catch=function(f){return this.then(void 0,f)};e.prototype.callWhenSettled_=function(f,h){function k(){switch(l.state_){case 1:f(l.result_);break;case 2:h(l.result_);break;default:throw Error("Unexpected state: "+l.state_);}}var l=this;null==this.onSettledCallbacks_?d.asyncExecute(k):this.onSettledCallbacks_.push(k)};e.resolve=c;e.reject=function(f){return new e(function(h,k){k(f)})};e.race=function(f){return new e(function(h,k){for(var l=$jscomp.makeIterator(f),m=l.next();!m.done;m=l.next())c(m.value).callWhenSettled_(h,
k)})};e.all=function(f){var h=$jscomp.makeIterator(f),k=h.next();return k.done?c([]):new e(function(l,m){function t(q){return function(r){n[q]=r;p--;0==p&&l(n)}}var n=[],p=0;do n.push(void 0),p++,c(k.value).callWhenSettled_(t(n.length-1),m),k=h.next();while(!k.done)})};return e},"es6","es3");$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var g=a.length,e=0;e<g;e++){var d=a[e];if(b.call(c,d,e,a))return{i:e,v:d}}return{i:-1,v:void 0}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");var popCtx={groupTagsDict:{}},username,inResearchMode=!1,ac,GlobalData=null,_url=getParameterByName("url"),_title=getParameterByName("title");function isInResearchMode(){return $("#op-focus").prop("checked")}function sendMessage(a){window.parent.postMessage(a,"*")}
chrome.runtime.sendMessage({name:"initialData"},function(a){GlobalData=a.globalData;initBookmarkWindow();sendMessage({type:"ifbookmark"})});window.addEventListener("message",receiveMessage,!1);
function receiveMessage(a){a=a.data;switch(a.type){case "sendCtx":popCtx=$.extend(popCtx,a.data);objectToform(popCtx);break;case "sendRetags":showTags("recommended",a.data);break;case "updateGroupTag":popCtx.groupTagsDict=a.data;a=$("#diigobm-group").find(".content").attr("data-id");showTags("group",popCtx.groupTagsDict[a]);break;case "listCreateSuccessAndUpdateLists":updateLists({list:a.lists,outliners:a.outliners});a=a.newlist;var b=$("#diigobm-list");b.find(".content").text(a.title).attr("data-id",
a.id);b.removeClass("focused");b.find(".add-box").hide().find("input").val("");b.find(".search-box").show();break;case "listCreateFailureAndUpdateLists":$("#diigobm-list-addBtn").parent().removeClass("processing")}}
chrome.runtime.onMessage.addListener(function(a,b,c){"updateLists"==a.name?updateLists(a.data):"updateGroups"==a.name?updateGroups(a.data):"listCreateSuccessAndUpdateLists"==a.name?(updateLists({list:a.lists,outliners:a.outliners}),a=a.newlist,b=$("#diigobm-list"),b.find(".content").text(a.title).attr("data-id",a.id),b.removeClass("focused"),b.find(".add-box").hide().find("input").val(""),b.find(".search-box").show()):"listCreateFailureAndUpdateLists"==a.name&&$("#diigobm-list-addBtn").parent().removeClass("processing")});
$("#tag-edit").on("click",function(){chrome.tabs.create({url:"https://www.diigo.com/cloud/"+username})});$("#remove").on("click",function(){sendMessage({type:"qdeletebookmark"})});$("#show-url").on("click",function(){$("#diigobm-url-input").toggle()}).Gtooltip({position:"top"});$("#tag-cloud-icon").on("click",function(){$("#tag-cloud").toggle()}).Gtooltip({positon:"top"});$("#diigo-acache-field").on("click",function(){sendMessage({type:"showMHTMLinfo"})});
function triggerEvent(a,b){b=new Event(b);a.dispatchEvent||(a=a[0]);a.dispatchEvent(b)}function inList(a){return some(popCtx.bm.lists,function(b){return b.id==a})}function inOutliner(a){return some(popCtx.bm.outliners,function(b){return b.id==a})}function inGroup(a){return some(popCtx.bm.groups,function(b){return b.name==a})}
function getParameterByName(a,b){b||(b=window.location.href);a=a.replace(/[\[\]]/g,"\\$&");return(a=(new RegExp("[?&]"+a+"(=([^&#]*)|&|#|$)")).exec(b))?a[2]?decodeURIComponent(a[2].replace(/\+/g," ")):"":null}function toggleTag(a,b){var c=$("#diigobm-tag-input"),g=ParseTags.parseTags(c.val(),!0),e=$.inArray(a,g);void 0===b?0<=e?g.splice(e,1):g.push(a):b?-1==e&&g.push(a):0<=e&&g.splice(e,1);a=ParseTags.unparseTags(g);a.length&&(a+=" ");c.val(a);placeCursorAtLast(c[0]);updateTagStatus()}
function updateTagStatus(){var a=$("#diigobm-tag-input"),b=ParseTags.parseTags(a.val(),!0);$("#tag-cloud-container").find(".Diigo-Bookmark-Tag-item").each(function(){var c=$(this),g=c.text();-1!=$.inArray(g,b)?c.addClass("selected"):c.removeClass("selected")});$("#diigobm-recent-tag, #diigobm-recommend-tag, #diigobm-group-tag").find(".diigo-tag").each(function(){var c=$(this),g=c.text();-1!=$.inArray(g,b)?c.addClass("selected"):c.removeClass("selected")})}
function placeCursorAtLast(a){var b=a.value.length;setTimeout(function(){placeInputCursor(a,b)},13)}function placeInputCursor(a,b){a.focus();a.createTextRange?(a=a.createTextRange(),a.move("character",b),a.select()):0<=a.selectionStart&&(a.focus(),a.setSelectionRange(b,b))}
function showTags(a,b){if("recommended"==a){b=b.filter(function(d){return 0<=$.inArray(d,popCtx.mytag)});b=popCtx.lastUsedTags.concat(b);if(0==b.length)return;$("#diigobm-recommend-tag").show()}for(var c=document.createDocumentFragment(),g=0;g<b.length;g++){var e=document.createElement("div");e.className="diigo-tag";e.innerText=b[g];$(e).toggleClass("selected",0<=$.inArray(b[g],popCtx.bm.tags));c.appendChild(e)}"recommended"==a?$(c).appendTo($("#diigobm-recommend-tag")):"group"==a&&($("#diigobm-group-tag").find(".loading").hide(),
$("#diigobm-group-tag").find(".diigo-tag").remove(),$(c).appendTo($("#diigobm-group-tag")))}function isURL(a){return/^(https|http|ftp|rtsp|mms)+:\/\//.test(a)?!0:!1}
function formToObject(){var a=!0,b=$("#diigobm-url-input").val();$("#diigobm-title-input").val().match(/^\s*$/)&&(a=!1,$("#diigobm-title").find(".diigo-alert-tip").show());isURL(b)&&!b.match(/^\s*$/)||1!=a||(a=!1,$("#diigobm-url").find(".diigo-alert-tip").show());if(0!=a){a=$("#diigobm-title-input").val();a.match(/^\s*$/)&&(a=popCtx.bm.title);b=$("#diigobm-url-input").val();if(b.match(/^\s*$/)||!isURL(b))b=popCtx.bm.url;var c=$("#diigobm-des-input").val();var g=ParseTags.parseTags($("#diigobm-tag-input").val(),
!0);var e=$("#op-private").prop("checked")?2:0;var d=$("#op-readlater").prop("checked")?!0:!1;var f=(f=$("#diigobm-list").find(".content").attr("data-id"))?[f]:[];var h=(h=$("#diigobm-group").find(".content").attr("data-id"))?[h]:[];var k=$("#Diigo-Bookmark-checkShareExisting").find(".op-checkbox-container").hasClass("checked")?!0:!1;var l=$("#op-cache").prop("checked")?!0:!1;chrome.runtime.sendMessage({name:"saveBookmarkFromBookmarkWin",data:{url:b,mode:e,title:a,tags:g,description:c,unread:d,urlId:popCtx.bm.urlId,
cache:l,groups:h,shareExistingAnnotations:k,lists:f}});setTimeout(function(){sendMessage({type:"closeWin"})},500)}}
function getTagScale(a){var b=[];a.sort(function(f,h){return f.count<=h.count?1:-1});a=a.slice(0,101);var c=a[0].count,g=a.length;a.sort(function(f,h){return f.name.toLowerCase()<=h.name.toLowerCase()?-1:1});for(var e=0;e<g;e++)b[e]=a[e].count;b=arrayUnique(b);g=b.length;b.sort(function(f,h){return f<h?1:-1});var d=Math.ceil(g/10);g=b.slice(1,1+d);e=b.slice(1+d,1+2*d);b=b.slice(1+2*d,1+3*d);return{topTags:a,maxCount:c,first:g,second:e,third:b}}
function updateBookmark(a){if(!0!==inResearchMode&&1==a.generated){var b=a.bm;!0===a.unread&&$("#read-later").addClass("unread").text("Mark as Read");$("#onload").hide();1==b.saved&&($("#remove").show(),$("#remove").attr("data-gtooltip","Saved "+b.datetime+". Click to remove"),$("#bookmark-save").text("Edit").addClass("saved"),$("#cached").show().unbind("click").bind("click",function(){getSelectedTab(function(c){var g="https://www.diigo.com/cached?url="+encodeURIComponent(c.url);chrome.tabs.create({url:g,
index:c.index+1})})}));void 0!=b?($("#diigobm-title-input").val(b.title).trigger("input"),triggerEvent($("#diigobm-title-input"),"change"),$("#diigobm-url-input").val(b.url)):($("#diigobm-title-input").val(window.parent.document.title),$("#diigobm-url-input").val(tab.url));2==b.mode&&$("#op-private").prop("checked",!0);1==b.unread&&$("#op-readlater").prop("checked",!0);a=ParseTags.unparseTags(b.tags);blank(a)||$("#diigobm-tag-input").val(a+" ")}}
function initBookmarkWindow(a){$("#research-mode-notification").hide();a&&($("#top-bar").find("span").text("Focused Research").end().find("div").hide(),$("#diigobm-title,#diigobm-url,#op-cache,#diigobm-recommend-tag").hide(),chrome.storage.local.get("isShowResearchTip",function(d){"undefined"!==typeof d.isShowResearchTip&&0==d.isShowResearchTip||$("#research-mode-notification").show()}),$("#research-mode-close-notify").on("click",function(){$("#research-mode-notification").hide();chrome.storage.local.set({isShowResearhTip:!1})}));
a=navigator.userAgent.toLowerCase();var b=-1!=a.indexOf("macintosh")||-1!=a.indexOf("mac os x");b?($("#diigobm-url").addClass("mac"),$("#list-group select").css("text-indent","7px")):$("#diigobm-url").addClass("win");$("#link-icon").on("click",function(){var d=$("#diigobm-url");b?d.toggleClass("mac-unfold"):d.hasClass("unfold")?d.addClass("fold").removeClass("unfold"):d.addClass("unfold").removeClass("fold")});autoTextarea.init(document.getElementById("diigobm-title-input"),40);autoTextarea.init(document.getElementById("diigobm-des-input"),
80);$("#diigobm-tag-dropdown").on("click",function(){$(this).toggleClass("cloud");"none"==$("#tag-cloud").css("display")?($("#tag-suggestion").hide(),$("#tag-cloud").show()):($("#tag-suggestion").show(),$("#tag-cloud").hide())});$("#recommend-tag").on("click",function(d){d.preventDefault();$("#diigobm-recommend-tag").find(".diigo-tag").each(function(){$(this).trigger("click")})});$("#diigobm-recent-tag").on("click","a",function(){$("#diigobm-recent-tag").find(".diigo-tag").each(function(){toggleTag($(this).addClass("selected").text(),
!0)})});$("#diigobm-options,#Diigo-Bookmark-checkShareExisting").on("click",".op-checkbox-container",function(){$(this).toggleClass("checked")});$("#bm-main").on("keydown",function(d){13==d.keyCode?"diigobm-tag-input"!=d.target.id||$("#diigolet-ac").is(":visible")||formToObject():83==d.keyCode&&(d.ctrlKey||d.metaKey)?(d.preventDefault(),formToObject()):27==d.keyCode&&window.close()});$("#op-cache").find(".op-checkbox-container").removeClass("checked");$("#remove").Gtooltip();$("#close").Gtooltip().on("click",
function(){sendMessage({type:"closeWin"})});a=[];var c=popCtx.myTagsWithCount?popCtx.myTagsWithCount:GlobalData.myTagsWithCount;c.sort(function(d,f){return d.count<=f.count?1:-1});for(var g=c.length,e=0;e<g;e++)a[e]=c[e].name;a={resultsClass:"diigolet ac_results",data:a,mode:"multiple",multipleSeparator:" ,",id:"diigolet-ac"};try{new AutoComplete("#diigobm-tag-input",a)}catch(d){debug(d)}$("#diigobm-tag-input").bind("input",function(){updateTagStatus()});$("#diigobm-list-addInput").on("focus",function(){$("#diigobm-list-add .diigo-alert-tip").hide()});
$("#close-upgrade-info").on("click",function(){$("#upgrade-info").hide()});$("#diigobm-list-addBtn").on("click",function(){if(!$(this).parent().hasClass("processing"))if(GlobalData.permissions.createOutliner){var d=$("#diigobm-list-addInput").val(),f=$("#diigobm-list-add .diigo-alert-tip"),h=[],k=popCtx.lists.length,l;for(l=0;l<k;l++)h.push(popCtx.lists[l].title);d.match(/^\s*$/)?(f.show().find("span").text("Input a name"),$("#diigobm-list-addInput").focus()):-1!==$.inArray(d,h)?f.show().find("span").text("Name existed !"):
($(this).parent().addClass("processing"),sendMessage({type:"createList",data:d}))}else $("#upgrade-info").show()});$("#diigobm-list-addCancel").on("click",function(){$("#diigobm-list-add .diigo-alert-tip").hide();$("#diigobm-list-add").hide();$("#diigobm-list").show();$("#diigobm-list-addInput").val("")});$("#w-upgrade").on("click",function(d){d.preventDefault();googleEvent("Chrome extension","Click upgrade from outliner creation","outliner");chrome.tabs.create({url:"https://www.diigo.com/premium?f=outliner"});
$("#diigobm-list-add-tip").hide();$("#diigobm-list").show()});$("#w-cancel").on("click",function(d){d.preventDefault();$("#diigobm-list-add-tip").hide();$("#diigobm-list").show()});$("#diigobm-recent-tag,#diigobm-recommend-tag,#diigobm-group-tag").on("click","div",function(d){/diigo\-tag/.test(d.target.className)&&toggleTag($(this).text())});$("#diigobm-saveBtn").on("click",function(){isInResearchMode()?saveResearchMode(formToObject):formToObject()});$("#bottom").on("click",function(d){switch(d.target.id){case "diigobm-saveBtn":isInResearchMode()?
saveResearchMode(formToObject):formToObject();break;case "diigobm-cancelBtn":window.close()}});$("#diigobm-tag-input").focus();$("#refresh-outliner,#refresh-group").on("click",function(){$(this).addClass("processing");sendMessage({type:"refreshMyStuff"})})}
function saveResearchMode(a){var b={};b.tags=ParseTags.parseTags($("#diigobm-tag-input").val(),!0);$("#op-private").prop("checked")?b._private=!0:b._private=!1;$("#op-readlater").prop("checked")?b.unread=!0:b.unread=!1;$("#op-cache").prop("checked")?b.cache=!0:b.cache=!1;b.outliner=$("#diigobm-list").find(".content").attr("data-id");b.group=$("#diigobm-group").find(".content").attr("data-id");console.log(b);chrome.storage.local.set({researchModeData:b},function(){a&&a()})}
function objectToform(a){var b,c,g,e,d,f;return $jscomp.asyncExecutePromiseGeneratorProgram(function(h){if(1==h.nextAddress)return h.yield(getStorage(["prefs.bookmark.privateByDefault","prefs.bookmark.unreadByDefault","openedOutlinerId","prefs.outlinerIcon"]),2);b=h.yieldResult;c=a.bm;!0===a.generated&&$("#onload").hide();1==c.saved&&($("#remove").show(),$("#top-bar").find(".top-bar-title").text("Edit bookmark"));$("#remove").attr("data-gtooltip","Saved "+c.datetime+". Click to remove");void 0!=c?
($("#diigobm-title-input").val(c.title),triggerEvent($("#diigobm-title-input"),"change"),$("#diigobm-url-input").val(c.url),_title&&$("#diigobm-title-input").val(_title),_url&&$("#diigobm-url-input").val(_url)):chrome.tabs.getSelected(function(k){$("#diigobm-title-input").val(k.title);triggerEvent($("#diigobm-title-input"),"change");$("#diigobm-url-input").val(k.url)});2==c.mode&&$("#op-private").prop("checked",!0);0==c.saved&&"true"==b["prefs.bookmark.privateByDefault"]&&$("#op-private").prop("checked",
!0);(1==c.unread||0==c.saved&&"true"==b["prefs.bookmark.unreadByDefault"])&&$("#op-readlater").prop("checked",!0);0<c.description.length?($("#diigobm-des-input").text(c.description).trigger("change"),triggerEvent($("#diigobm-des-input"),"change")):a.selection&&($("#diigobm-des-input").text('"'+a.selection+'"'),triggerEvent($("#diigobm-des-input"),"change"));g=ParseTags.unparseTags(c.tags);blank(g)||$("#diigobm-tag-input").val(g+" ");updateLists({list:a.lists,outliners:a.outliners},!1);updateGroups(a.groups,
!1);updateTagStatus();0==$("#diigobm-recommend-tag").find(".diigo-tag").length&&sendMessage({type:"getRecommendedTags"});buildTagCloud(a.myTagsWithCount);chrome.storage.local.get(null,function(k){console.log(k);!0===k.researchMode&&(inResearchMode=!0,$("#op-focus").prop("checked",!0),$("#top-bar").find(".focus-research-tip").show(),!1===c.saved&&fillReasearchModeData(k,c.mode))});b.openedOutlinerId&&"true"==b["prefs.outlinerIcon"]&&(e=b.openedOutlinerId,d=$("#diigobm-list"),f=d.find(".menu-item[data-id="+
e+"]").text(),d.find(".content").text(f).attr("data-id",e).end().addClass("inputed"));h.jumpToEnd()})}
function updateTagStatus(){var a=$("#diigobm-tag-input"),b=ParseTags.parseTags(a.val(),!0);$("#tag-cloud-container").find(".Diigo-Bookmark-Tag-item").each(function(){var c=$(this),g=c.text();-1!=$.inArray(g,b)?c.addClass("selected"):c.removeClass("selected")});$("#diigobm-recent-tag, #diigobm-recommend-tag, #diigobm-group-tag").find(".diigo-tag").each(function(){var c=$(this),g=c.text();-1!=$.inArray(g,b)?c.addClass("selected"):c.removeClass("selected")})}
function updateLists(a,b){$("#refresh-outliner").removeClass("processing");var c=a.list;a=a.outliners;var g=$("#diigobm-list").find(".item-container");g.empty();a.length&&($('<div class="menu-title">Outliners</div>').appendTo(g),forEach(a,function(d){var f=inOutliner(d.id)?d.title+" (added)":d.title;$('<div class="menu-item" data-id="'+d.id+'">'+f+"</div>").appendTo(g)}));c.length&&($('<div class="menu-title">Lists</div>').appendTo(g),forEach(c,function(d){var f=inList(d.id)?d.title+" (added)":d.title;
$('<div class="menu-item" data-id="'+d.id+'">'+f+"</div>").appendTo(g)}));var e=$("#diigobm-list").find("select").empty().unbind().removeClass("processing");e.append(Utils.dom.buildOne("option",{value:0},["Add to an Outliner"]));e.append(Utils.dom.buildOne("option",{value:-1},[Array(20).join("-")]));$(Utils.dom.buildOne("option",{value:-2},["Create an Outliner..."])).appendTo(e);e.append(Utils.dom.buildOne("option",{value:-1},[Array(20).join("-")]));forEach(a,function(d){b?e.append(Utils.dom.buildOne("option",
{value:d.id},[d.title])):e.append(Utils.dom.buildOne("option",{value:d.id},[d.title+(inList(d.id)?" (added)":"")]))});e.append(Utils.dom.buildOne("option",{value:-1},[Array(20).join("-")]));c.length&&(e.append(Utils.dom.buildOne("option",{value:-8},["Add to a List"])),e.append(Utils.dom.buildOne("option",{value:-1},[Array(20).join("-")])),forEach(c,function(d){b?e.append(Utils.dom.buildOne("option",{value:d.id},[d.title])):e.append(Utils.dom.buildOne("option",{value:d.id},[d.title+(inList(d.id)?" (added)":
"")]))}));e.append(Utils.dom.buildOne("option",{value:-1},[Array(20).join("-")]));$(Utils.dom.buildOne("option",{value:-3},["Refresh"])).appendTo(e);e.change(function(){var d=e.val();-2==d?(!0===GlobalData.permissions.createOutliner?($("#diigobm-list-add").show(),$("#diigobm-list").hide(),$("#diigobm-list-addInput").focus()):($("#diigobm-list-add-tip").show(),$("#diigobm-list").hide()),e.val(0),e.remvoeClass("selected")):-3==d&&($(this).addClass("processing"),chrome.tabs.getSelected(null,function(f){chrome.tabs.sendMessage(f.id,
{name:"refreshMyStuff"})}),e.val(-1))});e.val(0).change()}
function updateGroups(a,b){$("#refresh-group").removeClass("processing");var c=a.filter(function(d){return 5>d.access_mode});a=a.filter(function(d){return 5<=d.access_mode});var g=$("#diigobm-group").find(".item-container");g.empty();a.length&&($('<div class="menu-title">Teams</div>').appendTo(g),forEach(a,function(d){var f=inGroup(d.name)?d.displayName+" (shared)":d.displayName;$('<div class="menu-item" data-id="'+d.name+'">'+f+"</div>").on("click",function(){var h=d.name;void 0!=popCtx.groupTagsDict[h]?
showTags("group",popCtx.groupTagsDict[h]):($("#diigobm-group-tag").show(),sendMessage({type:"loadGroupTagsDictionary",groupName:h}))}).appendTo(g)}));c.length&&($('<div class="menu-title">Groups</div>').appendTo(g),forEach(c,function(d){var f=inGroup(d.name)?d.displayName+" (shared)":d.displayName;$('<div class="menu-item" data-id="'+d.name+'">'+f+"</div>").on("click",function(){var h=d.name;void 0!=popCtx.groupTagsDict[h]?showTags("group",popCtx.groupTagsDict[h]):($("#diigobm-group-tag").show(),
sendMessage({type:"loadGroupTagsDictionary",groupName:h}))}).appendTo(g)}));var e=$("#diigobm-group").find("select").empty().unbind().removeClass("processing");0<a.length&&(e.append(Utils.dom.buildOne("option",{value:0},["Share to a Team"])),e.append(Utils.dom.buildOne("option",{value:-5},[Array(20).join("-")])),forEach(a,function(d){b?e.append(Utils.dom.buildOne("option",{value:d.name},[d.displayName])):e.append(Utils.dom.buildOne("option",{value:d.name},[d.displayName+(inGroup(d.name)?" (shared)":
"")]))}),e.append(Utils.dom.buildOne("option",{value:-5},[Array(20).join("-")])));e.append(Utils.dom.buildOne("option",{value:0},["Share to a Group"]));e.append(Utils.dom.buildOne("option",{value:-1},[Array(20).join("-")]));$(Utils.dom.buildOne("option",{value:-2},["Create a Group..."])).appendTo(e);e.append(Utils.dom.buildOne("option",{value:-5},[Array(20).join("-")]));forEach(c,function(d){b?e.append(Utils.dom.buildOne("option",{value:d.name},[d.displayName])):e.append(Utils.dom.buildOne("option",
{value:d.name},[d.displayName+(inGroup(d.name)?" (shared)":"")]))});e.append(Utils.dom.buildOne("option",{value:-5},[Array(20).join("-")]));$(Utils.dom.buildOne("option",{value:-3},["Refresh"])).appendTo(e);e.change(function(){var d=e.val();-2==d?(chrome.tabs.create({url:"https://groups.diigo.com/create"}),e.val(-1)):-3==d&&($(this).addClass("processing"),chrome.tabs.getSelected(null,function(f){chrome.tabs.sendMessage(f.id,{name:"refreshMyStuff"})}),e.val(-1));0!=d&&-1!=d&&-2!=d&&-3!=d&&($("#diigosc-group-tag").show(),
popCtx.isAnnotated&&$("#bottom").find("div:first-child").show(),$("#Diigo-Bookmark-checkShareExisting").show(),void 0!=popCtx.groupTagsDict[d]?showTags("group",popCtx.groupTagsDict[d]):($("#diigobm-group-tag").show(),chrome.tabs.getSelected(null,function(f){chrome.tabs.sendMessage(f.id,{name:"loadGroupTagsDictionary",groupName:d})})))});e.val(0).change()}
function fillReasearchModeData(a,b){a=a.researchModeData;!0===a._private||2==b?$("#op-private").prop("checked",!0):$("#op-private").prop("checked",!1);!0===a.unread&&$("#op-readlater").prop("checked",!0);a.cache&&!0===a.cache&&$("#op-cache").prop("checked",!0);b=ParseTags.unparseTags(a.tags);$("#diigobm-tag-input").val(b);updateTagStatus();if(a.outliner){var c=$("#diigobm-list");b=c.find(".menu-item[data-id="+a.outliner+"]").text();c.find(".content").text(b).attr("data-id",a.outliner).end().addClass("inputed")}a.group&&
(c=$("#diigobm-group"),b=c.find(".menu-item[data-id="+a.group+"]").text(),c.find(".content").text(b).attr("data-id",a.group).end().addClass("inputed"))}
function buildTagCloud(a){if(0==a.length){var b=document.getElementById("tag-cloud-container");a=document.createElement("div");a.id="no-tag";a.innerHTML="You haven't create any tags yet,:)";b.appendChild(a)}else if(!(0<$("#tag-cloud-container").find("a").length)){var c=getTagScale(a);b=c.topTags;var g=c.maxCount;a=c.first;var e=c.second,d=c.third,f=b.length;c=document.createDocumentFragment();for(var h=0;h<f;h++){var k=document.createElement("a");k.className="Diigo-Bookmark-Tag-item";k.href="#";k.innerText=
b[h].name;var l=b[h].count;l==g&&(k.style.fontSize="20px",k.style.fontWeight="bold");a.forEach(function(m){l==m&&(k.style.fontSize="18px",k.style.fontWeight="bold")});e.forEach(function(m){l==m&&(k.style.fontSize="16px",k.style.fontWeight="bold")});d.forEach(function(m){l==m&&(k.style.fontSize="16px",k.style.fontWeight="regular")});c.appendChild(k)}b=document.getElementById("tag-cloud-container");b.appendChild(c);$("#tag-cloud-container").on("click","a",function(m){/Diigo\-Bookmark\-Tag\-item/.test(m.target.className)&&
toggleTag($(this).text())});updateTagStatus()}};
