var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var e=a[b];if(e&&e.Math==Math)return e}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,e){if(a==Array.prototype||a==Object.prototype)return a;a[b]=e.value;return a};$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";
var $jscomp$lookupPolyfilledValue=function(a,b){var e=$jscomp.propertyToPolyfillSymbol[b];if(null==e)return a[b];e=a[e];return void 0!==e?e:a[b]};$jscomp.polyfill=function(a,b,e,g){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,e,g):$jscomp.polyfillUnisolated(a,b,e,g))};
$jscomp.polyfillUnisolated=function(a,b,e,g){e=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var d=a[g];if(!(d in e))return;e=e[d]}a=a[a.length-1];g=e[a];b=b(g);b!=g&&null!=b&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,e,g){var d=a.split(".");a=1===d.length;g=d[0];g=!a&&g in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var l=0;l<d.length-1;l++){var c=d[l];if(!(c in g))return;g=g[c]}d=d[d.length-1];e=$jscomp.IS_SYMBOL_NATIVE&&"es6"===e?g[d]:null;b=b(e);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:b}):b!==e&&($jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+d,d=
$jscomp.propertyToPolyfillSymbol[d],$jscomp.defineProperty(g,d,{configurable:!0,writable:!0,value:b})))};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function e(c){return c instanceof d?c:new d(function(f,h){f(c)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(c){if(null==this.batch_){this.batch_=[];var f=this;this.asyncExecuteFunction(function(){f.executeBatch_()})}this.batch_.push(c)};var g=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(c){g(c,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var c=
this.batch_;this.batch_=[];for(var f=0;f<c.length;++f){var h=c[f];c[f]=null;try{h()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};b.prototype.asyncThrow_=function(c){this.asyncExecuteFunction(function(){throw c;})};var d=function(c){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var f=this.createResolveAndReject_();try{c(f.resolve,f.reject)}catch(h){f.reject(h)}};d.prototype.createResolveAndReject_=function(){function c(k){return function(m){h||(h=!0,k.call(f,m))}}var f=this,h=!1;
return{resolve:c(this.resolveTo_),reject:c(this.reject_)}};d.prototype.resolveTo_=function(c){if(c===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(c instanceof d)this.settleSameAsPromise_(c);else{a:switch(typeof c){case "object":var f=null!=c;break a;case "function":f=!0;break a;default:f=!1}f?this.resolveToNonPromiseObj_(c):this.fulfill_(c)}};d.prototype.resolveToNonPromiseObj_=function(c){var f=void 0;try{f=c.then}catch(h){this.reject_(h);return}"function"==typeof f?
this.settleSameAsThenable_(f,c):this.fulfill_(c)};d.prototype.reject_=function(c){this.settle_(2,c)};d.prototype.fulfill_=function(c){this.settle_(1,c)};d.prototype.settle_=function(c,f){if(0!=this.state_)throw Error("Cannot settle("+c+", "+f+"): Promise already settled in state"+this.state_);this.state_=c;this.result_=f;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var c=0;c<this.onSettledCallbacks_.length;++c)l.asyncExecute(this.onSettledCallbacks_[c]);
this.onSettledCallbacks_=null}};var l=new b;d.prototype.settleSameAsPromise_=function(c){var f=this.createResolveAndReject_();c.callWhenSettled_(f.resolve,f.reject)};d.prototype.settleSameAsThenable_=function(c,f){var h=this.createResolveAndReject_();try{c.call(f,h.resolve,h.reject)}catch(k){h.reject(k)}};d.prototype.then=function(c,f){function h(n,p){return"function"==typeof n?function(q){try{k(n(q))}catch(r){m(r)}}:p}var k,m,t=new d(function(n,p){k=n;m=p});this.callWhenSettled_(h(c,k),h(f,m));return t};
d.prototype.catch=function(c){return this.then(void 0,c)};d.prototype.callWhenSettled_=function(c,f){function h(){switch(k.state_){case 1:c(k.result_);break;case 2:f(k.result_);break;default:throw Error("Unexpected state: "+k.state_);}}var k=this;null==this.onSettledCallbacks_?l.asyncExecute(h):this.onSettledCallbacks_.push(h)};d.resolve=e;d.reject=function(c){return new d(function(f,h){h(c)})};d.race=function(c){return new d(function(f,h){for(var k=$jscomp.makeIterator(c),m=k.next();!m.done;m=k.next())e(m.value).callWhenSettled_(f,
h)})};d.all=function(c){var f=$jscomp.makeIterator(c),h=f.next();return h.done?e([]):new d(function(k,m){function t(q){return function(r){n[q]=r;p--;0==p&&k(n)}}var n=[],p=0;do n.push(void 0),p++,e(h.value).callWhenSettled_(t(n.length-1),m),h=f.next();while(!h.done)})};return d},"es6","es3");
var Prefs={getUserData:function(a,b){chrome.runtime.sendMessage({name:"getUserData",details:{keys:a}},b)},setUserData:function(a,b){chrome.runtime.sendMessage({name:"setUserData",details:{data:a}},b)}},BoxOAuth={Box_AuthCode:null,Box_Acesstoken:null,DropBox_AuthCode:null,DropBox_Token:null,box_getOauthCode_url:"https://account.box.com/api/oauth2/authorize",box_accesstoken_url:"https://api.box.com/oauth2/token",dropBox_getOauthCode_url:"https://www.dropbox.com/oauth2/authorize",dropBox_accesstoken_url:"https://api.dropboxapi.com/oauth2/token",
Box_client_id:"ulhusf6e8z6vaz6jzh5bloh1gkipgvmu",Box_serert:"eMiQjk9T28IA5ByL3XaY1dIgBeYsRmJd",DropBoxkey:"s9959tffnnfeyie",DropBoxserert:"3cg7o2nmkhlr3nd",init:function(a){var b=this;b.channel=a;b.reset();b.tabUpdatededListener=function(){return b.onTabUpdated.apply(b,[].slice.call(arguments))};chrome.tabs.getCurrent(function(e){b.id=e.id})},onTabUpdated:function(a,b,e){this.oauthPinTab&&this.oauthPinTab.id==a&&/error=/.test(e.url)?(chrome.tabs.remove(this.oauthPinTab.id),chrome.tabs.update(this.id,
{selected:!0}),closeFilePicker()):this.oauthPinTab&&this.oauthPinTab.id==a&&/localhost\/\?code=/.test(e.url)&&this.getAuthCode(e.url)},reset:function(a){this.oauthPinTab=null;chrome.tabs.onUpdated.removeListener(this.tabUpdatededListener);this.channel==Box?this.Box_Acesstoken=this.Box_AuthCode=null:this.channel==Dropbox&&(this.DropBox_Token=this.DropBox_AuthCode=null)},removeUser:function(){this.channel==Box?Prefs.removeUserData("BoxToken"):this.channel==Dropbox&&Prefs.removeUserData("DropBoxToken")},
tryGetAuthCode:function(){var a=this;a.reset();if(a.channel==Box){var b=a.Box_client_id;var e=a.box_getOauthCode_url}else a.channel==Dropbox&&(b=a.DropBoxkey,e=a.dropBox_getOauthCode_url);b&&chrome.tabs.create({url:e+"?response_type=code&redirect_uri=https://localhost&client_id="+b,selected:!0},function(g){a.oauthPinTab=g;chrome.tabs.onUpdated.addListener(a.tabUpdatededListener)})},getAuthCode:function(a){if(a=a.match(/localhost\/\?code=(.*)/)[1])this.Box_AuthCode=a,chrome.tabs.remove(this.oauthPinTab.id),
chrome.tabs.update(this.id,{selected:!0}),this.getAccessToken(a),chrome.tabs.onUpdated.removeListener(this.tabUpdatededListener)},loadTokenInfo:function(){var a=this;return new Promise(function(b,e){a.channel==Box?Prefs.getUserData("BoxToken",function(g){g&&(a.Box_Acesstoken=g,b(g))}):a.channel==Dropbox&&Prefs.getUserData("DropBoxToken",function(g){g&&(a.DropBox_Token=g,b(g))})})},storeTokenInfo:function(a){this.channel==Box?(this.Box_Acesstoken=a,Prefs.setUserData({BoxToken:a})):this.channel==Dropbox&&
(this.DropBox_Token=a,Prefs.setUserData({DropBoxToken:a}))},getAccessToken:function(a){var b=this;if(b.channel==Box){var e=b.Box_client_id;var g=b.box_accesstoken_url;var d=b.Box_serert}else b.channel==Dropbox&&(e=b.DropBoxkey,g=b.dropBox_accesstoken_url,d=b.DropBoxserert);a&&$.ajax({type:"POST",url:g,data:{grant_type:"authorization_code",code:a,client_id:e,client_secret:d,redirect_uri:"https://localhost"},dataType:"json",success:function(l){b.storeTokenInfo(l.access_token);buildBoxItem(l.access_token)},
error:function(l){console.log(l)}})}};
