var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(b){var a=0;return function(){return a<b.length?{done:!1,value:b[a++]}:{done:!0}}};$jscomp.arrayIterator=function(b){return{next:$jscomp.arrayIteratorImpl(b)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,a,c){if(b==Array.prototype||b==Object.prototype)return b;b[a]=c.value;return b};$jscomp.getGlobal=function(b){b=["object"==typeof globalThis&&globalThis,b,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var a=0;a<b.length;++a){var c=b[a];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(b,a){var c=$jscomp.propertyToPolyfillSymbol[a];if(null==c)return b[a];c=b[c];return void 0!==c?c:b[a]};
$jscomp.polyfill=function(b,a,c,d){a&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(b,a,c,d):$jscomp.polyfillUnisolated(b,a,c,d))};$jscomp.polyfillUnisolated=function(b,a,c,d){c=$jscomp.global;b=b.split(".");for(d=0;d<b.length-1;d++){var e=b[d];if(!(e in c))return;c=c[e]}b=b[b.length-1];d=c[b];a=a(d);a!=d&&null!=a&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:a})};
$jscomp.polyfillIsolated=function(b,a,c,d){var e=b.split(".");b=1===e.length;d=e[0];d=!b&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var g=0;g<e.length-1;g++){var f=e[g];if(!(f in d))return;d=d[f]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;a=a(c);null!=a&&(b?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:a}):a!==c&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(d,e,{configurable:!0,writable:!0,value:a})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(b){if(b)return b;var a=function(e,g){this.$jscomp$symbol$id_=e;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:g})};a.prototype.toString=function(){return this.$jscomp$symbol$id_};var c=0,d=function(e){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new a("jscomp_symbol_"+(e||"")+"_"+c++,e)};return d},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(b){if(b)return b;b=Symbol("Symbol.iterator");for(var a="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<a.length;c++){var d=$jscomp.global[a[c]];"function"===typeof d&&"function"!=typeof d.prototype[b]&&$jscomp.defineProperty(d.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return b},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(b){b={next:b};b[Symbol.iterator]=function(){return this};return b};$jscomp.iteratorFromArray=function(b,a){b instanceof String&&(b+="");var c=0,d=!1,e={next:function(){if(!d&&c<b.length){var g=c++;return{value:a(g,b[g]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};
$jscomp.polyfill("Array.prototype.keys",function(b){return b?b:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
var CachePage=function(){var b=function(a){this.tabId=a.tabId;this.groups=a.groups;this.urlMD5=a.urlMD5;this.username=a.username;this.text=a.text;this.html=a.html;this.textMD5=MD5(b.utf8ToBytes(this.text));this.htmlMD5=MD5(b.utf8ToBytes(this.html));this.ispdf=a.ispdf;this.pdfurl=a.pdfurl;debug("new [CachePage]",this)};extend(b,{UPLOAD_TYPE_PAGE_SCREEN_SHOT:1,UPLOAD_TYPE_PAGE:2,UPLOAD_TYPE_TEXT:3,init:function(){},utf8ToBytes:function(a){return unescape(encodeURIComponent(a))},utf8FromBytes:function(a){return decodeURIComponent(escape(a))}});
extend(b.prototype,{sendRequest:function(a,c,d){a=D.config.UPLOAD_SERVER+"/upload/"+a;var e=this,g=new FormData;Object.keys(c).forEach(function(f){g.append(f,c[f])});fetch(a,{method:"POST",body:g}).then(function(f){if(f&&200===f.status)return f.json();e.hasError=!0;d.call(e,e,{code:-1})}).then(function(f){d.call(e,e,f)}).catch(function(f){debug("[CachePage ajax error]",f)})},start:function(){var a=this;a.failed=!1;debug("[CachePage] start uploading");a.ispdf?fetch(a.pdfurl).then(function(c){if(c.ok)return c.arrayBuffer()}).then(function(c){a.html=
c;c=new Uint8Array(a.html);var d="";for(i=0;i<c.length;i++)d+=c[i];a.htmlMD5=hex_md5(d);a.upload_before()}):a.upload_before()},upload_before:function(){this.sendRequest("before",{link_id:this.urlMD5,upload_type:2,user_name:this.username,md5:this.htmlMD5},function(a,c){1==c.code&&c.batch_id?(a.batchId=c.batch_id,a.ispdf?fetch(D.config.UPLOAD_SERVER+"/upload/index?link_id="+(a.urlMD5+"&type=application/pdf&upload_type="+b.UPLOAD_TYPE_PAGE+"&user_name="+a.username+"&batch_id="+a.batchId+"&md5="+a.htmlMD5+
"&charset=UTF-8&override_charset=true"),{method:"POST",headers:{"Content-type":"application/pdf"},body:a.html}).then(function(d){d.ok?a.upload_check():a.uploadDidFail()}):a.upload_upload({type:"text/html",uploadType:b.UPLOAD_TYPE_PAGE,content:a.html,md5:a.htmlMD5},function(){a.upload_upload({type:"text/plain",uploadType:b.UPLOAD_TYPE_TEXT,content:a.text,md5:a.textMD5},function(){a.upload_check()})})):2==c.code?a.uploadNotNeeded():c.over_quota?a.uploadDidFail({overQuota:!0,msg:c.msg}):a.uploadDidFail()})},
upload_upload:function(a,c){this.sendRequest("",{link_id:this.urlMD5,type:a.type,upload_type:a.uploadType,user_name:this.username,batch_id:this.batchId,md5:a.md5,content_string:a.content,charset:"UTF-8",override_charset:!0},function(d,e){1==e.code?c():d.uploadDidFail()})},upload_check:function(){this.sendRequest("check_transaction",{link_id:this.urlMD5,upload_type:2,user_name:this.username,batch_id:this.batchId},function(a,c){if(1==c.code){a.batchId=c.batch_id;var d,e;if(a.ispdf){if($.each(c.files,
function(g,f){g=f[2];f[0]==b.UPLOAD_TYPE_PAGE&&(e=a.htmlMD5==g)}),e){debug("[CachePage] check OK");a.upload_complete({status:1});return}}else if($.each(c.files,function(g,f){g=f[0];f=f[2];g==b.UPLOAD_TYPE_TEXT?d=a.textMD5==f:g==b.UPLOAD_TYPE_PAGE&&(e=a.htmlMD5==f)}),e&&d){debug("[CachePage] check OK");a.upload_complete({status:1});return}}debug("[CachePage] check failed");a.uploadDidFail()})},upload_complete:function(a){this.sendRequest("upload_complete",{link_id:this.urlMD5,user_name:this.username,
batch_id:this.batchId,status:a.status,groups:JSON.stringify(this.groups)},function(c,d){c.failed||c.uploadDidSucceed()})},uploadDidFail:function(a){a=a||{};this.failed=!0;a.dontRequetComplete||this.upload_complete({status:0});Messenger.send(this.tabId,{name:"uploadDidFail",details:a})},uploadDidSucceed:function(){},uploadNotNeeded:function(){Messenger.send(this.tabId,{name:"uploadDidSucceed"})}});return b}();
