function ComboSearch(c,a,b,d){this.query=c;this.tabId=a;this.element=b;this.issearcho=d;this.timer=null}
extend(ComboSearch,{init:function(){},onTabUpdated:function(c,a,b,d){b=b.url;if("loading"==a.status&&SignInManager.isSignedIn()){if(/\.google\./.test(b)){var e=(a=b.match(/.*(&|\?|#)q=([^&]+)(&|$)/))&&a[2];var f="#rhs"}else/\.bing\./.test(b)?(e=(a=b.match(/(&q|\?q)=(.*?)(&|$)/))&&a[2],f="#results_container"):/\.yahoo\./.test(b)&&(e=(a=b.match(/(&p|\?p)=(.*?)(&|$)/))&&a[2],f="#web");(new this(e,c,f,d)).search()}},isGoogleSearch:function(c){return/\.google\./.test(c)?(c=c.match(/&q=(.*?)(&|$)/))&&c[1]:
null}});
extend(ComboSearch.prototype,{discard:function(){this.discarded=!0;this.api.cancel()},inject:function(){var c=this;chrome.tabs.get(c.tabId,function(a){isURLApplicable2(a.url)&&(chrome.scripting.insertCSS({target:{tabId:c.tabId},files:["css/comboSearch.css"]}),chrome.scripting.executeScript({target:{tabId:c.tabId},files:["js/content/comboSearch.js"]}))})},search:function(){var c=this;c.inject();var a=new WebAPICall;void 0!=c.query&&a.invoke("search_bookmark",{fullText:decodeURIComponent(c.query.replace(/\+/g,"%20"))},
{user:GlobalData.user,complete:function(b){if(!b.cancelled&&(b=b.resp)&&1==b.code&&0<b.result.bookmarks.length)c.onResult(b.result)}})},onResult:function(c){function a(d,e,f){ComboSearch.showResult(JSON.stringify({results:d.bookmarks,total:d.total,key:e,element:f}))}var b=this;b.discarded||chrome.tabs.get(b.tabId,function(d){b.timer=setInterval(function(){chrome.scripting.executeScript({target:{tabId:d.id},func:a,args:[c,b.query,b.element]},function(){clearInterval(b.timer)})},300)})}});
function isURLApplicable2(c){return/\/item\/pdf/i.test(c)||/^https?:\/\/chrome\.google\.com\/(extensions|webstore)/i.test(c)||/^chrome?:\/\/*/i.test(c)?!1:!0}function SearchO(c,a,b){this.query=c;this.tabId=a;this.iscombosearch=b}
extend(SearchO,{init:function(c,a,b,d){b=b.url;isURLApplicable2(b)&&(chrome.scripting.insertCSS({target:{tabId:this.tabId},files:["css/comboSearch.css"]}),chrome.scripting.executeScript({target:{tabId:this.tabId},files:["js/content/searcho.js"]}),"loading"==a.status&&(/\.google\./.test(b)?(a=(a=b.match(/(&q|\?q)=(.*?)(&|$|#)/))&&a[2],(new this(a,c,d)).google()):/\.bing\./.test(b)?(a=(a=b.match(/(&q|\?q)=(.*?)(&|$|#)/))&&a[2],(new this(a,c,d)).bing()):/\.yahoo\./.test(b)&&(a=(a=b.match(/(&p|\?p)=(.*?)(&|$|#)/))&&
a[2],(new this(a,c,d)).yahoo())))}});
extend(SearchO.prototype,{google:function(){function c(){searcho.showResult(JSON.stringify({query:a.query,iscombosearch:a.iscombosearch,element:"#center_col"}))}var a=this;chrome.tabs.get(a.tabId,function(b){chrome.scripting.executeScript({target:{tabId:b.id},func:c})})},bing:function(){function c(){searcho.showResult(JSON.stringify({query:a.query,iscombosearch:a.iscombosearch,element:"#results_container"}))}var a=this;chrome.tabs.get(a.tabId,function(b){chrome.scripting.executeScript({target:{tabId:b.id},func:c})})},
yahoo:function(){function c(){searcho.showResult(JSON.stringify({query:a.query,iscombosearch:a.iscombosearch,element:"#web"}))}var a=this;chrome.tabs.get(a.tabId,function(b){chrome.scripting.executeScript({target:{tabId:b.id},func:c})})}});
