var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,f){if(a==Array.prototype||a==Object.prototype)return a;a[b]=f.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var f=a[b];if(f&&f.Math==Math)return f}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var f=$jscomp.propertyToPolyfillSymbol[b];if(null==f)return a[b];f=a[f];return void 0!==f?f:a[b]};$jscomp.polyfill=function(a,b,f,g){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,f,g):$jscomp.polyfillUnisolated(a,b,f,g))};
$jscomp.polyfillUnisolated=function(a,b,f,g){f=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var c=a[g];if(!(c in f))return;f=f[c]}a=a[a.length-1];g=f[a];b=b(g);b!=g&&null!=b&&$jscomp.defineProperty(f,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,f,g){var c=a.split(".");a=1===c.length;g=c[0];g=!a&&g in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var m=0;m<c.length-1;m++){var d=c[m];if(!(d in g))return;g=g[d]}c=c[c.length-1];f=$jscomp.IS_SYMBOL_NATIVE&&"es6"===f?g[c]:null;b=b(f);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,c,{configurable:!0,writable:!0,value:b}):b!==f&&($jscomp.propertyToPolyfillSymbol[c]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(c):$jscomp.POLYFILL_PREFIX+c,c=
$jscomp.propertyToPolyfillSymbol[c],$jscomp.defineProperty(g,c,{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(f){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.generator={};
$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};
$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};
$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};
$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var f=a.next();$jscomp.generator.ensureIteratorResultIsObject_(f);if(f.done)this.yieldResult=f.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(f.value,b)};$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};
$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,f){f?this.finallyContexts_[f]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(f){return{value:f,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,f){try{var g=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(g);if(!g.done)return this.context_.stop_(),g;var c=g.value}catch(m){return this.context_.yieldAllIterator_=null,this.context_.throw_(m),this.nextStep_()}this.context_.yieldAllIterator_=null;f.call(this.context_,c);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(g){return a.next(g)}function f(g){return a.throw(g)}return new Promise(function(g,c){function m(d){d.done?g(d.value):Promise.resolve(d.value).then(b,f).then(m,c)}m(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.initSymbol=function(){};$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(c,m){this.$jscomp$symbol$id_=c;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:m})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var f=0,g=function(c){if(this instanceof g)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(c||"")+"_"+f++,c)};return g},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),f=0;f<b.length;f++){var g=$jscomp.global[b[f]];"function"===typeof g&&"function"!=typeof g.prototype[a]&&$jscomp.defineProperty(g.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function f(d){return d instanceof c?d:new c(function(e,h){e(d)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(d){if(null==this.batch_){this.batch_=[];var e=this;this.asyncExecuteFunction(function(){e.executeBatch_()})}this.batch_.push(d)};var g=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(d){g(d,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var d=
this.batch_;this.batch_=[];for(var e=0;e<d.length;++e){var h=d[e];d[e]=null;try{h()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(d){this.asyncExecuteFunction(function(){throw d;})};var c=function(d){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var e=this.createResolveAndReject_();try{d(e.resolve,e.reject)}catch(h){e.reject(h)}};c.prototype.createResolveAndReject_=function(){function d(l){return function(n){h||(h=!0,l.call(e,n))}}var e=this,h=!1;
return{resolve:d(this.resolveTo_),reject:d(this.reject_)}};c.prototype.resolveTo_=function(d){if(d===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof c)this.settleSameAsPromise_(d);else{a:switch(typeof d){case "object":var e=null!=d;break a;case "function":e=!0;break a;default:e=!1}e?this.resolveToNonPromiseObj_(d):this.fulfill_(d)}};c.prototype.resolveToNonPromiseObj_=function(d){var e=void 0;try{e=d.then}catch(h){this.reject_(h);return}"function"==typeof e?
this.settleSameAsThenable_(e,d):this.fulfill_(d)};c.prototype.reject_=function(d){this.settle_(2,d)};c.prototype.fulfill_=function(d){this.settle_(1,d)};c.prototype.settle_=function(d,e){if(0!=this.state_)throw Error("Cannot settle("+d+", "+e+"): Promise already settled in state"+this.state_);this.state_=d;this.result_=e;this.executeOnSettledCallbacks_()};c.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var d=0;d<this.onSettledCallbacks_.length;++d)m.asyncExecute(this.onSettledCallbacks_[d]);
this.onSettledCallbacks_=null}};var m=new b;c.prototype.settleSameAsPromise_=function(d){var e=this.createResolveAndReject_();d.callWhenSettled_(e.resolve,e.reject)};c.prototype.settleSameAsThenable_=function(d,e){var h=this.createResolveAndReject_();try{d.call(e,h.resolve,h.reject)}catch(l){h.reject(l)}};c.prototype.then=function(d,e){function h(q,t){return"function"==typeof q?function(r){try{l(q(r))}catch(k){n(k)}}:t}var l,n,p=new c(function(q,t){l=q;n=t});this.callWhenSettled_(h(d,l),h(e,n));return p};
c.prototype.catch=function(d){return this.then(void 0,d)};c.prototype.callWhenSettled_=function(d,e){function h(){switch(l.state_){case 1:d(l.result_);break;case 2:e(l.result_);break;default:throw Error("Unexpected state: "+l.state_);}}var l=this;null==this.onSettledCallbacks_?m.asyncExecute(h):this.onSettledCallbacks_.push(h)};c.resolve=f;c.reject=function(d){return new c(function(e,h){h(d)})};c.race=function(d){return new c(function(e,h){for(var l=$jscomp.makeIterator(d),n=l.next();!n.done;n=l.next())f(n.value).callWhenSettled_(e,
h)})};c.all=function(d){var e=$jscomp.makeIterator(d),h=e.next();return h.done?f([]):new c(function(l,n){function p(r){return function(k){q[r]=k;t--;0==t&&l(q)}}var q=[],t=0;do q.push(void 0),t++,f(h.value).callWhenSettled_(p(q.length-1),n),h=e.next();while(!h.done)})};return c},"es6","es3");$jscomp.findInternal=function(a,b,f){a instanceof String&&(a=String(a));for(var g=a.length,c=0;c<g;c++){var m=a[c];if(b.call(f,m,c,a))return{i:c,v:m}}return{i:-1,v:void 0}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,f){return $jscomp.findInternal(this,b,f).v}},"es6","es3");var KEY_UP=38,KEY_DOWN=40,KEY_ESC=27,KEY_ENTER=13;
function initForm(){function a(g){function c(){""==e.find(".content").text()?e.removeClass("inputed focused"):e.removeClass("focused");l.val("").trigger("input");p.scrollTop(0);n.show();q.hide()}function m(){e.find(".menu-item:visible").removeClass("selected").eq(r).addClass("selected");var k=e.find(".menu-item:visible").eq(r),u=k.offset().top+p.scrollTop()-p.offset().top;k=k.outerHeight();u+k>p.outerHeight()+p.scrollTop()?p.scrollTop(u+k-p.outerHeight()):u<p.scrollTop()&&p.scrollTop(u)}function d(){r=
-1;e.find(".menu-item").removeClass("selected")}var e=$(g),h=e.find(".content"),l=e.find(".search-box input"),n=e.find(".search-box"),p=e.find(".item-container"),q=e.find(".add-box"),t=e.find(".remove-select"),r=-1;e.on("click",".menu-item",function(){h.text($(this).text()).attr("data-id",$(this).attr("data-id"));c();e.trigger("change")}).on("mouseenter",".menu-item",function(){$(this).addClass("selected").siblings().removeClass("selected")});t.on("click",function(k){k.stopPropagation();e.removeClass("inputed focused");
h.text("").attr("data-id","");e.trigger("change")});p.on("mouseleave",function(){d()});h.on("click",function(){e.addClass("inputed focused");l.focus()});e.on("keydown",function(k){13!=k.keyCode&&32!=k.keyCode||h.trigger("click")});e.find(".add-btn").on("click",function(){n.hide();q.show().find("input").focus()});e.find(".cancel").on("click",function(){n.show();q.hide()});l.on("input",function(){var k=$(this).val().toLowerCase();e.find(".menu-item").each(function(){-1==$(this).text().toLowerCase().indexOf(k)?
$(this).hide():$(this).show();d()})}).on("keydown",function(k){switch(k.keyCode){case KEY_UP:-1==r&&(r=e.find(".menu-item:visible").length);r--;m();break;case KEY_DOWN:r==e.find(".menu-item:visible").length-1&&(r=-1);r++;m();break;case KEY_ENTER:k.stopPropagation();k=e.find(".menu-item.selected");h.text(k.text()).attr("data-id",k.attr("data-id"));c();e.focus();break;case KEY_ESC:c()}});$(document).on("click",function(k){$.contains(g,k.target)||c()})}var b,f;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){if(1==
g.nextAddress)return $(".form-input").find("input").on("focus",function(){$(this).parent().addClass("inputed focused")}).on("blur",function(){""===$(this).val()&&$(this).parent().removeClass("inputed");$(this).parent().removeClass("focused")}).on("change",function(){""!==$(this).val()&&$(this).parent().addClass("inputed")}),g.yield(getStorage("globalData"),2);b=g.yieldResult;f=b.permissions;f.snapshot?$("#diigo-acache-field").hide():($("#diigo-acache-field").show(),$("#op-cache").prop("disabled",
!0),$("#op-cache").parent().addClass("disabled"),$("#f-cache").prop("disabled",!0),$("#f-cache").parent().addClass("disabled"));$(".form-checkbox").on("mouseup",function(){console.log("mouseup");var c=this;setTimeout(function(){$(c).find("input").blur()},0)}).find("input").on("keydown",function(c){13==c.keyCode&&$(this).trigger("click")});$(".form-textarea").find("textarea").on("focus",function(){$(this).parent().addClass("inputed focused")}).on("blur",function(){""===$(this).val()&&$(this).parent().removeClass("inputed");
$(this).parent().removeClass("focused")}).on("change",function(){""!==$(this).text()&&$(this).parent().addClass("inputed")});$(".form-select").each(function(){a(this)});g.jumpToEnd()})}$(document).ready(function(){initForm()});
