/*
 jQuery JavaScript Library v1.7.1
 http://jquery.com/

 Copyright 2011, John Resig
 Dual licensed under the MIT or GPL Version 2 licenses.
 http://jquery.org/license

 Includes Sizzle.js
 http://sizzlejs.com/
 Copyright 2011, The Dojo Foundation
 Released under the MIT, BSD, and GPL Licenses.

 Date: Mon Nov 21 21:11:03 2011 -0500
 Sizzle CSS Selector Engine
  Copyright 2011, The Dojo Foundation
  Released under the MIT, BSD, and GPL Licenses.
  More information: http://sizzlejs.com/
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(F,v,M){F instanceof String&&(F=String(F));for(var R=F.length,P=0;P<R;P++){var ba=F[P];if(v.call(M,ba,P,F))return{i:P,v:ba}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(F,v,M){if(F==Array.prototype||F==Object.prototype)return F;F[v]=M.value;return F};$jscomp.getGlobal=function(F){F=["object"==typeof globalThis&&globalThis,F,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var v=0;v<F.length;++v){var M=F[v];if(M&&M.Math==Math)return M}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(F,v){var M=$jscomp.propertyToPolyfillSymbol[v];if(null==M)return F[v];M=F[M];return void 0!==M?M:F[v]};
$jscomp.polyfill=function(F,v,M,R){v&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(F,v,M,R):$jscomp.polyfillUnisolated(F,v,M,R))};$jscomp.polyfillUnisolated=function(F,v,M,R){M=$jscomp.global;F=F.split(".");for(R=0;R<F.length-1;R++){var P=F[R];if(!(P in M))return;M=M[P]}F=F[F.length-1];R=M[F];v=v(R);v!=R&&null!=v&&$jscomp.defineProperty(M,F,{configurable:!0,writable:!0,value:v})};
$jscomp.polyfillIsolated=function(F,v,M,R){var P=F.split(".");F=1===P.length;R=P[0];R=!F&&R in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var ba=0;ba<P.length-1;ba++){var ca=P[ba];if(!(ca in R))return;R=R[ca]}P=P[P.length-1];M=$jscomp.IS_SYMBOL_NATIVE&&"es6"===M?R[P]:null;v=v(M);null!=v&&(F?$jscomp.defineProperty($jscomp.polyfills,P,{configurable:!0,writable:!0,value:v}):v!==M&&($jscomp.propertyToPolyfillSymbol[P]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(P):$jscomp.POLYFILL_PREFIX+
P,P=$jscomp.propertyToPolyfillSymbol[P],$jscomp.defineProperty(R,P,{configurable:!0,writable:!0,value:v})))};$jscomp.polyfill("Array.prototype.find",function(F){return F?F:function(v,M){return $jscomp.findInternal(this,v,M).v}},"es6","es3");
(function(F,v){function M(a){var b=Ha[a]={},d;a=a.split(/\s+/);var e=0;for(d=a.length;e<d;e++)b[a[e]]=!0;return b}function R(a,b,d){if(d===v&&1===a.nodeType)if(d="data-"+b.replace(ub,"-$1").toLowerCase(),d=a.getAttribute(d),"string"===typeof d){try{d="true"===d?!0:"false"===d?!1:"null"===d?null:c.isNumeric(d)?parseFloat(d):vb.test(d)?c.parseJSON(d):d}catch(e){}c.data(a,b,d)}else d=v;return d}function P(a){for(var b in a)if(("data"!==b||!c.isEmptyObject(a[b]))&&"toJSON"!==b)return!1;return!0}function ba(a,
b,d){var e=b+"defer",f=b+"queue",h=b+"mark",k=c._data(a,e);!k||"queue"!==d&&c._data(a,f)||"mark"!==d&&c._data(a,h)||setTimeout(function(){c._data(a,f)||c._data(a,h)||(c.removeData(a,e,!0),k.fire())},0)}function ca(){return!1}function pa(){return!0}function Ia(a){return!a||!a.parentNode||11===a.parentNode.nodeType}function Ja(a,b,d){b=b||0;if(c.isFunction(b))return c.grep(a,function(f,h){return!!b.call(f,h,f)===d});if(b.nodeType)return c.grep(a,function(f,h){return f===b===d});if("string"===typeof b){var e=
c.grep(a,function(f){return 1===f.nodeType});if(wb.test(b))return c.filter(b,e,!d);b=c.filter(b,e)}return c.grep(a,function(f,h){return 0<=c.inArray(f,b)===d})}function Ka(a){var b=La.split("|");a=a.createDocumentFragment();if(a.createElement)for(;b.length;)a.createElement(b.pop());return a}function xb(a,b){return c.nodeName(a,"table")?a.getElementsByTagName("tbody")[0]||a.appendChild(a.ownerDocument.createElement("tbody")):a}function Ma(a,b){if(1===b.nodeType&&c.hasData(a)){var d,e;var f=c._data(a);
a=c._data(b,f);var h=f.events;if(h)for(d in delete a.handle,a.events={},h)for(f=0,e=h[d].length;f<e;f++)c.event.add(b,d+(h[d][f].namespace?".":"")+h[d][f].namespace,h[d][f],h[d][f].data);a.data&&(a.data=c.extend({},a.data))}}function Na(a,b){if(1===b.nodeType){b.clearAttributes&&b.clearAttributes();b.mergeAttributes&&b.mergeAttributes(a);var d=b.nodeName.toLowerCase();if("object"===d)b.outerHTML=a.outerHTML;else if("input"===d&&("checkbox"===a.type||"radio"===a.type))a.checked&&(b.defaultChecked=
b.checked=a.checked),b.value!==a.value&&(b.value=a.value);else if("option"===d)b.selected=a.defaultSelected;else if("input"===d||"textarea"===d)b.defaultValue=a.defaultValue;b.removeAttribute(c.expando)}}function qa(a){return"undefined"!==typeof a.getElementsByTagName?a.getElementsByTagName("*"):"undefined"!==typeof a.querySelectorAll?a.querySelectorAll("*"):[]}function Oa(a){if("checkbox"===a.type||"radio"===a.type)a.defaultChecked=a.checked}function Pa(a){var b=(a.nodeName||"").toLowerCase();"input"===
b?Oa(a):"script"!==b&&"undefined"!==typeof a.getElementsByTagName&&c.grep(a.getElementsByTagName("input"),Oa)}function yb(a,b){b.src?c.ajax({url:b.src,async:!1,dataType:"script"}):c.globalEval((b.text||b.textContent||b.innerHTML||"").replace(zb,"/*$0*/"));b.parentNode&&b.parentNode.removeChild(b)}function Qa(a,b,d){var e="width"===b?a.offsetWidth:a.offsetHeight,f="width"===b?Ab:Bb,h=0,k=f.length;if(0<e){if("border"!==d)for(;h<k;h++)d||(e-=parseFloat(c.css(a,"padding"+f[h]))||0),e="margin"===d?e+(parseFloat(c.css(a,
d+f[h]))||0):e-(parseFloat(c.css(a,"border"+f[h]+"Width"))||0);return e+"px"}e=ma(a,b,b);if(0>e||null==e)e=a.style[b]||0;e=parseFloat(e)||0;if(d)for(;h<k;h++)e+=parseFloat(c.css(a,"padding"+f[h]))||0,"padding"!==d&&(e+=parseFloat(c.css(a,"border"+f[h]+"Width"))||0),"margin"===d&&(e+=parseFloat(c.css(a,d+f[h]))||0);return e+"px"}function Ra(a){return function(b,d){"string"!==typeof b&&(d=b,b="*");if(c.isFunction(d)){b=b.toLowerCase().split(Sa);for(var e=0,f=b.length,h,k;e<f;e++)h=b[e],(k=/^\+/.test(h))&&
(h=h.substr(1)||"*"),h=a[h]=a[h]||[],h[k?"unshift":"push"](d)}}}function ra(a,b,d,e,f,h){f=f||b.dataTypes[0];h=h||{};h[f]=!0;f=a[f];for(var k=0,n=f?f.length:0,q=a===wa,x;k<n&&(q||!x);k++)x=f[k](b,d,e),"string"===typeof x&&(!q||h[x]?x=v:(b.dataTypes.unshift(x),x=ra(a,b,d,e,x,h)));!q&&x||h["*"]||(x=ra(a,b,d,e,"*",h));return x}function Ta(a,b){var d,e,f=c.ajaxSettings.flatOptions||{};for(d in b)b[d]!==v&&((f[d]?a:e||(e={}))[d]=b[d]);e&&c.extend(!0,a,e)}function xa(a,b,d,e){if(c.isArray(b))c.each(b,function(h,
k){d||Cb.test(a)?e(a,k):xa(a+"["+("object"===typeof k||c.isArray(k)?h:"")+"]",k,d,e)});else if(d||null==b||"object"!==typeof b)e(a,b);else for(var f in b)xa(a+"["+f+"]",b[f],d,e)}function Ua(){try{return new F.XMLHttpRequest}catch(a){}}function Va(){setTimeout(Db,0);return sa=c.now()}function Db(){sa=v}function fa(a,b){var d={};c.each(Wa.concat.apply([],Wa.slice(0,b)),function(){d[this]=a});return d}function Xa(a){if(!ya[a]){var b=E.body,d=c("<"+a+">").appendTo(b),e=d.css("display");d.remove();if("none"===
e||""===e)Z||(Z=E.createElement("iframe"),Z.frameBorder=Z.width=Z.height=0),b.appendChild(Z),ha&&Z.createElement||(ha=(Z.contentWindow||Z.contentDocument).document,ha.write(("CSS1Compat"===E.compatMode?"<!doctype html>":"")+"<html><body>"),ha.close()),d=ha.createElement(a),ha.body.appendChild(d),e=c.css(d,"display"),b.removeChild(Z);ya[a]=e}return ya[a]}function za(a){return c.isWindow(a)?a:9===a.nodeType?a.defaultView||a.parentWindow:!1}var E=F.document,Eb=F.navigator,Fb=F.location,c=function(){function a(){if(!b.isReady){try{E.documentElement.doScroll("left")}catch(m){setTimeout(a,
1);return}b.ready()}}var b=function(m,w){return new b.fn.init(m,w,O)},d=F.jQuery,e=F.$,f=/^(?:[^#<]*(<[\w\W]+>)[^>]*$|#([\w\-]*)$)/,h=/\S/,k=/^\s+/,n=/\s+$/,q=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,x=/^[\],:{}\s]*$/,z=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,r=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,D=/(?:^|:|,)(?:\s*\[)+/g,A=/(webkit)[ \/]([\w.]+)/,N=/(opera)(?:.*version)?[ \/]([\w.]+)/,K=/(msie) ([\w.]+)/,U=/(mozilla)(?:.*? rv:([\w.]+))?/,J=/-([a-z]|[0-9])/ig,aa=/^-ms-/,W=function(m,
w){return(w+"").toUpperCase()},Y=Eb.userAgent,g,l,p=Object.prototype.toString,t=Object.prototype.hasOwnProperty,u=Array.prototype.push,y=Array.prototype.slice,G=String.prototype.trim,H=Array.prototype.indexOf,L={};b.fn=b.prototype={constructor:b,init:function(m,w,C){if(!m)return this;if(m.nodeType)return this.context=this[0]=m,this.length=1,this;if("body"===m&&!w&&E.body)return this.context=E,this[0]=E.body,this.selector=m,this.length=1,this;if("string"===typeof m){var B="<"===m.charAt(0)&&">"===
m.charAt(m.length-1)&&3<=m.length?[null,m,null]:f.exec(m);if(!B||!B[1]&&w)return!w||w.jquery?(w||C).find(m):this.constructor(w).find(m);if(B[1])return C=(w=w instanceof b?w[0]:w)?w.ownerDocument||w:E,(m=q.exec(m))?b.isPlainObject(w)?(m=[E.createElement(m[1])],b.fn.attr.call(m,w,!0)):m=[C.createElement(m[1])]:(m=b.buildFragment([B[1]],[C]),m=(m.cacheable?b.clone(m.fragment):m.fragment).childNodes),b.merge(this,m);if((w=E.getElementById(B[2]))&&w.parentNode){if(w.id!==B[2])return C.find(m);this.length=
1;this[0]=w}this.context=E;this.selector=m;return this}if(b.isFunction(m))return C.ready(m);m.selector!==v&&(this.selector=m.selector,this.context=m.context);return b.makeArray(m,this)},selector:"",jquery:"1.7.1",length:0,size:function(){return this.length},toArray:function(){return y.call(this,0)},get:function(m){return null==m?this.toArray():0>m?this[this.length+m]:this[m]},pushStack:function(m,w,C){var B=this.constructor();b.isArray(m)?u.apply(B,m):b.merge(B,m);B.prevObject=this;B.context=this.context;
"find"===w?B.selector=this.selector+(this.selector?" ":"")+C:w&&(B.selector=this.selector+"."+w+"("+C+")");return B},each:function(m,w){return b.each(this,m,w)},ready:function(m){b.bindReady();g.add(m);return this},eq:function(m){m=+m;return-1===m?this.slice(m):this.slice(m,m+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},slice:function(){return this.pushStack(y.apply(this,arguments),"slice",y.call(arguments).join(","))},map:function(m){return this.pushStack(b.map(this,
function(w,C){return m.call(w,C,w)}))},end:function(){return this.prevObject||this.constructor(null)},push:u,sort:[].sort,splice:[].splice};b.fn.init.prototype=b.fn;b.extend=b.fn.extend=function(){var m,w,C,B=arguments[0]||{},I=1,S=arguments.length,T=!1;"boolean"===typeof B&&(T=B,B=arguments[1]||{},I=2);"object"===typeof B||b.isFunction(B)||(B={});S===I&&(B=this,--I);for(;I<S;I++)if(null!=(m=arguments[I]))for(w in m){var Q=B[w];var V=m[w];B!==V&&(T&&V&&(b.isPlainObject(V)||(C=b.isArray(V)))?(C?(C=
!1,Q=Q&&b.isArray(Q)?Q:[]):Q=Q&&b.isPlainObject(Q)?Q:{},B[w]=b.extend(T,Q,V)):V!==v&&(B[w]=V))}return B};b.extend({noConflict:function(m){F.$===b&&(F.$=e);m&&F.jQuery===b&&(F.jQuery=d);return b},isReady:!1,readyWait:1,holdReady:function(m){m?b.readyWait++:b.ready(!0)},ready:function(m){if(!0===m&&!--b.readyWait||!0!==m&&!b.isReady){if(!E.body)return setTimeout(b.ready,1);b.isReady=!0;!0!==m&&0<--b.readyWait||(g.fireWith(E,[b]),b.fn.trigger&&b(E).trigger("ready").off("ready"))}},bindReady:function(){if(!g){g=
b.Callbacks("once memory");if("complete"===E.readyState)return setTimeout(b.ready,1);if(E.addEventListener)E.addEventListener("DOMContentLoaded",l,!1),F.addEventListener("load",b.ready,!1);else if(E.attachEvent){E.attachEvent("onreadystatechange",l);F.attachEvent("onload",b.ready);var m=!1;try{m=null==F.frameElement}catch(w){}E.documentElement.doScroll&&m&&a()}}},isFunction:function(m){return"function"===b.type(m)},isArray:Array.isArray||function(m){return"array"===b.type(m)},isWindow:function(m){return m&&
"object"===typeof m&&"setInterval"in m},isNumeric:function(m){return!isNaN(parseFloat(m))&&isFinite(m)},type:function(m){return null==m?String(m):L[p.call(m)]||"object"},isPlainObject:function(m){if(!m||"object"!==b.type(m)||m.nodeType||b.isWindow(m))return!1;try{if(m.constructor&&!t.call(m,"constructor")&&!t.call(m.constructor.prototype,"isPrototypeOf"))return!1}catch(C){return!1}for(var w in m);return w===v||t.call(m,w)},isEmptyObject:function(m){for(var w in m)return!1;return!0},error:function(m){throw Error(m);
},parseJSON:function(m){if("string"!==typeof m||!m)return null;m=b.trim(m);if(F.JSON&&F.JSON.parse)return F.JSON.parse(m);if(x.test(m.replace(z,"@").replace(r,"]").replace(D,"")))return(new Function("return "+m))();b.error("Invalid JSON: "+m)},parseXML:function(m){try{if(F.DOMParser){var w=new DOMParser;var C=w.parseFromString(m,"text/xml")}else C=new ActiveXObject("Microsoft.XMLDOM"),C.async="false",C.loadXML(m)}catch(B){C=v}C&&C.documentElement&&!C.getElementsByTagName("parsererror").length||b.error("Invalid XML: "+
m);return C},noop:function(){},globalEval:function(m){m&&h.test(m)&&(F.execScript||function(w){F.eval.call(F,w)})(m)},camelCase:function(m){return m.replace(aa,"ms-").replace(J,W)},nodeName:function(m,w){return m.nodeName&&m.nodeName.toUpperCase()===w.toUpperCase()},each:function(m,w,C){var B,I=0,S=m.length,T=S===v||b.isFunction(m);if(C)if(T)for(B in m){if(!1===w.apply(m[B],C))break}else for(;I<S&&!1!==w.apply(m[I++],C););else if(T)for(B in m){if(!1===w.call(m[B],B,m[B]))break}else for(;I<S&&!1!==
w.call(m[I],I,m[I++]););return m},trim:G?function(m){return null==m?"":G.call(m)}:function(m){return null==m?"":m.toString().replace(k,"").replace(n,"")},makeArray:function(m,w){w=w||[];if(null!=m){var C=b.type(m);null==m.length||"string"===C||"function"===C||"regexp"===C||b.isWindow(m)?u.call(w,m):b.merge(w,m)}return w},inArray:function(m,w,C){if(w){if(H)return H.call(w,m,C);var B=w.length;for(C=C?0>C?Math.max(0,B+C):C:0;C<B;C++)if(C in w&&w[C]===m)return C}return-1},merge:function(m,w){var C=m.length,
B=0;if("number"===typeof w.length)for(var I=w.length;B<I;B++)m[C++]=w[B];else for(;w[B]!==v;)m[C++]=w[B++];m.length=C;return m},grep:function(m,w,C){var B=[];C=!!C;for(var I=0,S=m.length;I<S;I++){var T=!!w(m[I],I);C!==T&&B.push(m[I])}return B},map:function(m,w,C){var B,I=[],S=0,T=m.length;if(m instanceof b||T!==v&&"number"===typeof T&&(0<T&&m[0]&&m[T-1]||0===T||b.isArray(m)))for(;S<T;S++){var Q=w(m[S],S,C);null!=Q&&(I[I.length]=Q)}else for(B in m)Q=w(m[B],B,C),null!=Q&&(I[I.length]=Q);return I.concat.apply([],
I)},guid:1,proxy:function(m,w){if("string"===typeof w){var C=m[w];w=m;m=C}if(!b.isFunction(m))return v;var B=y.call(arguments,2);C=function(){return m.apply(w,B.concat(y.call(arguments)))};C.guid=m.guid=m.guid||C.guid||b.guid++;return C},access:function(m,w,C,B,I,S){var T=m.length;if("object"===typeof w){for(var Q in w)b.access(m,Q,w[Q],B,I,C);return m}if(C!==v){B=!S&&B&&b.isFunction(C);for(Q=0;Q<T;Q++)I(m[Q],w,B?C.call(m[Q],Q,I(m[Q],w)):C,S);return m}return T?I(m[0],w):v},now:function(){return(new Date).getTime()},
uaMatch:function(m){m=m.toLowerCase();m=A.exec(m)||N.exec(m)||K.exec(m)||0>m.indexOf("compatible")&&U.exec(m)||[];return{browser:m[1]||"",version:m[2]||"0"}},sub:function(){function m(C,B){return new m.fn.init(C,B)}b.extend(!0,m,this);m.superclass=this;m.fn=m.prototype=this();m.fn.constructor=m;m.sub=this.sub;m.fn.init=function(C,B){B&&B instanceof b&&!(B instanceof m)&&(B=m(B));return b.fn.init.call(this,C,B,w)};m.fn.init.prototype=m.fn;var w=m(E);return m},browser:{}});b.each("Boolean Number String Function Array Date RegExp Object".split(" "),
function(m,w){L["[object "+w+"]"]=w.toLowerCase()});Y=b.uaMatch(Y);Y.browser&&(b.browser[Y.browser]=!0,b.browser.version=Y.version);b.browser.webkit&&(b.browser.safari=!0);h.test("\u00a0")&&(k=/^[\s\xA0]+/,n=/[\s\xA0]+$/);var O=b(E);E.addEventListener?l=function(){E.removeEventListener("DOMContentLoaded",l,!1);b.ready()}:E.attachEvent&&(l=function(){"complete"===E.readyState&&(E.detachEvent("onreadystatechange",l),b.ready())});return b}(),Ha={};c.Callbacks=function(a){a=a?Ha[a]||M(a):{};var b=[],
d=[],e,f,h,k,n,q=function(r){var D;var A=0;for(D=r.length;A<D;A++){var N=r[A];var K=c.type(N);"array"===K?q(N):"function"===K&&(a.unique&&z.has(N)||b.push(N))}},x=function(r,D){D=D||[];e=!a.memory||[r,D];f=!0;n=h||0;h=0;for(k=b.length;b&&n<k;n++)if(!1===b[n].apply(r,D)&&a.stopOnFalse){e=!0;break}f=!1;b&&(a.once?!0===e?z.disable():b=[]:d&&d.length&&(e=d.shift(),z.fireWith(e[0],e[1])))},z={add:function(){if(b){var r=b.length;q(arguments);f?k=b.length:e&&!0!==e&&(h=r,x(e[0],e[1]))}return this},remove:function(){if(b)for(var r=
arguments,D=0,A=r.length;D<A;D++)for(var N=0;N<b.length&&(r[D]!==b[N]||(f&&N<=k&&(k--,N<=n&&n--),b.splice(N--,1),!a.unique));N++);return this},has:function(r){if(b)for(var D=0,A=b.length;D<A;D++)if(r===b[D])return!0;return!1},empty:function(){b=[];return this},disable:function(){b=d=e=v;return this},disabled:function(){return!b},lock:function(){d=v;e&&!0!==e||z.disable();return this},locked:function(){return!d},fireWith:function(r,D){d&&(f?a.once||d.push([r,D]):a.once&&e||x(r,D));return this},fire:function(){z.fireWith(this,
arguments);return this},fired:function(){return!!e}};return z};var Aa=[].slice;c.extend({Deferred:function(a){var b=c.Callbacks("once memory"),d=c.Callbacks("once memory"),e=c.Callbacks("memory"),f="pending",h={resolve:b,reject:d,notify:e},k={done:b.add,fail:d.add,progress:e.add,state:function(){return f},isResolved:b.fired,isRejected:d.fired,then:function(x,z,r){n.done(x).fail(z).progress(r);return this},always:function(){n.done.apply(n,arguments).fail.apply(n,arguments);return this},pipe:function(x,
z,r){return c.Deferred(function(D){c.each({done:[x,"resolve"],fail:[z,"reject"],progress:[r,"notify"]},function(A,N){var K=N[0],U=N[1],J;if(c.isFunction(K))n[A](function(){if((J=K.apply(this,arguments))&&c.isFunction(J.promise))J.promise().then(D.resolve,D.reject,D.notify);else D[U+"With"](this===n?D:this,[J])});else n[A](D[U])})}).promise()},promise:function(x){if(null==x)x=k;else for(var z in k)x[z]=k[z];return x}},n=k.promise({}),q;for(q in h)n[q]=h[q].fire,n[q+"With"]=h[q].fireWith;n.done(function(){f=
"resolved"},d.disable,e.lock).fail(function(){f="rejected"},b.disable,e.lock);a&&a.call(n,n);return n},when:function(a){function b(z){return function(r){e[z]=1<arguments.length?Aa.call(arguments,0):r;--n||q.resolveWith(q,e)}}function d(z){return function(r){k[z]=1<arguments.length?Aa.call(arguments,0):r;q.notifyWith(x,k)}}var e=Aa.call(arguments,0),f=0,h=e.length,k=Array(h),n=h,q=1>=h&&a&&c.isFunction(a.promise)?a:c.Deferred(),x=q.promise();if(1<h){for(;f<h;f++)e[f]&&e[f].promise&&c.isFunction(e[f].promise)?
e[f].promise().then(b(f),q.reject,d(f)):--n;n||q.resolveWith(q,e)}else q!==a&&q.resolveWith(q,h?[a]:[]);return x}});c.support=function(){var a,b,d=E.createElement("div");d.setAttribute("className","t");d.innerHTML="   <link/><table></table><a href='/a' style='top:1px;float:left;opacity:.55;'>a</a><input type='checkbox'/>";var e=d.getElementsByTagName("*");var f=d.getElementsByTagName("a")[0];if(!e||!e.length||!f)return{};var h=E.createElement("select");var k=h.appendChild(E.createElement("option"));
e=d.getElementsByTagName("input")[0];var n={leadingWhitespace:3===d.firstChild.nodeType,tbody:!d.getElementsByTagName("tbody").length,htmlSerialize:!!d.getElementsByTagName("link").length,style:/top/.test(f.getAttribute("style")),hrefNormalized:"/a"===f.getAttribute("href"),opacity:/^0.55/.test(f.style.opacity),cssFloat:!!f.style.cssFloat,checkOn:"on"===e.value,optSelected:k.selected,getSetAttribute:"t"!==d.className,enctype:!!E.createElement("form").enctype,html5Clone:"<:nav></:nav>"!==E.createElement("nav").cloneNode(!0).outerHTML,
submitBubbles:!0,changeBubbles:!0,focusinBubbles:!1,deleteExpando:!0,noCloneEvent:!0,inlineBlockNeedsLayout:!1,shrinkWrapBlocks:!1,reliableMarginRight:!0};e.checked=!0;n.noCloneChecked=e.cloneNode(!0).checked;h.disabled=!0;n.optDisabled=!k.disabled;try{delete d.test}catch(x){n.deleteExpando=!1}!d.addEventListener&&d.attachEvent&&d.fireEvent&&(d.attachEvent("onclick",function(){n.noCloneEvent=!1}),d.cloneNode(!0).fireEvent("onclick"));e=E.createElement("input");e.value="t";e.setAttribute("type","radio");
n.radioValue="t"===e.value;e.setAttribute("checked","checked");d.appendChild(e);f=E.createDocumentFragment();f.appendChild(d.lastChild);n.checkClone=f.cloneNode(!0).cloneNode(!0).lastChild.checked;n.appendChecked=e.checked;f.removeChild(e);f.appendChild(d);d.innerHTML="";F.getComputedStyle&&(e=E.createElement("div"),e.style.width="0",e.style.marginRight="0",d.style.width="2px",d.appendChild(e),n.reliableMarginRight=0===(parseInt((F.getComputedStyle(e,null)||{marginRight:0}).marginRight,10)||0));if(d.attachEvent)for(b in{submit:1,
change:1,focusin:1}){e="on"+b;var q=e in d;q||(d.setAttribute(e,"return;"),q="function"===typeof d[e]);n[b+"Bubbles"]=q}f.removeChild(d);f=h=k=e=d=e=null;c(function(){var x=E.getElementsByTagName("body")[0];if(x){var z=E.createElement("div");z.style.cssText="visibility:hidden;border:0;width:0;height:0;position:static;top:0;margin-top:1px";x.insertBefore(z,x.firstChild);d=E.createElement("div");z.appendChild(d);d.innerHTML="<table><tr><td style='padding:0;border:0;display:none'></td><td>t</td></tr></table>";
a=d.getElementsByTagName("td");q=0===a[0].offsetHeight;a[0].style.display="";a[1].style.display="none";n.reliableHiddenOffsets=q&&0===a[0].offsetHeight;d.innerHTML="";d.style.width=d.style.paddingLeft="1px";c.boxModel=n.boxModel=2===d.offsetWidth;"undefined"!==typeof d.style.zoom&&(d.style.display="inline",d.style.zoom=1,n.inlineBlockNeedsLayout=2===d.offsetWidth,d.style.display="",d.innerHTML="<div style='width:4px;'></div>",n.shrinkWrapBlocks=2!==d.offsetWidth);d.style.cssText="position:absolute;top:0;left:0;width:1px;height:1px;margin:0;visibility:hidden;border:0;";
d.innerHTML="<div style='position:absolute;top:0;left:0;width:1px;height:1px;margin:0;border:5px solid #000;padding:0;'><div></div></div><table style='position:absolute;top:0;left:0;width:1px;height:1px;margin:0;border:5px solid #000;padding:0;' cellpadding='0' cellspacing='0'><tr><td></td></tr></table>";var r=d.firstChild;var D=r.firstChild;var A={doesNotAddBorder:5!==D.offsetTop,doesAddBorderForTableAndCells:5===r.nextSibling.firstChild.firstChild.offsetTop};D.style.position="fixed";D.style.top=
"20px";A.fixedPosition=20===D.offsetTop||15===D.offsetTop;D.style.position=D.style.top="";r.style.overflow="hidden";r.style.position="relative";A.subtractsBorderForOverflowNotVisible=-5===D.offsetTop;A.doesNotIncludeMarginInBodyOffset=1!==x.offsetTop;x.removeChild(z);d=null;c.extend(n,A)}});return n}();var vb=/^(?:\{.*\}|\[.*\])$/,ub=/([A-Z])/g;c.extend({cache:{},uuid:0,expando:"jQuery"+(c.fn.jquery+Math.random()).replace(/\D/g,""),noData:{embed:!0,object:"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000",
applet:!0},hasData:function(a){a=a.nodeType?c.cache[a[c.expando]]:a[c.expando];return!!a&&!P(a)},data:function(a,b,d,e){if(c.acceptData(a)){var f=c.expando;var h="string"===typeof b,k=a.nodeType,n=k?c.cache:a,q=k?a[f]:a[f]&&f,x="events"===b;if(q&&n[q]&&(x||e||n[q].data)||!h||d!==v){q||(k?a[f]=q=++c.uuid:q=f);n[q]||(n[q]={},k||(n[q].toJSON=c.noop));if("object"===typeof b||"function"===typeof b)e?n[q]=c.extend(n[q],b):n[q].data=c.extend(n[q].data,b);f=a=n[q];e||(a.data||(a.data={}),a=a.data);d!==v&&
(a[c.camelCase(b)]=d);if(x&&!a[b])return f.events;h?(d=a[b],null==d&&(d=a[c.camelCase(b)])):d=a;return d}}},removeData:function(a,b,d){if(c.acceptData(a)){var e,f,h=c.expando,k=a.nodeType,n=k?c.cache:a,q=k?a[h]:h;if(n[q]){if(b&&(e=d?n[q]:n[q].data)){c.isArray(b)||(b in e?b=[b]:(b=c.camelCase(b),b=b in e?[b]:b.split(" ")));var x=0;for(f=b.length;x<f;x++)delete e[b[x]];if(!(d?P:c.isEmptyObject)(e))return}if(!d&&(delete n[q].data,!P(n[q])))return;c.support.deleteExpando||!n.setInterval?delete n[q]:n[q]=
null;k&&(c.support.deleteExpando?delete a[h]:a.removeAttribute?a.removeAttribute(h):a[h]=null)}}},_data:function(a,b,d){return c.data(a,b,d,!0)},acceptData:function(a){if(a.nodeName){var b=c.noData[a.nodeName.toLowerCase()];if(b)return!(!0===b||a.getAttribute("classid")!==b)}return!0}});c.fn.extend({data:function(a,b){var d=null;if("undefined"===typeof a){if(this.length&&(d=c.data(this[0]),1===this[0].nodeType&&!c._data(this[0],"parsedAttrs"))){var e=this[0].attributes;for(var f=0,h=e.length;f<h;f++){var k=
e[f].name;0===k.indexOf("data-")&&(k=c.camelCase(k.substring(5)),R(this[0],k,d[k]))}c._data(this[0],"parsedAttrs",!0)}return d}if("object"===typeof a)return this.each(function(){c.data(this,a)});var n=a.split(".");n[1]=n[1]?"."+n[1]:"";return b===v?(d=this.triggerHandler("getData"+n[1]+"!",[n[0]]),d===v&&this.length&&(d=c.data(this[0],a),d=R(this[0],a,d)),d===v&&n[1]?this.data(n[0]):d):this.each(function(){var q=c(this),x=[n[0],b];q.triggerHandler("setData"+n[1]+"!",x);c.data(this,a,b);q.triggerHandler("changeData"+
n[1]+"!",x)})},removeData:function(a){return this.each(function(){c.removeData(this,a)})}});c.extend({_mark:function(a,b){a&&(b=(b||"fx")+"mark",c._data(a,b,(c._data(a,b)||0)+1))},_unmark:function(a,b,d){!0!==a&&(d=b,b=a,a=!1);if(b){d=d||"fx";var e=d+"mark";(a=a?0:(c._data(b,e)||1)-1)?c._data(b,e,a):(c.removeData(b,e,!0),ba(b,d,"mark"))}},queue:function(a,b,d){if(a){b=(b||"fx")+"queue";var e=c._data(a,b);d&&(!e||c.isArray(d)?e=c._data(a,b,c.makeArray(d)):e.push(d));return e||[]}},dequeue:function(a,
b){b=b||"fx";var d=c.queue(a,b),e=d.shift(),f={};"inprogress"===e&&(e=d.shift());e&&("fx"===b&&d.unshift("inprogress"),c._data(a,b+".run",f),e.call(a,function(){c.dequeue(a,b)},f));d.length||(c.removeData(a,b+"queue "+b+".run",!0),ba(a,b,"queue"))}});c.fn.extend({queue:function(a,b){"string"!==typeof a&&(b=a,a="fx");return b===v?c.queue(this[0],a):this.each(function(){var d=c.queue(this,a,b);"fx"===a&&"inprogress"!==d[0]&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,
a)})},delay:function(a,b){a=c.fx?c.fx.speeds[a]||a:a;return this.queue(b||"fx",function(d,e){var f=setTimeout(d,a);e.stop=function(){clearTimeout(f)}})},clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a,b){function d(){--h||e.resolveWith(f,[f])}"string"!==typeof a&&(a=v);a=a||"fx";var e=c.Deferred(),f=this;b=f.length;var h=1,k=a+"defer",n=a+"queue";a+="mark";for(var q;b--;)if(q=c.data(f[b],k,v,!0)||(c.data(f[b],n,v,!0)||c.data(f[b],a,v,!0))&&c.data(f[b],k,c.Callbacks("once memory"),
!0))h++,q.add(d);d();return e.promise()}});var Ya=/[\n\t\r]/g,ta=/\s+/,Gb=/\r/g,Hb=/^(?:button|input)$/i,Ib=/^(?:button|input|object|select|textarea)$/i,Jb=/^a(?:rea)?$/i,Za=/^(?:autofocus|autoplay|async|checked|controls|defer|disabled|hidden|loop|multiple|open|readonly|required|scoped|selected)$/i,$a=c.support.getSetAttribute;c.fn.extend({attr:function(a,b){return c.access(this,a,b,!0,c.attr)},removeAttr:function(a){return this.each(function(){c.removeAttr(this,a)})},prop:function(a,b){return c.access(this,
a,b,!0,c.prop)},removeProp:function(a){a=c.propFix[a]||a;return this.each(function(){try{this[a]=v,delete this[a]}catch(b){}})},addClass:function(a){var b,d;if(c.isFunction(a))return this.each(function(q){c(this).addClass(a.call(this,q,this.className))});if(a&&"string"===typeof a){var e=a.split(ta);var f=0;for(b=this.length;f<b;f++){var h=this[f];if(1===h.nodeType)if(h.className||1!==e.length){var k=" "+h.className+" ";var n=0;for(d=e.length;n<d;n++)~k.indexOf(" "+e[n]+" ")||(k+=e[n]+" ");h.className=
c.trim(k)}else h.className=a}}return this},removeClass:function(a){var b,d;if(c.isFunction(a))return this.each(function(q){c(this).removeClass(a.call(this,q,this.className))});if(a&&"string"===typeof a||a===v){var e=(a||"").split(ta);var f=0;for(b=this.length;f<b;f++){var h=this[f];if(1===h.nodeType&&h.className)if(a){var k=(" "+h.className+" ").replace(Ya," ");var n=0;for(d=e.length;n<d;n++)k=k.replace(" "+e[n]+" "," ");h.className=c.trim(k)}else h.className=""}}return this},toggleClass:function(a,
b){var d=typeof a,e="boolean"===typeof b;return c.isFunction(a)?this.each(function(f){c(this).toggleClass(a.call(this,f,this.className,b),b)}):this.each(function(){if("string"===d)for(var f,h=0,k=c(this),n=b,q=a.split(ta);f=q[h++];)n=e?n:!k.hasClass(f),k[n?"addClass":"removeClass"](f);else if("undefined"===d||"boolean"===d)this.className&&c._data(this,"__className__",this.className),this.className=this.className||!1===a?"":c._data(this,"__className__")||""})},hasClass:function(a){a=" "+a+" ";for(var b=
0,d=this.length;b<d;b++)if(1===this[b].nodeType&&-1<(" "+this[b].className+" ").replace(Ya," ").indexOf(a))return!0;return!1},val:function(a){var b,d,e=this[0];if(arguments.length){var f=c.isFunction(a);return this.each(function(h){var k=c(this);1===this.nodeType&&(h=f?a.call(this,h,k.val()):a,null==h?h="":"number"===typeof h?h+="":c.isArray(h)&&(h=c.map(h,function(n){return null==n?"":n+""})),b=c.valHooks[this.nodeName.toLowerCase()]||c.valHooks[this.type],b&&"set"in b&&b.set(this,h,"value")!==v||
(this.value=h))})}if(e){if((b=c.valHooks[e.nodeName.toLowerCase()]||c.valHooks[e.type])&&"get"in b&&(d=b.get(e,"value"))!==v)return d;d=e.value;return"string"===typeof d?d.replace(Gb,""):null==d?"":d}}});c.extend({valHooks:{option:{get:function(a){var b=a.attributes.value;return!b||b.specified?a.value:a.text}},select:{get:function(a){var b,d=a.selectedIndex,e=[],f=a.options,h="select-one"===a.type;if(0>d)return null;a=h?d:0;for(b=h?d+1:f.length;a<b;a++){var k=f[a];if(!(!k.selected||(c.support.optDisabled?
k.disabled:null!==k.getAttribute("disabled"))||k.parentNode.disabled&&c.nodeName(k.parentNode,"optgroup"))){k=c(k).val();if(h)return k;e.push(k)}}return h&&!e.length&&f.length?c(f[d]).val():e},set:function(a,b){var d=c.makeArray(b);c(a).find("option").each(function(){this.selected=0<=c.inArray(c(this).val(),d)});d.length||(a.selectedIndex=-1);return d}}},attrFn:{val:!0,css:!0,html:!0,text:!0,data:!0,width:!0,height:!0,offset:!0},attr:function(a,b,d,e){var f,h=a.nodeType;if(a&&3!==h&&8!==h&&2!==h){if(e&&
b in c.attrFn)return c(a)[b](d);if("undefined"===typeof a.getAttribute)return c.prop(a,b,d);if(e=1!==h||!c.isXMLDoc(a)){b=b.toLowerCase();var k=c.attrHooks[b]||(Za.test(b)?Kb:da)}if(d!==v)if(null===d)c.removeAttr(a,b);else{if(k&&"set"in k&&e&&(f=k.set(a,d,b))!==v)return f;a.setAttribute(b,""+d);return d}else{if(k&&"get"in k&&e&&null!==(f=k.get(a,b)))return f;f=a.getAttribute(b);return null===f?v:f}}},removeAttr:function(a,b){var d,e,f=0;if(b&&1===a.nodeType){var h=b.toLowerCase().split(ta);for(e=
h.length;f<e;f++)if(d=h[f])b=c.propFix[d]||d,c.attr(a,d,""),a.removeAttribute($a?d:b),Za.test(d)&&b in a&&(a[b]=!1)}},attrHooks:{type:{set:function(a,b){if(Hb.test(a.nodeName)&&a.parentNode)c.error("type property can't be changed");else if(!c.support.radioValue&&"radio"===b&&c.nodeName(a,"input")){var d=a.value;a.setAttribute("type",b);d&&(a.value=d);return b}}},value:{get:function(a,b){return da&&c.nodeName(a,"button")?da.get(a,b):b in a?a.value:null},set:function(a,b,d){if(da&&c.nodeName(a,"button"))return da.set(a,
b,d);a.value=b}}},propFix:{tabindex:"tabIndex",readonly:"readOnly","for":"htmlFor","class":"className",maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"},prop:function(a,b,d){var e,f=a.nodeType;if(a&&3!==f&&8!==f&&2!==f){if(1!==f||!c.isXMLDoc(a)){b=c.propFix[b]||b;var h=c.propHooks[b]}return d!==v?h&&"set"in h&&(e=h.set(a,d,b))!==v?e:a[b]=d:h&&"get"in h&&null!==(e=
h.get(a,b))?e:a[b]}},propHooks:{tabIndex:{get:function(a){var b=a.getAttributeNode("tabindex");return b&&b.specified?parseInt(b.value,10):Ib.test(a.nodeName)||Jb.test(a.nodeName)&&a.href?0:v}}}});c.attrHooks.tabindex=c.propHooks.tabIndex;var Kb={get:function(a,b){var d,e=c.prop(a,b);return!0===e||"boolean"!==typeof e&&(d=a.getAttributeNode(b))&&!1!==d.nodeValue?b.toLowerCase():v},set:function(a,b,d){!1===b?c.removeAttr(a,d):(b=c.propFix[d]||d,b in a&&(a[b]=!0),a.setAttribute(d,d.toLowerCase()));return d}};
if(!$a){var Lb={name:!0,id:!0};var da=c.valHooks.button={get:function(a,b){return(a=a.getAttributeNode(b))&&(Lb[b]?""!==a.nodeValue:a.specified)?a.nodeValue:v},set:function(a,b,d){var e=a.getAttributeNode(d);e||(e=E.createAttribute(d),a.setAttributeNode(e));return e.nodeValue=b+""}};c.attrHooks.tabindex.set=da.set;c.each(["width","height"],function(a,b){c.attrHooks[b]=c.extend(c.attrHooks[b],{set:function(d,e){if(""===e)return d.setAttribute(b,"auto"),e}})});c.attrHooks.contenteditable={get:da.get,
set:function(a,b,d){""===b&&(b="false");da.set(a,b,d)}}}c.support.hrefNormalized||c.each(["href","src","width","height"],function(a,b){c.attrHooks[b]=c.extend(c.attrHooks[b],{get:function(d){d=d.getAttribute(b,2);return null===d?v:d}})});c.support.style||(c.attrHooks.style={get:function(a){return a.style.cssText.toLowerCase()||v},set:function(a,b){return a.style.cssText=""+b}});c.support.optSelected||(c.propHooks.selected=c.extend(c.propHooks.selected,{get:function(a){if(a=a.parentNode)a.selectedIndex,
a.parentNode&&a.parentNode.selectedIndex;return null}}));c.support.enctype||(c.propFix.enctype="encoding");c.support.checkOn||c.each(["radio","checkbox"],function(){c.valHooks[this]={get:function(a){return null===a.getAttribute("value")?"on":a.value}}});c.each(["radio","checkbox"],function(){c.valHooks[this]=c.extend(c.valHooks[this],{set:function(a,b){if(c.isArray(b))return a.checked=0<=c.inArray(c(a).val(),b)}})});var Ba=/^(?:textarea|input|select)$/i,ab=/^([^\.]*)?(?:\.(.+))?$/,Mb=/\bhover(\.\S+)?\b/,
Nb=/^key/,Ob=/^(?:mouse|contextmenu)|click/,bb=/^(?:focusinfocus|focusoutblur)$/,Pb=/^(\w*)(?:#([\w\-]+))?(?:\.([\w\-]+))?$/,Qb=function(a){if(a=Pb.exec(a))a[1]=(a[1]||"").toLowerCase(),a[3]=a[3]&&new RegExp("(?:^|\\s)"+a[3]+"(?:\\s|$)");return a},cb=function(a){return c.event.special.hover?a:a.replace(Mb,"mouseenter$1 mouseleave$1")};c.event={add:function(a,b,d,e,f){var h;if(3!==a.nodeType&&8!==a.nodeType&&b&&d&&(h=c._data(a))){if(d.handler){var k=d;d=k.handler}d.guid||(d.guid=c.guid++);var n=h.events;
n||(h.events=n={});var q=h.handle;q||(h.handle=q=function(N){return"undefined"===typeof c||N&&c.event.triggered===N.type?v:c.event.dispatch.apply(q.elem,arguments)},q.elem=a);b=c.trim(cb(b)).split(" ");for(h=0;h<b.length;h++){var x=ab.exec(b[h])||[];var z=x[1];var r=(x[2]||"").split(".").sort();var D=c.event.special[z]||{};z=(f?D.delegateType:D.bindType)||z;D=c.event.special[z]||{};x=c.extend({type:z,origType:x[1],data:e,handler:d,guid:d.guid,selector:f,quick:Qb(f),namespace:r.join(".")},k);var A=
n[z];A||(A=n[z]=[],A.delegateCount=0,D.setup&&!1!==D.setup.call(a,e,r,q)||(a.addEventListener?a.addEventListener(z,q,!1):a.attachEvent&&a.attachEvent("on"+z,q)));D.add&&(D.add.call(a,x),x.handler.guid||(x.handler.guid=d.guid));f?A.splice(A.delegateCount++,0,x):A.push(x);c.event.global[z]=!0}a=null}},global:{},remove:function(a,b,d,e,f){var h=c.hasData(a)&&c._data(a),k,n,q,x;if(h&&(x=h.events)){b=c.trim(cb(b||"")).split(" ");for(k=0;k<b.length;k++){var z=ab.exec(b[k])||[];var r=n=z[1];z=z[2];if(r){var D=
c.event.special[r]||{};r=(e?D.delegateType:D.bindType)||r;var A=x[r]||[];var N=A.length;z=z?new RegExp("(^|\\.)"+z.split(".").sort().join("\\.(?:.*\\.)?")+"(\\.|$)"):null;for(q=0;q<A.length;q++){var K=A[q];!f&&n!==K.origType||d&&d.guid!==K.guid||z&&!z.test(K.namespace)||e&&e!==K.selector&&("**"!==e||!K.selector)||(A.splice(q--,1),K.selector&&A.delegateCount--,D.remove&&D.remove.call(a,K))}0===A.length&&N!==A.length&&(D.teardown&&!1!==D.teardown.call(a,z)||c.removeEvent(a,r,h.handle),delete x[r])}else for(r in x)c.event.remove(a,
r+b[k],d,e,!0)}if(c.isEmptyObject(x)){if(b=h.handle)b.elem=null;c.removeData(a,["events","handle"],!0)}}},customEvent:{getData:!0,setData:!0,changeData:!0},trigger:function(a,b,d,e){if(!d||3!==d.nodeType&&8!==d.nodeType){var f=a.type||a,h=[],k;if(!bb.test(f+c.event.triggered)){if(0<=f.indexOf("!")){f=f.slice(0,-1);var n=!0}0<=f.indexOf(".")&&(h=f.split("."),f=h.shift(),h.sort());if(d&&!c.event.customEvent[f]||c.event.global[f])if(a="object"===typeof a?a[c.expando]?a:new c.Event(f,a):new c.Event(f),
a.type=f,a.isTrigger=!0,a.exclusive=n,a.namespace=h.join("."),a.namespace_re=a.namespace?new RegExp("(^|\\.)"+h.join("\\.(?:.*\\.)?")+"(\\.|$)"):null,n=0>f.indexOf(":")?"on"+f:"",d){a.result=v;a.target||(a.target=d);b=null!=b?c.makeArray(b):[];b.unshift(a);var q=c.event.special[f]||{};if(!q.trigger||!1!==q.trigger.apply(d,b)){var x=[[d,q.bindType||f]];if(!e&&!q.noBubble&&!c.isWindow(d)){var z=q.delegateType||f;h=bb.test(z+f)?d:d.parentNode;for(k=null;h;h=h.parentNode)x.push([h,z]),k=h;k&&k===d.ownerDocument&&
x.push([k.defaultView||k.parentWindow||F,z])}for(k=0;k<x.length&&!a.isPropagationStopped();k++)h=x[k][0],a.type=x[k][1],(z=(c._data(h,"events")||{})[a.type]&&c._data(h,"handle"))&&z.apply(h,b),(z=n&&h[n])&&c.acceptData(h)&&!1===z.apply(h,b)&&a.preventDefault();a.type=f;e||a.isDefaultPrevented()||q._default&&!1!==q._default.apply(d.ownerDocument,b)||"click"===f&&c.nodeName(d,"a")||!c.acceptData(d)||!n||!d[f]||("focus"===f||"blur"===f)&&0===a.target.offsetWidth||c.isWindow(d)||((k=d[n])&&(d[n]=null),
c.event.triggered=f,d[f](),c.event.triggered=v,k&&(d[n]=k));return a.result}}else for(k in d=c.cache,d)d[k].events&&d[k].events[f]&&c.event.trigger(a,b,d[k].handle.elem,!0)}}},dispatch:function(a){a=c.event.fix(a||F.event);var b=(c._data(this,"events")||{})[a.type]||[],d=b.delegateCount,e=[].slice.call(arguments,0),f=!a.exclusive&&!a.namespace,h=[],k,n;e[0]=a;a.delegateTarget=this;if(d&&!a.target.disabled&&(!a.button||"click"!==a.type)){var q=c(this);q.context=this.ownerDocument||this;for(n=a.target;n!=
this;n=n.parentNode||this){var x={};var z=[];q[0]=n;for(k=0;k<d;k++){var r=b[k];var D=r.selector;if(x[D]===v){var A=x,N=D;if(r.quick){var K=r.quick;var U=n.attributes||{};K=(!K[1]||n.nodeName.toLowerCase()===K[1])&&(!K[2]||(U.id||{}).value===K[2])&&(!K[3]||K[3].test((U["class"]||{}).value))}else K=q.is(D);A[N]=K}x[D]&&z.push(r)}z.length&&h.push({elem:n,matches:z})}}b.length>d&&h.push({elem:this,matches:b.slice(d)});for(k=0;k<h.length&&!a.isPropagationStopped();k++)for(d=h[k],a.currentTarget=d.elem,
b=0;b<d.matches.length&&!a.isImmediatePropagationStopped();b++)if(r=d.matches[b],f||!a.namespace&&!r.namespace||a.namespace_re&&a.namespace_re.test(r.namespace))a.data=r.data,a.handleObj=r,r=((c.event.special[r.origType]||{}).handle||r.handler).apply(d.elem,e),r!==v&&(a.result=r,!1===r&&(a.preventDefault(),a.stopPropagation()));return a.result},props:"attrChange attrName relatedNode srcElement altKey bubbles cancelable ctrlKey currentTarget eventPhase metaKey relatedTarget shiftKey target timeStamp view which".split(" "),
fixHooks:{},keyHooks:{props:["char","charCode","key","keyCode"],filter:function(a,b){null==a.which&&(a.which=null!=b.charCode?b.charCode:b.keyCode);return a}},mouseHooks:{props:"button buttons clientX clientY fromElement offsetX offsetY pageX pageY screenX screenY toElement".split(" "),filter:function(a,b){var d=b.button,e=b.fromElement;if(null==a.pageX&&null!=b.clientX){var f=a.target.ownerDocument||E;var h=f.documentElement;f=f.body;a.pageX=b.clientX+(h&&h.scrollLeft||f&&f.scrollLeft||0)-(h&&h.clientLeft||
f&&f.clientLeft||0);a.pageY=b.clientY+(h&&h.scrollTop||f&&f.scrollTop||0)-(h&&h.clientTop||f&&f.clientTop||0)}!a.relatedTarget&&e&&(a.relatedTarget=e===a.target?b.toElement:e);a.which||d===v||(a.which=d&1?1:d&2?3:d&4?2:0);return a}},fix:function(a){if(a[c.expando])return a;var b,d=a,e=c.event.fixHooks[a.type]||{},f=e.props?this.props.concat(e.props):this.props;a=c.Event(d);for(b=f.length;b;){var h=f[--b];a[h]=d[h]}a.target||(a.target=d.srcElement||E);3===a.target.nodeType&&(a.target=a.target.parentNode);
a.metaKey===v&&(a.metaKey=a.ctrlKey);return e.filter?e.filter(a,d):a},special:{ready:{setup:c.bindReady},load:{noBubble:!0},focus:{delegateType:"focusin"},blur:{delegateType:"focusout"},beforeunload:{setup:function(a,b,d){c.isWindow(this)&&(this.onbeforeunload=d)},teardown:function(a,b){this.onbeforeunload===b&&(this.onbeforeunload=null)}}},simulate:function(a,b,d,e){a=c.extend(new c.Event,d,{type:a,isSimulated:!0,originalEvent:{}});e?c.event.trigger(a,null,b):c.event.dispatch.call(b,a);a.isDefaultPrevented()&&
d.preventDefault()}};c.event.handle=c.event.dispatch;c.removeEvent=E.removeEventListener?function(a,b,d){a.removeEventListener&&a.removeEventListener(b,d,!1)}:function(a,b,d){a.detachEvent&&a.detachEvent("on"+b,d)};c.Event=function(a,b){if(!(this instanceof c.Event))return new c.Event(a,b);a&&a.type?(this.originalEvent=a,this.type=a.type,this.isDefaultPrevented=a.defaultPrevented||!1===a.returnValue||a.getPreventDefault&&a.getPreventDefault()?pa:ca):this.type=a;b&&c.extend(this,b);this.timeStamp=
a&&a.timeStamp||c.now();this[c.expando]=!0};c.Event.prototype={preventDefault:function(){this.isDefaultPrevented=pa;var a=this.originalEvent;a&&(a.preventDefault?a.preventDefault():a.returnValue=!1)},stopPropagation:function(){this.isPropagationStopped=pa;var a=this.originalEvent;a&&(a.stopPropagation&&a.stopPropagation(),a.cancelBubble=!0)},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=pa;this.stopPropagation()},isDefaultPrevented:ca,isPropagationStopped:ca,isImmediatePropagationStopped:ca};
c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={delegateType:b,bindType:b,handle:function(d){var e=d.relatedTarget,f=d.handleObj;if(!e||e!==this&&!c.contains(this,e)){d.type=f.origType;var h=f.handler.apply(this,arguments);d.type=b}return h}}});c.support.submitBubbles||(c.event.special.submit={setup:function(){if(c.nodeName(this,"form"))return!1;c.event.add(this,"click._submit keypress._submit",function(a){a=a.target;(a=c.nodeName(a,"input")||c.nodeName(a,"button")?
a.form:v)&&!a._submit_attached&&(c.event.add(a,"submit._submit",function(b){this.parentNode&&!b.isTrigger&&c.event.simulate("submit",this.parentNode,b,!0)}),a._submit_attached=!0)})},teardown:function(){if(c.nodeName(this,"form"))return!1;c.event.remove(this,"._submit")}});c.support.changeBubbles||(c.event.special.change={setup:function(){if(Ba.test(this.nodeName)){if("checkbox"===this.type||"radio"===this.type)c.event.add(this,"propertychange._change",function(a){"checked"===a.originalEvent.propertyName&&
(this._just_changed=!0)}),c.event.add(this,"click._change",function(a){this._just_changed&&!a.isTrigger&&(this._just_changed=!1,c.event.simulate("change",this,a,!0))});return!1}c.event.add(this,"beforeactivate._change",function(a){a=a.target;Ba.test(a.nodeName)&&!a._change_attached&&(c.event.add(a,"change._change",function(b){!this.parentNode||b.isSimulated||b.isTrigger||c.event.simulate("change",this.parentNode,b,!0)}),a._change_attached=!0)})},handle:function(a){var b=a.target;if(this!==b||a.isSimulated||
a.isTrigger||"radio"!==b.type&&"checkbox"!==b.type)return a.handleObj.handler.apply(this,arguments)},teardown:function(){c.event.remove(this,"._change");return Ba.test(this.nodeName)}});c.support.focusinBubbles||c.each({focus:"focusin",blur:"focusout"},function(a,b){var d=0,e=function(f){c.event.simulate(b,f.target,c.event.fix(f),!0)};c.event.special[b]={setup:function(){0===d++&&E.addEventListener(a,e,!0)},teardown:function(){0===--d&&E.removeEventListener(a,e,!0)}}});c.fn.extend({on:function(a,
b,d,e,f){var h;if("object"===typeof a){"string"!==typeof b&&(d=b,b=v);for(h in a)this.on(h,b,d,a[h],f);return this}null==d&&null==e?(e=b,d=b=v):null==e&&("string"===typeof b?(e=d,d=v):(e=d,d=b,b=v));if(!1===e)e=ca;else if(!e)return this;if(1===f){var k=e;e=function(n){c().off(n);return k.apply(this,arguments)};e.guid=k.guid||(k.guid=c.guid++)}return this.each(function(){c.event.add(this,a,e,d,b)})},one:function(a,b,d,e){return this.on.call(this,a,b,d,e,1)},off:function(a,b,d){if(a&&a.preventDefault&&
a.handleObj){var e=a.handleObj;c(a.delegateTarget).off(e.namespace?e.type+"."+e.namespace:e.type,e.selector,e.handler);return this}if("object"===typeof a){for(e in a)this.off(e,b,a[e]);return this}if(!1===b||"function"===typeof b)d=b,b=v;!1===d&&(d=ca);return this.each(function(){c.event.remove(this,a,d,b)})},bind:function(a,b,d){return this.on(a,null,b,d)},unbind:function(a,b){return this.off(a,null,b)},live:function(a,b,d){c(this.context).on(a,this.selector,b,d);return this},die:function(a,b){c(this.context).off(a,
this.selector||"**",b);return this},delegate:function(a,b,d,e){return this.on(b,a,d,e)},undelegate:function(a,b,d){return 1==arguments.length?this.off(a,"**"):this.off(b,a,d)},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){if(this[0])return c.event.trigger(a,b,this[0],!0)},toggle:function(a){var b=arguments,d=a.guid||c.guid++,e=0,f=function(h){var k=(c._data(this,"lastToggle"+a.guid)||0)%e;c._data(this,"lastToggle"+a.guid,k+1);h.preventDefault();
return b[k].apply(this,arguments)||!1};for(f.guid=d;e<b.length;)b[e++].guid=d;return this.click(f)},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error contextmenu".split(" "),function(a,b){c.fn[b]=function(d,e){null==e&&(e=d,d=null);return 0<arguments.length?this.on(b,null,d,e):this.trigger(b)};
c.attrFn&&(c.attrFn[b]=!0);Nb.test(b)&&(c.event.fixHooks[b]=c.event.keyHooks);Ob.test(b)&&(c.event.fixHooks[b]=c.event.mouseHooks)});(function(){function a(g,l,p,t,u,y){u=0;for(var G=t.length;u<G;u++){var H=t[u];if(H){var L=!1;for(H=H[g];H;){if(H[e]===p){L=t[H.sizset];break}1!==H.nodeType||y||(H[e]=p,H.sizset=u);if(H.nodeName.toLowerCase()===l){L=H;break}H=H[g]}t[u]=L}}}function b(g,l,p,t,u,y){u=0;for(var G=t.length;u<G;u++){var H=t[u];if(H){var L=!1;for(H=H[g];H;){if(H[e]===p){L=t[H.sizset];break}if(1===
H.nodeType)if(y||(H[e]=p,H.sizset=u),"string"!==typeof l){if(H===l){L=!0;break}}else if(0<r.filter(l,[H]).length){L=H;break}H=H[g]}t[u]=L}}}var d=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|['"][^'"]*['"]|[^\[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,e="sizcache"+(Math.random()+"").replace(".",""),f=0,h=Object.prototype.toString,k=!1,n=!0,q=/\\/g,x=/\r\n/g,z=/\W/;[0,0].sort(function(){n=!1;return 0});var r=function(g,l,p,t){p=p||[];var u=l=l||E;if(1!==l.nodeType&&9!==
l.nodeType)return[];if(!g||"string"!==typeof g)return p;var y,G,H,L=!0,O=r.isXML(l),m=[],w=g;do if(d.exec(""),y=d.exec(w))if(w=y[3],m.push(y[1]),y[2]){var C=y[3];break}while(y);if(1<m.length&&N.exec(g))if(2===m.length&&A.relative[m[0]])var B=Y(m[0]+m[1],l,t);else for(B=A.relative[m[0]]?[l]:r(m.shift(),l);m.length;)g=m.shift(),A.relative[g]&&(g+=m.shift()),B=Y(g,B,t);else if(!t&&1<m.length&&9===l.nodeType&&!O&&A.match.ID.test(m[0])&&!A.match.ID.test(m[m.length-1])&&(y=r.find(m.shift(),l,O),l=y.expr?
r.filter(y.expr,y.set)[0]:y.set[0]),l)for(y=t?{expr:m.pop(),set:J(t)}:r.find(m.pop(),1!==m.length||"~"!==m[0]&&"+"!==m[0]||!l.parentNode?l:l.parentNode,O),B=y.expr?r.filter(y.expr,y.set):y.set,0<m.length?G=J(B):L=!1;m.length;)y=H=m.pop(),A.relative[H]?y=m.pop():H="",null==y&&(y=l),A.relative[H](G,y,O);else G=[];G||(G=B);G||r.error(H||g);if("[object Array]"===h.call(G))if(L)if(l&&1===l.nodeType)for(g=0;null!=G[g];g++)G[g]&&(!0===G[g]||1===G[g].nodeType&&r.contains(l,G[g]))&&p.push(B[g]);else for(g=
0;null!=G[g];g++)G[g]&&1===G[g].nodeType&&p.push(B[g]);else p.push.apply(p,G);else J(G,p);C&&(r(C,u,p,t),r.uniqueSort(p));return p};r.uniqueSort=function(g){if(aa&&(k=n,g.sort(aa),k))for(var l=1;l<g.length;l++)g[l]===g[l-1]&&g.splice(l--,1);return g};r.matches=function(g,l){return r(g,null,null,l)};r.matchesSelector=function(g,l){return 0<r(l,null,null,[g]).length};r.find=function(g,l,p){var t,u;if(!g)return[];var y=0;for(t=A.order.length;y<t;y++){var G=A.order[y];if(u=A.leftMatch[G].exec(g)){var H=
u[1];u.splice(1,1);if("\\"!==H.substr(H.length-1)){u[1]=(u[1]||"").replace(q,"");var L=A.find[G](u,l,p);if(null!=L){g=g.replace(A.match[G],"");break}}}}L||(L="undefined"!==typeof l.getElementsByTagName?l.getElementsByTagName("*"):[]);return{set:L,expr:g}};r.filter=function(g,l,p,t){for(var u,y,G,H,L,O,m,w,C=g,B=[],I=l,S=l&&l[0]&&r.isXML(l[0]);g&&l.length;){for(G in A.filter)if(null!=(u=A.leftMatch[G].exec(g))&&u[2]&&(O=A.filter[G],L=u[1],y=!1,u.splice(1,1),"\\"!==L.substr(L.length-1))){I===B&&(B=
[]);if(A.preFilter[G])if(u=A.preFilter[G](u,I,p,B,t,S),!u)y=H=!0;else if(!0===u)continue;if(u)for(m=0;null!=(L=I[m]);m++)L&&(H=O(L,u,m,I),w=t^H,p&&null!=H?w?y=!0:I[m]=!1:w&&(B.push(L),y=!0));if(H!==v){p||(I=B);g=g.replace(A.match[G],"");if(!y)return[];break}}if(g===C)if(null==y)r.error(g);else break;C=g}return I};r.error=function(g){throw Error("Syntax error, unrecognized expression: "+g);};var D=r.getText=function(g){var l;var p=g.nodeType;var t="";if(p)if(1===p||9===p){if("string"===typeof g.textContent)return g.textContent;
if("string"===typeof g.innerText)return g.innerText.replace(x,"");for(g=g.firstChild;g;g=g.nextSibling)t+=D(g)}else{if(3===p||4===p)return g.nodeValue}else for(p=0;l=g[p];p++)8!==l.nodeType&&(t+=D(l));return t},A=r.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF\-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF\-]|\\.)+)\s*(?:(\S?=)\s*(?:(['"])(.*?)\3|(#?(?:[\w\u00c0-\uFFFF\-]|\\.)*)|)|)\s*\]/,
TAG:/^((?:[\w\u00c0-\uFFFF\*\-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child(?:\(\s*(even|odd|(?:[+\-]?\d+|(?:[+\-]?\d*)?n\s*(?:[+\-]\s*\d+)?))\s*\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^\-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF\-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(g){return g.getAttribute("href")},type:function(g){return g.getAttribute("type")}},relative:{"+":function(g,l){var p=
"string"===typeof l,t=p&&!z.test(l);p=p&&!t;t&&(l=l.toLowerCase());t=0;for(var u=g.length,y;t<u;t++)if(y=g[t]){for(;(y=y.previousSibling)&&1!==y.nodeType;);g[t]=p||y&&y.nodeName.toLowerCase()===l?y||!1:y===l}p&&r.filter(l,g,!0)},">":function(g,l){var p,t="string"===typeof l,u=0,y=g.length;if(t&&!z.test(l))for(l=l.toLowerCase();u<y;u++){if(p=g[u])p=p.parentNode,g[u]=p.nodeName.toLowerCase()===l?p:!1}else{for(;u<y;u++)(p=g[u])&&(g[u]=t?p.parentNode:p.parentNode===l);t&&r.filter(l,g,!0)}},"":function(g,
l,p){var t=f++,u=b;if("string"===typeof l&&!z.test(l)){var y=l=l.toLowerCase();u=a}u("parentNode",l,t,g,y,p)},"~":function(g,l,p){var t=f++,u=b;if("string"===typeof l&&!z.test(l)){var y=l=l.toLowerCase();u=a}u("previousSibling",l,t,g,y,p)}},find:{ID:function(g,l,p){if("undefined"!==typeof l.getElementById&&!p)return(g=l.getElementById(g[1]))&&g.parentNode?[g]:[]},NAME:function(g,l){if("undefined"!==typeof l.getElementsByName){var p=[];l=l.getElementsByName(g[1]);for(var t=0,u=l.length;t<u;t++)l[t].getAttribute("name")===
g[1]&&p.push(l[t]);return 0===p.length?null:p}},TAG:function(g,l){if("undefined"!==typeof l.getElementsByTagName)return l.getElementsByTagName(g[1])}},preFilter:{CLASS:function(g,l,p,t,u,y){g=" "+g[1].replace(q,"")+" ";if(y)return g;y=0;for(var G;null!=(G=l[y]);y++)G&&(u^(G.className&&0<=(" "+G.className+" ").replace(/[\t\n\r]/g," ").indexOf(g))?p||t.push(G):p&&(l[y]=!1));return!1},ID:function(g){return g[1].replace(q,"")},TAG:function(g,l){return g[1].replace(q,"").toLowerCase()},CHILD:function(g){if("nth"===
g[1]){g[2]||r.error(g[0]);g[2]=g[2].replace(/^\+|\s*/g,"");var l=/(-?)(\d*)(?:n([+\-]?\d*))?/.exec("even"===g[2]&&"2n"||"odd"===g[2]&&"2n+1"||!/\D/.test(g[2])&&"0n+"+g[2]||g[2]);g[2]=l[1]+(l[2]||1)-0;g[3]=l[3]-0}else g[2]&&r.error(g[0]);g[0]=f++;return g},ATTR:function(g,l,p,t,u,y){l=g[1]=g[1].replace(q,"");!y&&A.attrMap[l]&&(g[1]=A.attrMap[l]);g[4]=(g[4]||g[5]||"").replace(q,"");"~="===g[2]&&(g[4]=" "+g[4]+" ");return g},PSEUDO:function(g,l,p,t,u){if("not"===g[1])if(1<(d.exec(g[3])||"").length||
/^\w/.test(g[3]))g[3]=r(g[3],null,null,l);else return g=r.filter(g[3],l,p,1^u),p||t.push.apply(t,g),!1;else if(A.match.POS.test(g[0])||A.match.CHILD.test(g[0]))return!0;return g},POS:function(g){g.unshift(!0);return g}},filters:{enabled:function(g){return!1===g.disabled&&"hidden"!==g.type},disabled:function(g){return!0===g.disabled},checked:function(g){return!0===g.checked},selected:function(g){g.parentNode&&g.parentNode.selectedIndex;return!0===g.selected},parent:function(g){return!!g.firstChild},
empty:function(g){return!g.firstChild},has:function(g,l,p){return!!r(p[3],g).length},header:function(g){return/h\d/i.test(g.nodeName)},text:function(g){var l=g.getAttribute("type"),p=g.type;return"input"===g.nodeName.toLowerCase()&&"text"===p&&(l===p||null===l)},radio:function(g){return"input"===g.nodeName.toLowerCase()&&"radio"===g.type},checkbox:function(g){return"input"===g.nodeName.toLowerCase()&&"checkbox"===g.type},file:function(g){return"input"===g.nodeName.toLowerCase()&&"file"===g.type},
password:function(g){return"input"===g.nodeName.toLowerCase()&&"password"===g.type},submit:function(g){var l=g.nodeName.toLowerCase();return("input"===l||"button"===l)&&"submit"===g.type},image:function(g){return"input"===g.nodeName.toLowerCase()&&"image"===g.type},reset:function(g){var l=g.nodeName.toLowerCase();return("input"===l||"button"===l)&&"reset"===g.type},button:function(g){var l=g.nodeName.toLowerCase();return"input"===l&&"button"===g.type||"button"===l},input:function(g){return/input|select|textarea|button/i.test(g.nodeName)},
focus:function(g){return g===g.ownerDocument.activeElement}},setFilters:{first:function(g,l){return 0===l},last:function(g,l,p,t){return l===t.length-1},even:function(g,l){return 0===l%2},odd:function(g,l){return 1===l%2},lt:function(g,l,p){return l<p[3]-0},gt:function(g,l,p){return l>p[3]-0},nth:function(g,l,p){return p[3]-0===l},eq:function(g,l,p){return p[3]-0===l}},filter:{PSEUDO:function(g,l,p,t){var u=l[1],y=A.filters[u];if(y)return y(g,p,l,t);if("contains"===u)return 0<=(g.textContent||g.innerText||
D([g])||"").indexOf(l[3]);if("not"===u){l=l[3];p=0;for(t=l.length;p<t;p++)if(l[p]===g)return!1;return!0}r.error(u)},CHILD:function(g,l){var p;var t=l[1];var u=g;switch(t){case "only":case "first":for(;u=u.previousSibling;)if(1===u.nodeType)return!1;if("first"===t)return!0;u=g;case "last":for(;u=u.nextSibling;)if(1===u.nodeType)return!1;return!0;case "nth":t=l[2];var y=l[3];if(1===t&&0===y)return!0;l=l[0];if((p=g.parentNode)&&(p[e]!==l||!g.nodeIndex)){var G=0;for(u=p.firstChild;u;u=u.nextSibling)1===
u.nodeType&&(u.nodeIndex=++G);p[e]=l}g=g.nodeIndex-y;return 0===t?0===g:0===g%t&&0<=g/t}},ID:function(g,l){return 1===g.nodeType&&g.getAttribute("id")===l},TAG:function(g,l){return"*"===l&&1===g.nodeType||!!g.nodeName&&g.nodeName.toLowerCase()===l},CLASS:function(g,l){return-1<(" "+(g.className||g.getAttribute("class"))+" ").indexOf(l)},ATTR:function(g,l){var p=l[1];g=r.attr?r.attr(g,p):A.attrHandle[p]?A.attrHandle[p](g):null!=g[p]?g[p]:g.getAttribute(p);p=g+"";var t=l[2];l=l[4];return null==g?"!="===
t:!t&&r.attr?null!=g:"="===t?p===l:"*="===t?0<=p.indexOf(l):"~="===t?0<=(" "+p+" ").indexOf(l):l?"!="===t?p!==l:"^="===t?0===p.indexOf(l):"$="===t?p.substr(p.length-l.length)===l:"|="===t?p===l||p.substr(0,l.length+1)===l+"-":!1:p&&!1!==g},POS:function(g,l,p,t){var u=A.setFilters[l[2]];if(u)return u(g,p,l,t)}}},N=A.match.POS,K=function(g,l){return"\\"+(l-0+1)},U;for(U in A.match)A.match[U]=new RegExp(A.match[U].source+/(?![^\[]*\])(?![^\(]*\))/.source),A.leftMatch[U]=new RegExp(/(^(?:.|\r|\n)*?)/.source+
A.match[U].source.replace(/\\(\d+)/g,K));var J=function(g,l){g=Array.prototype.slice.call(g,0);return l?(l.push.apply(l,g),l):g};try{Array.prototype.slice.call(E.documentElement.childNodes,0)[0].nodeType}catch(g){J=function(l,p){var t=0;p=p||[];if("[object Array]"===h.call(l))Array.prototype.push.apply(p,l);else if("number"===typeof l.length)for(var u=l.length;t<u;t++)p.push(l[t]);else for(;l[t];t++)p.push(l[t]);return p}}if(E.documentElement.compareDocumentPosition)var aa=function(g,l){return g===
l?(k=!0,0):g.compareDocumentPosition&&l.compareDocumentPosition?g.compareDocumentPosition(l)&4?-1:1:g.compareDocumentPosition?-1:1};else{aa=function(g,l){if(g===l)return k=!0,0;if(g.sourceIndex&&l.sourceIndex)return g.sourceIndex-l.sourceIndex;var p=[],t=[];var u=g.parentNode;var y=l.parentNode;var G=u;if(u===y)return W(g,l);if(!u)return-1;if(!y)return 1;for(;G;)p.unshift(G),G=G.parentNode;for(G=y;G;)t.unshift(G),G=G.parentNode;u=p.length;y=t.length;for(G=0;G<u&&G<y;G++)if(p[G]!==t[G])return W(p[G],
t[G]);return G===u?W(g,t[G],-1):W(p[G],l,1)};var W=function(g,l,p){if(g===l)return p;for(g=g.nextSibling;g;){if(g===l)return-1;g=g.nextSibling}return 1}}(function(){var g=E.createElement("div"),l="script"+(new Date).getTime(),p=E.documentElement;g.innerHTML="<a name='"+l+"'/>";p.insertBefore(g,p.firstChild);E.getElementById(l)&&(A.find.ID=function(t,u,y){if("undefined"!==typeof u.getElementById&&!y)return(u=u.getElementById(t[1]))?u.id===t[1]||"undefined"!==typeof u.getAttributeNode&&u.getAttributeNode("id").nodeValue===
t[1]?[u]:v:[]},A.filter.ID=function(t,u){var y="undefined"!==typeof t.getAttributeNode&&t.getAttributeNode("id");return 1===t.nodeType&&y&&y.nodeValue===u});p.removeChild(g);p=g=null})();(function(){var g=E.createElement("div");g.appendChild(E.createComment(""));0<g.getElementsByTagName("*").length&&(A.find.TAG=function(l,p){p=p.getElementsByTagName(l[1]);if("*"===l[1]){l=[];for(var t=0;p[t];t++)1===p[t].nodeType&&l.push(p[t]);p=l}return p});g.innerHTML="<a href='#'></a>";g.firstChild&&"undefined"!==
typeof g.firstChild.getAttribute&&"#"!==g.firstChild.getAttribute("href")&&(A.attrHandle.href=function(l){return l.getAttribute("href",2)});g=null})();E.querySelectorAll&&function(){var g=r,l=E.createElement("div");l.innerHTML="<p class='TEST'></p>";if(!l.querySelectorAll||0!==l.querySelectorAll(".TEST").length){r=function(t,u,y,G){u=u||E;if(!G&&!r.isXML(u)){var H=/^(\w+$)|^\.([\w\-]+$)|^#([\w\-]+$)/.exec(t);if(H&&(1===u.nodeType||9===u.nodeType)){if(H[1])return J(u.getElementsByTagName(t),y);if(H[2]&&
A.find.CLASS&&u.getElementsByClassName)return J(u.getElementsByClassName(H[2]),y)}if(9===u.nodeType){if("body"===t&&u.body)return J([u.body],y);if(H&&H[3]){var L=u.getElementById(H[3]);if(L&&L.parentNode){if(L.id===H[3])return J([L],y)}else return J([],y)}try{return J(u.querySelectorAll(t),y)}catch(C){}}else if(1===u.nodeType&&"object"!==u.nodeName.toLowerCase()){H=u;var O=(L=u.getAttribute("id"))||"__sizzle__",m=u.parentNode,w=/^\s*[+~]/.test(t);L?O=O.replace(/'/g,"\\$&"):u.setAttribute("id",O);
w&&m&&(u=u.parentNode);try{if(!w||m)return J(u.querySelectorAll("[id='"+O+"'] "+t),y)}catch(C){}finally{L||H.removeAttribute("id")}}}return g(t,u,y,G)};for(var p in g)r[p]=g[p];l=null}}();(function(){var g=E.documentElement,l=g.matchesSelector||g.mozMatchesSelector||g.webkitMatchesSelector||g.msMatchesSelector;if(l){var p=!l.call(E.createElement("div"),"div"),t=!1;try{l.call(E.documentElement,"[test!='']:sizzle")}catch(u){t=!0}r.matchesSelector=function(u,y){y=y.replace(/=\s*([^'"\]]*)\s*\]/g,"='$1']");
if(!r.isXML(u))try{if(t||!A.match.PSEUDO.test(y)&&!/!=/.test(y)){var G=l.call(u,y);if(G||!p||u.document&&11!==u.document.nodeType)return G}}catch(H){}return 0<r(y,null,null,[u]).length}}})();(function(){var g=E.createElement("div");g.innerHTML="<div class='test e'></div><div class='test'></div>";g.getElementsByClassName&&0!==g.getElementsByClassName("e").length&&(g.lastChild.className="e",1!==g.getElementsByClassName("e").length&&(A.order.splice(1,0,"CLASS"),A.find.CLASS=function(l,p,t){if("undefined"!==
typeof p.getElementsByClassName&&!t)return p.getElementsByClassName(l[1])},g=null))})();r.contains=E.documentElement.contains?function(g,l){return g!==l&&(g.contains?g.contains(l):!0)}:E.documentElement.compareDocumentPosition?function(g,l){return!!(g.compareDocumentPosition(l)&16)}:function(){return!1};r.isXML=function(g){return(g=(g?g.ownerDocument||g:0).documentElement)?"HTML"!==g.nodeName:!1};var Y=function(g,l,p){var t,u=[],y="";for(l=l.nodeType?[l]:l;t=A.match.PSEUDO.exec(g);)y+=t[0],g=g.replace(A.match.PSEUDO,
"");g=A.relative[g]?g+"*":g;t=0;for(var G=l.length;t<G;t++)r(g,l[t],u,p);return r.filter(y,u)};r.attr=c.attr;r.selectors.attrMap={};c.find=r;c.expr=r.selectors;c.expr[":"]=c.expr.filters;c.unique=r.uniqueSort;c.text=r.getText;c.isXMLDoc=r.isXML;c.contains=r.contains})();var Rb=/Until$/,Sb=/^(?:parents|prevUntil|prevAll)/,Tb=/,/,wb=/^.[^:#\[\.,]*$/,Ub=Array.prototype.slice,db=c.expr.match.POS,Vb={children:!0,contents:!0,next:!0,prev:!0};c.fn.extend({find:function(a){var b=this,d;if("string"!==typeof a)return c(a).filter(function(){k=
0;for(d=b.length;k<d;k++)if(c.contains(b[k],this))return!0});var e=this.pushStack("","find",a),f,h;var k=0;for(d=this.length;k<d;k++){var n=e.length;c.find(a,this[k],e);if(0<k)for(f=n;f<e.length;f++)for(h=0;h<n;h++)if(e[h]===e[f]){e.splice(f--,1);break}}return e},has:function(a){var b=c(a);return this.filter(function(){for(var d=0,e=b.length;d<e;d++)if(c.contains(this,b[d]))return!0})},not:function(a){return this.pushStack(Ja(this,a,!1),"not",a)},filter:function(a){return this.pushStack(Ja(this,a,
!0),"filter",a)},is:function(a){return!!a&&("string"===typeof a?db.test(a)?0<=c(a,this.context).index(this[0]):0<c.filter(a,this).length:0<this.filter(a).length)},closest:function(a,b){var d=[],e,f,h=this[0];if(c.isArray(a)){for(f=1;h&&h.ownerDocument&&h!==b;){for(e=0;e<a.length;e++)c(h).is(a[e])&&d.push({selector:a[e],elem:h,level:f});h=h.parentNode;f++}return d}var k=db.test(a)||"string"!==typeof a?c(a,b||this.context):0;e=0;for(f=this.length;e<f;e++)for(h=this[e];h;)if(k?-1<k.index(h):c.find.matchesSelector(h,
a)){d.push(h);break}else if(h=h.parentNode,!h||!h.ownerDocument||h===b||11===h.nodeType)break;d=1<d.length?c.unique(d):d;return this.pushStack(d,"closest",a)},index:function(a){return a?"string"===typeof a?c.inArray(this[0],c(a)):c.inArray(a.jquery?a[0]:a,this):this[0]&&this[0].parentNode?this.prevAll().length:-1},add:function(a,b){a="string"===typeof a?c(a,b):c.makeArray(a&&a.nodeType?[a]:a);b=c.merge(this.get(),a);return this.pushStack(Ia(a[0])||Ia(b[0])?b:c.unique(b))},andSelf:function(){return this.add(this.prevObject)}});
c.each({parent:function(a){return(a=a.parentNode)&&11!==a.nodeType?a:null},parents:function(a){return c.dir(a,"parentNode")},parentsUntil:function(a,b,d){return c.dir(a,"parentNode",d)},next:function(a){return c.nth(a,2,"nextSibling")},prev:function(a){return c.nth(a,2,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",
d)},siblings:function(a){return c.sibling(a.parentNode.firstChild,a)},children:function(a){return c.sibling(a.firstChild)},contents:function(a){return c.nodeName(a,"iframe")?a.contentDocument||a.contentWindow.document:c.makeArray(a.childNodes)}},function(a,b){c.fn[a]=function(d,e){var f=c.map(this,b,d);Rb.test(a)||(e=d);e&&"string"===typeof e&&(f=c.filter(e,f));f=1<this.length&&!Vb[a]?c.unique(f):f;(1<this.length||Tb.test(e))&&Sb.test(a)&&(f=f.reverse());return this.pushStack(f,a,Ub.call(arguments).join(","))}});
c.extend({filter:function(a,b,d){d&&(a=":not("+a+")");return 1===b.length?c.find.matchesSelector(b[0],a)?[b[0]]:[]:c.find.matches(a,b)},dir:function(a,b,d){var e=[];for(a=a[b];a&&9!==a.nodeType&&(d===v||1!==a.nodeType||!c(a).is(d));)1===a.nodeType&&e.push(a),a=a[b];return e},nth:function(a,b,d,e){b=b||1;for(e=0;a&&(1!==a.nodeType||++e!==b);a=a[d]);return a},sibling:function(a,b){for(var d=[];a;a=a.nextSibling)1===a.nodeType&&a!==b&&d.push(a);return d}});var La="abbr|article|aside|audio|canvas|datalist|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video",
Wb=/ jQuery\d+="(?:\d+|null)"/g,Ca=/^\s+/,eb=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,fb=/<([\w:]+)/,Xb=/<tbody/i,Yb=/<|&#?\w+;/,Zb=/<(?:script|style)/i,$b=/<(?:script|object|embed|option|style)/i,gb=new RegExp("<(?:"+La+")","i"),hb=/checked\s*(?:[^=]|=\s*.checked.)/i,ac=/\/(java|ecma)script/i,zb=/^\s*<!(?:\[CDATA\[|\-\-)/,X={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>",
"</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],area:[1,"<map>","</map>"],_default:[0,"",""]},ib=Ka(E);X.optgroup=X.option;X.tbody=X.tfoot=X.colgroup=X.caption=X.thead;X.th=X.td;c.support.htmlSerialize||(X._default=[1,"div<div>","</div>"]);c.fn.extend({text:function(a){return c.isFunction(a)?this.each(function(b){var d=c(this);d.text(a.call(this,b,d.text()))}):"object"!==typeof a&&a!==v?this.empty().append((this[0]&&
this[0].ownerDocument||E).createTextNode(a)):c.text(this)},wrapAll:function(a){if(c.isFunction(a))return this.each(function(d){c(this).wrapAll(a.call(this,d))});if(this[0]){var b=c(a,this[0].ownerDocument).eq(0).clone(!0);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var d=this;d.firstChild&&1===d.firstChild.nodeType;)d=d.firstChild;return d}).append(this)}return this},wrapInner:function(a){return c.isFunction(a)?this.each(function(b){c(this).wrapInner(a.call(this,b))}):this.each(function(){var b=
c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){var b=c.isFunction(a);return this.each(function(d){c(this).wrapAll(b?a.call(this,d):a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,!0,function(a){1===this.nodeType&&this.appendChild(a)})},prepend:function(){return this.domManip(arguments,!0,function(a){1===this.nodeType&&this.insertBefore(a,
this.firstChild)})},before:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,!1,function(b){this.parentNode.insertBefore(b,this)});if(arguments.length){var a=c.clean(arguments);a.push.apply(a,this.toArray());return this.pushStack(a,"before",arguments)}},after:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,!1,function(b){this.parentNode.insertBefore(b,this.nextSibling)});if(arguments.length){var a=this.pushStack(this,"after",arguments);a.push.apply(a,
c.clean(arguments));return a}},remove:function(a,b){for(var d=0,e;null!=(e=this[d]);d++)if(!a||c.filter(a,[e]).length)b||1!==e.nodeType||(c.cleanData(e.getElementsByTagName("*")),c.cleanData([e])),e.parentNode&&e.parentNode.removeChild(e);return this},empty:function(){for(var a=0,b;null!=(b=this[a]);a++)for(1===b.nodeType&&c.cleanData(b.getElementsByTagName("*"));b.firstChild;)b.removeChild(b.firstChild);return this},clone:function(a,b){a=null==a?!1:a;b=null==b?a:b;return this.map(function(){return c.clone(this,
a,b)})},html:function(a){if(a===v)return this[0]&&1===this[0].nodeType?this[0].innerHTML.replace(Wb,""):null;if("string"!==typeof a||Zb.test(a)||!c.support.leadingWhitespace&&Ca.test(a)||X[(fb.exec(a)||["",""])[1].toLowerCase()])c.isFunction(a)?this.each(function(e){var f=c(this);f.html(a.call(this,e,f.html()))}):this.empty().append(a);else{a=a.replace(eb,"<$1></$2>");try{for(var b=0,d=this.length;b<d;b++)1===this[b].nodeType&&(c.cleanData(this[b].getElementsByTagName("*")),this[b].innerHTML=a)}catch(e){this.empty().append(a)}}return this},
replaceWith:function(a){if(this[0]&&this[0].parentNode){if(c.isFunction(a))return this.each(function(b){var d=c(this),e=d.html();d.replaceWith(a.call(this,b,e))});"string"!==typeof a&&(a=c(a).detach());return this.each(function(){var b=this.nextSibling,d=this.parentNode;c(this).remove();b?c(b).before(a):c(d).append(a)})}return this.length?this.pushStack(c(c.isFunction(a)?a():a),"replaceWith",a):this},detach:function(a){return this.remove(a,!0)},domManip:function(a,b,d){var e,f=a[0],h=[];if(!c.support.checkClone&&
3===arguments.length&&"string"===typeof f&&hb.test(f))return this.each(function(){c(this).domManip(a,b,d,!0)});if(c.isFunction(f))return this.each(function(r){var D=c(this);a[0]=f.call(this,r,b?D.html():v);D.domManip(a,b,d)});if(this[0]){var k=f&&f.parentNode;k=c.support.parentNode&&k&&11===k.nodeType&&k.childNodes.length===this.length?{fragment:k}:c.buildFragment(a,this,h);var n=k.fragment;if(e=1===n.childNodes.length?n=n.firstChild:n.firstChild){b=b&&c.nodeName(e,"tr");for(var q=0,x=this.length,
z=x-1;q<x;q++)d.call(b?xb(this[q],e):this[q],k.cacheable||1<x&&q<z?c.clone(n,!0,!0):n)}h.length&&c.each(h,yb)}return this}});c.buildFragment=function(a,b,d){var e,f,h,k=a[0];b&&b[0]&&(h=b[0].ownerDocument||b[0]);h.createDocumentFragment||(h=E);if(1===a.length&&"string"===typeof k&&512>k.length&&h===E&&"<"===k.charAt(0)&&!$b.test(k)&&(c.support.checkClone||!hb.test(k))&&(c.support.html5Clone||!gb.test(k))){var n=!0;(f=c.fragments[k])&&1!==f&&(e=f)}e||(e=h.createDocumentFragment(),c.clean(a,h,e,d));
n&&(c.fragments[k]=f?e:1);return{fragment:e,cacheable:n}};c.fragments={};c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){c.fn[a]=function(d){var e=[];d=c(d);var f=1===this.length&&this[0].parentNode;if(f&&11===f.nodeType&&1===f.childNodes.length&&1===d.length)return d[b](this[0]),this;f=0;for(var h=d.length;f<h;f++){var k=(0<f?this.clone(!0):this).get();c(d[f])[b](k);e=e.concat(k)}return this.pushStack(e,a,d.selector)}});
c.extend({clone:function(a,b,d){var e;if(c.support.html5Clone||!gb.test("<"+a.nodeName))var f=a.cloneNode(!0);else f=E.createElement("div"),ib.appendChild(f),f.innerHTML=a.outerHTML,f=f.firstChild;var h=f;if(!(c.support.noCloneEvent&&c.support.noCloneChecked||1!==a.nodeType&&11!==a.nodeType||c.isXMLDoc(a))){Na(a,h);f=qa(a);var k=qa(h);for(e=0;f[e];++e)k[e]&&Na(f[e],k[e])}if(b&&(Ma(a,h),d))for(f=qa(a),k=qa(h),e=0;f[e];++e)Ma(f[e],k[e]);return h},clean:function(a,b,d,e){b=b||E;"undefined"===typeof b.createElement&&
(b=b.ownerDocument||b[0]&&b[0].ownerDocument||E);for(var f=[],h,k=0,n;null!=(n=a[k]);k++)if("number"===typeof n&&(n+=""),n){if("string"===typeof n)if(Yb.test(n)){n=n.replace(eb,"<$1></$2>");h=(fb.exec(n)||["",""])[1].toLowerCase();var q=X[h]||X._default,x=q[0],z=b.createElement("div");b===E?ib.appendChild(z):Ka(b).appendChild(z);for(z.innerHTML=q[1]+n+q[2];x--;)z=z.lastChild;if(!c.support.tbody)for(x=Xb.test(n),q="table"!==h||x?"<table>"!==q[1]||x?[]:z.childNodes:z.firstChild&&z.firstChild.childNodes,
h=q.length-1;0<=h;--h)c.nodeName(q[h],"tbody")&&!q[h].childNodes.length&&q[h].parentNode.removeChild(q[h]);!c.support.leadingWhitespace&&Ca.test(n)&&z.insertBefore(b.createTextNode(Ca.exec(n)[0]),z.firstChild);n=z.childNodes}else n=b.createTextNode(n);var r;if(!c.support.appendChecked)if(n[0]&&"number"===typeof(r=n.length))for(h=0;h<r;h++)Pa(n[h]);else Pa(n);n.nodeType?f.push(n):f=c.merge(f,n)}if(d)for(a=function(D){return!D.type||ac.test(D.type)},k=0;f[k];k++)!e||!c.nodeName(f[k],"script")||f[k].type&&
"text/javascript"!==f[k].type.toLowerCase()?(1===f[k].nodeType&&(b=c.grep(f[k].getElementsByTagName("script"),a),f.splice.apply(f,[k+1,0].concat(b))),d.appendChild(f[k])):e.push(f[k].parentNode?f[k].parentNode.removeChild(f[k]):f[k]);return f},cleanData:function(a){for(var b,d,e=c.cache,f=c.event.special,h=c.support.deleteExpando,k=0,n;null!=(n=a[k]);k++)if(!n.nodeName||!c.noData[n.nodeName.toLowerCase()])if(d=n[c.expando]){if((b=e[d])&&b.events){for(var q in b.events)f[q]?c.event.remove(n,q):c.removeEvent(n,
q,b.handle);b.handle&&(b.handle.elem=null)}h?delete n[c.expando]:n.removeAttribute&&n.removeAttribute(c.expando);delete e[d]}}});var Da=/alpha\([^)]*\)/i,bc=/opacity=([^)]*)/,cc=/([A-Z]|^ms)/g,jb=/^-?\d+(?:px)?$/i,dc=/^-?\d/,ec=/^([\-+])=([\-+.\de]+)/,fc={position:"absolute",visibility:"hidden",display:"block"},Ab=["Left","Right"],Bb=["Top","Bottom"],kb,lb;c.fn.css=function(a,b){return 2===arguments.length&&b===v?this:c.access(this,a,b,!0,function(d,e,f){return f!==v?c.style(d,e,f):c.css(d,e)})};
c.extend({cssHooks:{opacity:{get:function(a,b){return b?(a=ma(a,"opacity","opacity"),""===a?"1":a):a.style.opacity}}},cssNumber:{fillOpacity:!0,fontWeight:!0,lineHeight:!0,opacity:!0,orphans:!0,widows:!0,zIndex:!0,zoom:!0},cssProps:{"float":c.support.cssFloat?"cssFloat":"styleFloat"},style:function(a,b,d,e){if(a&&3!==a.nodeType&&8!==a.nodeType&&a.style){var f,h=c.camelCase(b),k=a.style,n=c.cssHooks[h];b=c.cssProps[h]||h;if(d!==v){if(e=typeof d,"string"===e&&(f=ec.exec(d))&&(d=+(f[1]+1)*+f[2]+parseFloat(c.css(a,
b)),e="number"),!(null==d||"number"===e&&isNaN(d)||("number"!==e||c.cssNumber[h]||(d+="px"),n&&"set"in n&&(d=n.set(a,d))===v)))try{k[b]=d}catch(q){}}else return n&&"get"in n&&(f=n.get(a,!1,e))!==v?f:k[b]}},css:function(a,b,d){var e;b=c.camelCase(b);var f=c.cssHooks[b];b=c.cssProps[b]||b;"cssFloat"===b&&(b="float");if(f&&"get"in f&&(e=f.get(a,!0,d))!==v)return e;if(ma)return ma(a,b)},swap:function(a,b,d){var e={},f;for(f in b)e[f]=a.style[f],a.style[f]=b[f];d.call(a);for(f in b)a.style[f]=e[f]}});
c.curCSS=c.css;c.each(["height","width"],function(a,b){c.cssHooks[b]={get:function(d,e,f){var h;if(e){if(0!==d.offsetWidth)return Qa(d,b,f);c.swap(d,fc,function(){h=Qa(d,b,f)});return h}},set:function(d,e){if(jb.test(e)){if(e=parseFloat(e),0<=e)return e+"px"}else return e}}});c.support.opacity||(c.cssHooks.opacity={get:function(a,b){return bc.test((b&&a.currentStyle?a.currentStyle.filter:a.style.filter)||"")?parseFloat(RegExp.$1)/100+"":b?"1":""},set:function(a,b){var d=a.style;a=a.currentStyle;var e=
c.isNumeric(b)?"alpha(opacity="+100*b+")":"",f=a&&a.filter||d.filter||"";d.zoom=1;if(1<=b&&""===c.trim(f.replace(Da,""))&&(d.removeAttribute("filter"),a&&!a.filter))return;d.filter=Da.test(f)?f.replace(Da,e):f+" "+e}});c(function(){c.support.reliableMarginRight||(c.cssHooks.marginRight={get:function(a,b){var d;c.swap(a,{display:"inline-block"},function(){d=b?ma(a,"margin-right","marginRight"):a.style.marginRight});return d}})});E.defaultView&&E.defaultView.getComputedStyle&&(kb=function(a,b){var d,
e;b=b.replace(cc,"-$1").toLowerCase();if((d=a.ownerDocument.defaultView)&&(e=d.getComputedStyle(a,null))){var f=e.getPropertyValue(b);""!==f||c.contains(a.ownerDocument.documentElement,a)||(f=c.style(a,b))}return f});E.documentElement.currentStyle&&(lb=function(a,b){var d,e,f=a.currentStyle&&a.currentStyle[b],h=a.style;null===f&&h&&(d=h[b])&&(f=d);if(!jb.test(f)&&dc.test(f)){d=h.left;if(e=a.runtimeStyle&&a.runtimeStyle.left)a.runtimeStyle.left=a.currentStyle.left;h.left="fontSize"===b?"1em":f||0;
f=h.pixelLeft+"px";h.left=d;e&&(a.runtimeStyle.left=e)}return""===f?"auto":f});var ma=kb||lb;c.expr&&c.expr.filters&&(c.expr.filters.hidden=function(a){var b=a.offsetHeight;return 0===a.offsetWidth&&0===b||!c.support.reliableHiddenOffsets&&"none"===(a.style&&a.style.display||c.css(a,"display"))},c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)});var gc=/%20/g,Cb=/\[\]$/,mb=/\r?\n/g,hc=/#.*$/,ic=/^(.*?):[ \t]*([^\r\n]*)\r?$/mg,jc=/^(?:color|date|datetime|datetime-local|email|hidden|month|number|password|range|search|tel|text|time|url|week)$/i,
kc=/^(?:GET|HEAD)$/,lc=/^\/\//,nb=/\?/,mc=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,nc=/^(?:select|textarea)/i,Sa=/\s+/,oc=/([?&])_=[^&]*/,ob=/^([\w\+\.\-]+:)(?:\/\/([^\/?#:]*)(?::(\d+))?)?/,pb=c.fn.load,wa={},qb={};try{var ia=Fb.href}catch(a){ia=E.createElement("a"),ia.href="",ia=ia.href}var ja=ob.exec(ia.toLowerCase())||[];c.fn.extend({load:function(a,b,d){if("string"!==typeof a&&pb)return pb.apply(this,arguments);if(!this.length)return this;var e=a.indexOf(" ");if(0<=e){var f=a.slice(e,
a.length);a=a.slice(0,e)}e="GET";b&&(c.isFunction(b)?(d=b,b=v):"object"===typeof b&&(b=c.param(b,c.ajaxSettings.traditional),e="POST"));var h=this;c.ajax({url:a,type:e,dataType:"html",data:b,complete:function(k,n,q){q=k.responseText;k.isResolved()&&(k.done(function(x){q=x}),h.html(f?c("<div>").append(q.replace(mc,"")).find(f):q));d&&h.each(d,[q,n,k])}});return this},serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){return this.elements?
c.makeArray(this.elements):this}).filter(function(){return this.name&&!this.disabled&&(this.checked||nc.test(this.nodeName)||jc.test(this.type))}).map(function(a,b){a=c(this).val();return null==a?null:c.isArray(a)?c.map(a,function(d,e){return{name:b.name,value:d.replace(mb,"\r\n")}}):{name:b.name,value:a.replace(mb,"\r\n")}}).get()}});c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){c.fn[b]=function(d){return this.on(b,d)}});c.each(["get","post"],function(a,
b){c[b]=function(d,e,f,h){c.isFunction(e)&&(h=h||f,f=e,e=v);return c.ajax({type:b,url:d,data:e,success:f,dataType:h})}});c.extend({getScript:function(a,b){return c.get(a,v,b,"script")},getJSON:function(a,b,d){return c.get(a,b,d,"json")},ajaxSetup:function(a,b){b?Ta(a,c.ajaxSettings):(b=a,a=c.ajaxSettings);Ta(a,b);return a},ajaxSettings:{url:ia,isLocal:/^(?:about|app|app\-storage|.+\-extension|file|res|widget):$/.test(ja[1]),global:!0,type:"GET",contentType:"application/x-www-form-urlencoded",processData:!0,
async:!0,accepts:{xml:"application/xml, text/xml",html:"text/html",text:"text/plain",json:"application/json, text/javascript","*":"*/*"},contents:{xml:/xml/,html:/html/,json:/json/},responseFields:{xml:"responseXML",text:"responseText"},converters:{"* text":F.String,"text html":!0,"text json":c.parseJSON,"text xml":c.parseXML},flatOptions:{context:!0,url:!0}},ajaxPrefilter:Ra(wa),ajaxTransport:Ra(qb),ajax:function(a,b){function d(g,l,p,t){if(2!==K){K=2;N&&clearTimeout(N);A=v;r=t||"";J.readyState=
0<g?4:0;t=l;if(p){var u=e,y=J,G=u.contents,H=u.dataTypes,L=u.responseFields,O,m;for(I in L)I in p&&(y[L[I]]=p[I]);for(;"*"===H[0];)H.shift(),O===v&&(O=u.mimeType||y.getResponseHeader("content-type"));if(O)for(I in G)if(G[I]&&G[I].test(O)){H.unshift(I);break}if(H[0]in p)var w=H[0];else{for(I in p){if(!H[0]||u.converters[I+" "+H[0]]){w=I;break}m||(m=I)}w=w||m}w?(w!==H[0]&&H.unshift(w),p=p[w]):p=void 0}else p=v;if(200<=g&&300>g||304===g){if(e.ifModified){if(O=J.getResponseHeader("Last-Modified"))c.lastModified[W]=
O;if(O=J.getResponseHeader("Etag"))c.etag[W]=O}if(304===g){t="notmodified";var C=!0}else try{O=e;O.dataFilter&&(p=O.dataFilter(p,O.dataType));var B=O.dataTypes;var I={};var S,T,Q=B.length,V=B[0];for(S=1;S<Q;S++){if(1===S)for(T in O.converters)"string"===typeof T&&(I[T.toLowerCase()]=O.converters[T]);var na=V;V=B[S];if("*"===V)V=na;else if("*"!==na&&na!==V){var rb=na+" "+V;var ea=I[rb]||I["* "+V];if(!ea){var oa=v;for(ka in I){var Ea=ka.split(" ");if(Ea[0]===na||"*"===Ea[0])if(oa=I[Ea[1]+" "+V]){var ka=
I[ka];!0===ka?ea=oa:!0===oa&&(ea=ka);break}}}ea||oa||c.error("No conversion from "+rb.replace(" "," to "));!0!==ea&&(p=ea?ea(p):oa(ka(p)))}}var sb=p;t="success";C=!0}catch(pc){t="parsererror";var Fa=pc}}else if(Fa=t,!t||g)t="error",0>g&&(g=0);J.status=g;J.statusText=""+(l||t);C?k.resolveWith(f,[sb,t,J]):k.rejectWith(f,[J,t,Fa]);J.statusCode(q);q=v;aa&&h.trigger("ajax"+(C?"Success":"Error"),[J,e,C?sb:Fa]);n.fireWith(f,[J,t]);aa&&(h.trigger("ajaxComplete",[J,e]),--c.active||c.event.trigger("ajaxStop"))}}
"object"===typeof a&&(b=a,a=v);b=b||{};var e=c.ajaxSetup({},b),f=e.context||e,h=f!==e&&(f.nodeType||f instanceof c)?c(f):c.event,k=c.Deferred(),n=c.Callbacks("once memory"),q=e.statusCode||{},x={},z={},r,D,A,N,K=0,U,J={readyState:0,setRequestHeader:function(g,l){if(!K){var p=g.toLowerCase();g=z[p]=z[p]||g;x[g]=l}return this},getAllResponseHeaders:function(){return 2===K?r:null},getResponseHeader:function(g){var l;if(2===K){if(!D)for(D={};l=ic.exec(r);)D[l[1].toLowerCase()]=l[2];l=D[g.toLowerCase()]}return l===
v?null:l},overrideMimeType:function(g){K||(e.mimeType=g);return this},abort:function(g){g=g||"abort";A&&A.abort(g);d(0,g);return this}};k.promise(J);J.success=J.done;J.error=J.fail;J.complete=n.add;J.statusCode=function(g){if(g)if(2>K)for(l in g)q[l]=[q[l],g[l]];else{var l=g[J.status];J.then(l,l)}return this};e.url=((a||e.url)+"").replace(hc,"").replace(lc,ja[1]+"//");e.dataTypes=c.trim(e.dataType||"*").toLowerCase().split(Sa);null==e.crossDomain&&(a=ob.exec(e.url.toLowerCase()),e.crossDomain=!(!a||
a[1]==ja[1]&&a[2]==ja[2]&&(a[3]||("http:"===a[1]?80:443))==(ja[3]||("http:"===ja[1]?80:443))));e.data&&e.processData&&"string"!==typeof e.data&&(e.data=c.param(e.data,e.traditional));ra(wa,e,b,J);if(2===K)return!1;var aa=e.global;e.type=e.type.toUpperCase();e.hasContent=!kc.test(e.type);aa&&0===c.active++&&c.event.trigger("ajaxStart");if(!e.hasContent){e.data&&(e.url+=(nb.test(e.url)?"&":"?")+e.data,delete e.data);var W=e.url;if(!1===e.cache){a=c.now();var Y=e.url.replace(oc,"$1_="+a);e.url=Y+(Y===
e.url?(nb.test(e.url)?"&":"?")+"_="+a:"")}}(e.data&&e.hasContent&&!1!==e.contentType||b.contentType)&&J.setRequestHeader("Content-Type",e.contentType);e.ifModified&&(W=W||e.url,c.lastModified[W]&&J.setRequestHeader("If-Modified-Since",c.lastModified[W]),c.etag[W]&&J.setRequestHeader("If-None-Match",c.etag[W]));J.setRequestHeader("Accept",e.dataTypes[0]&&e.accepts[e.dataTypes[0]]?e.accepts[e.dataTypes[0]]+("*"!==e.dataTypes[0]?", */*; q=0.01":""):e.accepts["*"]);for(U in e.headers)J.setRequestHeader(U,
e.headers[U]);if(e.beforeSend&&(!1===e.beforeSend.call(f,J,e)||2===K))return J.abort(),!1;for(U in{success:1,error:1,complete:1})J[U](e[U]);if(A=ra(qb,e,b,J)){J.readyState=1;aa&&h.trigger("ajaxSend",[J,e]);e.async&&0<e.timeout&&(N=setTimeout(function(){J.abort("timeout")},e.timeout));try{K=1,A.send(x,d)}catch(g){if(2>K)d(-1,g);else throw g;}}else d(-1,"No Transport");return J},param:function(a,b){var d=[],e=function(h,k){k=c.isFunction(k)?k():k;d[d.length]=encodeURIComponent(h)+"="+encodeURIComponent(k)};
b===v&&(b=c.ajaxSettings.traditional);if(c.isArray(a)||a.jquery&&!c.isPlainObject(a))c.each(a,function(){e(this.name,this.value)});else for(var f in a)xa(f,a[f],b,e);return d.join("&").replace(gc,"+")}});c.extend({active:0,lastModified:{},etag:{}});var qc=c.now(),ua=/(=)\?(&|$)|\?\?/i;c.ajaxSetup({jsonp:"callback",jsonpCallback:function(){return c.expando+"_"+qc++}});c.ajaxPrefilter("json jsonp",function(a,b,d){b="application/x-www-form-urlencoded"===a.contentType&&"string"===typeof a.data;if("jsonp"===
a.dataTypes[0]||!1!==a.jsonp&&(ua.test(a.url)||b&&ua.test(a.data))){var e,f=a.jsonpCallback=c.isFunction(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback,h=F[f],k=a.url,n=a.data,q="$1"+f+"$2";!1!==a.jsonp&&(k=k.replace(ua,q),a.url===k&&(b&&(n=n.replace(ua,q)),a.data===n&&(k+=(/\?/.test(k)?"&":"?")+a.jsonp+"="+f)));a.url=k;a.data=n;F[f]=function(x){e=[x]};d.always(function(){F[f]=h;if(e&&c.isFunction(h))F[f](e[0])});a.converters["script json"]=function(){e||c.error(f+" was not called");return e[0]};
a.dataTypes[0]="json";return"script"}});c.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},contents:{script:/javascript|ecmascript/},converters:{"text script":function(a){c.globalEval(a);return a}}});c.ajaxPrefilter("script",function(a){a.cache===v&&(a.cache=!1);a.crossDomain&&(a.type="GET",a.global=!1)});c.ajaxTransport("script",function(a){if(a.crossDomain){var b,d=E.head||E.getElementsByTagName("head")[0]||E.documentElement;
return{send:function(e,f){b=E.createElement("script");b.async="async";a.scriptCharset&&(b.charset=a.scriptCharset);b.src=a.url;b.onload=b.onreadystatechange=function(h,k){if(k||!b.readyState||/loaded|complete/.test(b.readyState))b.onload=b.onreadystatechange=null,d&&b.parentNode&&d.removeChild(b),b=v,k||f(200,"success")};d.insertBefore(b,d.firstChild)},abort:function(){if(b)b.onload(0,1)}}}});var Ga=F.ActiveXObject?function(){for(var a in la)la[a](0,1)}:!1,rc=0,la;c.ajaxSettings.xhr=F.ActiveXObject?
function(){var a;if(!(a=!this.isLocal&&Ua()))a:{try{a=new F.ActiveXObject("Microsoft.XMLHTTP");break a}catch(b){}a=void 0}return a}:Ua;(function(a){c.extend(c.support,{ajax:!!a,cors:!!a&&"withCredentials"in a})})(c.ajaxSettings.xhr());c.support.ajax&&c.ajaxTransport(function(a){if(!a.crossDomain||c.support.cors){var b;return{send:function(d,e){var f=a.xhr(),h;a.username?f.open(a.type,a.url,a.async,a.username,a.password):f.open(a.type,a.url,a.async);if(a.xhrFields)for(h in a.xhrFields)f[h]=a.xhrFields[h];
a.mimeType&&f.overrideMimeType&&f.overrideMimeType(a.mimeType);a.crossDomain||d["X-Requested-With"]||(d["X-Requested-With"]="XMLHttpRequest");try{for(h in d)f.setRequestHeader(h,d[h])}catch(n){}f.send(a.hasContent&&a.data||null);b=function(n,q){var x;try{if(b&&(q||4===f.readyState))if(b=v,k&&(f.onreadystatechange=c.noop,Ga&&delete la[k]),q)4!==f.readyState&&f.abort();else{var z=f.status;var r=f.getAllResponseHeaders();var D={};(x=f.responseXML)&&x.documentElement&&(D.xml=x);D.text=f.responseText;
try{var A=f.statusText}catch(N){A=""}z||!a.isLocal||a.crossDomain?1223===z&&(z=204):z=D.text?200:404}}catch(N){q||e(-1,N)}D&&e(z,A,D,r)};if(a.async&&4!==f.readyState){var k=++rc;Ga&&(la||(la={},c(F).unload(Ga)),la[k]=b);f.onreadystatechange=b}else b()},abort:function(){b&&b(0,1)}}}});var ya={},Z,ha,sc=/^(?:toggle|show|hide)$/,tc=/^([+\-]=)?([\d+.\-]+)([a-z%]*)$/i,va,Wa=[["height","marginTop","marginBottom","paddingTop","paddingBottom"],["width","marginLeft","marginRight","paddingLeft","paddingRight"],
["opacity"]],sa;c.fn.extend({show:function(a,b,d){if(a||0===a)return this.animate(fa("show",3),a,b,d);d=0;for(var e=this.length;d<e;d++)a=this[d],a.style&&(b=a.style.display,c._data(a,"olddisplay")||"none"!==b||(b=a.style.display=""),""===b&&"none"===c.css(a,"display")&&c._data(a,"olddisplay",Xa(a.nodeName)));for(d=0;d<e;d++)if(a=this[d],a.style&&(b=a.style.display,""===b||"none"===b))a.style.display=c._data(a,"olddisplay")||"";return this},hide:function(a,b,d){if(a||0===a)return this.animate(fa("hide",
3),a,b,d);d=0;for(var e=this.length;d<e;d++)a=this[d],a.style&&(b=c.css(a,"display"),"none"===b||c._data(a,"olddisplay")||c._data(a,"olddisplay",b));for(d=0;d<e;d++)this[d].style&&(this[d].style.display="none");return this},_toggle:c.fn.toggle,toggle:function(a,b,d){var e="boolean"===typeof a;c.isFunction(a)&&c.isFunction(b)?this._toggle.apply(this,arguments):null==a||e?this.each(function(){var f=e?a:c(this).is(":hidden");c(this)[f?"show":"hide"]()}):this.animate(fa("toggle",3),a,b,d);return this},
fadeTo:function(a,b,d,e){return this.filter(":hidden").css("opacity",0).show().end().animate({opacity:b},a,d,e)},animate:function(a,b,d,e){function f(){!1===h.queue&&c._mark(this);var k=c.extend({},h),n=1===this.nodeType,q=n&&c(this).is(":hidden"),x;k.animatedProperties={};for(x in a){var z=c.camelCase(x);x!==z&&(a[z]=a[x],delete a[x]);var r=a[z];c.isArray(r)?(k.animatedProperties[z]=r[1],r=a[z]=r[0]):k.animatedProperties[z]=k.specialEasing&&k.specialEasing[z]||k.easing||"swing";if("hide"===r&&q||
"show"===r&&!q)return k.complete.call(this);!n||"height"!==z&&"width"!==z||(k.overflow=[this.style.overflow,this.style.overflowX,this.style.overflowY],"inline"===c.css(this,"display")&&"none"===c.css(this,"float")&&(c.support.inlineBlockNeedsLayout&&"inline"!==Xa(this.nodeName)?this.style.zoom=1:this.style.display="inline-block"))}null!=k.overflow&&(this.style.overflow="hidden");for(x in a)if(n=new c.fx(this,k,x),r=a[x],sc.test(r))if(z=c._data(this,"toggle"+x)||("toggle"===r?q?"show":"hide":0))c._data(this,
"toggle"+x,"show"===z?"hide":"show"),n[z]();else n[r]();else{z=tc.exec(r);var D=n.cur();if(z){r=parseFloat(z[2]);var A=z[3]||(c.cssNumber[x]?"":"px");"px"!==A&&(c.style(this,x,(r||1)+A),D*=(r||1)/n.cur(),c.style(this,x,D+A));z[1]&&(r=("-="===z[1]?-1:1)*r+D);n.custom(D,r,A)}else n.custom(D,r,"")}return!0}var h=c.speed(b,d,e);if(c.isEmptyObject(a))return this.each(h.complete,[!1]);a=c.extend({},a);return!1===h.queue?this.each(f):this.queue(h.queue,f)},stop:function(a,b,d){"string"!==typeof a&&(d=b,
b=a,a=v);b&&!1!==a&&this.queue(a||"fx",[]);return this.each(function(){var e,f=!1,h=c.timers,k=c._data(this);d||c._unmark(!0,this);if(null==a)for(e in k){if(k[e]&&k[e].stop&&e.indexOf(".run")===e.length-4){var n=k[e];c.removeData(this,e,!0);n.stop(d)}}else k[e=a+".run"]&&k[e].stop&&(k=k[e],c.removeData(this,e,!0),k.stop(d));for(e=h.length;e--;)if(h[e].elem===this&&(null==a||h[e].queue===a)){if(d)h[e](!0);else h[e].saveState();f=!0;h.splice(e,1)}d&&f||c.dequeue(this,a)})}});c.each({slideDown:fa("show",
1),slideUp:fa("hide",1),slideToggle:fa("toggle",1),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){c.fn[a]=function(d,e,f){return this.animate(b,d,e,f)}});c.extend({speed:function(a,b,d){var e=a&&"object"===typeof a?c.extend({},a):{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};e.duration=c.fx.off?0:"number"===typeof e.duration?e.duration:e.duration in c.fx.speeds?c.fx.speeds[e.duration]:c.fx.speeds._default;if(null==
e.queue||!0===e.queue)e.queue="fx";e.old=e.complete;e.complete=function(f){c.isFunction(e.old)&&e.old.call(this);e.queue?c.dequeue(this,e.queue):!1!==f&&c._unmark(this)};return e},easing:{linear:function(a,b,d,e){return d+e*a},swing:function(a,b,d,e){return(-Math.cos(a*Math.PI)/2+.5)*e+d}},timers:[],fx:function(a,b,d){this.options=b;this.elem=a;this.prop=d;b.orig=b.orig||{}}});c.fx.prototype={update:function(){this.options.step&&this.options.step.call(this.elem,this.now,this);(c.fx.step[this.prop]||
c.fx.step._default)(this)},cur:function(){if(null!=this.elem[this.prop]&&(!this.elem.style||null==this.elem.style[this.prop]))return this.elem[this.prop];var a,b=c.css(this.elem,this.prop);return isNaN(a=parseFloat(b))?b&&"auto"!==b?b:0:a},custom:function(a,b,d){function e(k){return f.step(k)}var f=this,h=c.fx;this.startTime=sa||Va();this.end=b;this.now=this.start=a;this.pos=this.state=0;this.unit=d||this.unit||(c.cssNumber[this.prop]?"":"px");e.queue=this.options.queue;e.elem=this.elem;e.saveState=
function(){f.options.hide&&c._data(f.elem,"fxshow"+f.prop)===v&&c._data(f.elem,"fxshow"+f.prop,f.start)};e()&&c.timers.push(e)&&!va&&(va=setInterval(h.tick,h.interval))},show:function(){var a=c._data(this.elem,"fxshow"+this.prop);this.options.orig[this.prop]=a||c.style(this.elem,this.prop);this.options.show=!0;a!==v?this.custom(this.cur(),a):this.custom("width"===this.prop||"height"===this.prop?1:0,this.cur());c(this.elem).show()},hide:function(){this.options.orig[this.prop]=c._data(this.elem,"fxshow"+
this.prop)||c.style(this.elem,this.prop);this.options.hide=!0;this.custom(this.cur(),0)},step:function(a){var b,d=sa||Va(),e=!0,f=this.elem,h=this.options;if(a||d>=h.duration+this.startTime){this.now=this.end;this.pos=this.state=1;this.update();h.animatedProperties[this.prop]=!0;for(b in h.animatedProperties)!0!==h.animatedProperties[b]&&(e=!1);if(e){null==h.overflow||c.support.shrinkWrapBlocks||c.each(["","X","Y"],function(k,n){f.style["overflow"+n]=h.overflow[k]});h.hide&&c(f).hide();if(h.hide||
h.show)for(b in h.animatedProperties)c.style(f,b,h.orig[b]),c.removeData(f,"fxshow"+b,!0),c.removeData(f,"toggle"+b,!0);if(a=h.complete)h.complete=!1,a.call(f)}return!1}Infinity==h.duration?this.now=d:(a=d-this.startTime,this.state=a/h.duration,this.pos=c.easing[h.animatedProperties[this.prop]](this.state,a,0,1,h.duration),this.now=this.start+(this.end-this.start)*this.pos);this.update();return!0}};c.extend(c.fx,{tick:function(){for(var a,b=c.timers,d=0;d<b.length;d++)a=b[d],a()||b[d]!==a||b.splice(d--,
1);b.length||c.fx.stop()},interval:13,stop:function(){clearInterval(va);va=null},speeds:{slow:600,fast:200,_default:400},step:{opacity:function(a){c.style(a.elem,"opacity",a.now)},_default:function(a){a.elem.style&&null!=a.elem.style[a.prop]?a.elem.style[a.prop]=a.now+a.unit:a.elem[a.prop]=a.now}}});c.each(["width","height"],function(a,b){c.fx.step[b]=function(d){c.style(d.elem,b,Math.max(0,d.now)+d.unit)}});c.expr&&c.expr.filters&&(c.expr.filters.animated=function(a){return c.grep(c.timers,function(b){return a===
b.elem}).length});var uc=/^t(?:able|d|h)$/i,tb=/^(?:body|html)$/i;c.fn.offset="getBoundingClientRect"in E.documentElement?function(a){var b=this[0];if(a)return this.each(function(h){c.offset.setOffset(this,a,h)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);try{var d=b.getBoundingClientRect()}catch(h){}var e=b.ownerDocument,f=e.documentElement;if(!d||!c.contains(f,b))return d?{top:d.top,left:d.left}:{top:0,left:0};b=e.body;e=za(e);return{top:d.top+
(e.pageYOffset||c.support.boxModel&&f.scrollTop||b.scrollTop)-(f.clientTop||b.clientTop||0),left:d.left+(e.pageXOffset||c.support.boxModel&&f.scrollLeft||b.scrollLeft)-(f.clientLeft||b.clientLeft||0)}}:function(a){var b=this[0];if(a)return this.each(function(x){c.offset.setOffset(this,a,x)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);var d=b.offsetParent,e=b.ownerDocument,f=e.documentElement,h=e.body;var k=(e=e.defaultView)?e.getComputedStyle(b,null):
b.currentStyle;for(var n=b.offsetTop,q=b.offsetLeft;(b=b.parentNode)&&b!==h&&b!==f&&(!c.support.fixedPosition||"fixed"!==k.position);)k=e?e.getComputedStyle(b,null):b.currentStyle,n-=b.scrollTop,q-=b.scrollLeft,b===d&&(n+=b.offsetTop,q+=b.offsetLeft,!c.support.doesNotAddBorder||c.support.doesAddBorderForTableAndCells&&uc.test(b.nodeName)||(n+=parseFloat(k.borderTopWidth)||0,q+=parseFloat(k.borderLeftWidth)||0),d=b.offsetParent),c.support.subtractsBorderForOverflowNotVisible&&"visible"!==k.overflow&&
(n+=parseFloat(k.borderTopWidth)||0,q+=parseFloat(k.borderLeftWidth)||0);if("relative"===k.position||"static"===k.position)n+=h.offsetTop,q+=h.offsetLeft;c.support.fixedPosition&&"fixed"===k.position&&(n+=Math.max(f.scrollTop,h.scrollTop),q+=Math.max(f.scrollLeft,h.scrollLeft));return{top:n,left:q}};c.offset={bodyOffset:function(a){var b=a.offsetTop,d=a.offsetLeft;c.support.doesNotIncludeMarginInBodyOffset&&(b+=parseFloat(c.css(a,"marginTop"))||0,d+=parseFloat(c.css(a,"marginLeft"))||0);return{top:b,
left:d}},setOffset:function(a,b,d){var e=c.css(a,"position");"static"===e&&(a.style.position="relative");var f=c(a),h=f.offset(),k=c.css(a,"top"),n=c.css(a,"left"),q={};("absolute"===e||"fixed"===e)&&-1<c.inArray("auto",[k,n])?(n=f.position(),e=n.top,n=n.left):(e=parseFloat(k)||0,n=parseFloat(n)||0);c.isFunction(b)&&(b=b.call(a,d,h));null!=b.top&&(q.top=b.top-h.top+e);null!=b.left&&(q.left=b.left-h.left+n);"using"in b?b.using.call(a,q):f.css(q)}};c.fn.extend({position:function(){if(!this[0])return null;
var a=this[0],b=this.offsetParent(),d=this.offset(),e=tb.test(b[0].nodeName)?{top:0,left:0}:b.offset();d.top-=parseFloat(c.css(a,"marginTop"))||0;d.left-=parseFloat(c.css(a,"marginLeft"))||0;e.top+=parseFloat(c.css(b[0],"borderTopWidth"))||0;e.left+=parseFloat(c.css(b[0],"borderLeftWidth"))||0;return{top:d.top-e.top,left:d.left-e.left}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||E.body;a&&!tb.test(a.nodeName)&&"static"===c.css(a,"position");)a=a.offsetParent;return a})}});
c.each(["Left","Top"],function(a,b){var d="scroll"+b;c.fn[d]=function(e){var f;if(e===v){var h=this[0];return h?(f=za(h))?"pageXOffset"in f?f[a?"pageYOffset":"pageXOffset"]:c.support.boxModel&&f.document.documentElement[d]||f.document.body[d]:h[d]:null}return this.each(function(){(f=za(this))?f.scrollTo(a?c(f).scrollLeft():e,a?e:c(f).scrollTop()):this[d]=e})}});c.each(["Height","Width"],function(a,b){var d=b.toLowerCase();c.fn["inner"+b]=function(){var e=this[0];return e?e.style?parseFloat(c.css(e,
d,"padding")):this[d]():null};c.fn["outer"+b]=function(e){var f=this[0];return f?f.style?parseFloat(c.css(f,d,e?"margin":"border")):this[d]():null};c.fn[d]=function(e){var f=this[0];if(!f)return null==e?null:this;if(c.isFunction(e))return this.each(function(n){var q=c(this);q[d](e.call(this,n,q[d]()))});if(c.isWindow(f)){var h=f.document.documentElement["client"+b],k=f.document.body;return"CSS1Compat"===f.document.compatMode&&h||k&&k["client"+b]||h}return 9===f.nodeType?Math.max(f.documentElement["client"+
b],f.body["scroll"+b],f.documentElement["scroll"+b],f.body["offset"+b],f.documentElement["offset"+b]):e===v?(f=c.css(f,d),h=parseFloat(f),c.isNumeric(h)?h:f):this.css(d,"string"===typeof e?e:e+"px")}});F.jQuery=F.$=c;"function"===typeof define&&define.amd&&define.amd.jQuery&&define("jquery",[],function(){return c})})(window);
