var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(d,g,f){d instanceof String&&(d=String(d));for(var m=d.length,k=0;k<m;k++){var q=d[k];if(g.call(f,q,k,d))return{i:k,v:q}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,g,f){if(d==Array.prototype||d==Object.prototype)return d;d[g]=f.value;return d};$jscomp.getGlobal=function(d){d=["object"==typeof globalThis&&globalThis,d,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var g=0;g<d.length;++g){var f=d[g];if(f&&f.Math==Math)return f}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(d,g){var f=$jscomp.propertyToPolyfillSymbol[g];if(null==f)return d[g];f=d[f];return void 0!==f?f:d[g]};
$jscomp.polyfill=function(d,g,f,m){g&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(d,g,f,m):$jscomp.polyfillUnisolated(d,g,f,m))};$jscomp.polyfillUnisolated=function(d,g,f,m){f=$jscomp.global;d=d.split(".");for(m=0;m<d.length-1;m++){var k=d[m];if(!(k in f))return;f=f[k]}d=d[d.length-1];m=f[d];g=g(m);g!=m&&null!=g&&$jscomp.defineProperty(f,d,{configurable:!0,writable:!0,value:g})};
$jscomp.polyfillIsolated=function(d,g,f,m){var k=d.split(".");d=1===k.length;m=k[0];m=!d&&m in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var q=0;q<k.length-1;q++){var c=k[q];if(!(c in m))return;m=m[c]}k=k[k.length-1];f=$jscomp.IS_SYMBOL_NATIVE&&"es6"===f?m[k]:null;g=g(f);null!=g&&(d?$jscomp.defineProperty($jscomp.polyfills,k,{configurable:!0,writable:!0,value:g}):g!==f&&($jscomp.propertyToPolyfillSymbol[k]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(k):$jscomp.POLYFILL_PREFIX+k,k=
$jscomp.propertyToPolyfillSymbol[k],$jscomp.defineProperty(m,k,{configurable:!0,writable:!0,value:g})))};$jscomp.polyfill("Array.prototype.find",function(d){return d?d:function(g,f){return $jscomp.findInternal(this,g,f).v}},"es6","es3");
getStorage(null).then(function(d){function g(a){chrome.tabs.query({active:!0,currentWindow:!0},function(h){a(h[0])})}function f(a){$("#check-shortcut-"+a).is(":checked")?$("#check-shortcut-"+a+"-ctrl,#check-shortcut-"+a+"-alt,#shortcut-"+a+" select").removeAttr("disabled"):$("#check-shortcut-"+a+"-ctrl,#check-shortcut-"+a+"-alt,#shortcut-"+a+" select").attr("disabled","true")}function m(a,h){console.trace();$("#refresh-outliner").removeClass("processing");var l=a.list;a=a.outliners;var n=$("#diigobm-list").find(".item-container");
n.empty();a.length&&($('<div class="menu-title">Outliners</div>').appendTo(n),forEach(a,function(b){$('<div class="menu-item" data-id="'+b.id+'">'+b.title+"</div>").appendTo(n)}));l.length&&($('<div class="menu-title">Lists</div>').appendTo(n),forEach(l,function(b){$('<div class="menu-item" data-id="'+b.id+'">'+b.title+"</div>").appendTo(n)}));var e=$("#diigobm-list").find("select").empty().unbind().removeClass("processing");e.append(Utils.dom.buildOne("option",{value:0},["Add to an Outliner"]));
e.append(Utils.dom.buildOne("option",{value:-1},[Array(20).join("-")]));$(Utils.dom.buildOne("option",{value:-2},["Create an Outliner..."])).appendTo(e);e.append(Utils.dom.buildOne("option",{value:-1},[Array(20).join("-")]));forEach(a,function(b){h?e.append(Utils.dom.buildOne("option",{value:b.id},[b.title])):e.append(Utils.dom.buildOne("option",{value:b.id},[b.title+""]))});e.append(Utils.dom.buildOne("option",{value:-1},[Array(20).join("-")]));l.length&&(e.append(Utils.dom.buildOne("option",{value:-8},
["Add to a List"])),e.append(Utils.dom.buildOne("option",{value:-1},[Array(20).join("-")])),forEach(l,function(b){h?e.append(Utils.dom.buildOne("option",{value:b.id},[b.title])):e.append(Utils.dom.buildOne("option",{value:b.id},[b.title+""]))}));e.append(Utils.dom.buildOne("option",{value:-1},[Array(20).join("-")]));$(Utils.dom.buildOne("option",{value:-3},["Refresh"])).appendTo(e);e.change(function(){var b=e.val();-2==b?(!0===d.globalData.permissions.createOutliner?($("#diigobm-list-add").show(),
$("#diigobm-list").hide(),$("#diigobm-list-addInput").focus()):($("#diigobm-list-add-tip").show(),$("#diigobm-list").hide()),e.val(0),e.remvoeClass("selected")):-3==b&&($(this).addClass("processing"),chrome.tabs.getSelected(null,function(p){chrome.tabs.sendMessage(p.id,{name:"refreshMyStuff"})}),e.val(-1))});e.val(0).change()}function k(a,h){$("#refresh-group").removeClass("processing");var l=a.filter(function(b){return 5>b.access_mode});a=a.filter(function(b){console.log(b.access_mode);return 5<=
b.access_mode});var n=$("#diigobm-group").find(".item-container");n.empty();a.length&&($('<div class="menu-title">Teams</div>').appendTo(n),forEach(a,function(b){var p=inGroup(b.name)?b.displayName+" (shared)":b.displayName;$('<div class="menu-item" data-id="'+b.name+'">'+p+"</div>").on("click",function(){console.log("Click");var r=b.name;void 0!=popCtx.groupTagsDict[r]?showTags("group",popCtx.groupTagsDict[r]):($("#diigobm-group-tag").show(),g(function(t){chrome.tabs.sendMessage(t.id,{name:"loadGroupTagsDictionary",
groupName:r})}))}).appendTo(n)}));l.length&&($('<div class="menu-title">Groups</div>').appendTo(n),forEach(l,function(b){var p=inGroup(b.name)?b.displayName+" (shared)":b.displayName;$('<div class="menu-item" data-id="'+b.name+'">'+p+"</div>").on("click",function(){console.log("Click");var r=b.name;void 0!=popCtx.groupTagsDict[r]?showTags("group",popCtx.groupTagsDict[r]):($("#diigobm-group-tag").show(),g(function(t){chrome.tabs.sendMessage(t.id,{name:"loadGroupTagsDictionary",groupName:r})}))}).appendTo(n)}));
var e=$("#diigobm-group").find("select").empty().unbind().removeClass("processing");0<a.length&&(e.append(Utils.dom.buildOne("option",{value:0},["Share to a Team"])),e.append(Utils.dom.buildOne("option",{value:-5},[Array(20).join("-")])),forEach(a,function(b){h?e.append(Utils.dom.buildOne("option",{value:b.name},[b.displayName])):e.append(Utils.dom.buildOne("option",{value:b.name},[b.displayName+(inGroup(b.name)?" (shared)":"")]))}),e.append(Utils.dom.buildOne("option",{value:-5},[Array(20).join("-")])));
e.append(Utils.dom.buildOne("option",{value:0},["Share to a Group"]));e.append(Utils.dom.buildOne("option",{value:-1},[Array(20).join("-")]));$(Utils.dom.buildOne("option",{value:-2},["Create a Group..."])).appendTo(e);e.append(Utils.dom.buildOne("option",{value:-5},[Array(20).join("-")]));forEach(l,function(b){h?e.append(Utils.dom.buildOne("option",{value:b.name},[b.displayName])):e.append(Utils.dom.buildOne("option",{value:b.name},[b.displayName+(inGroup(b.name)?" (shared)":"")]))});e.append(Utils.dom.buildOne("option",
{value:-5},[Array(20).join("-")]));$(Utils.dom.buildOne("option",{value:-3},["Refresh"])).appendTo(e);e.change(function(){var b=e.val();-2==b?(chrome.tabs.create({url:"https://groups.diigo.com/create"}),e.val(-1)):-3==b&&($(this).addClass("processing"),chrome.tabs.getSelected(null,function(p){chrome.tabs.sendMessage(p.id,{name:"refreshMyStuff"})}),e.val(-1));0!=b&&-1!=b&&-2!=b&&-3!=b&&($("#diigosc-group-tag").show(),popCtx.isAnnotated&&$("#bottom").find("div:first-child").show(),$("#Diigo-Bookmark-checkShareExisting").show(),
console.log(popCtx),void 0!=popCtx.groupTagsDict[b]?showTags("group",popCtx.groupTagsDict[b]):($("#diigobm-group-tag").show(),chrome.tabs.getSelected(null,function(p){chrome.tabs.sendMessage(p.id,{name:"loadGroupTagsDictionary",groupName:b})})))});e.val(0).change()}function q(){null!==u&&clearTimeout(u);u=setTimeout(function(){var a=$("#r-tag-input").val();a=ParseTags.parseTags(a);var h=$("#f-private").prop("checked"),l=$("#f-read-later").prop("checked"),n=$("#f-cache").prop("checked"),e=$("#diigobm-list").find(".content").attr("data-id"),
b=$("#diigobm-group").find(".content").attr("data-id");chrome.storage.local.set({researchModeData:{tags:a,_private:h,unread:l,cache:n,outliner:e,group:b}})},150)}var c={get:function(a){return d[a]},set:function(a){saveStorage(a)}},u=null;$("label input[data-pref]").on("change",function(){var a=$(this).attr("data-pref"),h=$(this).prop("checked")+"";if("prefs.directlyShowSearchResults"==a&&1==h){if(!d.globalData.permissions.autoShowAnnotation){$("#check-showSearchResultDirectly").prop("checked",!1);
$(".modelWin-wrapper").show();$("#comboSearch-tip").show();return}$("#check-comboSearch").prop("checked",!0);c.set({"prefs.comboSearch":!0})}var l={};l[a]=h;c.set(l);"prefs.autoloadBookmarkStatus"==a&&0==h&&($("#check-autoload").prop("checked",!1),c.set({"prefs.autoload":!1}));"prefs.autoload"==a&&1==h&&($("#check-autoloadBookmarkStatus").prop("checked",!0),c.set({"prefs.autoloadBookmarkStatus":!0}));"prefs.comboSearch"==a&&0==h&&($("#check-showSearchResultDirectly").prop("checked",!1),c.set({"prefs.directlyShowSearchResults":!1}));
"prefs.shortcutAnnotate"==a&&f("annotate");"prefs.shortcutBookmark"==a&&f("bookmark");"prefs.shortcutReadlater"==a&&f("readlater")});$("#check-focusResearch").on("change",function(){var a=$(this).prop("checked");chrome.storage.local.set({researchMode:a});a?$("#focus-research-options").show():$("#focus-research-options").hide()});$(".form-select").on("change",function(){q()});$("#focus-research-options").find("input").on("input",q).end().find("input[type=checkbox]").on("change",q);(function(){for(var a=
$("<select></select>"),h=48;91>h;h++)if(!(57<h&&65>h)){var l=String.fromCharCode(h);$("<option></option>").attr({value:l}).text(l).appendTo(a)}a.on("change",function(){var n=$(this).parents(".shortcut").attr("data-type"),e={};e["prefs.shortcut"+n+"Key"]=$(this).val();c.set(e)});a.appendTo($(".shortcut"));$(".shortcut[data-type=Bookmark]").find("select").val(c.get("prefs.shortcutBookmarkKey")||"Q");$(".shortcut[data-type=Annotate]").find("select").val(c.get("prefs.shortcutAnnotateKey")||"D");$(".shortcut[data-type=Readlater]").find("select").val(c.get("prefs.shortcutReadlaterKey")||
"R");$(".shortcut[data-type=OpenOutlinerSidebar]").find("select").val(c.get("prefs.shortcutOpenOutlinerSidebarKey")||"O");$(".shortcut[data-type=AnnotateArticle]").find("select").val(c.get("prefs.shortcutAnnotateArticleKey")||"T");$(".shortcut[data-type=AnnotatePDF]").find("select").val(c.get("prefs.shortcutAnnotatePDFKey")||"P");$(".shortcut[data-type=AnnotateScreenshot]").find("select").val(c.get("prefs.shortcutAnnotateScreenshotKey")||"S")})();$("#check-bmPrivateAsDefault").attr({checked:"true"==
c.get("prefs.bookmark.privateByDefault")});$("#check-bmUnreadAsDefault").attr({checked:"true"==c.get("prefs.bookmark.unreadByDefault")});$("#check-autoloadBookmarkStatus").attr({checked:"true"==c.get("prefs.autoloadBookmarkStatus")});$("#check-autoload").attr({checked:"true"==c.get("prefs.autoload")});$("#check-contextMenu").attr({checked:"true"==c.get("prefs.contextMenu")});$("#check-comboSearch").attr({checked:"true"==c.get("prefs.comboSearch")});$("#check-searcho").attr({checked:"true"==c.get("prefs.SearchO")});
$("#check-autoshowicon").attr({checked:"true"==c.get("prefs.autoShowHighlightIcon")});$("#check-autoImageClipper").attr({checked:"true"==c.get("prefs.autoImageClipper")});$("#check-autoCloseReadLater").attr({checked:"true"==c.get("prefs.autoCloseReadLater")});$("#check-shortcut-annotate").attr({checked:"true"==c.get("prefs.shortcutAnnotate")});$("#check-shortcut-bookmark").attr({checked:"true"==c.get("prefs.shortcutBookmark")});$("#check-shortcut-readlater").attr({checked:"true"==c.get("prefs.shortcutReadlater")});
$("#check-showSearchResultDirectly").attr({checked:"true"==c.get("prefs.directlyShowSearchResults")});$("#check-shortcut-annotate-ctrl").attr({checked:"true"==c.get("prefs.shortcutAnnotateCtrl")});$("#check-shortcut-annotate-alt").attr({checked:"true"==c.get("prefs.shortcutAnnotateAlt")});$("#shortcut-annotate select").val(c.get("prefs.shortcutAnnotateKey"));$("#check-shortcut-bookmark-ctrl").attr({checked:"true"==c.get("prefs.shortcutBookmarkCtrl")});$("#check-shortcut-bookmark-alt").attr({checked:"true"==
c.get("prefs.shortcutBookmarkAlt")});$("#shortcut-bookmark select").val(c.get("prefs.shortcutBookmarkKey"));$("#check-shortcut-a-article-ctrl").attr({checked:"true"==c.get("prefs.shortcutAnnotateArticleCtrl")});$("#check-shortcut-a-article-alt").attr({checked:"true"==c.get("prefs.shortcutAnnotateArticleAlt")});$("#check-shortcut-a-article").attr({checked:"true"==c.get("prefs.shortcutAnnotateArticle")});$("#check-shortcut-a-pdf-ctrl").attr({checked:"true"==c.get("prefs.shortcutAnnotatePDFCtrl")});
$("#check-shortcut-a-pdf-alt").attr({checked:"true"==c.get("prefs.shortcutAnnotatePDFAlt")});$("#check-shortcut-a-pdf").attr({checked:"true"==c.get("prefs.shortcutAnnotatePDF")});$("#check-shortcut-a-screenshot-ctrl").attr({checked:"true"==c.get("prefs.shortcutAnnotateScreenshotCtrl")});$("#check-shortcut-a-screenshot-alt").attr({checked:"true"==c.get("prefs.shortcutAnnotateScreenshotAlt")});$("#check-shortcut-a-screenshot").attr({checked:"true"==c.get("prefs.shortcutAnnotateScreenshot")});$("#check-shortcut-readlater-ctrl").attr({checked:"true"==
c.get("prefs.shortcutReadlaterCtrl")});$("#check-shortcut-readlater-alt").attr({checked:"true"==c.get("prefs.shortcutReadlaterAlt")});$("#check-shortcut-openOutlinerSidebar").attr({checked:"true"==c.get("prefs.shortcutOpenOutlinerSidebar")});$("#check-shortcut-openOutlinerSidebar-ctrl").attr({checked:"true"==c.get("prefs.shortcutOpenOutlinerSidebarCtrl")});$("#check-shortcut-openOutlinerSidebar-alt").attr({checked:"true"==c.get("prefs.shortcutOpenOutlinerSidebarAlt")});$("#shortcut-readlater select").val(c.get("prefs.shortcutReadlaterKey"));
$("#check-shortcut-openOutlinerSidebar select").val(c.get("prefs.shortcutOpenOutlinerSidebarKey"));$("#check-showPdfButton").attr({checked:"true"==c.get("prefs.showPdfButton")});$("#check-showVideoButton").attr({checked:"true"==c.get("prefs.showVideoCapture")});f("bookmark");f("annotate");f("readlater");f("openOutlinerSidebar");(function(){m({list:d.globalData.myBmLists,outliners:d.globalData.outliners},!1);k(d.globalData.myGroups,!1);$("#close-upgrade-info").on("click",function(){$("#upgrade-info").hide()});
$("#btn-upgrade-info").on("click",function(){chrome.tabs.create({url:"https://www.diigo.com/premium?f=outliner"})});$("#diigobm-list-addBtn").on("click",function(){console.log("click");if(!$(this).parent().hasClass("processing"))if(d.globalData.permissions.createOutliner){var a=$("#diigobm-list-addInput").val(),h=$("#diigobm-list-add .diigo-alert-tip"),l=[],n=d.globalData.myBmLists.length,e;for(e=0;e<n;e++)l.push(d.globalData.myBmLists[e].title);a.match(/^\s*$/)?(h.show().find("span").text("Input a name"),
$("#diigobm-list-addInput").focus()):-1!==$.inArray(a,l)?h.show().find("span").text("Name existed !"):($(this).parent().addClass("processing"),Bg.WebAPI.createList(a,function(b){m({list:b.lists,outliners:b.outliners});b=b.newOutliner;var p=$("#diigobm-list");p.find(".content").text(b.title).attr("data-id",b.id);p.removeClass("focused");p.find(".add-box").hide().find("input").val("");p.find(".search-box").show();p.trigger("change")}))}else $("#upgrade-info").show()});$("#diigobm-list-addCancel").on("click",
function(){$("#diigobm-list-add .diigo-alert-tip").hide();$("#diigobm-list-add").hide();$("#diigobm-list").show();$("#diigobm-list-addInput").val("")});$("#w-upgrade").on("click",function(a){a.preventDefault();googleEvent("Chrome extension","Click upgrade from outliner creation","outliner");chrome.tabs.create({url:"https://www.diigo.com/premium?f=outliner"});$("#diigobm-list-add-tip").hide();$("#diigobm-list").show()});$("#w-cancel").on("click",function(a){a.preventDefault();$("#diigobm-list-add-tip").hide();
$("#diigobm-list").show()});chrome.storage.local.get(["researchMode","researchModeData"],function(a){1==a.researchMode&&($("#check-focusResearch").prop("checked",!0),$("#focus-research-options").show());if(a.researchModeData){a=a.researchModeData;var h=ParseTags.unparseTags(a.tags||[]);$("#r-tag-input").val(h);(a._private||"true"==c.get("prefs.bookmark.privateByDefault"))&&$("#f-private").prop("checked",!0);a.unread&&$("#f-read-later").prop("checked",!0);a.cache&&$("#f-cache").prop("checked",!0);
if(a.outliner){var l=$("#diigobm-list");h=l.find(".menu-item[data-id="+a.outliner+"]").text();l.find(".content").text(h).attr("data-id",a.outliner).end().addClass("inputed")}a.group&&(l=$("#diigobm-group"),h=l.find(".menu-item[data-id="+a.group+"]").text(),l.find(".content").text(h).attr("data-id",a.group).end().addClass("inputed"))}})})();$(".modelWin-close").on("click",function(){$(this).parents(".modelWin-wrapper").hide()})});
