var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var e=a.length,d=0;d<e;d++){var f=a[d];if(b.call(c,f,d,a))return{i:d,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,e){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,e):$jscomp.polyfillUnisolated(a,b,c,e))};$jscomp.polyfillUnisolated=function(a,b,c,e){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];if(!(d in c))return;c=c[d]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,e){var d=a.split(".");a=1===d.length;e=d[0];e=!a&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<d.length-1;f++){var g=d[f];if(!(g in e))return;e=e[g]}d=d[d.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?e[d]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+d,d=
$jscomp.propertyToPolyfillSymbol[d],$jscomp.defineProperty(e,d,{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");var Bg=chrome.extension.getBackgroundPage(),Prefs=Bg.Prefs;function getSelectedTab(a){chrome.tabs.query({active:!0,currentWindow:!0},function(b){a(b[0])})}
$(document).ready(function(){$("#btnSave").click(function(){save();$("#noticeSaved").fadeIn("slow").delay(1E3).fadeOut("slow");return!1});$("#btnCancel").click(function(){getSelectedTab(function(a){chrome.tabs.remove(a.id)})});$(".go-premium-btn").on("click",function(){refreshWindow.show()});$(".diigolet-option-tip-btn").on("click",function(){$(this).siblings(".diigolet-option-tip-container").fadeIn()});$(".tp-close").on("click",function(){$(this).parents(".diigolet-option-tip-container").fadeOut()});
buildSelect();prefs2UI();$(".diigolet-question-mark").hover(function(){$(this).find(".diigolet-question-mark-tip").fadeIn()},function(){$(this).find(".diigolet-question-mark-tip").fadeOut()});$(".cancel-go-premium-btn").on("click",function(){$(this).parents(".diigolet-option-tip-container").fadeOut()});"#search"==window.location.hash&&$("#search-tip").find(".diigolet-option-tip-container").show();Bg.GlobalData.permissions.autoShowAnnotation?$(".tip-premium").addClass("show"):($(".tip-no-premium").addClass("show"),
$("#search-tip-premium").show());(function(){var a=$("#check-autoloadBookmarkStatus"),b=$("#check-autoload"),c=$("#check-showSearchResultDirectly"),e=$("#check-comboSearch");a.change(function(){a.is(":checked")||b.attr("checked",!1)});e.change(function(){e.is(":checked")||c.attr("checked",!1)});b.change(function(d){b.is(":checked")&&a.attr("checked",!0)});c.change(function(d){Bg.GlobalData.permissions.autoShowAnnotation?c.is(":checked")&&e.attr("checked",!0):(d.preventDefault(),c.attr("checked",!1),
$("#search-tip").find(".diigolet-option-tip-container").show())});$("#check-shortcut-annotate").change(function(){shortcutSwitchState("annotate")});$("#check-shortcut-bookmark").change(function(){shortcutSwitchState("bookmark")});$("#check-shortcut-readlater").change(function(){shortcutSwitchState("readlater")});$("#shortcut-annotate select").change(function(){var d=$(this).val();$("#shortcut-bookmark select option").each(function(){$(this).removeAttr("disabled")});$('#shortcut-bookmark select option[value="'+
d+'"]').attr("disabled",!0);$("#shortcut-readlater select option").each(function(){$(this).removeAttr("disabled")});$('#shortcut-readlater select option[value="'+d+'"]').attr("disabled",!0)});$("#shortcut-bookmark select").change(function(){var d=$(this).val();$("#shortcut-annotate select option").each(function(){$(this).removeAttr("disabled")});$('#shortcut-annotate select option[value="'+d+'"]').attr("disabled",!0);$("#shortcut-readlater select option").each(function(){$(this).removeAttr("disabled")});
$('#shortcut-readlater select option[value="'+d+'"]').attr("disabled",!0)});$("#shortcut-readlater select").change(function(){var d=$(this).val();$("#shortcut-annotate select option").each(function(){$(this).removeAttr("disabled")});$('#shortcut-annotate select option[value="'+d+'"]').attr("disabled",!0);$("#shortcut-bookmark select option").each(function(){$(this).removeAttr("disabled")});$('#shortcut-bookmark select option[value="'+d+'"]').attr("disabled",!0)})})()});
function buildSelect(){for(var a=["Q","D"],b=$("<select></select>"),c=48;91>c;c++)if(!(57<c&&65>c)){var e=String.fromCharCode(c);$("<option></option>").attr({value:e}).text(e).appendTo(b)}b.appendTo($(".shortcut")).each(function(d){this.value=a[d]})}function save(){$("#check-searcho").is(":checked")||_gaq.push(["_trackEvent","Disable SearchO","Diigo"]);UI2prefs()}
function shortcutSwitchState(a){$("#check-shortcut-"+a).is(":checked")?$("#check-shortcut-"+a+"-ctrl,#check-shortcut-"+a+"-alt,#shortcut-"+a+" select").removeAttr("disabled"):$("#check-shortcut-"+a+"-ctrl,#check-shortcut-"+a+"-alt,#shortcut-"+a+" select").attr("disabled","true")}
function prefs2UI(){$("#check-bmPrivateAsDefault").attr({checked:"true"==Prefs.get("prefs.bookmark.privateByDefault")});$("#check-bmUnreadAsDefault").attr({checked:"true"==Prefs.get("prefs.bookmark.unreadByDefault")});$("#check-autoloadBookmarkStatus").attr({checked:"true"==Prefs.get("prefs.autoloadBookmarkStatus")});$("#check-autoload").attr({checked:"true"==Prefs.get("prefs.autoload")});$("#check-contextMenu").attr({checked:"true"==Prefs.get("prefs.contextMenu")});$("#check-comboSearch").attr({checked:"true"==
Prefs.get("prefs.comboSearch")});$("#check-searcho").attr({checked:"true"==Prefs.get("prefs.SearchO")});$("#check-autoshowicon").attr({checked:"true"==Prefs.get("prefs.autoShowHighlightIcon")});$("#check-autoImageClipper").attr({checked:"true"==Prefs.get("prefs.autoImageClipper")});$("#check-autoCloseReadLater").attr({checked:"true"==Prefs.get("prefs.autoCloseReadLater")});$("#check-shortcut-annotate").attr({checked:"true"==Prefs.get("prefs.shortcutAnnotate")});$("#check-shortcut-bookmark").attr({checked:"true"==
Prefs.get("prefs.shortcutBookmark")});$("#check-shortcut-readlater").attr({checked:"true"==Prefs.get("prefs.shortcutReadlater")});$("#check-showSearchResultDirectly").attr({checked:"true"==Prefs.get("prefs.directlyShowSearchResults")});$("#check-shortcut-annotate-ctrl").attr({checked:"true"==Prefs.get("prefs.shortcutAnnotateCtrl")});$("#check-shortcut-annotate-alt").attr({checked:"true"==Prefs.get("prefs.shortcutAnnotateAlt")});$("#shortcut-annotate select").val(Prefs.get("prefs.shortcutAnnotateKey"));
$("#check-shortcut-bookmark-ctrl").attr({checked:"true"==Prefs.get("prefs.shortcutBookmarkCtrl")});$("#check-shortcut-bookmark-alt").attr({checked:"true"==Prefs.get("prefs.shortcutBookmarkAlt")});$("#shortcut-bookmark select").val(Prefs.get("prefs.shortcutBookmarkKey"));$("#check-shortcut-readlater-ctrl").attr({checked:"true"==Prefs.get("prefs.shortcutReadlaterCtrl")});$("#check-shortcut-readlater-alt").attr({checked:"true"==Prefs.get("prefs.shortcutReadlaterAlt")});$("#shortcut-readlater select").val(Prefs.get("prefs.shortcutReadlaterKey"));
$("#check-showPdfButton").attr({checked:"true"==Prefs.get("prefs.showPdfButton")});shortcutSwitchState("bookmark");shortcutSwitchState("annotate");shortcutSwitchState("readlater")}
function UI2prefs(){Prefs.set({"prefs.bookmark.privateByDefault":$("#check-bmPrivateAsDefault").is(":checked")});Prefs.set({"prefs.bookmark.unreadByDefault":$("#check-bmUnreadAsDefault").is(":checked")});Prefs.set({"prefs.autoloadBookmarkStatus":$("#check-autoloadBookmarkStatus").is(":checked")});Prefs.set({"prefs.autoload":$("#check-autoload").is(":checked")});Prefs.set({"prefs.contextMenu":$("#check-contextMenu").is(":checked")});Prefs.set({"prefs.comboSearch":$("#check-comboSearch").is(":checked")});
Prefs.set({"prefs.SearchO":$("#check-searcho").is(":checked")});Prefs.set({"prefs.autoShowHighlightIcon":$("#check-autoshowicon").is(":checked")});Prefs.set({"prefs.autoImageClipper":$("#check-autoImageClipper").is(":checked")});Prefs.set({"prefs.shortcutAnnotate":$("#check-shortcut-annotate").is(":checked")});Prefs.set({"prefs.shortcutBookmark":$("#check-shortcut-bookmark").is(":checked")});Prefs.set({"prefs.shortcutReadlater":$("#check-shortcut-readlater").is(":checked")});Prefs.set({"prefs.shortcutAnnotateCtrl":$("#check-shortcut-annotate-ctrl").is(":checked")});
Prefs.set({"prefs.shortcutAnnotateAlt":$("#check-shortcut-annotate-alt").is(":checked")});Prefs.set({"prefs.shortcutBookmarkCtrl":$("#check-shortcut-bookmark-ctrl").is(":checked")});Prefs.set({"prefs.shortcutBookmarkAlt":$("#check-shortcut-bookmark-alt").is(":checked")});Prefs.set({"prefs.shortcutReadlaterCtrl":$("#check-shortcut-readlater-ctrl").is(":checked")});Prefs.set({"prefs.shortcutReadlaterAlt":$("#check-shortcut-readlater-alt").is(":checked")});Prefs.set({"prefs.shortcutAnnotateKey":$("#shortcut-annotate select").val()});
Prefs.set({"prefs.shortcutBookmarkKey":$("#shortcut-bookmark select").val()});Prefs.set({"prefs.shortcutReadlaterKey":$("#shortcut-readlater select").val()});Prefs.set({"prefs.autoCloseReadLater":$("#check-autoCloseReadLater").is(":checked")});Prefs.set({"prefs.directlyShowSearchResults":$("#check-showSearchResultDirectly").is(":checked")});Prefs.set({"prefs.showPdfButton":$("#check-showPdfButton").is(":checked")})}var _gaq=_gaq||[];_gaq.push(["_setAccount","UA-295754-35"]);_gaq.push(["_trackPageview"]);
var refreshWindow={j:null,k:null,shown:!1,init:function(){this.create()},create:function(){var a=this;a.j=$('<div id="diigo-refresh-warning"><div id="diigo-refresh-warning-content"><div id="diigo-refresh-warning-main" class="clearfloat"><div id="diigo-refresh-warning-icon"></div><div id="diigo-refresh-warning-text"><p>After you upgrade to premium, click \u2018refresh\u2019 to access premium options.</p></div></div><div id="diigo-refresh-warning-bottom" class="clearfloat"><div id="diigo-refresh"class="diigo-refresh-warning-btn">Refresh</div><div id="diigo-refresh-warning-cancel"class="diigo-refresh-warning-btn">Cancel</div></div></div></div>').eq(0).appendTo(document.body.parentNode).hide();
a.k=$('<div id="diigo-refresh-warning-wrapper"></div>').eq(0).appendTo(document.body.parentNode).hide();$("#diigo-refresh").on("click",function(){$(this).hasClass("disabled")||($(this).text("Refreshing...").addClass("disabled"),(new Bg.WebAPICall).invoke("user_loadMyStuff",{what:"permissions"},{user:Bg.GlobalData.user,transId:null,complete:function(b){b.resp&&(Bg.GlobalData.permissions=b.resp.result.permissions,$("#premium-field").hide(),a.destroy(),forEachWebTab(function(c){Messenger.send(c.id,{name:"myStuffLoaded",
details:b.resp.result,fromTabId:null})}))}}))});$("#diigo-refresh-warning-cancel").on("click",function(){a.destroy()})},destroy:function(){this.k.remove();this.j.remove();this.j=null;this.shown=!1},show:function(){this.j||this.init();var a=this;if(1!=a.shown){var b=document.body.scrollWidth;a.k.css("height",document.body.scrollHeight).css("width",b).show();b=(window.screen.availHeight-356)/2+document.body.scrollTop;this.j.css("left",(window.screen.availWidth-356)/2+"px").css("top",b+"px");a.j.show();
a.shown=!0;$("#diigo-go-premium").click(function(){window.open("https://www.diigo.com/premium")});$("#diigo-premium-warning-cancel").click(function(){a.destroy()})}}};
function showUpgradeWin(){var a=$('<div class="modelWin-wrapper"><div class="modelWin"><div class="modelWin-close"></div><div class="modelWin-content">The ability to show highlights and notes automatically when you return to your annotated pages is a premium feature, and the free trial has expired.</div><div class="modelWin-action"><a class="modelWin-primary-btn" id="upgrade" href="https://www.diigo.com/premium" target="_blank">Upgrade now</a></div></div></div>').appendTo($("html"));$("#upgrade").on("click",
function(){refreshWindow.show();a.remove()});$(".modelWin-close").on("click",function(){$(this).parents(".modelWin-wrapper").remove()})};
