var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(b){var f=0;return function(){return f<b.length?{done:!1,value:b[f++]}:{done:!0}}};$jscomp.arrayIterator=function(b){return{next:$jscomp.arrayIteratorImpl(b)}};$jscomp.makeIterator=function(b){var f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];return f?f.call(b):$jscomp.arrayIterator(b)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,f,l){if(b==Array.prototype||b==Object.prototype)return b;b[f]=l.value;return b};
$jscomp.getGlobal=function(b){b=["object"==typeof globalThis&&globalThis,b,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var f=0;f<b.length;++f){var l=b[f];if(l&&l.Math==Math)return l}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(b,f){var l=$jscomp.propertyToPolyfillSymbol[f];if(null==l)return b[f];l=b[l];return void 0!==l?l:b[f]};$jscomp.polyfill=function(b,f,l,p){f&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(b,f,l,p):$jscomp.polyfillUnisolated(b,f,l,p))};
$jscomp.polyfillUnisolated=function(b,f,l,p){l=$jscomp.global;b=b.split(".");for(p=0;p<b.length-1;p++){var m=b[p];if(!(m in l))return;l=l[m]}b=b[b.length-1];p=l[b];f=f(p);f!=p&&null!=f&&$jscomp.defineProperty(l,b,{configurable:!0,writable:!0,value:f})};
$jscomp.polyfillIsolated=function(b,f,l,p){var m=b.split(".");b=1===m.length;p=m[0];p=!b&&p in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var y=0;y<m.length-1;y++){var k=m[y];if(!(k in p))return;p=p[k]}m=m[m.length-1];l=$jscomp.IS_SYMBOL_NATIVE&&"es6"===l?p[m]:null;f=f(l);null!=f&&(b?$jscomp.defineProperty($jscomp.polyfills,m,{configurable:!0,writable:!0,value:f}):f!==l&&($jscomp.propertyToPolyfillSymbol[m]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(m):$jscomp.POLYFILL_PREFIX+m,m=
$jscomp.propertyToPolyfillSymbol[m],$jscomp.defineProperty(p,m,{configurable:!0,writable:!0,value:f})))};$jscomp.underscoreProtoCanBeSet=function(){var b={a:!0},f={};try{return f.__proto__=b,f.a}catch(l){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(b,f){b.__proto__=f;if(b.__proto__!==f)throw new TypeError(b+" is not extensible");return b}:null;$jscomp.generator={};
$jscomp.generator.ensureIteratorResultIsObject_=function(b){if(!(b instanceof Object))throw new TypeError("Iterator result "+b+" is not an object");};$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};
$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(b){this.yieldResult=b};
$jscomp.generator.Context.prototype.throw_=function(b){this.abruptCompletion_={exception:b,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(b){this.abruptCompletion_={return:b};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(b){this.abruptCompletion_={jumpTo:b};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(b,f){this.nextAddress=f;return{value:b}};
$jscomp.generator.Context.prototype.yieldAll=function(b,f){b=$jscomp.makeIterator(b);var l=b.next();$jscomp.generator.ensureIteratorResultIsObject_(l);if(l.done)this.yieldResult=l.value,this.nextAddress=f;else return this.yieldAllIterator_=b,this.yield(l.value,f)};$jscomp.generator.Context.prototype.jumpTo=function(b){this.nextAddress=b};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};
$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(b,f){this.catchAddress_=b;void 0!=f&&(this.finallyAddress_=f)};$jscomp.generator.Context.prototype.setFinallyBlock=function(b){this.catchAddress_=0;this.finallyAddress_=b||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(b,f){this.nextAddress=b;this.catchAddress_=f||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(b){this.catchAddress_=b||0;b=this.abruptCompletion_.exception;this.abruptCompletion_=null;return b};$jscomp.generator.Context.prototype.enterFinallyBlock=function(b,f,l){l?this.finallyContexts_[l]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=b||0;this.finallyAddress_=f||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(b,f){f=this.finallyContexts_.splice(f||0)[0];if(f=this.abruptCompletion_=this.abruptCompletion_||f){if(f.isException)return this.jumpToErrorHandler_();void 0!=f.jumpTo&&this.finallyAddress_<f.jumpTo?(this.nextAddress=f.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=b};$jscomp.generator.Context.prototype.forIn=function(b){return new $jscomp.generator.Context.PropertyIterator(b)};
$jscomp.generator.Context.PropertyIterator=function(b){this.object_=b;this.properties_=[];for(var f in b)this.properties_.push(f);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var b=this.properties_.pop();if(b in this.object_)return b}return null};$jscomp.generator.Engine_=function(b){this.context_=new $jscomp.generator.Context;this.program_=b};
$jscomp.generator.Engine_.prototype.next_=function(b){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,b,this.context_.next_);this.context_.next_(b);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(b){this.context_.start_();var f=this.context_.yieldAllIterator_;if(f)return this.yieldAllStep_("return"in f?f["return"]:function(l){return{value:l,done:!0}},b,this.context_.return);this.context_.return(b);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(b){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],b,this.context_.next_);this.context_.throw_(b);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(b,f,l){try{var p=b.call(this.context_.yieldAllIterator_,f);$jscomp.generator.ensureIteratorResultIsObject_(p);if(!p.done)return this.context_.stop_(),p;var m=p.value}catch(y){return this.context_.yieldAllIterator_=null,this.context_.throw_(y),this.nextStep_()}this.context_.yieldAllIterator_=null;l.call(this.context_,m);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var b=this.program_(this.context_);if(b)return this.context_.stop_(),{value:b.value,done:!1}}catch(f){this.context_.yieldResult=void 0,this.context_.throw_(f)}this.context_.stop_();if(this.context_.abruptCompletion_){b=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(b.isException)throw b.exception;return{value:b.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(b){this.next=function(f){return b.next_(f)};this.throw=function(f){return b.throw_(f)};this.return=function(f){return b.return_(f)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(b,f){f=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(f));$jscomp.setPrototypeOf&&b.prototype&&$jscomp.setPrototypeOf(f,b.prototype);return f};
$jscomp.asyncExecutePromiseGenerator=function(b){function f(p){return b.next(p)}function l(p){return b.throw(p)}return new Promise(function(p,m){function y(k){k.done?p(k.value):Promise.resolve(k.value).then(f,l).then(y,m)}y(b.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(b){return $jscomp.asyncExecutePromiseGenerator(b())};$jscomp.asyncExecutePromiseGeneratorProgram=function(b){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b)))};
$jscomp.initSymbol=function(){};$jscomp.polyfill("Symbol",function(b){if(b)return b;var f=function(m,y){this.$jscomp$symbol$id_=m;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:y})};f.prototype.toString=function(){return this.$jscomp$symbol$id_};var l=0,p=function(m){if(this instanceof p)throw new TypeError("Symbol is not a constructor");return new f("jscomp_symbol_"+(m||"")+"_"+l++,m)};return p},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(b){if(b)return b;b=Symbol("Symbol.iterator");for(var f="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),l=0;l<f.length;l++){var p=$jscomp.global[f[l]];"function"===typeof p&&"function"!=typeof p.prototype[b]&&$jscomp.defineProperty(p.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return b},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(b){b={next:b};b[Symbol.iterator]=function(){return this};return b};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(b){function f(){this.batch_=null}function l(k){return k instanceof m?k:new m(function(q,t){q(k)})}if(b&&!$jscomp.FORCE_POLYFILL_PROMISE)return b;f.prototype.asyncExecute=function(k){if(null==this.batch_){this.batch_=[];var q=this;this.asyncExecuteFunction(function(){q.executeBatch_()})}this.batch_.push(k)};var p=$jscomp.global.setTimeout;f.prototype.asyncExecuteFunction=function(k){p(k,0)};f.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var k=
this.batch_;this.batch_=[];for(var q=0;q<k.length;++q){var t=k[q];k[q]=null;try{t()}catch(w){this.asyncThrow_(w)}}}this.batch_=null};f.prototype.asyncThrow_=function(k){this.asyncExecuteFunction(function(){throw k;})};var m=function(k){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var q=this.createResolveAndReject_();try{k(q.resolve,q.reject)}catch(t){q.reject(t)}};m.prototype.createResolveAndReject_=function(){function k(w){return function(z){t||(t=!0,w.call(q,z))}}var q=this,t=!1;
return{resolve:k(this.resolveTo_),reject:k(this.reject_)}};m.prototype.resolveTo_=function(k){if(k===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(k instanceof m)this.settleSameAsPromise_(k);else{a:switch(typeof k){case "object":var q=null!=k;break a;case "function":q=!0;break a;default:q=!1}q?this.resolveToNonPromiseObj_(k):this.fulfill_(k)}};m.prototype.resolveToNonPromiseObj_=function(k){var q=void 0;try{q=k.then}catch(t){this.reject_(t);return}"function"==typeof q?
this.settleSameAsThenable_(q,k):this.fulfill_(k)};m.prototype.reject_=function(k){this.settle_(2,k)};m.prototype.fulfill_=function(k){this.settle_(1,k)};m.prototype.settle_=function(k,q){if(0!=this.state_)throw Error("Cannot settle("+k+", "+q+"): Promise already settled in state"+this.state_);this.state_=k;this.result_=q;this.executeOnSettledCallbacks_()};m.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var k=0;k<this.onSettledCallbacks_.length;++k)y.asyncExecute(this.onSettledCallbacks_[k]);
this.onSettledCallbacks_=null}};var y=new f;m.prototype.settleSameAsPromise_=function(k){var q=this.createResolveAndReject_();k.callWhenSettled_(q.resolve,q.reject)};m.prototype.settleSameAsThenable_=function(k,q){var t=this.createResolveAndReject_();try{k.call(q,t.resolve,t.reject)}catch(w){t.reject(w)}};m.prototype.then=function(k,q){function t(A,B){return"function"==typeof A?function(D){try{w(A(D))}catch(H){z(H)}}:B}var w,z,E=new m(function(A,B){w=A;z=B});this.callWhenSettled_(t(k,w),t(q,z));return E};
m.prototype.catch=function(k){return this.then(void 0,k)};m.prototype.callWhenSettled_=function(k,q){function t(){switch(w.state_){case 1:k(w.result_);break;case 2:q(w.result_);break;default:throw Error("Unexpected state: "+w.state_);}}var w=this;null==this.onSettledCallbacks_?y.asyncExecute(t):this.onSettledCallbacks_.push(t)};m.resolve=l;m.reject=function(k){return new m(function(q,t){t(k)})};m.race=function(k){return new m(function(q,t){for(var w=$jscomp.makeIterator(k),z=w.next();!z.done;z=w.next())l(z.value).callWhenSettled_(q,
t)})};m.all=function(k){var q=$jscomp.makeIterator(k),t=q.next();return t.done?l([]):new m(function(w,z){function E(D){return function(H){A[D]=H;B--;0==B&&w(A)}}var A=[],B=0;do A.push(void 0),B++,l(t.value).callWhenSettled_(E(A.length-1),z),t=q.next();while(!t.done)})};return m},"es6","es3");$jscomp.findInternal=function(b,f,l){b instanceof String&&(b=String(b));for(var p=b.length,m=0;m<p;m++){var y=b[m];if(f.call(l,y,m,b))return{i:m,v:y}}return{i:-1,v:void 0}};
$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(f,l){return $jscomp.findInternal(this,f,l).v}},"es6","es3");var permissions={},GlobalData={};(function(){var b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){if(1==f.nextAddress)return f.setCatchFinallyBlocks(2),f.yield(getStorage("globalData"),4);if(2!=f.nextAddress)return GlobalData=f.yieldResult,permissions=GlobalData.permissions,f.leaveTryBlock(0);b=f.enterCatchBlock();console.error(b);f.jumpToEnd()})})();
function getSelectedTab(b){chrome.tabs.query({active:!0,currentWindow:!0},function(f){b(f[0])})}function googleEvent(b,f,l){}getSelectedTab(function(b){chrome.tabs.sendMessage(b.id,{name:"checkVersion"})});var popCtx;function isInResearchMode(){return $("#op-focus").prop("checked")}
function initPopup(){var b,f,l,p,m,y,k,q,t,w,z,E,A,B,D,H,T,I,Q,M,U,V,J,W,X,K,O,Y,L,R,F,P,S,C,N,Z;return $jscomp.asyncExecutePromiseGeneratorProgram(function(G){if(1==G.nextAddress)return G.setCatchFinallyBlocks(2),b=function(a){injectScriptToTab(a,["js/checkTab.js"],function(){debug("executeScript callback")})},f=function(a){$("#research-mode-notification").hide();a&&($("#top-bar").find("span").text("Focused Research").end().find("div").hide(),$("#diigobm-title,#diigobm-url,#op-cache,#diigobm-recommend-tag").hide(),
chrome.storage.local.get("isShowResearchTip",function(e){console.log(e);"undefined"!==typeof e.isShowResearchTip&&0==e.isShowResearchTip||$("#research-mode-notification").show()}),$("#research-mode-close-notify").on("click",function(){$("#research-mode-notification").hide();chrome.storage.local.set({isShowResearhTip:!1})}));a=navigator.userAgent.toLowerCase();var c=-1!=a.indexOf("macintosh")||-1!=a.indexOf("mac os x");c?($("#diigobm-url").addClass("mac"),$("#list-group select").css("text-indent",
"7px")):$("#diigobm-url").addClass("win");$("#link-icon").on("click",function(){var e=$("#diigobm-url");c?e.toggleClass("mac-unfold"):e.hasClass("unfold")?e.addClass("fold").removeClass("unfold"):e.addClass("unfold").removeClass("fold")});autoTextarea.init(document.getElementById("diigobm-title-input"),40);autoTextarea.init(document.getElementById("diigobm-des-input"),80);$("#diigobm-title-input").on("keydown",function(e){40==e.which&&$("#diigobm-des-input").focus()});$("#diigobm-des-input").on("keydown",
function(e){38==e.which&&$("#diigobm-title-input").focus()});$("#recommend-tag").on("click",function(e){e.preventDefault();$("#diigobm-recommend-tag").find(".diigo-tag").trigger("click")});$("#op-focus").on("change",function(){var e=$(this).prop("checked");chrome.storage.local.set({researchMode:e})});$("#diigobm-tag-dropdown").on("click",function(){$(this).toggleClass("cloud");"none"==$("#tag-cloud").css("display")?($("#tag-suggestion").hide(),$("#tag-cloud").show()):($("#tag-suggestion").show(),
$("#tag-cloud").hide())});$("#diigobm-recent-tag").on("click","a",function(){$("#diigobm-recent-tag").find(".diigo-tag").each(function(){O($(this).addClass("selected").text(),!0)})});$("#diigobm-options,#Diigo-Bookmark-checkShareExisting").on("click",".op-checkbox-container",function(){$(this).toggleClass("checked")});$("#bm-main").on("keydown",function(e){13==e.keyCode?"diigobm-tag-input"!=e.target.id||$("#diigolet-ac").is(":visible")||I():83==e.keyCode&&(e.ctrlKey||e.metaKey)?I():27==e.keyCode&&
window.close()});$("#op-cache").find(".op-checkbox-container").removeClass("checked");$("#remove").Gtooltip();a=[];var d=popCtx.myTagsWithCount?popCtx.myTagsWithCount:GlobalData.myTagsWithCount;d.sort(function(e,n){return e.count<=n.count?1:-1});for(var g=d.length,h=0;h<g;h++)a[h]=d[h].name;a={resultsClass:"diigolet ac_results",data:a,mode:"multiple",multipleSeparator:" ,",id:"diigolet-ac"};try{new AutoComplete("#diigobm-tag-input",a)}catch(e){debug(e)}$("#diigobm-tag-input").bind("input",function(){K()});
$("#diigobm-list-addInput").on("focus",function(){$("#diigobm-list-add .diigo-alert-tip").hide()});$("#close-upgrade-info").on("click",function(){$("#upgrade-info").hide()});$("#btn-upgrade-info").on("click",function(){chrome.tabs.create({url:"https://www.diigo.com/premium?f=outliner"})});$("#diigobm-list-addBtn").on("click",function(){console.log("click");if(!$(this).parent().hasClass("processing"))if(GlobalData.permissions.createOutliner){var e=$("#diigobm-list-addInput").val(),n=$("#diigobm-list-add .diigo-alert-tip"),
r=[],v=popCtx.lists.length,x;for(x=0;x<v;x++)r.push(popCtx.lists[x].title);e.match(/^\s*$/)?(n.show().find("span").text("Input a name"),$("#diigobm-list-addInput").focus()):-1!==$.inArray(e,r)?n.show().find("span").text("Name existed !"):($(this).parent().addClass("processing"),getSelectedTab(function(u){chrome.tabs.sendMessage(u.id,{name:"createList",data:e})}))}else $("#upgrade-info").show()});$("#diigobm-list-addCancel").on("click",function(){$("#diigobm-list-add .diigo-alert-tip").hide();$("#diigobm-list-add").hide();
$("#diigobm-list").show();$("#diigobm-list-addInput").val("")});$("#w-upgrade").on("click",function(e){e.preventDefault();googleEvent("Chrome extension","Click upgrade from outliner creation","outliner");chrome.tabs.create({url:"https://www.diigo.com/premium?f=outliner"});$("#diigobm-list-add-tip").hide();$("#diigobm-list").show()});$("#w-cancel").on("click",function(e){e.preventDefault();$("#diigobm-list-add-tip").hide();$("#diigobm-list").show()});$("#diigobm-recent-tag,#diigobm-recommend-tag,#diigobm-group-tag").on("click",
"div",function(e){/diigo\-tag/.test(e.target.className)&&O($(this).text())});$("#diigobm-saveBtn").on("click",function(){isInResearchMode()?l(I):I()});$("#bottom").on("click",function(e){switch(e.target.id){case "diigobm-saveBtn":isInResearchMode()?l(I):I();break;case "diigobm-cancelBtn":window.close()}});$("#diigobm-tag-input").focus();$("#refresh-outliner,#refresh-group").on("click",function(){$(this).addClass("processing");getSelectedTab(function(e){chrome.tabs.sendMessage(e.id,{name:"refreshMyStuff"})})})},
l=function(a){var c={};c.tags=ParseTags.parseTags($("#diigobm-tag-input").val(),!0);$("#op-private").prop("checked")?c._private=!0:c._private=!1;$("#op-readlater").prop("checked")?c.unread=!0:c.unread=!1;$("#op-cache").prop("checked")?c.cache=!0:c.cache=!1;c.outliner=$("#diigobm-list").find(".content").attr("data-id");c.group=$("#diigobm-group").find(".content").attr("data-id");console.log(c);chrome.storage.local.set({researchModeData:c},function(){a&&a()})},p=function(a,c){a=a.researchModeData;!0===
a._private||2==c?$("#op-private").prop("checked",!0):$("#op-private").prop("checked",!1);!0===a.unread&&$("#op-readlater").prop("checked",!0);a.cache&&!0===a.cache&&$("#op-cache").prop("checked",!0);c=ParseTags.unparseTags(a.tags);$("#diigobm-tag-input").val(c);K();if(a.outliner){var d=$("#diigobm-list");c=d.find(".menu-item[data-id="+a.outliner+"]").text();d.find(".content").text(c).attr("data-id",a.outliner).end().addClass("inputed")}a.group&&(d=$("#diigobm-group"),c=d.find(".menu-item[data-id="+
a.group+"]").text(),d.find(".content").text(c).attr("data-id",a.group).end().addClass("inputed"))},m=function(){$("#op-private").prop("checked",!1);$("#op-readlater").prop("checked",!1);$("#diigobm-tag-input").val("");$("#diigobm-list").find("select").val(0);$("#diigobm-group").find("select").val(0)},y=function(a){var c=a.groups?a.groups:GlobalData.myGroups;D({list:a.lists?a.lists:GlobalData.myBmLists,outliners:a.outliners?a.outliners:GlobalData.outliners},!0);B(c,!0);c=a.lastUsedTags?a.lastUsedTags:
[];if(0==$("#diigobm-recent-tag").find(".diigo-tag").length)if(0<c.length){for(var d=document.createDocumentFragment(),g=0;g<c.length;g++){var h=document.createElement("div");h.className="diigo-tag";h.innerText=c[g];d.appendChild(h)}$("#diigobm-recent-tag").append(d)}else $("#diigobm-recent-tag").hide();H(a.myTagsWithCount?a.myTagsWithCount:GlobalData.myTagsWithCount);chrome.storage.local.get("researchModeData",function(e){e.researchModeData?p(e):m()})},k=function(a){var c,d;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){if(1==
g.nextAddress)return g.yield(getStorage("search_type"),2);c=g.yieldResult;if(""==a)return $("#recent-result").hasClass("current")||t("recent"),g.return();$("#search-result").hasClass("current")||t("search");saveStorage("lastSearch",{tab:"search",key:a});$("#search-result-main").hide();$("#search-result-loading").show();"meta"===c?(d="https://www.diigo.com/chrome/meta?what="+encodeURIComponent(a),$("#viewAllLink").attr("data-href","https://www.diigo.com/search?adSScope=my&what="+encodeURIComponent(a))):
(d="https://www.diigo.com/chrome/fulltext?what="+encodeURIComponent(a),$("#viewAllLink").attr("data-href","https://www.diigo.com/search?adSScope=my&what="+encodeURIComponent(a)+"&snapshot=yes"));$("#search-result-iframe").attr({src:d});googleEvent("Chrome extension","do popup search","search");g.jumpToEnd()})},q=function(a,c){"recent"==a?($("#recent-result").addClass("current"),$("#search-result").removeClass("current"),w("recentTab")):"search"==a&&($("#recent-result").removeClass("current"),$("#search-result").addClass("current"),
$("#search-result-main").hide(),$("#search-result-loading").show(),$("#search-input").val(c),"meta"===localStorage.search_type?(a="https://www.diigo.com/chrome/meta?what="+encodeURIComponent(c),$("#viewAllLink").attr("data-href","https://www.diigo.com/search?adSScope=my&what="+encodeURIComponent(c))):(a="https://www.diigo.com/chrome/fulltext?what="+encodeURIComponent(c),$("#viewAllLink").attr("data-href","https://www.diigo.com/search?adSScope=my&what="+encodeURIComponent(c)+"&snapshot=yes")),$("#search-result-iframe").attr({src:a}))},
t=function(a){"recent"===a?($("#search-input").val(""),$("#recent-result").addClass("current rotateSlideIn-r"),$("#search-result").addClass("rotateSlideOut-r"),w("recentTab"),saveStorage("lastSearch",{tab:"recent",key:"null"}),setTimeout(function(){$(".tab").removeClass("rotateSlideIn-r rotateSlideOut-r");$("#search-result").removeClass("current")},1E3)):"search"===a&&($("#search-result").addClass("current rotateSlideIn-l"),$("#recent-result").addClass("rotateSlideOut-l"),setTimeout(function(){$(".tab").removeClass("rotateSlideIn-l rotateSlideOut-l");
$("#recent-result").removeClass("current")},1E3))},w=function(a){$("#recent-result-tab-loading").show();"recentTab"==a?$("#recent-result-iframe").attr({src:"https://www.diigo.com/chrome/items"}):"unreadTab"==a&&$("#recent-result-iframe").attr({src:"https://www.diigo.com/chrome/items?read=no"})},z=function(){var a,c,d,g,h,e,n,r,v;return $jscomp.asyncExecutePromiseGeneratorProgram(function(x){if(1==x.nextAddress)return $("#search-input").on("keydown",function(u){13==u.which&&(u=$("#search-input").val(),
k(u))}).focus(),$("#search-btn").on("click",function(){var u=$("#search-input").val();k(u)}),$("#search-type").on("click",function(u){u.stopPropagation();$("#search-type-switcher").show()}),$("#search-type-switcher").on("click","li",function(){$(this).hasClass("meta")?E("meta"):E("full")}),$(document).on("click",function(){$("#search-type-switcher").hide()}),$("#viewAllLink").on("click",function(){var u=$(this).attr("data-href");chrome.tabs.create({url:u})}),$("#recent-result-tab").on("click",".result-link",
function(){$(".result-link").removeClass("current");$(this).addClass("current");w($(this).attr("id"))}),$("#recent-result-iframe").load(function(){$("#recent-result-tab-loading").hide()}),$("#search-result-iframe").load(function(){$("#search-result-main").show();$("#search-result-loading").hide()}),$("#backLink").off("click").on("click",function(){t("recent")}),a=$jscomp,c=a.makeIterator,x.yield(getStorage(["lastSearch","search_type"]),2);d=c.call(a,x.yieldResult);g=d.next().value;h=d.next().value;
"string"===typeof g&&(g=JSON.parse(g));"recent"==g.tab?q("recent"):"search"==g.tab&&q("search",g.key);e=GlobalData.myTags;n=[];for(r=0;r<e.length;r++)n.push(e[r]);n=removeFromArray("no_tag",n);console.log(n);v={resultsClass:"diigolet ac_results ac_search",data:n,mode:"multiple",multipleSeparator:" ,",id:"diigolet-ac",moveToSelect:!0};try{S=new AutoComplete("#search-input",v)}catch(u){debug(u)}E(h,!0);x.jumpToEnd()})},E=function(a,c){$("#search-type").removeClass("meta full").addClass(a);c||saveStorage("search_type",
a);"meta"===a?S.enable():S.disable();""!=$("#search-input").val()&&k($("#search-input").val())},A=function(a,c){var d,g,h,e,n,r,v;return $jscomp.asyncExecutePromiseGeneratorProgram(function(x){if(1==x.nextAddress)return console.trace(a),d=a.bm,!0===a.generated&&$("#onload").hide(),1==d.saved&&($("#remove").show(),$("#top-bar").find(".top-bar-title").text("Edit bookmark")),$("#remove").attr("data-gtooltip","Saved "+d.datetime+". Click to remove"),void 0!=d?(1!=d.saved&&void 0!=c?$("#diigobm-title-input").val(c):
$("#diigobm-title-input").val(d.title),L($("#diigobm-title-input"),"change"),$("#diigobm-url-input").val(d.url)):getSelectedTab(function(u){$("#diigobm-title-input").val(u.title);L($("#diigobm-title-input"),"change");$("#diigobm-url-input").val(u.url)}),g={},x.yield(getStorage(["prefs.bookmark.privateByDefault","prefs.bookmark.unreadByDefault","openedOutlinerId","prefs.outlinerIcon"]),2);h=x.yieldResult;g["prefs.bookmark.privateByDefault"]=h[0];g["prefs.bookmark.unreadByDefault"]=h[1];g.openedOutlinerId=
h[2];g["prefs.outlinerIcon"]=h[3];2==d.mode&&$("#op-private").prop("checked",!0);0==d.saved&&("true"==g["prefs.bookmark.privateByDefault"]&&$("#op-private").prop("checked",!0),"true"==g["prefs.bookmark.unreadByDefault"]&&$("#op-readlater").prop("checked",!0));1==d.unread&&$("#op-readlater").prop("checked",!0);d.description&&0<d.description.length?($("#diigobm-des-input").text(d.description).trigger("change"),L($("#diigobm-des-input"),"change")):a.selection&&($("#diigobm-des-input").text('"'+a.selection+
'"'),L($("#diigobm-des-input"),"change"));e=ParseTags.unparseTags(d.tags);console.log(e);blank(e)||$("#diigobm-tag-input").val(e+" ");D({list:a.lists,outliners:a.outliners},!1);B(a.groups,!1);K();0==$("#diigobm-recommend-tag").find(".diigo-tag").length&&getSelectedTab(function(u){chrome.tabs.sendMessage(u.id,{name:"getRecommendedTags"})});H(a.myTagsWithCount);chrome.storage.local.get(null,function(u){console.log(u);!0===u.researchMode&&(P=!0,$("#op-focus").prop("checked",!0),$("#top-bar").find(".focus-research-tip").show(),
!1===d.saved&&p(u,d.mode))});g.openedOutlinerId&&"true"==g["prefs.outlinerIcon"]&&(n=g.openedOutlinerId,r=$("#diigobm-list"),v=r.find(".menu-item[data-id="+n+"]").text(),r.find(".content").text(v).attr("data-id",n).end().addClass("inputed"));x.jumpToEnd()})},B=function(a,c){$("#refresh-group").removeClass("processing");var d=a.filter(function(e){return 5>e.access_mode});a=a.filter(function(e){console.log(e.access_mode);return 5<=e.access_mode});var g=$("#diigobm-group").find(".item-container");g.empty();
a.length&&($('<div class="menu-title">Teams</div>').appendTo(g),forEach(a,function(e){var n=M(e.name)?e.displayName+" (shared)":e.displayName;$('<div class="menu-item" data-id="'+e.name+'">'+n+"</div>").on("click",function(){console.log("Click");var r=e.name;void 0!=popCtx.groupTagsDict[r]?J("group",popCtx.groupTagsDict[r]):($("#diigobm-group-tag").show(),getSelectedTab(function(v){chrome.tabs.sendMessage(v.id,{name:"loadGroupTagsDictionary",groupName:r})}))}).appendTo(g)}));d.length&&($('<div class="menu-title">Groups</div>').appendTo(g),
forEach(d,function(e){var n=M(e.name)?e.displayName+" (shared)":e.displayName;$('<div class="menu-item" data-id="'+e.name+'">'+n+"</div>").on("click",function(){console.log("Click");var r=e.name;void 0!=popCtx.groupTagsDict[r]?J("group",popCtx.groupTagsDict[r]):($("#diigobm-group-tag").show(),getSelectedTab(function(v){chrome.tabs.sendMessage(v.id,{name:"loadGroupTagsDictionary",groupName:r})}))}).appendTo(g)}));var h=$("#diigobm-group").find("select").empty().unbind().removeClass("processing");0<
a.length&&(h.append(Utils.dom.buildOne("option",{value:0},["Share to a Team"])),h.append(Utils.dom.buildOne("option",{value:-5},[Array(20).join("-")])),forEach(a,function(e){c?h.append(Utils.dom.buildOne("option",{value:e.name},[e.displayName])):h.append(Utils.dom.buildOne("option",{value:e.name},[e.displayName+(M(e.name)?" (shared)":"")]))}),h.append(Utils.dom.buildOne("option",{value:-5},[Array(20).join("-")])));h.append(Utils.dom.buildOne("option",{value:0},["Share to a Group"]));h.append(Utils.dom.buildOne("option",
{value:-1},[Array(20).join("-")]));$(Utils.dom.buildOne("option",{value:-2},["Create a Group..."])).appendTo(h);h.append(Utils.dom.buildOne("option",{value:-5},[Array(20).join("-")]));forEach(d,function(e){c?h.append(Utils.dom.buildOne("option",{value:e.name},[e.displayName])):h.append(Utils.dom.buildOne("option",{value:e.name},[e.displayName+(M(e.name)?" (shared)":"")]))});h.append(Utils.dom.buildOne("option",{value:-5},[Array(20).join("-")]));$(Utils.dom.buildOne("option",{value:-3},["Refresh"])).appendTo(h);
h.change(function(){var e=h.val();-2==e?(chrome.tabs.create({url:"https://groups.diigo.com/create"}),h.val(-1)):-3==e&&($(this).addClass("processing"),getSelectedTab(function(n){chrome.tabs.sendMessage(n.id,{name:"refreshMyStuff"})}),h.val(-1));0!=e&&-1!=e&&-2!=e&&-3!=e&&($("#diigosc-group-tag").show(),popCtx.isAnnotated&&$("#bottom").find("div:first-child").show(),$("#Diigo-Bookmark-checkShareExisting").show(),console.log(popCtx),void 0!=popCtx.groupTagsDict[e]?J("group",popCtx.groupTagsDict[e]):
($("#diigobm-group-tag").show(),getSelectedTab(function(n){chrome.tabs.sendMessage(n.id,{name:"loadGroupTagsDictionary",groupName:e})})))});h.val(0).change()},D=function(a,c){$("#refresh-outliner").removeClass("processing");c=a.list;a=a.outliners;var d=$("#diigobm-list").find(".item-container");d.empty();a.length&&($('<div class="menu-title">Outliners</div>').appendTo(d),forEach(a,function(g){var h=U(g.id)?g.title+" (added)":g.title;$('<div class="menu-item" data-id="'+g.id+'">'+h+"</div>").appendTo(d)}));
c.length&&($('<div class="menu-title">Lists</div>').appendTo(d),forEach(c,function(g){var h=V(g.id)?g.title+" (added)":g.title;$('<div class="menu-item" data-id="'+g.id+'">'+h+"</div>").appendTo(d)}))},H=function(a){if(0==a.length){var c=document.getElementById("tag-cloud-container");a=document.createElement("div");a.id="no-tag";a.innerHTML="You haven't create any tags yet,:)";c.appendChild(a)}else if(!(0<$("#tag-cloud-container").find("a").length)){var d=T(a);c=d.topTags;var g=d.maxCount;a=d.first;
var h=d.second,e=d.third,n=c.length;d=document.createDocumentFragment();for(var r=0;r<n;r++){var v=document.createElement("a");v.className="Diigo-Bookmark-Tag-item";v.href="#";v.innerText=c[r].name;var x=c[r].count;x==g&&(v.style.fontSize="20px",v.style.fontWeight="bold");a.forEach(function(u){x==u&&(v.style.fontSize="18px",v.style.fontWeight="bold")});h.forEach(function(u){x==u&&(v.style.fontSize="16px",v.style.fontWeight="bold")});e.forEach(function(u){x==u&&(v.style.fontSize="16px",v.style.fontWeight=
"regular")});d.appendChild(v)}c=document.getElementById("tag-cloud-container");c.appendChild(d);$("#tag-cloud-container").on("click","a",function(u){/Diigo\-Bookmark\-Tag\-item/.test(u.target.className)&&O($(this).text())});K()}},T=function(a){var c=[];a.sort(function(n,r){return n.count<=r.count?1:-1});a=a.slice(0,101);var d=a[0].count,g=a.length;a.sort(function(n,r){return n.name.toLowerCase()<=r.name.toLowerCase()?-1:1});for(var h=0;h<g;h++)c[h]=a[h].count;c=arrayUnique(c);g=c.length;c.sort(function(n,
r){return n<r?1:-1});var e=Math.ceil(g/10);g=c.slice(1,1+e);h=c.slice(1+e,1+2*e);c=c.slice(1+2*e,1+3*e);return{topTags:a,maxCount:d,first:g,second:h,third:c}},I=function(){var a=!0,c=$("#diigobm-url-input").val();$("#diigobm-title-input").val().match(/^\s*$/)&&(a=!1,$("#diigobm-title").find(".diigo-alert-tip").show());Q(c)&&!c.match(/^\s*$/)||1!=a||(a=!1,$("#diigobm-url").find(".diigo-alert-tip").show());if(0!=a){a=$("#diigobm-title-input").val();a.match(/^\s*$/)&&(a=popCtx.bm.title);c=$("#diigobm-url-input").val();
if(c.match(/^\s*$/)||!Q(c))c=popCtx.bm.url;var d=$("#diigobm-des-input").val();var g=ParseTags.parseTags($("#diigobm-tag-input").val(),!0);var h=$("#op-private").prop("checked")?2:0;var e=$("#op-readlater").prop("checked")?!0:!1;var n=(n=$("#diigobm-list").find(".content").attr("data-id"))?[n]:[];var r=(r=$("#diigobm-group").find(".content").attr("data-id"))?[r]:[];var v=$("#Diigo-Bookmark-checkShareExisting").find(".op-checkbox-container").hasClass("checked")?!0:!1;var x=$("#op-cache").prop("checked")?
!0:!1;var u={url:c,mode:h,title:a,tags:g,description:d,unread:e,urlId:popCtx.bm.urlId,cache:x,groups:r,shareExistingAnnotations:v,lists:n};getSelectedTab(function(aa){u.tabId=aa.id;chrome.runtime.sendMessage({name:"popupSaveBookmark",data:u},function(){window.close()})})}},Q=function(a){return/^(https|http|ftp|rtsp|mms)+:\/\//.test(a)?!0:!1},M=function(a){return some(popCtx.bm.groups,function(c){return c.name==a})},U=function(a){return some(popCtx.bm.outliners,function(c){return c.id==a})},V=function(a){return some(popCtx.bm.lists,
function(c){return c.id==a})},J=function(a,c){if("recommended"==a){c=c.filter(function(e){return 0<=$.inArray(e,popCtx.mytag)});c=popCtx.lastUsedTags.concat(c);if(0==c.length)return;$("#diigobm-recommend-tag").show();c=arrayUnique(c)}for(var d=document.createDocumentFragment(),g=0;g<c.length;g++){var h=document.createElement("div");h.className="diigo-tag";h.innerText=c[g];$(h).toggleClass("selected",0<=$.inArray(c[g],popCtx.bm.tags));d.appendChild(h)}"recommended"==a?$(d).appendTo($("#diigobm-recommend-tag")):
"group"==a&&($("#diigobm-group-tag").find(".loading").hide(),$("#diigobm-group-tag").find(".diigo-tag").remove(),$(d).appendTo($("#diigobm-group-tag")))},W=function(a,c){a.focus();a.createTextRange?(a=a.createTextRange(),a.move("character",c),a.select()):0<=a.selectionStart&&(a.focus(),a.setSelectionRange(c,c))},X=function(a){var c=a.value.length;setTimeout(function(){W(a,c)},13)},K=function(){var a=$("#diigobm-tag-input"),c=ParseTags.parseTags(a.val(),!0);$("#tag-cloud-container").find(".Diigo-Bookmark-Tag-item").each(function(){var d=
$(this),g=d.text();-1!=$.inArray(g,c)?d.addClass("selected"):d.removeClass("selected")});$("#diigobm-recent-tag, #diigobm-recommend-tag, #diigobm-group-tag").find(".diigo-tag").each(function(){var d=$(this),g=d.text();console.log(g,c);-1!=$.inArray(g,c)?d.addClass("selected"):d.removeClass("selected")})},O=function(a,c){var d=$("#diigobm-tag-input"),g=ParseTags.parseTags(d.val(),!0),h=$.inArray(a,g);void 0===c?0<=h?g.splice(h,1):g.push(a):c?-1==h&&g.push(a):0<=h&&g.splice(h,1);a=ParseTags.unparseTags(g);
a.length&&(a+=" ");d.val(a);X(d[0]);K()},Y=function(a,c){if(!0!==P&&(console.log("updateBookmark",a),1==a.generated)){var d=a.bm;!0===a.unread&&$("#read-later").addClass("unread").text("Mark as Read");$("#onload").hide();1==d.saved&&($("#remove").show(),$("#remove").attr("data-gtooltip","Saved "+d.datetime+". Click to remove"),$("#bookmark-save").text("Edit").addClass("saved"),$("#cached").show().unbind("click").bind("click",function(){getSelectedTab(function(g){var h="https://www.diigo.com/cached?url="+
encodeURIComponent(g.url);chrome.tabs.create({url:h,index:g.index+1})})}));void 0!=d?(console.log(c),1!=d.saved&&c?$("#diigobm-title-input").val(c).trigger("input"):$("#diigobm-title-input").val(d.title).trigger("input"),L($("#diigobm-title-input"),"change"),$("#diigobm-url-input").val(d.url)):getSelectedTab(function(g){$("#diigobm-title-input").val(g.title);$("#diigobm-url-input").val(g.url)});2==d.mode&&$("#op-private").prop("checked",!0);1==d.unread&&$("#op-readlater").prop("checked",!0);a=ParseTags.unparseTags(d.tags);
console.log(a);blank(a)||$("#diigobm-tag-input").val(a+" ")}},L=function(a,c){c=new Event(c);a.dispatchEvent||(a=a[0]);a.dispatchEvent(c)},R=function(a){var c=/\.?diigo\./i.test(a);console.log("isDiigoURL",c);return c&&/\/item\/pdf/i.test(a)||/^https?:\/\/chrome\.google\.com\/(extensions|webstore)/i.test(a)?!1:!0},popCtx={groupTagsDict:{}},P=!1,getSelectedTab(function(a){chrome.action.getBadgeText({tabId:a.id},function(c){"New"==c&&(chrome.action.setBadgeText({text:""}),chrome.runtime.sendMessage({name:"getNewClickVersion"}).then(function(d){saveStorage("newClickVersion",
d).then(function(){chrome.tabs.create({url:"https://blog.diigo.com/2018/03/23/simplified-focused-research/"})})}))})}),G.yield(getStorage("prefs.shortcutOpenOutlinerSidebar prefs.shortcutOpenOutlinerSidebarCtrl prefs.shortcutOpenOutlinerSidebarAlt prefs.shortcutOpenOutlinerSidebarKey gcc_login_send rating".split(" ")),4);if(2!=G.nextAddress)return C=G.yieldResult,"true"==C["prefs.shortcutOpenOutlinerSidebar"]?($("#toggle-outliner").addClass("shortcut"),N="","true"==C["prefs.shortcutOpenOutlinerSidebarCtrl"]&&
(N+="Ctrl + "),"true"==C["prefs.shortcutOpenOutlinerSidebarAlt"]&&(N+="Alt + "),N+=C["prefs.shortcutOpenOutlinerSidebarKey"],$(".shortcut-tip").text(N)):$("#toggle-outliner").removeClass("shortcut"),chrome.storage.local.get("researchMode",function(a){$("#research-mode-checkbox").prop("checked",a?a.researchMode:!1)}),chrome.cookies.get({url:"https://www.diigo.com",name:"diigoandlogincookie"},function(a){var c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(d){if(a){if(!C.gcc_login_send){console.log("111");
if(C.gcc_login_send)return d.return();C.gcc_login_send="true"}c=a.value.split("-.-");if(F=c[1])$("#sign-out-btn").find("span").text("Sign Out ("+F+")"),$("#userInfo").find(".username").text(F).attr("title",F).on("click",function(){});console.timeEnd("cookie");permissions.servicePlanName&&"Free"==permissions.servicePlanName&&$("#userInfo").find(".upgrade").show();console.log(permissions);permissions.snapshot?$("#diigo-acache-field").hide():($("#diigo-acache-field").show(),$("#op-cache")[0].disabled=
!0,$("#op-cache").parent().addClass("disabled"));$("[data-link]").click(function(g){var h=$(this).attr("data-link");if("more"!=h)if("tutorial"===h)getSelectedTab(function(n){chrome.tabs.sendMessage(n.id,{name:"showTutorial"});window.close()});else{switch(h){case "home":var e="https://www.diigo.com/user/"+F;break;case "rating":e="https://chrome.google.com/webstore/detail/diigo-web-collector-captu/pnhplgjpclknigjpccbcnmicgcieojbh/reviews";break;case "unread":e="https://www.diigo.com/user/"+F+"?type=bookmark&read=no";
break;case "my-outliner":e="https://www.diigo.com/outliner";break;case "my-groups":e="https://groups.diigo.com/user/"+F;break;case "option":e=chrome.runtime.getURL("")+"options.html";break;case "changelog":e="https://blog.diigo.com/2017/08/22/introduce-a-new-way-to-retain-knowledge-from-books/";break;case "sign-out-btn":e="https://www.diigo.com/sign-out";break;case "upgrade":e="https://www.diigo.com/premium?f=chrome_ext_menu";googleEvent("Chrome extension","Click upgrade from main menu","Name");chrome.runtime.sendMessage({name:"sendAnalysisData",
data:{gcc_cookie_ad_click_from_extension_old:1}});break;case "feedback":e="/feedback.html"}"feedback"==h?getSelectedTab(function(n){e=e+"?refer="+encodeURIComponent(n.url);chrome.tabs.create({url:e,index:n.index+1})}):getSelectedTab(function(n){"diigo-acache"==h?(console.log("diigo-acache1"),chrome.tabs.sendMessage(n.id,{name:"showMHTMLinfo"}),window.close()):chrome.tabs.create({url:e,index:n.index+1})})}});if(!C.rating)$("#rating").show().on("click",function(){$(this).hide();C.rating=!0});getSelectedTab(function(g){var h=
g.url,e=h.match(/https?:\/\/*\/*/gi);console.log(R(h));null!=e&&R(h)?(chrome.tabs.sendMessage(g.id,{name:"ifbookmark"}),chrome.tabs.sendMessage(g.id,{name:"isOutlinerSidebarOpened"},function(n){n&&n.opened&&$("#toggle-outliner").find(".content").text("Close outliner sidebar")}),console.log("ifbookmark")):$("ul").find("li").not("#annotate-pdf").addClass("disabled").off("click")})}else $("#main").hide(),$("#sign-in").show();d.jumpToEnd()})}),chrome.runtime.onMessage.addListener(function(a,c,d){if("isSaved"==
a.name)d=a.data,!0===d.saved&&($("#save-bookmark").find("span").text("Edit Bookmark").end().addClass("saved"),$("#cached").show().bind("click",function(){getSelectedTab(function(h){var e="https://www.diigo.com/cached?url="+encodeURIComponent(h.url);chrome.tabs.create({url:e,index:h.index+1})})})),!0===d.unread&&$("#read-later").addClass("unread");else if("sendCtx"==a.name)console.log("sendCtx",a.data),getSelectedTab(function(h){console.log(c.tab.id,h.id,c);c.tab.id==h.id&&(popCtx=$.extend(popCtx,
a.data),Y(a.data,h.title))});else if("sendRetags"==a.name)console.log(a.data),J("recommended",a.data);else if("sendGtags"==a.name)console.log(a.data),J("group",a.data);else if("popupclose"==a.name)window.close();else if("shownew"==a.name)window.close();else if("updateLists"==a.name)D(a.data);else if("updateGroups"==a.name)B(a.data);else if("updateGroupTag"==a.name)popCtx.groupTagsDict=a.data,d=$("#diigobm-group").find(".content").attr("data-id"),console.log(d),J("group",popCtx.groupTagsDict[d]);else if("listCreateSuccessAndUpdateLists"==
a.name){D({list:a.lists,outliners:a.outliners});d=a.newlist;var g=$("#diigobm-list");g.find(".content").text(d.title).attr("data-id",d.id);g.removeClass("focused");g.find(".add-box").hide().find("input").val("");g.find(".search-box").show()}else"listCreateFailureAndUpdateLists"==a.name&&$("#diigobm-list-addBtn").parent().removeClass("processing")}),$("#sign-in-btn").click(function(){window.open("https://www.diigo.com/sign-in?referInfo="+encodeURIComponent("/images/diigo-logo.png#SIGNED_IN"))}),$("#sign-up-btn").click(function(){var a=
"https://www.diigo.com/account/thirdparty/openid?openid_url=https://www.google.com/accounts/o8/id&redirect_url="+encodeURIComponent("https://www.diigo.com/chrome_diigo_extension_done")+"&request_from=chrome_diigo_extension";window.open(a)}),$("#bookmark").on("click","div",function(a){switch(a.target.id){case "bookmark-save":getSelectedTab(function(c){c.url.substring(c.url.length-4);b(c.id);$("#main").hide();$("#bm-main").show();chrome.tabs.sendMessage(c.id,{name:"makeSnapshot"});chrome.tabs.sendMessage(c.id,
{name:"getMhtml",tabId:c.id});f(!1);A(popCtx,c.title)});break;case "bookmark-annotate":chrome.runtime.sendMessage({name:"showToolbar"}),window.close()}}),$("#bookmark-annotate").hover(function(){$(this).parent().addClass("annotate-hover")},function(){$(this).parent().removeClass("annotate-hover")}),$("#bookmark-save").hover(function(){$(this).parent().addClass("tag-hover")},function(){$(this).parent().removeClass("tag-hover")}),$("li").on("click","b",function(){$(this).parent().trigger("click")}),
$("#toggle-outliner").on("click",function(){getSelectedTab(function(a){injectScriptToTab(a.id,["js/checkTab.js"],function(){});chrome.tabs.sendMessage(a.id,{name:"toggleOutlinerSidebar"});setTimeout(function(){window.close()})})}),$("#save-bookmark").on("click",function(){$(this).hasClass("disabled")||getSelectedTab(function(a){a.url.substring(a.url.length-4);b(a.id);$("#main").hide();$("#bm-main").show();getSelectedTab(function(c){chrome.tabs.sendMessage(c.id,{name:"makeSnapshot"});chrome.tabs.sendMessage(c.id,
{name:"getMhtml",tabId:c.id})});f();A(popCtx,a.title)})}),$("ul").on("click","li",function(a){a=a.target.id;var c=$(this).parent().hasClass("disabled");switch(a){case "annotate-article":getSelectedTab(function(d){injectScriptToTab(d.id,["js/checkTab.js"],function(){});chrome.tabs.sendMessage(d.id,{name:"annotate"})});window.close();break;case "read-later":getSelectedTab(function(d){b(d.id);var g=$("#read-later").hasClass("unread")?!0:!1;chrome.tabs.sendMessage(d.id,{name:"readlater",ifUnread:g});
console.log("readlater");window.close()});break;case "screenshot":if(c)break;getSelectedTab(function(d){b(d.id);chrome.tabs.sendMessage(d.id,{name:"screenshot"});window.close();console.log("send")});break;case "annotate-image":if(c)break;getSelectedTab(function(d){b(d.id);chrome.tabs.sendMessage(d.id,{name:"screenshot"});window.close();console.log("send")});break;case "screenshot-visible":chrome.extension.sendRequest({action:"visible"});window.close();break;case "screenshot-selected":chrome.extension.sendRequest({action:"selected"});
window.close();break;case "screenshot-entire":chrome.extension.sendRequest({action:"entire"});window.close();break;case "annotate-pdf":getSelectedTab(function(d){".pdf"==d.url.substring(d.url.length-4)?chrome.tabs.create({url:"/pdf/viewer.html?file="+d.url}):chrome.tabs.create({url:"/pdf/viewer.html"})});break;case "share":if(c)break;getSelectedTab(function(d){b(d.id);chrome.tabs.sendMessage(d.id,{name:"share"});window.close()});break;case "research-mode":if(c)break;$("#main").hide();$("#bm-main").show();
P=!0;f(!0);y(popCtx);break;case "search":$("#main").hide(),$("#search-main").show(),z(),googleEvent("Chrome extension","click popup search","search"),window.addEventListener("message",function(d){console.log(d.data);var g=d.data.action;if("openUrl"==g){var h=d.data.url;getSelectedTab(function(e){d.data.ctrl?chrome.tabs.create({url:h,active:!1}):chrome.tabs.create({url:h})})}else"searchTag"==g&&(g=-1!=d.data.tag.indexOf(" ")?'#"'+d.data.tag+'"':"#"+d.data.tag,$("#search-input").val(g),$("#search-btn").trigger("click"))},
!1)}}),$("#search").on("click",function(){$("#main").hide();$("#search-main").show();z();googleEvent("Chrome extension","click popup search","search");window.addEventListener("message",function(a){console.log(a.data);var c=a.data.action;if("openUrl"==c){var d=a.data.url;getSelectedTab(function(g){a.data.ctrl?chrome.tabs.create({url:d,active:!1}):chrome.tabs.create({url:d})})}else"searchTag"==c&&(c=-1!=a.data.tag.indexOf(" ")?'#"'+a.data.tag+'"':"#"+a.data.tag,$("#search-input").val(c),$("#search-btn").trigger("click"))},
!1)}),$("#share").on("click",function(){$(this).hasClass("disbaled")||getSelectedTab(function(a){b(a.id);chrome.tabs.sendMessage(a.id,{name:"share"});window.close()})}),$("#read-later").on("click",function(){$(this).hasClass("disbaled")||getSelectedTab(function(a){b(a.id);var c=$("#read-later").hasClass("unread")?!0:!1;chrome.tabs.sendMessage(a.id,{name:"readlater",ifUnread:c});console.log("readlater");window.close()})}),$("#action #more").on("click",function(){$(this).parents(".bottom-area").toggleClass("unfold")}),
$("#screenshot-main").find(".back").on("click",function(){$("#screenshot-main").hide();$("#main").show()}),$("#tag-edit").on("click",function(){chrome.tabs.create({url:"https://www.diigo.com/cloud/"+F})}),$("#remove").on("click",function(){getSelectedTab(function(a){chrome.tabs.sendMessage(a.id,{name:"qdeletebookmark"});window.close()})}),$("#show-url").on("click",function(){$("#diigobm-url-input").toggle()}).Gtooltip({position:"top"}),$("#tag-cloud-icon").on("click",function(){$("#tag-cloud").toggle()}),
$("#research-mode-checkbox").on("change",function(){$(this).prop("checked")&&!GlobalData.permissions.autoShowAnnotation?($(this).prop("checked",!1),chrome.tabs.create({url:"researchMode.html"})):(chrome.storage.local.set({researchMode:$(this).prop("checked")}),$(this).prop("checked")&&chrome.storage.local.get("researchModeData",function(a){"undefined"===typeof a.researchModeData&&($(this).prop("checked",!1),$("#main").hide(),$("#bm-main").show(),f(!0),y(popCtx))}))}),G.leaveTryBlock(0);Z=G.enterCatchBlock();
console.error(Z);G.jumpToEnd()})}initPopup();
