var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in d))return;d=d[g]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(d,e,{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");
window.addEventListener("message",function(a){a=a.data;var b=a.data;"processFinish"==a.type?(window._DIIGO_CACHE={originUrl:b.url,originUser:"luokebi",charset:"utf-8"},$("#entry-content").html(b.content),$("#article_original_link").find("a").text(b.host).attr("href",b.url),$("title").text(b.title),$("#title").text(b.title),$(".top-bar").find(".title").text(b.title),runDiigolet(),$("pre").each(function(c,d){hljs.highlightBlock(d)}),$(window).on("scroll",function(){document.body.scrollTop>$("#title").offset().top+
$("#title").height()?$(".top-bar").find(".title").addClass("show"):$(".top-bar").find(".title").removeClass("show")}),window.parent.postMessage({type:"processFinish"},"*")):"processStart"!=a.type&&("doc_html"==a.type?document.getElementById("process-frame").contentWindow.postMessage({type:"doc_html",html:b.html,uri:b.uri,title:b.title},"*"):"event"==a.type?console.log(b.e):"processFailed"==a.type&&window.parent.postMessage({type:"processFailed"},"*"));localStorage.readability_guide||(Guide.show(),
localStorage.readability_guide="true")});
$(document).ready(function(){function a(){$(".reader-area").show();$(".save-area").hide();$(".top-bar").hide();chrome.tabs.getSelected(function(c){chrome.pageCapture.saveAsMHTML({tabId:c.id},function(d){var e=window.URL.createObjectURL(d);chrome.permissions.request({permissions:["downloads"]},function(f){f&&chrome.downloads.download({url:e,filename:$("#title").text()+".mhtml",saveAs:!0},function(){$(".reader-area").hide();$(".save-area").show();$(".top-bar").show();URL.revokeObjectURL(e)})})})})}
function b(){var c={filename:document.title+".read",contentType:"application/json",url:window._DIIGO_CACHE.originUrl,blob:JSON.stringify({title:document.title,url:window._DIIGO_CACHE.originUrl,content:$(".left").find("#readability-content")[0].outerHTML})};Web.getCommonSharableLink(c).then(function(d){},function(d){console.log(d)})}$("#print").on("click",function(){$(".top-bar").hide();window.print();$(".top-bar").show()});$("#saveMHTML").on("click",function(){$(".top-bar").hide();chrome.tabs.getSelected(function(c){chrome.pageCapture.saveAsMHTML({tabId:c.id},
function(d){d=window.URL.createObjectURL(d);var e=document.createElement("a");e.download=$("#title").text()+".mhtml";e.href=d;e.click();$(".top-bar").show()})})});$("#done").on("click",function(){$(".save-area .left").empty().html($("#readability-content")[0].outerHTML);$(".reader-area").hide();$(".save-area").show()});$(".action-list").find("a").on("click",function(c){c.preventDefault();switch($(this).attr("data-action")){case "reEdit":$(".reader-area").show();$(".save-area").hide();break;case "share":b();
break;case "download":a();break;case "print":$(".reader-area").show(),$(".save-area").hide(),window.print(),$(".reader-area").hide(),$(".save-area").show()}});$("#close").on("click",function(){window.history.back()});$("#open-outliner").on("click",function(){$("body").toggleClass("outliner-open")})});
