var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var e=a.length,d=0;d<e;d++){var f=a[d];if(b.call(c,f,d,a))return{i:d,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,e){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,e):$jscomp.polyfillUnisolated(a,b,c,e))};$jscomp.polyfillUnisolated=function(a,b,c,e){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];if(!(d in c))return;c=c[d]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,e){var d=a.split(".");a=1===d.length;e=d[0];e=!a&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<d.length-1;f++){var g=d[f];if(!(g in e))return;e=e[g]}d=d[d.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?e[d]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+d,d=
$jscomp.propertyToPolyfillSymbol[d],$jscomp.defineProperty(e,d,{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");var editor=null;
function editor_style_callback(a,b){switch(a){case "crop":"done"!==b&&($("#crop-dimension").show(),$("#cd-width").val(b.width),$("#cd-height").val(b.height));break;case "undo":sendMessage({type:"canUndo",canUndo:b});break;case "redo":$('.single-btn[data-action="redo"]').toggleClass("disabled",!b);break;case "del":$('.single-btn[data-action="deleteSelected"]').toggleClass("disabled",!b);break;case "clear":$('.single-btn[data-action="clear"]').toggleClass("disabled",b)}}
function initEditor(a,b){var c=$("#editor-outer-container"),e=c.find(".editor-container"),d=c.find(".doodle-canvas"),f=c.find(".layer-canvas"),g=c.find(".editor-outer-textarea"),k=c.find(".editor-textarea"),l=c.find(".editor-list-dialog"),h=new Image;editor=new Diigo.Doodle._Drawer({out_container:c[0],container:e[0],doodle_canvas:d[0],layer_canvas:f[0],textarea:k[0],textarea_out:g[0],$list_dialog:l,image:h},function(m,n){editor_style_callback(m,n)});h.src=a;h.onload=function(){editor.setBgImage(h,
!1);editor.setPenColor("#f00");editor.setPenType("curve");b&&editor.setPenType(b)}}function sendMessage(a){window.parent.postMessage(a,"*")}
window.addEventListener("message",function(a){"init"==a.data.type?initEditor(a.data.dataUrl,a.data.initTool):"changeTool"==a.data.type?editor.setPenType(a.data.tool):"changeColor"==a.data.type?editor.setPenColor(a.data.color):"undo"==a.data.type?editor.undo():"changeFontSize"==a.data.type?editor.setFontSize(a.data.size):"saveWithTag"==a.data.type?(a=editor.getImageDataURL(),sendMessage({type:"saveWithTag",dataURL:a})):"saveAttach"==a.data.type&&(a=editor.getImageDataURL(),sendMessage({type:"saveAttach",
dataURL:a}));sendMessage({type:"canUndo",canUndo:editor.history.canUndo()})});
