var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,f){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,f):$jscomp.polyfillUnisolated(a,b,c,f))};
$jscomp.polyfillUnisolated=function(a,b,c,f){c=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var d=a[f];if(!(d in c))return;c=c[d]}a=a[a.length-1];f=c[a];b=b(f);b!=f&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,f){var d=a.split(".");a=1===d.length;f=d[0];f=!a&&f in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var k=0;k<d.length-1;k++){var e=d[k];if(!(e in f))return;f=f[e]}d=d[d.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?f[d]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+d,d=
$jscomp.propertyToPolyfillSymbol[d],$jscomp.defineProperty(f,d,{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.generator={};
$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};
$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};
$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};
$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var c=a.next();$jscomp.generator.ensureIteratorResultIsObject_(c);if(c.done)this.yieldResult=c.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(c.value,b)};$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};
$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(c){return{value:c,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var f=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(f);if(!f.done)return this.context_.stop_(),f;var d=f.value}catch(k){return this.context_.yieldAllIterator_=null,this.context_.throw_(k),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,d);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(f){return a.next(f)}function c(f){return a.throw(f)}return new Promise(function(f,d){function k(e){e.done?f(e.value):Promise.resolve(e.value).then(b,c).then(k,d)}k(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.initSymbol=function(){};$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(d,k){this.$jscomp$symbol$id_=d;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:k})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c=0,f=function(d){if(this instanceof f)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(d||"")+"_"+c++,d)};return f},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var f=$jscomp.global[b[c]];"function"===typeof f&&"function"!=typeof f.prototype[a]&&$jscomp.defineProperty(f.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(e){return e instanceof d?e:new d(function(g,h){g(e)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(e){if(null==this.batch_){this.batch_=[];var g=this;this.asyncExecuteFunction(function(){g.executeBatch_()})}this.batch_.push(e)};var f=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(e){f(e,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var e=
this.batch_;this.batch_=[];for(var g=0;g<e.length;++g){var h=e[g];e[g]=null;try{h()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(e){this.asyncExecuteFunction(function(){throw e;})};var d=function(e){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var g=this.createResolveAndReject_();try{e(g.resolve,g.reject)}catch(h){g.reject(h)}};d.prototype.createResolveAndReject_=function(){function e(l){return function(m){h||(h=!0,l.call(g,m))}}var g=this,h=!1;
return{resolve:e(this.resolveTo_),reject:e(this.reject_)}};d.prototype.resolveTo_=function(e){if(e===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(e instanceof d)this.settleSameAsPromise_(e);else{a:switch(typeof e){case "object":var g=null!=e;break a;case "function":g=!0;break a;default:g=!1}g?this.resolveToNonPromiseObj_(e):this.fulfill_(e)}};d.prototype.resolveToNonPromiseObj_=function(e){var g=void 0;try{g=e.then}catch(h){this.reject_(h);return}"function"==typeof g?
this.settleSameAsThenable_(g,e):this.fulfill_(e)};d.prototype.reject_=function(e){this.settle_(2,e)};d.prototype.fulfill_=function(e){this.settle_(1,e)};d.prototype.settle_=function(e,g){if(0!=this.state_)throw Error("Cannot settle("+e+", "+g+"): Promise already settled in state"+this.state_);this.state_=e;this.result_=g;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var e=0;e<this.onSettledCallbacks_.length;++e)k.asyncExecute(this.onSettledCallbacks_[e]);
this.onSettledCallbacks_=null}};var k=new b;d.prototype.settleSameAsPromise_=function(e){var g=this.createResolveAndReject_();e.callWhenSettled_(g.resolve,g.reject)};d.prototype.settleSameAsThenable_=function(e,g){var h=this.createResolveAndReject_();try{e.call(g,h.resolve,h.reject)}catch(l){h.reject(l)}};d.prototype.then=function(e,g){function h(n,p){return"function"==typeof n?function(q){try{l(n(q))}catch(r){m(r)}}:p}var l,m,t=new d(function(n,p){l=n;m=p});this.callWhenSettled_(h(e,l),h(g,m));return t};
d.prototype.catch=function(e){return this.then(void 0,e)};d.prototype.callWhenSettled_=function(e,g){function h(){switch(l.state_){case 1:e(l.result_);break;case 2:g(l.result_);break;default:throw Error("Unexpected state: "+l.state_);}}var l=this;null==this.onSettledCallbacks_?k.asyncExecute(h):this.onSettledCallbacks_.push(h)};d.resolve=c;d.reject=function(e){return new d(function(g,h){h(e)})};d.race=function(e){return new d(function(g,h){for(var l=$jscomp.makeIterator(e),m=l.next();!m.done;m=l.next())c(m.value).callWhenSettled_(g,
h)})};d.all=function(e){var g=$jscomp.makeIterator(e),h=g.next();return h.done?c([]):new d(function(l,m){function t(q){return function(r){n[q]=r;p--;0==p&&l(n)}}var n=[],p=0;do n.push(void 0),p++,c(h.value).callWhenSettled_(t(n.length-1),m),h=g.next();while(!h.done)})};return d},"es6","es3");
var TwitterOAuth={URL_OAUTH_BASE:"https://api.twitter.com/oauth/",URL_API_BASE:"https://api.twitter.com/1.1/",comsuerKey:"jPjTPeXVlxhx5Zqw3uTmGw",consumerSecret:"eLOSDUs7aHHn4p1ocSYz2xRUVNUfkDSjtf2DQlKUY",init:function(){var a=this;a.reset();a.tabUpdatededListener=function(){return a.onTabUpdated.apply(a,[].slice.call(arguments))}},onTabUpdated:function(a,b,c){this.oauthPinTab&&this.oauthPinTab.id==a&&"complete"==b.status&&/twitter.com\/oauth\/authorize$/.test(c.url)&&(debug("[Twitter OAuth PIN tab completed loading]"),
this.grabPin())},makeRequest:function(a){var b=this,c={method:a.method||"POST",action:(a.oauth?b.URL_OAUTH_BASE:b.URL_API_BASE)+a.url,parameters:{oauth_signature_method:"HMAC-SHA1",oauth_consumer_key:b.comsuerKey}},f={consumerSecret:b.consumerSecret,tokenSecret:b.oauth_token_secret};b.oauth_token&&OAuth.setParameter(c,"oauth_token",b.oauth_token);if(a.params)for(var d in a.params)OAuth.setParameter(c,d,a.params[d]);OAuth.completeRequest(c,f);fetch(c.action+"?"+new URLSearchParams(OAuth.getParameterMap(c.parameters)),
{method:c.method}).then(function(k){return k.text()}).then(function(k){a.successCallback&&a.successCallback.call(b,k)}).catch(function(k){a.errorCallback&&a.errorCallback.call(b,k)})},getRequestToken:function(){var a=this;a.reset();a.makeRequest({url:"request_token",oauth:!0,method:"GET",successCallback:function(b){var c=OAuth.getParameterMap(b);if(!["oauth_token","oauth_token_secret"].every(function(f){return!!c[f]}))return error("[oauth request token error]. data not correct",b),null;a.oauth_token=
c.oauth_token;a.oauth_token_secret=c.oauth_token_secret;chrome.tabs.create({url:a.URL_OAUTH_BASE+"authorize?oauth_token="+a.oauth_token,selected:!0},function(f){a.oauthPinTab=f;chrome.tabs.onUpdated.addListener(a.tabUpdatededListener)})},errorCallback:function(b){error("[oauth request_token] failed",b);this.reset()}})},getAccessToken:function(a,b){var c=this;debug("[oauth] got pin",a);a?(chrome.tabs.remove(b),chrome.tabs.update(D.switchToTabIdAfterTwitterOauth,{selected:!0}),c.makeRequest({url:"access_token",
method:"POST",oauth:!0,params:{oauth_verifier:a},successCallback:function(f){var d=OAuth.getParameterMap(f);["oauth_token","oauth_token_secret","user_id","screen_name"].every(function(k){return!!d[k]})?(c.oauth_token=d.oauth_token,c.oauth_token_secret=d.oauth_token_secret,c.user_id=d.user_id,c.screen_name=d.screen_name,c.authenticated=!0,c.storeOauthInfo(),forEachWebTab(function(k){Messenger.send(k.id,{name:"twitterSignIn",details:{screen_name:c.screen_name}})})):(error("[oauth access_token] failed",
f),c.reset())},errorCallback:function(f){error("[oauth access_token] failed",f);this.reset()}})):(alert("Authentication with twitter failed!"),c.reset())},grabPin:function(){var a=this;setTimeout(function(){chrome.scripting.executeScript({target:{tabId:a.oauthPinTab.id},files:["js/twitterGrabPin.js"]})},500);chrome.tabs.onUpdated.removeListener(a.tabUpdatededListener)},reset:function(){this.oauthPinTab=this.oauth_token_secret=this.oauth_token=null;chrome.tabs.onUpdated.removeListener(this.tabUpdatededListener)},
changeUser:function(){this.reset();this.clearStoredOauthInfo();forEachWebTab(function(a){Messenger.send(a.id,{name:"twitterSignOut",details:{}})});this.getRequestToken()},storeOauthInfo:function(){Prefs.setUserData({twitterOauth:this.rot13(btoa(JSON.stringify({oauth_token:this.oauth_token,oauth_token_secret:this.oauth_token_secret,user_id:this.user_id,screen_name:this.screen_name})))})},rot13:function(a){return a.replace(/[a-zA-Z]/g,function(b){return String.fromCharCode(("Z">=b?90:122)>=(b=b.charCodeAt(0)+
13)?b:b-26)})},loadOauthInfo:function(){var a=this,b,c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){if(1==f.nextAddress)return b=a,f.yield(Prefs.getUserData("twitterOauth"),2);c=f.yieldResult;console.log("twitter oauth",c);if(c)try{c=JSON.parse(atob(b.rot13(c)));if(!["oauth_token","oauth_token_secret","user_id","screen_name"].every(function(d){return!!c[d]}))return error("error loading oauth info from storage. data not correct",c),f.return(null);b.oauth_token=c.oauth_token;b.oauth_token_secret=
c.oauth_token_secret;b.user_id=c.user_id;b.screen_name=c.screen_name;console.log("twitter",c);return f.return(c)}catch(d){error("error loading oauth info from storage",d)}return f.return(null)})},clearStoredOauthInfo:function(){Prefs.removeUserData("twitterOauth")},checkAuthentication:function(){var a=this;return a.oauth_token?{screen_name:a.screen_name}:a.loadOauthInfo().then(function(){return{screen_name:a.screen_name}})},API_statuses_home_timeline:function(){this.makeRequest({url:"statuses/home_timeline.json",
method:"GET",params:{count:3},successCallback:function(a){debug("[twitter home timeline]",a)}})},API_friendships_exists:function(){this.makeRequest({url:"friendships/exists.json",method:"GET",params:{user_a:this.screen_name,user_b:"diigo"},successCallback:function(a){debug("[twitter friendships_exists]",a)}})},updateStatus:function(a,b){this.API_statuses_update(a,b)},API_statuses_update:function(a,b){this.makeRequest({url:"statuses/update.json",method:"POST",params:{status:a.status},successCallback:function(c){debug("[twitter statuses_update]",
c);b(c)},errorCallback:function(c){b(null)}})}};
