var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var d=0;return function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var d="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return d?d.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var d=0;d<a.length;++d){var e=a[d];if(e&&e.Math==Math)return e}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,e){if(a==Array.prototype||a==Object.prototype)return a;a[d]=e.value;return a};$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";
var $jscomp$lookupPolyfilledValue=function(a,d){var e=$jscomp.propertyToPolyfillSymbol[d];if(null==e)return a[d];e=a[e];return void 0!==e?e:a[d]};$jscomp.polyfill=function(a,d,e,g){d&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,d,e,g):$jscomp.polyfillUnisolated(a,d,e,g))};
$jscomp.polyfillUnisolated=function(a,d,e,g){e=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var c=a[g];if(!(c in e))return;e=e[c]}a=a[a.length-1];g=e[a];d=d(g);d!=g&&null!=d&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:d})};
$jscomp.polyfillIsolated=function(a,d,e,g){var c=a.split(".");a=1===c.length;g=c[0];g=!a&&g in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var l=0;l<c.length-1;l++){var b=c[l];if(!(b in g))return;g=g[b]}c=c[c.length-1];e=$jscomp.IS_SYMBOL_NATIVE&&"es6"===e?g[c]:null;d=d(e);null!=d&&(a?$jscomp.defineProperty($jscomp.polyfills,c,{configurable:!0,writable:!0,value:d}):d!==e&&($jscomp.propertyToPolyfillSymbol[c]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(c):$jscomp.POLYFILL_PREFIX+c,c=
$jscomp.propertyToPolyfillSymbol[c],$jscomp.defineProperty(g,c,{configurable:!0,writable:!0,value:d})))};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function d(){this.batch_=null}function e(b){return b instanceof c?b:new c(function(f,h){f(b)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;d.prototype.asyncExecute=function(b){if(null==this.batch_){this.batch_=[];var f=this;this.asyncExecuteFunction(function(){f.executeBatch_()})}this.batch_.push(b)};var g=$jscomp.global.setTimeout;d.prototype.asyncExecuteFunction=function(b){g(b,0)};d.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var b=
this.batch_;this.batch_=[];for(var f=0;f<b.length;++f){var h=b[f];b[f]=null;try{h()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};d.prototype.asyncThrow_=function(b){this.asyncExecuteFunction(function(){throw b;})};var c=function(b){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var f=this.createResolveAndReject_();try{b(f.resolve,f.reject)}catch(h){f.reject(h)}};c.prototype.createResolveAndReject_=function(){function b(k){return function(m){h||(h=!0,k.call(f,m))}}var f=this,h=!1;
return{resolve:b(this.resolveTo_),reject:b(this.reject_)}};c.prototype.resolveTo_=function(b){if(b===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof c)this.settleSameAsPromise_(b);else{a:switch(typeof b){case "object":var f=null!=b;break a;case "function":f=!0;break a;default:f=!1}f?this.resolveToNonPromiseObj_(b):this.fulfill_(b)}};c.prototype.resolveToNonPromiseObj_=function(b){var f=void 0;try{f=b.then}catch(h){this.reject_(h);return}"function"==typeof f?
this.settleSameAsThenable_(f,b):this.fulfill_(b)};c.prototype.reject_=function(b){this.settle_(2,b)};c.prototype.fulfill_=function(b){this.settle_(1,b)};c.prototype.settle_=function(b,f){if(0!=this.state_)throw Error("Cannot settle("+b+", "+f+"): Promise already settled in state"+this.state_);this.state_=b;this.result_=f;this.executeOnSettledCallbacks_()};c.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var b=0;b<this.onSettledCallbacks_.length;++b)l.asyncExecute(this.onSettledCallbacks_[b]);
this.onSettledCallbacks_=null}};var l=new d;c.prototype.settleSameAsPromise_=function(b){var f=this.createResolveAndReject_();b.callWhenSettled_(f.resolve,f.reject)};c.prototype.settleSameAsThenable_=function(b,f){var h=this.createResolveAndReject_();try{b.call(f,h.resolve,h.reject)}catch(k){h.reject(k)}};c.prototype.then=function(b,f){function h(n,p){return"function"==typeof n?function(q){try{k(n(q))}catch(r){m(r)}}:p}var k,m,t=new c(function(n,p){k=n;m=p});this.callWhenSettled_(h(b,k),h(f,m));return t};
c.prototype.catch=function(b){return this.then(void 0,b)};c.prototype.callWhenSettled_=function(b,f){function h(){switch(k.state_){case 1:b(k.result_);break;case 2:f(k.result_);break;default:throw Error("Unexpected state: "+k.state_);}}var k=this;null==this.onSettledCallbacks_?l.asyncExecute(h):this.onSettledCallbacks_.push(h)};c.resolve=e;c.reject=function(b){return new c(function(f,h){h(b)})};c.race=function(b){return new c(function(f,h){for(var k=$jscomp.makeIterator(b),m=k.next();!m.done;m=k.next())e(m.value).callWhenSettled_(f,
h)})};c.all=function(b){var f=$jscomp.makeIterator(b),h=f.next();return h.done?e([]):new c(function(k,m){function t(q){return function(r){n[q]=r;p--;0==p&&k(n)}}var n=[],p=0;do n.push(void 0),p++,e(h.value).callWhenSettled_(t(n.length-1),m),h=f.next();while(!h.done)})};return c},"es6","es3");
$.ajaxTransport("+binary",function(a,d,e){if(window.FormData&&(a.dataType&&"binary"==a.dataType||a.data&&(window.ArrayBuffer&&a.data instanceof ArrayBuffer||window.Blob&&a.data instanceof Blob)))return{send:function(g,c){var l=new XMLHttpRequest;g=a.url;var b=a.type,f=a.responseType||"blob",h=a.data||null;l.addEventListener("load",function(){var k={};k[a.dataType]=l.response;c(l.status,l.statusText,k,l.getAllResponseHeaders())});l.open(b,g,!0);l.responseType=f;l.send(h)},abort:function(){e.abort()}}});
var Web={getCommonSharableLink:function(a){var d=this,e="",g="";return d.getUploadUrl(a).then(function(c){e=c.VisitUrl;g=c.Id;return d.uploadFile(c.PresignedUrl,a.contentType,a.blob)}).then(function(){$.get("https://www.diigo.com/share_annotation/success?id="+g);return e},function(){$.get("https://www.diigo.com/share_annotation/failed?id="+g)})},getPDFSharableLink:function(a){var d=this;return this.getUploadUrl(a).then(function(e){return d.uploadPDF(e,a.blob,a.bm)})},getUploadUrl:function(a){var d=
{fileName:a.filename,contentType:a.contentType};a.url&&(d.url=a.url);a.title&&(d.title=a.title);return new Promise(function(e,g){$.ajax({type:"GET",url:"https://www.diigo.com/share_annotation/presign",data:d,dataType:"json",success:function(c){e(c)},error:function(){g("Get upload url error")}})})},uploadFile:function(a,d,e){return new Promise(function(g,c){$.ajax({type:"PUT",url:a,headers:{"Content-Type":d,"content-encoding":"utf-8","x-amz-meta-key":"REPLACE"},data:e,processData:!1,success:function(l){g(l)},
error:function(){c("Upload file error")}})})},downloadAnnotatedPdf:function(a){return new Promise(function(d,e){var g=new FormData;g.append("ann",a.ann);g.append("name",a.name);g.append("pdf",a.file);$.ajax({type:"POST",url:"https://www.diigo.com/share_annotation/pdfwithann",data:g,dataType:"binary",processData:!1,contentType:!1,success:function(c){d(c)},error:function(c){e(c)}})})},uploadPDF:function(a,d,e){var g=a.AnnPresignedUrl;return Promise.all([this.uploadFile(a.PresignedUrl,"application/pdf",
d),this.uploadFile(g,"application/json",e)]).then(function(c,l){$.get("https://www.diigo.com/share_annotation/success?id="+a.Id);return a.VisitUrl},function(){$.get("https://www.diigo.com/share_annotation/failed?id="+a.Id);reject("Upload pdf error")})},createList:function(a){return new Promise(function(d,e){Bg.WebAPI.createList(a,function(g){d(g)})})},refreshStuff:function(){return new Promise(function(a,d){Bg.WebAPI.refreshStuff(function(e){a(e)})})}};
