#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X

# Check if the HDMI monitor is connected
if [[ $(xrandr -q | grep "HDMI-2 connected") ]]; then
    # External monitor is connected
    xrandr --output eDP-1 --auto --output HDMI-2 --auto --same-as eDP-1
    bspc monitor eDP-1 -d I II III IV
    bspc monitor HDMI-2 -d V VI VII VIII IX X
else
    # Only the laptop monitor is connected
    xrandr --output eDP-1 --auto --output HDMI-2 --off
    bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
