var UI={},Util={},BG=chrome.extension.getBackgroundPage();
UI.BuildHtml=function(){LoadAllItems(function(b,a){var c=a.rows,e=c.length;b=[];for(a=0;a<e;a++){var d=c.item(a);if(1==d.enable)b.push(d);else{var f='<li data-id="'+d.id+'"><img src="'+d.icondataurl+'" />'+d.name+"<span></span></li>";$("#"+d.category+"_section ul").append(f)}}c=JSON.parse(localStorage.customize_sort_id);console.log(c);for(a=0;a<c.length;a++)for(k in b)if(b[k].id==c[a]){f='<li data-id="'+b[k].id+'" ><img src="'+b[k].icondataurl+'" />'+b[k].name+"<span>Remove</span></li>";$("#list_sortable").append(f);
break}console.log("html build OK");UI.BuildUIFunction()})};
UI.BuildItem=function(b){LoadItemById(b,function(a,c){a=c.rows.item(0);if(1==a.enable)c='<li data-id="'+a.id+'" ><img src="'+a.icondataurl+'" />'+a.name+"<span>Remove</span></li>",$("#list_sortable").append(c);else if("customize"==a.category)DeleteItemFromId(b,function(d,f){});else{c='<li data-id="'+a.id+'"><img src="'+a.icondataurl+'" />'+a.name+"<span></span></li>";var e=$("#list_ecommod div").index($("#"+a.category+"_section"));$("#list_ecommod").accordion("option","active",e);$("#"+a.category+
"_section ul").append(c)}UI.Sort()})};UI.BuildUIFunction=function(){$("#list_sortable").sortable({stop:UI.Sort});$("#list_ecommod").accordion({autoHeight:!1});UI.BindFunction()};UI.Sort=function(b,a){SortArray=[];$.each($("#list_sortable li"),function(c){SortArray.push($(this).attr("data-id"))});localStorage.customize_sort_id=JSON.stringify(SortArray);BG.util.CreateContextMenu()};
UI.BindFunction=function(){$("#list_sortable li span").live("click",function(b){if(1!=$("#list_sortable li").length){var a=$(this).parent(),c=a.attr("data-id");ModifyEnable(parseInt(c),0,function(e,d){a.remove();UI.BuildItem(parseInt(c))})}});$("#list_ecommod ul li span").live("click",function(b){var a=$(this).parent(),c=a.attr("data-id");ModifyEnable(parseInt(c),1,function(e,d){a.remove();UI.BuildItem(parseInt(c))})});$("#searchurl").bind("textchange",function(b){b=$(this).val();if(2>$("#searchname").val().length){var a=
b.match(/\.(.*?)\./);a=null==a?b.match(/(.*?)\./)[1]:a[1];$("#searchname").val(a)}/{%s}/.test(b)||(console.log(b),a=0<b.indexOf("www.asos.com")?b.replace(/searcho$/,"{%s}"):b.replace(/searcho/,"{%s}"),console.log(a),a!=b&&$(this).val(a))});$("#addnewsearch").click(function(b){b=$("#searchname").val();var a=$("#searchurl").val();if(2>b.length||!/{%s}/.test(a))$("#tip2").fadeIn(300).delay(2E3).hide(0);else{var c=UI.getFavicon(a);AddCustomizeSearch(b,a,c,function(e,d){e=d.insertId;$("#searchname").val("");
$("#searchurl").val("");UI.BuildItem(parseInt(e))})}})};UI.getFavicon=function(b){b=b.match(/\/\/(.*?)\//)[1];var a="chrome://favicon/https://"+b;try{requestFile(a,function(c){a=makeDataUrl(c.contentType,c.data)},!0)}catch(c){a="../style/favicon.png"}return a};
$(function(){$('label[for="googlelocal"]').html("Use "+chrome.i18n.getMessage("google"));$(":checkbox").each(function(b){this.checked="true"==localStorage[this.id]?!0:!1});$(":checkbox").change(function(b){localStorage[this.id]=this.checked;$("#tip").fadeIn(300).delay(2E3).hide(0);BG.refreshOptions()});UI.BuildHtml()});
