var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,c,d){a instanceof String&&(a=String(a));for(var g=a.length,e=0;e<g;e++){var f=a[e];if(c.call(d,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){if(a==Array.prototype||a==Object.prototype)return a;a[c]=d.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var d=a[c];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,c){var d=$jscomp.propertyToPolyfillSymbol[c];if(null==d)return a[c];d=a[d];return void 0!==d?d:a[c]};
$jscomp.polyfill=function(a,c,d,g){c&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,c,d,g):$jscomp.polyfillUnisolated(a,c,d,g))};$jscomp.polyfillUnisolated=function(a,c,d,g){d=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var e=a[g];if(!(e in d))return;d=d[e]}a=a[a.length-1];g=d[a];c=c(g);c!=g&&null!=c&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:c})};
$jscomp.polyfillIsolated=function(a,c,d,g){var e=a.split(".");a=1===e.length;g=e[0];g=!a&&g in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var h=e[f];if(!(h in g))return;g=g[h]}e=e[e.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?g[e]:null;c=c(d);null!=c&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:c}):c!==d&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(g,e,{configurable:!0,writable:!0,value:c})))};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(c,d){return $jscomp.findInternal(this,c,d).v}},"es6","es3");var HOST="",URL="",ISSEARCH,OPTION;HOST=window.location.host;
var TEXT="",googleSites="www.google.com.hk www.google.com.tw www.google.co.jp www.google.cn www.google.co.kr www.google.co.th www.google.de www.google.fr www.google.co.uk www.google.com.gr www.google.com.au www.google.ca www.google.co.il www.google.it www.google.ch www.google.cl www.google.nl www.google.be www.google.at www.google.com.pa www.google.pl www.google.com.ru www.google.com.br www.google.co.nz www.google.lt www.google.com.ar www.google.bi http://paoniu8.blogbus.com www.google.pn www.google.li www.google.com.nf www.google.vg www.google.mw www.google.fm www.google.sh www.google.cd www.google.ms www.google.co.cr www.google.lv www.google.ie www.google.co.gg www.google.co.je www.google.ae www.google.fi www.google.com.sg www.google.com.pe www.google.pr www.google.com.py www.google.gm www.google.td www.google.co.hu www.google.com.mx www.google.pt www.google.com.ua www.google.co.ve www.google.com.tr www.google.com.mt www.google.com.uy www.google.com.np www.google.hn www.google.com.ni www.google.gl www.google.kz www.google.sm www.google.co.mu www.google.as www.google.rw www.google.com.tj".split(" "),superfishBlacklist=
["www.interflora.co.uk"],Search={specialurl:function(a){var c=window.location.href;switch(a){case "twitter.com":var d=c.match(/\/search\/(.*?)(&|$)/);break;case "plus.google.com":d=c.match(/\/s\/(.*?)(&|$)/);break;case "www.shopping.com":d=c.match(/\/www.shopping.com\/(.*?)\/products/);break;case "www.tumblr.com":d=c.match(/\/tagged\/(.*?)(&|$)/);break;case "en.wikipedia.org":d=c.match(/\/wiki\/(.*?)(&|$)/);break;case "dictionary.reference.com":d=c.match(/\/browse\/(.*?)(&|$)/)}return d},showbar:function(a,
c,d,g,e){if(c="special"==c?Search.specialurl(d):window.location.href.match(new RegExp("[&|?|#]"+c+"(.*?)(&|$|#)","i"))){c=c[1];if("www.google.com"==HOST){var f=document.getElementsByName("q")[0];f&&(c=f.value)}$("body").addClass("searchbarshow");$("body").prepend('<div id="searchbar" class="searchbar"><div id="searchHistory">Keywords</div><ul id="searchHistory-list"></ul><div id="tab"><ul></ul><span class="button" title="Customize search engines"></span></div><div class="clear" style="clear:both;"></div></div>');
0!=g.length?$("#searchHistory").show():$("#searchHistory").hide();for(f=0;f<g.length;f++){var h='<li><a href="'+e.replace("{%s}",g[f])+'">'+g[f]+"</a></li>";$("#searchHistory-list").append(h)}$("#searchHistory").on("click",function(k){k.preventDefault();k.stopPropagation();$("#searchHistory-list").is(":visible")?$("#searchHistory-list").hide():$("#searchHistory-list").show()});"www.facebook.com"==HOST&&$("#blueBar").removeClass("fixed_elem");g=10<a.length?10:a.length;for(f=0;f<g;f++){imgurl="data"==
a[f].icondataurl.slice(0,4)?a[f].icondataurl:chrome.runtime.getURL(a[f].icondataurl);var l=a[f].searchurl.replace("{%s}",c);e=a[f].searchurl.match(/\/\/(.*?)\//)[1];e="<li "+(e==d?'class="current"':"")+'><a href="'+l+'" onClick="return false;" target="_parent"><img src="'+imgurl+'" />'+a[f].name+"</a></li>";$("#searchbar #tab ul").append(e)}if(10<a.length)for($("#searchbar #tab ul").append('<li id="switchbarmore"><a href="#" class="moreicon"></a></li>'),$("#switchbarmore").append('<div id="moreswitchlist"></div>'),
f=10;f<a.length;f++)imgurl="data"==a[f].icondataurl.slice(0,4)?a[f].icondataurl:chrome.runtime.getURL(a[f].icondataurl),l=a[f].searchurl.replace("{%s}",c),e=a[f].searchurl.match(/\/\/(.*?)\//)[1],e='<li><a href="'+l+'" target="_parent" title="'+a[f].name+'"><img src="'+imgurl+'" />'+a[f].name+"</a></li>",$("#moreswitchlist").append(e);$("#searchbar #tab ul li a").click(function(k){if(k=$(k.target).attr("href"))k.match(/\/\/(.*?)\//),l=k,window.location.href=l});$("#searchbar .button").click(function(k){k=
chrome.runtime.getURL("options.html");chrome.extension.sendRequest({action:"newTab",url:k})});chrome.extension.sendRequest({action:"saveQuery",query:decodeURIComponent(c)})}},addbar:function(){HOST=window.location.host;URL=window.location.href;"false"!=OPTION.switchbar&&chrome.extension.sendRequest({action:"getsearchs"},function(a){var c=a.searchs;console.log("searchs",c);a=a.querys;for(i=0;i<c.length;i++){var d=c[i].searchurl.match(/\/\/(.*?)\//)[1];if(HOST==d||-1!=$.inArray(HOST,googleSites)){if(/google\.(.*)\/maps/.test(URL))break;
var g=c[i].searchurl.match(/[&|\?]([-=\w]+)\{%s\}/);g=g?g[1]:"special";Search.removebar();Search.showbar(c,g,d,a,c[i].searchurl);break}}})},removebar:function(){$(".searchbar")&&$(".searchbar").remove()},searchinsite:function(){if(!(ISSEARCH||0<$("#searchinsite").length)){var a=document.referrer;1>a.length||(a=Search.issearch(a,a),a.query&&"false"!=OPTION.searchsite&&this.showsearchinsite(a.query))}},showsearchinsite:function(a){var c=encodeURIComponent("site:"+window.location.host);a='<div id="searchinsite"><div id="hidetool" style="display:none;"><span></span></div><div id="showtool"><h3>SearchO Extension<span class="hide"></span><span class="button"></span></h3><div class="searchbox">Search <b contentEditable="true">'+
decodeURIComponent(a)+"</b> in this site<span></span></div>";"NaN</div>";$("body").append(a);$("#searchinsite #showtool .searchbox span").click(function(d){d="http://www.searcho.com/search/google?q="+c+"+"+encodeURIComponent($("#searchinsite #showtool .searchbox b").html())+"&c=chromesearcho";window.open(d)});$("#searchinsite #showtool .searchbox b").keydown(function(d){13===d.keyCode&&(d.preventDefault(),d.stopPropagation(),d="http://www.searcho.com/search/google?q="+c+"+"+encodeURIComponent($("#searchinsite #showtool .searchbox b").html())+
"&c=chromesearcho",window.open(d))});$("#searchinsite #showtool h3 .hide").click(function(d){$("#searchinsite #showtool").hide();$("#searchinsite #hidetool").show()});$("#searchinsite #hidetool span").click(function(d){$("#searchinsite #showtool").show();$("#searchinsite #hidetool").hide()});$("#searchinsite #showtool h3 .button").click(function(d){d=chrome.runtime.getURL("options.html");window.open(d)})},modifysearchosite:function(){"false"==OPTION.switchbar?$("#searchBar #tab li span.popup").show():
$("#searchBar li a").removeAttr("target")},searchforselect:function(){0<$("#selectsearch").length||chrome.extension.sendRequest({action:"getsearchs"},function(a){function c(e,f){if("http://option/"==e)window.open(chrome.runtime.getURL("options.html"));else{var h=encodeURIComponent(TEXT);e=e.replace("{%s}",h);if("www.ebay.com"==f||"www.newegg.com"==f)e=Search.GetUrl(e);window.open(e)}}a=a.searchs;$("body").prepend('<div id="selectsearch" class="selectsearch"><div id="floaticon"></div><div id="list"></div><div id="searchlist"><ul></ul><ul><li data-url="http://option/">Options...</li></ul></div></div>');
var d=10<a.length?10:a.length;for(i=0;i<d;i++){imgurl="data"==a[i].icondataurl.slice(0,4)?a[i].icondataurl:chrome.runtime.getURL(a[i].icondataurl);var g='<li data-url="'+a[i].searchurl+'"><img src="'+imgurl+'" />'+a[i].name+"</li>";$("#searchlist ul:eq(0)").append(g)}if(10<a.length)for($("#searchlist ul:eq(0)").append('<li id="searchlistmore">More</li>'),$("#searchlistmore").append('<div id="MoreSearchList"></div>'),i=10;i<a.length;i++)imgurl="data"==a[i].icondataurl.slice(0,4)?a[i].icondataurl:chrome.runtime.getURL(a[i].icondataurl),
g='<li data-url="'+a[i].searchurl+'"><img src="'+imgurl+'" />'+a[i].name+"</li>",$("#MoreSearchList").append(g);$("body").mouseup(function(e){var f=$(e.target).parent().attr("id");$(e.target).parent().parent().attr("id");if("list"!=f&&"floaticon"!=f){sh=window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop||0;f=e.clientX;var h=e.clientY+sh+10,l=window.getSelection().toString();5<l.length&&!$(e.target).is("input")&&!$(e.target).is("textarea")?(TEXT=l,$("#searchlist").hide(0),
$("#selectsearch").css({left:f+"px",top:h+"px"}).show(),$("#searchlist ul li").unbind().click(function(k){k=$(k.target).attr("data-url");c(k)})):($("#searchlist").hide(0),$("#selectsearch").hide(0))}});$("#list").mouseover(function(e){$("#searchlist").delay(500).show(0)});$("#floaticon").click(function(e){$("#searchlist").hide(0);$("#selectsearch").hide(0);e=$("#searchlist ul li:eq(0)").attr("data-url");var f=e.match(/\/\/(.*?)\//)[1];c(e,f)})})},GetUrl:function(a){return"http://go.redirectingat.com?id=18202X786788&xs=1&url="+
encodeURIComponent(a)}};chrome.extension.sendRequest({action:"getoption"},function(a){if("docs.google.com"!=HOST&&"mail.google.com"!=HOST&&0<a.option.length&&(OPTION=a=JSON.parse(a.option),Search.removebar(),null==document.getElementById("searchbar")&&Search.addbar(),"true"==a.searchselection&&Search.searchforselect(),"true"==a.bookmarks||"true"==a.history))try{buildbookmartbar()}catch(c){}});
function insertAfter(a,c){var d=c.parentNode;d.lastChild==c?d.appendChild(a):d.insertBefore(a,c.nextSibling)}
function buildbookmartbar(a){if((a=document.getElementsByName("q")[0])&&"www.bing.com"!=HOST){var c=function(h,l,k){for(var m=8<h.length?8:h.length,t=document.createDocumentFragment(),n=0;n<m;n++){if(""==h[n].title)var p=h[n].url;else{p=h[n].title;var q=d.replace(/[\.\$\^\{\[\(\|\)\*\+\?\\]/gi,"\\$1");p=p.replace(new RegExp("("+q+")","ig"),'<span style="font-weight:bold">$1</span>')}q=h[n].url;h[n].url.replace(g,'<span style="text-decoration:none;font-weight:bold">'+g+"</span>");var r=document.createElement("div");
r.className="item";q.split("/");r.innerHTML='<img class="icon" id="icon" src="'+l[n]+'"><a title="'+h[n].title+'" target="_blank" href="'+q+'">'+p+"</a>";t.appendChild(r)}0<$("#"+k).length&&$("#"+k).append(t)},d=a.value;chrome.runtime.getURL("");var g=d.toLowerCase(),e=document.createElement("div");e.id="searchdiv";var f=document.getElementById("rhs");2<=d.length&&chrome.extension.sendRequest({action:"getsearchbookmarks",keyword:d},function(h){if(1<=h.bookmarkItems.length||1<=h.historyItems.length){if(f){var l=
f.firstChild;if(0<$("#searchdiv").length)return;f.insertBefore(e,l)}l=document.getElementById("searchdiv");if(1<=h.bookmarkItems.length&&1==h.ifBookmark){var k=document.createElement("div");k.id="searchdiv-bookmark-box";k.innerHTML='<div id="searchdiv-bookmark-banner" class="searchdiv-banner">Results from bookmarks<div class="searchdiv-close"></div><ul id="bookmark-close-action" class="searchdiv-close-action"><li class="searchdiv-close-t">Dismiss for now</li><li class="searchdiv-close-f">Disable forever</li><li class="searchdiv-tip">Enabled by Search All</li></ul></div><div id="searchdiv-bookmark-container" class="searchdiv-container"><a class="viewAllLink">view all bookmark results</a></div>';
l&&l.appendChild(k);c(h.bookmarkItems,h.bIcons,"searchdiv-bookmark-container")}1<=h.historyItems.length&&1==h.ifHistory&&(k=document.createElement("div"),k.id="searchdiv-history-box",k.innerHTML='<div id="searchdiv-history-banner" class="searchdiv-banner">Results from browsing history<div class="searchdiv-close"></div><ul id="history-close-action" class="searchdiv-close-action"><li class="searchdiv-close-t">Dismiss for now</li><li class="searchdiv-close-f">Disable forever</li><li class="searchdiv-tip">Enabled by Search All</li></ul></div><div id="searchdiv-history-container" class="searchdiv-container"><a class="viewAllLink">view all history results</a></div>',
l&&l.appendChild(k),c(h.historyItems,h.hIcons,"searchdiv-history-container"));l=1==h.bookmarkItems.length?"result":"results";k=1==h.historyItems.length?"result":"results";$("#searchdiv-bookmark-container").find(".viewAllLink").text("View all "+h.bookmarkItems.length+" "+l).on("click",function(){chrome.extension.sendRequest({action:"newTab",url:"chrome://bookmarks/#q="+d})});$("#searchdiv-history-container").find(".viewAllLink").text("View all "+h.historyItems.length+" "+k).on("click",function(){chrome.extension.sendRequest({action:"newTab",
url:"chrome://history/#q="+d})});$("#searchdiv-history-banner").find("a");$(".searchdiv-close").on("click",function(m){m.preventDefault();m.stopPropagation();$(this).parent().find(".searchdiv-close-action").show()});$(".searchdiv-close-action").on("click","li",function(m){m=m.target;if($(m).hasClass("searchdiv-close-t"))"bookmark-close-action"==m.parentNode.id?$("#searchdiv-bookmark-box").hide():"history-close-action"==m.parentNode.id&&$("#searchdiv-history-box").hide();else if($(m).hasClass("searchdiv-close-f"))if(1==
confirm("Want to disable this feature? You can enable it in the Search All extension options again."))"bookmark-close-action"==m.parentNode.id?($("#searchdiv-bookmark-box").hide(),chrome.extension.sendRequest({action:"closeBookmarkSearch"})):"history-close-action"==m.parentNode.id&&($("#searchdiv-history-box").hide(),chrome.extension.sendRequest({action:"closeHistorySearch"}));else return;$("#searchdiv-close-action").hide()});$("#option").click(function(m){m=chrome.runtime.getURL("options.html");
window.open(m)})}})}}function rmbookmartbar(){$("#searchdiv")&&$("#searchdiv").remove()}function myReplace(a,c){a=a.replace(/[\.\$\^\{\[\(\|\)\*\+\?\\]/gi,"\\$1");return c.replace(new RegExp("("+a+")","ig"),'<span style="font-weight:bold">$1</span>')}
function addAD(){var a=$("#gbqfq").val();chrome.extension.sendRequest({action:"getAD",query:a,url:window.location.href},function(c){console.log(c);c=c.data;var d=c.length;if(!document.getElementById("sa-admanage-box")){var g=document.createElement("div");g.id="sa-admanage-box";g.innerHTML="<h2><span>Ads</span></h2>";for(var e=document.createElement("ol"),f=0;f<d;f++){var h=myReplace(a,c[f].title["#cdata"]),l=myReplace(a,c[f].descr["#cdata"]),k=myReplace(a,c[f].host["#cdata"]);e.innerHTML+='<li class="Admanage-li"><h3><a target="_blank" href="'+
c[f].url["#cdata"]+'">'+h+"</a></h3><div><cite>"+k+"</cite></div><span>"+l+"</span></li>"}g.appendChild(e);$("#rhs").prepend(g)}})}$(document).on("click",function(a){$(".searchdiv-close-action").hide();$("#searchHistory-list").hide()});chrome.extension.onRequest.addListener(function(a,c,d){switch(a.action){case "tabupdate":rmbookmartbar();buildbookmartbar(event);Search.addbar();break;case "startdetect":detectOpensearch()}});detectOpensearch();window.onload=function(){try{buildbookmartbar()}catch(a){}};
var b=document.getElementsByName("q")[0];b&&b.addEventListener("input",function(a){rmbookmartbar();buildbookmartbar(a)});
function detectOpensearch(){chrome.extension.sendRequest({action:"resetBadge"});if($('link[type="application/opensearchdescription+xml"]')[0]){var a=$('link[type="application/opensearchdescription+xml"]')[0].getAttribute("href");a="http"!=a.substring(0,4)?document.location.protocol+"//"+document.location.host+a:a;chrome.extension.sendRequest({action:"opensearch",path:a})}else chrome.extension.sendRequest({action:"refreshtabid"})}
function insertChango(){var a=document.createElement("script");a.type="text/javascript";a.innerHTML='var __chd__ = {"aid":10623,"chaid":"diigo"};';var c=document.getElementsByTagName("head")[0];c.appendChild(a);a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"==document.location.protocol?"https://z":"http://p")+".chango.com/static/c.js";c=document.getElementsByTagName("head")[0];c.appendChild(a)}
function insertSkimlink(){var a=document.createElement("script");a.type="text/javascript";a.src="//s.skimresources.com/js/18202X824369.skimlinks.js";document.head.appendChild(a)}function getAffiate(){Array.prototype.slice.call(document.getElementsByTagName("a")).forEach(function(a,c,d){/www.amazon.com/.test(a.href)&&!/(&|\?)tag=([^&]*)(&|$)/.test(a.href)&&(/\?.*=/.test(a.href)?d[c].href+="&tag=diigo0c-20":d[c].href+="?tag=diigo0c-20")})};
