var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var e=a.length,d=0;d<e;d++){var g=a[d];if(b.call(c,g,d,a))return{i:d,v:g}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,e){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,e):$jscomp.polyfillUnisolated(a,b,c,e))};$jscomp.polyfillUnisolated=function(a,b,c,e){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];if(!(d in c))return;c=c[d]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,e){var d=a.split(".");a=1===d.length;e=d[0];e=!a&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var g=0;g<d.length-1;g++){var f=d[g];if(!(f in e))return;e=e[f]}d=d[d.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?e[d]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+d,d=
$jscomp.propertyToPolyfillSymbol[d],$jscomp.defineProperty(e,d,{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");
var SearchUrl=[],Opensearch=[],currentversion=chrome.app.getDetails().version,getTime={getUTCString:function(a){if("now"==a||!a){var b=new Date;b=Date.parse(b)/1E3;return getTime.getUTCString(b)}a=new Date(1E3*a);var c=a.getUTCFullYear();var e=a.getUTCMonth()+1;b=a.getUTCDate();var d=a.getUTCHours();var g=a.getUTCMinutes();a=a.getUTCSeconds();10>e&&(e="0"+e);10>b&&(b="0"+b);10>d&&(d="0"+d);10>g&&(g="0"+g);10>a&&(a="0"+a);return c+"-"+e+"-"+b+" "+d+":"+g+":"+a},getUTCInt:function(a){if("now"!=a&&a)return a=
a.split(" "),t0=a[0].split("-"),t1=a[1].split(":"),--t0[1],10>t0[1]&&(t0[1]="0"+t0[1]),Date.UTC(t0[0],t0[1],t0[2],t1[0],t1[1],t1[2])/1E3;a=new Date;return Date.parse(a)/1E3},localTimeFromUTC:function(a){var b=-((new Date).getTimezoneOffset()/60),c=a.split(" ");a=c[0].split("-");c=c[1].split(":");a=new Date(a[0],a[1]-1,a[2],c[0],c[1]);c=a.getHours();a.setHours(c+b);return $.format.date(a,"yyyy/MM/dd/HH:mm")}},util={contextmenus:function(a,b){switch(a.menuItemId){case 1:var c=util.GetGoogleUrl(a.selectionText);
break;case 4:b=a.pageUrl.match(/\/\/(.*?)\//)[1];b=encodeURIComponent("site:"+b);c="true"==localStorage.googlelocal?"http://"+chrome.i18n.getMessage("google")+"/search?q="+b+"+"+encodeURIComponent(a.selectionText):"http://www.google.com/search?q="+b+"+"+encodeURIComponent(a.selectionText);break;case 3:c="http://www.bing.com/search?q="+encodeURIComponent(a.selectionText);break;case 2:c="http://search.yahoo.com/search?fr=chr-greentree_gc&ei=utf-8&ilc=12&type=890416&p="+encodeURIComponent(a.selectionText);
break;case 5:c="http://en.wikipedia.org/wiki/"+encodeURIComponent(a.selectionText);break;case 6:c=util.GetAmazonUrl(a.selectionText);break;case 7:c="https://twitter.com/#!/search/"+encodeURIComponent(a.selectionText);break;case 8:c="http://www.youtube.com/results?search_query="+encodeURIComponent(a.selectionText);break;case 9:c=util.GetEbayUrl(a.selectionText);break;case 10:c="http://www.wolframalpha.com/input/?i="+encodeURIComponent(a.selectionText)}window.open(c)},GetAmazonUrl:function(a){return"www.amazon.com"==
chrome.i18n.getMessage("amazon")?"http://www.amazon.com/gp/search?ie=UTF8&keywords="+encodeURIComponent(a)+"&tag=diigo0c-20&index=aps&linkCode=ur2&camp=1789&creative=9325":"http://go.redirectingat.com?id=18202X786788&xs=1&url="+encodeURIComponent("http://"+chrome.i18n.getMessage("amazon")+"/s/field-keywords="+encodeURIComponent(a))},GetEbayUrl:function(a){chrome.i18n.getMessage("ebay");return"http://go.redirectingat.com?id=18202X786788&xs=1&url="+encodeURIComponent("http://"+chrome.i18n.getMessage("ebay")+
"/sch/i.html?_sacat=See-All-Categories&_nkw="+encodeURIComponent(a))},GetGoogleUrl:function(a){return"true"==localStorage.googlelocal?"http://"+chrome.i18n.getMessage("google")+"/search?q="+encodeURIComponent(a):"http://www.google.com/search?q="+encodeURIComponent(a)},GetMySearch:function(a){var b=[],c=[];LoadItemsByList(1,function(e,d){e=d.rows;d=e.length;for(i=0;i<d;i++){var g=e.item(i);b.push(g)}e=JSON.parse(localStorage.customize_sort_id);for(i=0;i<e.length;i++)for(k in b)if(b[k].id==e[i]){c.push(b[k]);
break}a(c)})},CreateContextMenu:function(){var a;chrome.contextMenus.removeAll(function(){util.GetMySearch(function(b){for(i=0;i<b.length;i++)a=chrome.contextMenus.create({title:b[i].name,onclick:util.ContextMenuClick,contexts:["selection"]}),SearchUrl[a]=b[i].searchurl})})},ContextMenuClick:function(a,b){console.log(a);b=SearchUrl[a.menuItemId];a=encodeURIComponent(a.selectionText);a=b.replace("{%s}",a);window.open(a)},GetUrl:function(a){return"http://go.redirectingat.com?id=18202X786788&xs=1&url="+
encodeURIComponent(a)},initUserId:function(){var a=getTime.getUTCInt(),b=parseInt(10*Math.random()+1);a=hex_md5(""+a+b);console.log(a);localStorage.userID=a}},OPTIONS_TRUE=["switchbar","searchsite","superfish","bookmarks","history"],OPTIONS_FALSE=["googlelocal","searchselection"];for(i in OPTIONS_TRUE)localStorage[OPTIONS_TRUE[i]]||(localStorage[OPTIONS_TRUE[i]]=!0);for(i in OPTIONS_FALSE)localStorage[OPTIONS_FALSE[i]]||(localStorage[OPTIONS_FALSE[i]]=!1);
chrome.tabs.onUpdated.addListener(function(a,b,c){console.log("update",a,b,c);"loading"!=b.status&&(b=c.url,c=b.match(/\.(.*?)\./),b=null==c?b.match(/(.*?)\./)[1]:c[1],console.log(b),"google"==b&&chrome.tabs.sendRequest(a,{action:"tabupdate"}),chrome.tabs.sendRequest(a,{action:"startdetect"}),chrome.tabs.sendRequest(a,{action:"insertChango"}))});Array.prototype.remove=function(a){if(isNaN(a)||a>this.length)return!1;for(var b=0,c=0;b<this.length;b++)this[b]!=this[a]&&(this[c++]=this[b]);--this.length};
chrome.extension.onRequest.addListener(function(a,b,c){switch(a.action){case "getoption":c({option:JSON.stringify(localStorage)});break;case "search":util.contextmenus(a.info,null);break;case "getsearchs":var e=localStorage.querys?localStorage.querys.split(","):[];util.GetMySearch(function(f){c({searchs:f,querys:e})});break;case "getuserid":c({userid:localStorage.userID});break;case "getsearchbookmarks":chrome.bookmarks.search(a.keyword,function(f){chrome.history.search({text:a.keyword,maxResults:1E4,
startTime:(new Date).getTime()-15552E6},function(h){function m(r){var q="chrome://favicon/"+r;try{requestFile(q,function(u){q=makeDataUrl(u.contentType,u.data)},!0)}catch(u){q="img/searchAll/favicon.png"}return q}console.log(h);for(var p=[],n=[],l=0;l<f.length;l++)p[l]=m(f[l].url);for(l=0;l<h.length;l++)n[l]=m(h[l].url);var t=l=!1;"true"==localStorage.bookmarks&&(l=!0);"true"==localStorage.history&&(t=!0);c({bookmarkItems:f,historyItems:h,bIcons:p,hIcons:n,ifBookmark:l,ifHistory:t})})});break;case "opensearch":console.log(a.path);
getSearchString(a.path);break;case "resetBadge":chrome.tabs.getSelected(null,function(f){chrome.browserAction.getBadgeText({tabId:f.id},function(h){"New"!=h&&chrome.browserAction.setBadgeText({text:""})})});break;case "refreshtabid":chrome.tabs.getSelected(null,function(f){Opensearch[f.id]=null});break;case "addsearch":b=a.searchname;var d=a.searchurl,g=getFavicon(d);AddCustomizeSearch(b,d,g,function(f,h){f=h.insertId;console.log(f);h=JSON.parse(localStorage.customize_sort_id);console.log(typeof h);
h.push(f.toString());localStorage.customize_sort_id=JSON.stringify(h);console.log(h)});console.log(localStorage.customize_sort_id);chrome.extension.sendRequest({action:"addsuccess"});chrome.browserAction.setBadgeText({text:""});chrome.tabs.getSelected(null,function(f){Opensearch.remove(f.id);console.log(Opensearch)});break;case "newtip":localStorage.version&&localStorage.version==currentversion||(chrome.browserAction.setBadgeText({text:"New"}),count=1,window.open("https://www.diigo.com/searchAll/new-for-search-all.html?v="+
currentversion),localStorage.version=currentversion,chrome.extension.sendRequest({action:"shownew"}));break;case "getAD":$.get("http://api.hostip.info/get_json.php",function(f){f=f.ip;var h=encodeURIComponent(a.url),m=a.query.replace(/\s/g,"+"),p=encodeURI(window.navigator.userAgent);$.get("http://65975.xml.premiumxml.com/xml/?fid=65975&keywords="+m+"&user_ip="+f+"&ua="+p+"&serve_url="+h,function(n){n=n.getElementsByTagName("listing");var l=n.length;if(l){for(var t=[],r=0;r<l;r++){var q=JSON.parse(xml2json(n[r],
""));t.push(q.listing)}c({data:t})}})});break;case "newTab":chrome.tabs.create({url:a.url});break;case "closeBookmarkSearch":localStorage.bookmarks=!1;break;case "closeHistorySearch":localStorage.history=!1;break;case "saveQuery":b=localStorage.querys?localStorage.querys.split(","):[],d=a.query,g=b.indexOf(d),""!=d&&(10<b.length&&b.splice(10,b.length-10),-1<g?b.splice(g,1):10<=b.length&&b.pop(),b.unshift(d),localStorage.querys=b.join(","))}});
function getFavicon(a){a=a.match(/\/\/(.*?)\//)[1];var b="chrome://favicon/http://"+a;try{requestFile(b,function(c){b=makeDataUrl(c.contentType,c.data)},!0)}catch(c){b="../style/favicon.png"}return b}localStorage.userID||util.initUserId();try{util.CreateContextMenu()}catch(a){}
function getSearchString(a){xmlhttp=new XMLHttpRequest;xmlhttp.open("GET",a,!1);xmlhttp.send();xmlDoc=xmlhttp.responseXML;a=$(xmlDoc).find('Url[type="text/html"]');var b=xmlDoc.getElementsByTagName("ShortName")[0].childNodes[0].nodeValue;console.log(b);console.log(a);var c=a[0].getAttribute("template");a=a[0].getElementsByTagName("Param");if(0<a.length){c+="?";for(var e=0;e<a.length;e++){var d=a[e].getAttribute("name"),g=a[e].getAttribute("value");c=0==e?c+d+"="+g:c+"&"+d+"="+g}}else c=c.replace(/searchTerms/,
"%s");c=c.replace(/searchTerms/,"%s");console.log(c);console.log(Opensearch);c&&LoadAllItems(function(f,h){console.log(h.rows.length);console.log(h.rows.item(0));for(f=0;f<h.rows.length;f++)if(h.rows.item(f).searchurl.toString().match(/:\/\/([\w | .]+)/)[1]==c.match(/:\/\/([\w | .]+)/)[1])return;chrome.tabs.getSelected(null,function(m){Opensearch[m.id]=[c,b];chrome.browserAction.getBadgeText({tabId:m.id},function(p){"New"!=p&&chrome.browserAction.setBadgeText({text:"+"})})});chrome.extension.onRequest.addListener(function(m,
p,n){"getopensearchurl"==m.action&&n({searchurl:Opensearch[m.tabid][0],searchname:Opensearch[m.tabid][1]})})})}chrome.tabs.onActivated.addListener(function(){chrome.tabs.getSelected(null,function(a){null!=Opensearch[a.id]?chrome.browserAction.setBadgeText({text:"+"}):chrome.browserAction.getBadgeText({tabId:a.id},function(b){"New"!=b&&(console.log("setnull"),chrome.browserAction.setBadgeText({text:""}))})})});chrome.contextMenus.create({title:"Google image search",contexts:["image"],onclick:SearchImage});
function validateBase64(a){for(var b=0;b<a.length;b++)if(!("a"<=a[b]&&"z">=a[b]||"A"<=a[b]&&"Z">=a[b]||"0"<=a[b]&&"9">=a[b]||"+"==a[b]||"/"==a[b]||"."==a[b]||"="==a[b]))return!1;return!0}
function newTab(a){var b=localStorage.imagePreview,c=b.indexOf(",");b=b.substring(c+1).replace(/\+/g,"-").replace(/\//g,"_").replace(/\./g,"=");chrome.tabs.executeScript(a.id,{code:'var form = document.createElement("form");form.setAttribute("method","POST");form.setAttribute("action","http://www.google.com/searchbyimage/upload");form.setAttribute("enctype","multipart/form-data");function addInput(key,value){  var input = document.createElement("input");  input.setAttribute("type","hidden");  input.setAttribute("name",key);  input.setAttribute("value",value);  form.appendChild(input);};addInput("image_content","'+b+
'");addInput("filename","");addInput("image_url","");addInput("sbisrc","");document.body.appendChild(form);form.submit();'})}
function SearchImage(a,b){a=a.srcUrl;0==a.indexOf("data:")?(lower_src=a.toLowerCase(),lower_src.indexOf("data:image/bmp;")&&lower_src.indexOf("data:image/gif;")&&lower_src.indexOf("data:image/jpeg;")&&lower_src.indexOf("data:image/jpg;")&&lower_src.indexOf("data:image/png;")&&lower_src.indexOf("data:image/tiff;")&&lower_src.indexOf("data:image/x-ico;")&&lower_src.indexOf("data:image/x-tiff;")||(b=a.indexOf(","),-1!=b&&validateBase64(a.substring(b+1))&&(localStorage.imagePreview=a,chrome.tabs.create({url:"http://images.google.com/imghp?sbi=1",
selected:!0},newTab)))):(a="http://www.google.com/searchbyimage?&image_url="+encodeURIComponent(a),chrome.tabs.create({url:a,selected:!0}));return!0}localStorage.version=currentversion;
